!1,1,1-TRICHLOROETHANE
!--------------------------------------
data id_list(1) / 1 /
data name_list(1) / "1,1,1-trichloroethane" /
data eps(1) / 7.082600000000000_wp /
data refr(1) / 1.437900000000000_wp /
data A(1) / 0.000000000000000_wp /
data B(1) / 0.090000000000000_wp /
data g(1) / 36.240000000000002_wp /
data rho(1) / 1483.200000000000045_wp /
data alias_list(:,1) / &
&     "1,1,1-trichloroethane",                          &
&     "trichloroethane",                                &
&     "methylchloroform",                               &
&     "71-55-6",                                        &
&     "chlorothene",                                    &
&     "methyl chloroform",                              &
&     "chcl3ch3",                                       &
&     "cleanite",                                       &
&     "chlorothene nu",                                 &
&     "chlorothene vg"                                  /


!1,1,2-TRICHLOROETHANE
!--------------------------------------
data id_list(2) / 2 /
data name_list(2) / "1,1,2-trichloroethane" /
data eps(2) / 7.193700000000000_wp /
data refr(2) / 1.471400000000000_wp /
data A(2) / 0.130000000000000_wp /
data B(2) / 0.130000000000000_wp /
data g(2) / 48.969999999999999_wp /
data rho(2) / 1435.000000000000000_wp /
data alias_list(:,2) / &
&     "1,1,2-trichloroethane",                          &
&     "",                                               &
&     "beta-trichloroethane",                           &
&     "79-00-5",                                        &
&     "rcra waste number u227",                         &
&     "rcra waste number u359",                         &
&     "caswell no. 875a",                               &
&     "1,1, 2-trichloroethane",                         &
&     "",                                               &
&     "ccris 602"                                       /


!1,2,4-TRIMETHYLBENZENE
!--------------------------------------
data id_list(3) / 3 /
data name_list(3) / "1,2,4-trimethylbenzene" /
data eps(3) / 2.365300000000000_wp /
data refr(3) / 1.504800000000000_wp /
data A(3) / 0.000000000000000_wp /
data B(3) / 0.190000000000000_wp /
data g(3) / 42.030000000000001_wp /
data rho(3) / 879.000000000000000_wp /
data alias_list(:,3) / &
&     "1,2,4-trimethylbenzene",                         &
&     "pseudocumene",                                   &
&     "95-63-6",                                        &
&     "pseudocumol",                                    &
&     "",                                               &
&     "pseudo-cumene",                                  &
&     "1,2,4-trimethyl-benzene",                        &
&     "nsc 65600",                                      &
&     "hsdb 5293",                                      &
&     "einecs 202-436-9"                                /


!1,2-DIBROMOETHANE
!--------------------------------------
data id_list(4) / 4 /
data name_list(4) / "1,2-dibromoethane" /
data eps(4) / 4.931300000000000_wp /
data refr(4) / 1.538700000000000_wp /
data A(4) / 0.100000000000000_wp /
data B(4) / 0.170000000000000_wp /
data g(4) / 56.930000000000000_wp /
data rho(4) / 1460.000000000000000_wp /
data alias_list(:,4) / &
&     "1,2-dibromoethane",                              &
&     "106-93-4",                                       &
&     "ethylene dibromide",                             &
&     "ethylene bromide",                               &
&     "sym-dibromoethane",                              &
&     "",                                               &
&     "alpha,beta-dibromoethane",                       &
&     "bromuro di etile",                               &
&     "aadibroom",                                      &
&     "bromofume"                                       /


!1,2-DICHLOROETHANE
!--------------------------------------
data id_list(5) / 5 /
data name_list(5) / "1,2-dichloroethane" /
data eps(5) / 10.125000000000000_wp /
data refr(5) / 1.444800000000000_wp /
data A(5) / 0.100000000000000_wp /
data B(5) / 0.110000000000000_wp /
data g(5) / 45.859999999999999_wp /
data rho(5) / 1245.000000000000000_wp /
data alias_list(:,5) / &
&     "1,2-dichloroethane",                             &
&     "ethylene dichloride",                            &
&     "107-06-2",                                       &
&     "ethylene chloride",                              &
&     "",                                               &
&     "ethane, 1,2-dichloro-",                          &
&     "1,2-dce",                                        &
&     "1,2-ethylidene dichloride",                      &
&     "caswell no. 440",                                &
&     "dichloroethane"                                  /


!1,2-ETHANEDIOL
!--------------------------------------
data id_list(6) / 6 /
data name_list(6) / "1,2-ethanediol" /
data eps(6) / 40.244999999999997_wp /
data refr(6) / 1.431800000000000_wp /
data A(6) / 0.580000000000000_wp /
data B(6) / 0.780000000000000_wp /
data g(6) / 69.069999999999993_wp /
data rho(6) / 1115.000000000000000_wp /
data alias_list(:,6) / &
&     "ethylene glycol",                                &
&     "ethane-1,2-diol",                                &
&     "1,2-ethanediol",                                 &
&     "107-21-1",                                       &
&     "monoethylene glycol",                            &
&     "1,2-dihydroxyethane",                            &
&     "2-hydroxyethanol",                               &
&     "glycol alcohol",                                 &
&     "ethylene alcohol",                               &
&     "fridex"                                          /


!1,4-DIOXANE
!--------------------------------------
data id_list(7) / 7 /
data name_list(7) / "1,4-dioxane" /
data eps(7) / 2.209900000000000_wp /
data refr(7) / 1.422400000000000_wp /
data A(7) / 0.000000000000000_wp /
data B(7) / 0.640000000000000_wp /
data g(7) / 47.140000000000001_wp /
data rho(7) / 1033.000000000000000_wp /
data alias_list(:,7) / &
&     "1,4-dioxane",                                    &
&     "dioxane",                                        &
&     "123-91-1",                                       &
&     "p-dioxane",                                      &
&     "diethylene ether",                               &
&     "1,4-diethylene dioxide",                         &
&     "dioxan",                                         &
&     "diethylene oxide",                               &
&     "para-dioxane",                                   &
&     "glycolethylenether"                              /


!1-BROMO-2-METHYLPROPANE
!--------------------------------------
data id_list(8) / 8 /
data name_list(8) / "1-bromo-2-methylpropane" /
data eps(8) / 7.779200000000000_wp /
data refr(8) / 1.434800000000000_wp /
data A(8) / 0.000000000000000_wp /
data B(8) / 0.120000000000000_wp /
data g(8) / 34.689999999999998_wp /
data rho(8) / 1260.000000000000000_wp /
data alias_list(:,8) / &
&     "1-bromo-2-methylpropane",                        &
&     "78-77-3",                                        &
&     "isobutyl bromide",                               &
&     "iso-butyl bromide",                              &
&     "",                                               &
&     "i-butyl bromide",                                &
&     "ccris 349",                                      &
&     "nsc 8416",                                       &
&     "einecs 201-141-2",                               &
&     "unii-5oec0bw987"                                 /


!1-BROMOOCTANE
!--------------------------------------
data id_list(9) / 9 /
data name_list(9) / "1-bromooctane" /
data eps(9) / 5.024400000000000_wp /
data refr(9) / 1.452400000000000_wp /
data A(9) / 0.000000000000000_wp /
data B(9) / 0.120000000000000_wp /
data g(9) / 41.280000000000001_wp /
data rho(9) / 1118.000000000000000_wp /
data alias_list(:,9) / &
&     "1-bromooctane",                                  &
&     "111-83-1",                                       &
&     "n-octyl bromide",                                &
&     "1-octyl bromide",                                &
&     "unii-q382hpc6lc",                                &
&     "nsc 9821",                                       &
&     "einecs 203-912-9",                               &
&     "q382hpc6lc",                                     &
&     "ccris 8914",                                     &
&     "dtxsid3021938"                                   /


!1-BROMOPENTANE
!--------------------------------------
data id_list(10) / 10 /
data name_list(10) / "1-bromopentane" /
data eps(10) / 6.269000000000000_wp /
data refr(10) / 1.444700000000000_wp /
data A(10) / 0.000000000000000_wp /
data B(10) / 0.120000000000000_wp /
data g(10) / 38.700000000000003_wp /
data rho(10) / 1218.000000000000000_wp /
data alias_list(:,10) / &
&     "1-bromopentane",                                 &
&     "n-amyl bromide",                                 &
&     "amyl bromide",                                   &
&     "110-53-2",                                       &
&     "1-bromo-pentane",                                &
&     "n-c5h11br",                                      &
&     "nsc 7895",                                       &
&     "einecs 203-776-0",                               &
&     "unii-z2s4r599p0",                                &
&     "dtxsid3049203"                                   /


!1-BROMOPROPANE
!--------------------------------------
data id_list(11) / 11 /
data name_list(11) / "1-bromopropane" /
data eps(11) / 8.049600000000000_wp /
data refr(11) / 1.434300000000000_wp /
data A(11) / 0.000000000000000_wp /
data B(11) / 0.120000000000000_wp /
data g(11) / 36.359999999999999_wp /
data rho(11) / 1354.000000000000000_wp /
data alias_list(:,11) / &
&     "1-bromopropane",                                 &
&     "106-94-5",                                       &
&     "n-propyl bromide",                               &
&     "propyl bromide",                                 &
&     "",                                               &
&     "1-propyl bromide",                               &
&     "1-bromo-propane",                                &
&     "propylbromide",                                  &
&     "n-propylbromide",                                &
&     ""                                                /


!1-BUTANOL
!--------------------------------------
data id_list(12) / 12 /
data name_list(12) / "1-butanol" /
data eps(12) / 17.332000000000001_wp /
data refr(12) / 1.399300000000000_wp /
data A(12) / 0.370000000000000_wp /
data B(12) / 0.480000000000000_wp /
data g(12) / 35.880000000000003_wp /
data rho(12) / 809.500000000000000_wp /
data alias_list(:,12) / &
&     "1-butanol",                                      &
&     "butan-1-ol",                                     &
&     "n-butanol",                                      &
&     "71-36-3",                                        &
&     "butyl alcohol",                                  &
&     "n-butyl alcohol",                                &
&     "1-hydroxybutane",                                &
&     "propylcarbinol",                                 &
&     "butyl hydroxide",                                &
&     "butanol"                                 /


!1-CHLOROHEXANE
!--------------------------------------
data id_list(13) / 13 /
data name_list(13) / "1-chlorohexane" /
data eps(13) / 5.949100000000000_wp /
data refr(13) / 1.419900000000000_wp /
data A(13) / 0.000000000000000_wp /
data B(13) / 0.100000000000000_wp /
data g(13) / 37.030000000000001_wp /
data rho(13) / 879.000000000000000_wp /
data alias_list(:,13) / &
&     "1-chlorohexane",                                 &
&     "544-10-5",                                       &
&     "hexyl chloride",                                 &
&     "chlorohexane",                                   &
&     "",                                               &
&     "n-hexyl chloride",                               &
&     "1-chloro-hexane",                                &
&     "hexane, 1-chloro-",                              &
&     "r5l7i6o9nw",                                     &
&     ""                                                /


!1-CHLOROPENTANE
!--------------------------------------
data id_list(14) / 14 /
data name_list(14) / "1-chloropentane" /
data eps(14) / 6.502200000000000_wp /
data refr(14) / 1.412700000000000_wp /
data A(14) / 0.000000000000000_wp /
data B(14) / 0.100000000000000_wp /
data g(14) / 35.119999999999997_wp /
data rho(14) / 883.000000000000000_wp /
data alias_list(:,14) / &
&     "1-chloropentane",                                &
&     "543-59-9",                                       &
&     "pentyl chloride",                                &
&     "n-amyl chloride",                                &
&     "amyl chloride",                                  &
&     "",                                               &
&     "n-pentyl chloride",                              &
&     "n-butylcarbonyl chloride",                       &
&     "0eg9msd3nk",                                     &
&     "hsdb 1071"                                       /


!1-CHLOROPROPANE
!--------------------------------------
data id_list(15) / 15 /
data name_list(15) / "1-chloropropane" /
data eps(15) / 8.354799999999999_wp /
data refr(15) / 1.387900000000000_wp /
data A(15) / 0.000000000000000_wp /
data B(15) / 0.100000000000000_wp /
data g(15) / 30.660000000000000_wp /
data rho(15) / 892.000000000000000_wp /
data alias_list(:,15) / &
&     "1-chloropropane",                                &
&     "540-54-5",                                       &
&     "propyl chloride",                                &
&     "n-propyl chloride",                              &
&     "",                                               &
&     "1-chloro-propane",                               &
&     "hsdb 5681",                                      &
&     "unii-tuv7462nwk",                                &
&     "einecs 208-749-7",                               &
&     "tuv7462nwk"                                      /


!1-DECANOL
!--------------------------------------
data id_list(16) / 16 /
data name_list(16) / "1-decanol" /
data eps(16) / 7.530500000000000_wp /
data refr(16) / 1.437200000000000_wp /
data A(16) / 0.370000000000000_wp /
data B(16) / 0.480000000000000_wp /
data g(16) / 41.039999999999999_wp /
data rho(16) / 840.000000000000000_wp /
data alias_list(:,16) / &
&     "1-decanol",                                      &
&     "decan-1-ol",                                     &
&     "decyl alcohol",                                  &
&     "112-30-1",                                       &
&     "decanol",                                        &
&     "n-decyl alcohol",                                &
&     "capric alcohol",                                 &
&     "alcohol c-10",                                   &
&     "n-decatyl alcohol",                              &
&     "decanol (van)"                                   /


!1-FLUOROOCTANE
!--------------------------------------
data id_list(17) / 17 /
data name_list(17) / "1-fluorooctane" /
data eps(17) / 3.890000000000000_wp /
data refr(17) / 1.393500000000000_wp /
data A(17) / 0.000000000000000_wp /
data B(17) / 0.100000000000000_wp /
data g(17) / 33.920000000000002_wp /
data rho(17) / 703.000000000000000_wp /
data alias_list(:,17) / &
&     "1-fluorooctane",                                 &
&     "octyl fluoride",                                 &
&     "",                                               &
&     "5jw9m3f8rw",                                     &
&     "nsc-62037",                                      &
&     "dtxsid70196787",                                 &
&     "dtxcid10119278",                                 &
&     "4-01-00-00418 (beilstein handbook reference)",   &
&     "dhivlkmgkizohf-uhfffaoysa-n",                    &
&     "463-11-6"                                        /


!1-HEPTANOL
!--------------------------------------
data id_list(18) / 18 /
data name_list(18) / "1-heptanol" /
data eps(18) / 11.321000000000000_wp /
data refr(18) / 1.424900000000000_wp /
data A(18) / 0.370000000000000_wp /
data B(18) / 0.480000000000000_wp /
data g(18) / 38.500000000000000_wp /
data rho(18) / 818.70_wp /
data alias_list(:,18) / &
&     "1-heptanol",                                     &
&     "heptan-1-ol",                                    &
&     "heptyl alcohol",                                 &
&     "heptanol",                                       &
&     "n-heptanol",                                     &
&     "enanthic alcohol",                               &
&     "hydroxy heptane",                                &
&     "hydroxyheptane",                                 &
&     "hexyl carbinol",                                 &
&     "111-70-6"                                        /


!1-HEXANOL
!--------------------------------------
data id_list(19) / 19 /
data name_list(19) / "1-hexanol" /
data eps(19) / 12.510000000000000_wp /
data refr(19) / 1.417800000000000_wp /
data A(19) / 0.370000000000000_wp /
data B(19) / 0.480000000000000_wp /
data g(19) / 37.149999999999999_wp /
data rho(19) / 820.0_wp /
data alias_list(:,19) / &
&     "1-hexanol",                                      &
&     "hexyl alcohol",                                  &
&     "hexan-1-ol",                                     &
&     "hexanol",                                        &
&     "n-hexanol",                                      &
&     "amylcarbinol",                                   &
&     "c6 alcohol",                                     &
&     "alcohol(c6)",                                    &
&     "hexanol (van)",                                  &
&     "hexyl alcohol (natural)"                         /


!1-HEXENE
!--------------------------------------
data id_list(20) / 20 /
data name_list(20) / "1-hexene" /
data eps(20) / 2.071700000000000_wp /
data refr(20) / 1.383700000000000_wp /
data A(20) / 0.000000000000000_wp /
data B(20) / 0.070000000000000_wp /
data g(20) / 25.760000000000002_wp /
data rho(20) / 673.000000000000000_wp /
data alias_list(:,20) / &
&     "1-hexene",                                       &
&     "hex-1-ene",                                      &
&     "592-41-6",                                       &
&     "hexene-1",                                       &
&     "1-n-hexene",                                     &
&     "butylethylene",                                  &
&     "hexylene",                                       &
&     "butyl ethylene",                                 &
&     "dialene 6",                                      &
&     "linealene 6"                                     /


!1-HEXYNE
!--------------------------------------
data id_list(21) / 21 /
data name_list(21) / "1-hexyne" /
data eps(21) / 2.615000000000000_wp /
data refr(21) / 1.398900000000000_wp /
data A(21) / 0.120000000000000_wp /
data B(21) / 0.100000000000000_wp /
data g(21) / 28.789999999999999_wp /
data rho(21) / 715.000000000000000_wp /
data alias_list(:,21) / &
&     "1-hexyne",                                       &
&     "hex-1-yne",                                      &
&     "693-02-7",                                       &
&     "n-butylacetylene",                               &
&     "butylacetylene",                                 &
&     "hexyne",                                         &
&     "n-hexyne",                                       &
&     "nsc 9709",                                       &
&     "mfcd00009504",                                   &
&     "26856-30-4"                                      /


!1-IODOBUTANE
!--------------------------------------
data id_list(22) / 22 /
data name_list(22) / "1-iodobutane" /
data eps(22) / 6.173000000000000_wp /
data refr(22) / 1.500100000000000_wp /
data A(22) / 0.000000000000000_wp /
data B(22) / 0.150000000000000_wp /
data g(22) / 40.649999999999999_wp /
data rho(22) / 1617.000000000000000_wp /
data alias_list(:,22) / &
&     "1-iodobutane",                                   &
&     "butyl iodide",                                   &
&     "542-69-8",                                       &
&     "n-butyl iodide",                                 &
&     "",                                               &
&     "1-jodbutan",                                     &
&     "1-jodbutan [czech]",                             &
&     "nsc 8420",                                       &
&     "einecs 208-824-4",                               &
&     "ai3-52403"                                       /


!1-IODOHEXADECANE
!--------------------------------------
data id_list(23) / 23 /
data name_list(23) / "1-iodohexadecane" /
data eps(23) / 3.533800000000000_wp /
data refr(23) / 1.480600000000000_wp /
data A(23) / 0.000000000000000_wp /
data B(23) / 0.150000000000000_wp /
data g(23) / 46.479999999999997_wp /
data rho(23) / 730.000000000000000_wp /
data alias_list(:,23) / &
&     "1-iodohexadecane",                               &
&     "544-77-4",                                       &
&     "",                                               &
&     "jo95x48m8o",                                     &
&     "dtxsid0049317",                                  &
&     "einecs 208-879-4",                               &
&     "dtxcid9029273",                                  &
&     "hexadecane, 1iodo",                              &
&     "208-879-4",                                      &
&     "cetyl iodide"                                    /


!1-IODOPENTANE
!--------------------------------------
data id_list(24) / 24 /
data name_list(24) / "1-iodopentane" /
data eps(24) / 5.697300000000000_wp /
data refr(24) / 1.495900000000000_wp /
data A(24) / 0.000000000000000_wp /
data B(24) / 0.150000000000000_wp /
data g(24) / 41.560000000000002_wp /
data rho(24) / 1100.000000000000000_wp /
data alias_list(:,24) / &
&     "1-iodopentane",                                  &
&     "628-17-1",                                       &
&     "einecs 211-030-0",                               &
&     "n-c5h11i",                                       &
&     "dtxsid1060849",                                  &
&     "blxsfchwmbeskv-uhfffaoysa-",                     &
&     "npentyl iodide",                                 &
&     "namyl iodide",                                   &
&     "1jodpentan",                                     &
&     "1pentyl iodide"                                  /


!1-IODOPROPANE
!--------------------------------------
data id_list(25) / 25 /
data name_list(25) / "1-iodopropane" /
data eps(25) / 6.962600000000000_wp /
data refr(25) / 1.505800000000000_wp /
data A(25) / 0.000000000000000_wp /
data B(25) / 0.150000000000000_wp /
data g(25) / 41.450000000000003_wp /
data rho(25) / 1743.000000000000000_wp /
data alias_list(:,25) / &
&     "1-iodopropane",                                  &
&     "107-08-4",                                       &
&     "propyl iodide",                                  &
&     "",                                               &
&     "iodopropane",                                    &
&     "",                                               &
&     "1-jodpropan",                                    &
&     "propyliodide",                                   &
&     "26914-02-3",                                     &
&     "1-jodpropan [czech]"                             /


!1-NITROPROPANE
!--------------------------------------
data id_list(26) / 26 /
data name_list(26) / "1-nitropropane" /
data eps(26) / 23.730000000000000_wp /
data refr(26) / 1.401800000000000_wp /
data A(26) / 0.000000000000000_wp /
data B(26) / 0.310000000000000_wp /
data g(26) / 43.320000000000000_wp /
data rho(26) / 998.000000000000000_wp /
data alias_list(:,26) / &
&     "1-nitropropane",                                 &
&     "",                                               &
&     "nitropropane",                                   &
&     "",                                               &
&     "ccris 1329",                                     &
&     "n-nitropropane",                                 &
&     "108-03-2",                                       &
&     "hsdb 2526",                                      &
&     "1-nitropan",                                     &
&     "nsc 6363"                                        /


!1-NONANOL
!--------------------------------------
data id_list(27) / 27 /
data name_list(27) / "1-nonanol" /
data eps(27) / 8.599100000000000_wp /
data refr(27) / 1.433300000000000_wp /
data A(27) / 0.370000000000000_wp /
data B(27) / 0.480000000000000_wp /
data g(27) / 40.140000000000001_wp /
data rho(27) / 827.000000000000000_wp /
data alias_list(:,27) / &
&     "1-nonanol",                                      &
&     "nonan-1-ol",                                     &
&     "nonanol",                                        &
&     "nonyl alcohol",                                  &
&     "pelargonic alcohol",                             &
&     "alcohol c-9",                                    &
&     "143-08-8",                                       &
&     "fema no. 2789",                                  &
&     "nonyl-alcohol",                                  &
&     "hsdb 5145"                                       /


!1-OCTANOL
!--------------------------------------
data id_list(28) / 28 /
data name_list(28) / "1-octanol" /
data eps(28) / 9.862900000000000_wp /
data refr(28) / 1.429500000000000_wp /
data A(28) / 0.370000000000000_wp /
data B(28) / 0.480000000000000_wp /
data g(28) / 39.009999999999998_wp /
data rho(28) / 830.0_wp /
data alias_list(:,28) / &
&     "1-octanol",                                      &
&     "octan-1-ol",                                     &
&     "octanol",                                        &
&     "n-octanol",                                      &
&     "octyl alcohol",                                  &
&     "capryl alcohol",                                 &
&     "caprylic alcohol",                               &
&     "alcohol c-8",                                    &
&     "woctanol",                                       &
&     "1-octyl alcohol"                                 /


!1-PENTANOL
!--------------------------------------
data id_list(29) / 29 /
data name_list(29) / "1-pentanol" /
data eps(29) / 15.130000000000001_wp /
data refr(29) / 1.410100000000000_wp /
data A(29) / 0.370000000000000_wp /
data B(29) / 0.480000000000000_wp /
data g(29) / 36.500000000000000_wp /
data rho(29) / 818.000000000000000_wp /
data alias_list(:,29) / &
&     "1-pentanol",                                     &
&     "pentan-1-ol",                                    &
&     "amyl alcohol",                                   &
&     "pentanol",                                       &
&     "n-pentanol",                                     &
&     "n-pentyl alcohol",                               &
&     "pentasol",                                       &
&     "amylalkohol",                                    &
&     "pentanol (van)",                                 &
&     "30899-19-5"                                      /


!1-PENTENE
!--------------------------------------
data id_list(30) / 30 /
data name_list(30) / "1-pentene" /
data eps(30) / 1.990500000000000_wp /
data refr(30) / 1.371500000000000_wp /
data A(30) / 0.000000000000000_wp /
data B(30) / 0.070000000000000_wp /
data g(30) / 22.239999999999998_wp /
data rho(30) / 641.000000000000000_wp /
data alias_list(:,30) / &
&     "1-pentene",                                      &
&     "pent-1-ene",                                     &
&     "109-67-1",                                       &
&     "pentene",                                        &
&     "propylethylene",                                 &
&     "1-n-pentene",                                    &
&     ".alpha.-n-amylene",                              &
&     "pentene-1",                                      &
&     "mfcd00003567",                                   &
&     "alp8m0lu81"                                      /


!1-PROPANOL
!--------------------------------------
data id_list(31) / 31 /
data name_list(31) / "1-propanol" /
data eps(31) / 20.524000000000001_wp /
data refr(31) / 1.385000000000000_wp /
data A(31) / 0.370000000000000_wp /
data B(31) / 0.480000000000000_wp /
data g(31) / 33.570000000000000_wp /
data rho(31) / 803.000000000000000_wp /
data alias_list(:,31) / &
&     "1-propanol",                                     &
&     "propanol",                                       &
&     "propan-1-ol",                                    &
&     "propyl alcohol",                                 &
&     "n-propanol",                                     &
&     "71-23-8",                                        &
&     "n-propyl alcohol",                               &
&     "ethylcarbinol",                                  &
&     "optal",                                          &
&     "1-hydroxypropane"                                /


!2,2,2-TRIFLUOROETHANOL
!--------------------------------------
data id_list(32) / 32 /
data name_list(32) / "2,2,2-trifluoroethanol" /
data eps(32) / 26.725999999999999_wp /
data refr(32) / 1.290700000000000_wp /
data A(32) / 0.570000000000000_wp /
data B(32) / 0.250000000000000_wp /
data g(32) / 42.020000000000003_wp /
data rho(32) / 1390.000000000000000_wp /
data alias_list(:,32) / &
&     "2,2,2-trifluoroethanol",                         &
&     "75-89-8",                                        &
&     "trifluoroethanol",                               &
&     "",                                               &
&     "trifluoroethyl alcohol",                         &
&     "cf3ch2oh",                                       &
&     "perfluoro-1,1-dihydroethanol",                   &
&     "2,2,2-trifluoro-ethanol",                        &
&     "einecs 200-913-6",                               &
&     "unii-8t8i76kyf1"                                 /


!2,2,4-TRIMETHYLPENTANE
!--------------------------------------
data id_list(33) / 33 /
data name_list(33) / "2,2,4-trimethylpentane" /
data eps(33) / 1.935800000000000_wp /
data refr(33) / 1.391500000000000_wp /
data A(33) / 0.000000000000000_wp /
data B(33) / 0.000000000000000_wp /
data g(33) / 26.379999999999999_wp /
data rho(33) / 692.00_wp /
data alias_list(:,33) / &
&     "2,2,4-trimethylpentane",                         &
&     "isooctane",                                      &
&     "540-84-1",                                       &
&     "iso-octane",                                     &
&     "hsdb 5682",                                      &
&     "einecs 208-759-1",                               &
&     "unii-qab8f5669o",                                &
&     "nsc 39117",                                      &
&     "brn 1696876",                                    &
&     "isobutyltrimethylethane"                         /


!2,4-DIMETHYLPENTANE
!--------------------------------------
data id_list(34) / 34 /
data name_list(34) / "2,4-dimethylpentane" /
data eps(34) / 1.893900000000000_wp /
data refr(34) / 1.381500000000000_wp /
data A(34) / 0.000000000000000_wp /
data B(34) / 0.000000000000000_wp /
data g(34) / 25.420000000000002_wp /
data rho(34) / 626.000000000000000_wp /
data alias_list(:,34) / &
&     "2,4-dimethylpentane",                            &
&     "108-08-7",                                       &
&     "",                                               &
&     "diisopropylmethane",                             &
&     "unii-4jt8q9qohi",                                &
&     "4jt8q9qohi",                                     &
&     "2,4-dimethyl-pentane",                           &
&     "einecs 203-548-0",                               &
&     "nsc 61989",                                      &
&     "nsc-61989"                                       /


!2,4-DIMETHYLPYRIDINE
!--------------------------------------
data id_list(35) / 35 /
data name_list(35) / "2,4-dimethylpyridine" /
data eps(35) / 9.417600000000000_wp /
data refr(35) / 1.501000000000000_wp /
data A(35) / 0.000000000000000_wp /
data B(35) / 0.630000000000000_wp /
data g(35) / 46.859999999999999_wp /
data rho(35) / 945.000000000000000_wp /
data alias_list(:,35) / &
&     "2,4-lutidine",                                   &
&     "2,4-dimethylpyridine",                           &
&     "108-47-4",                                       &
&     "2,4-lutidene",                                   &
&     "nsc 2156",                                       &
&     "einecs 203-586-8",                               &
&     "unii-83903uj0ww",                                &
&     "brn 0001506",                                    &
&     "ai3-24281",                                      &
&     "nsc-2156"                                        /


!2,6-DIMETHYLPYRIDINE
!--------------------------------------
data id_list(36) / 36 /
data name_list(36) / "2,6-dimethylpyridine" /
data eps(36) / 7.173500000000000_wp /
data refr(36) / 1.495300000000000_wp /
data A(36) / 0.000000000000000_wp /
data B(36) / 0.630000000000000_wp /
data g(36) / 44.640000000000001_wp /
data rho(36) / 945.000000000000000_wp /
data alias_list(:,36) / &
&     "2,6-dimethylpyridine",                           &
&     "2,6-lutidine",                                   &
&     "lutidine",                                       &
&     "108-48-5",                                       &
&     "fema no. 3540",                                  &
&     "2,6-lutidene",                                   &
&     "einecs 203-587-3",                               &
&     "unii-15fq5d0t3p",                                &
&     "15fq5d0t3p",                                     &
&     "dtxsid7051557"                                   /


!2-BROMOPROPANE
!--------------------------------------
data id_list(37) / 37 /
data name_list(37) / "2-bromopropane" /
data eps(37) / 9.361000000000001_wp /
data refr(37) / 1.425100000000000_wp /
data A(37) / 0.000000000000000_wp /
data B(37) / 0.140000000000000_wp /
data g(37) / 33.460000000000001_wp /
data rho(37) / 1310.000000000000000_wp /
data alias_list(:,37) / &
&     "2-bromopropane",                                 &
&     "isopropyl bromide",                              &
&     "75-26-3",                                        &
&     "isopropylbromide",                               &
&     "sec-propyl bromide",                             &
&     "2-bromo-propane",                                &
&     "un2344",                                         &
&     "ccris 7919",                                     &
&     "hsdb 623",                                       &
&     "einecs 200-855-1"                                /


!2-BUTANOL
!--------------------------------------
data id_list(38) / 38 /
data name_list(38) / "2-butanol" /
data eps(38) / 15.944000000000001_wp /
data refr(38) / 1.397800000000000_wp /
data A(38) / 0.330000000000000_wp /
data B(38) / 0.560000000000000_wp /
data g(38) / 32.439999999999998_wp /
data rho(38) / 806.299999999999955_wp /
data alias_list(:,38) / &
&     "2-butanol",                                      &
&     "sec-butanol",                                    &
&     "butan-2-ol",                                     &
&     "sec-butyl alcohol",                              &
&     "2-hydroxybutane",                                &
&     "2-butyl alcohol",                                &
&     "butylene hydrate",                               &
&     "1-methyl-1-propanol",                            &
&     "1-methylpropyl alcohol",                         &
&     "methyl ethyl carbinol"                           /


!2-CHLOROBUTANE
!--------------------------------------
data id_list(39) / 39 /
data name_list(39) / "2-chlorobutane" /
data eps(39) / 8.393000000000001_wp /
data refr(39) / 1.397100000000000_wp /
data A(39) / 0.000000000000000_wp /
data B(39) / 0.120000000000000_wp /
data g(39) / 31.100000000000001_wp /
data rho(39) / 873.000000000000000_wp /
data alias_list(:,39) / &
&     "2-chlorobutane",                                 &
&     "sec-butyl chloride",                             &
&     "78-86-4",                                        &
&     "1-methylpropyl chloride",                        &
&     "2-chloro-butane",                                &
&     "(r)-2-chlorobutane",                             &
&     "einecs 201-151-7",                               &
&     "brn 1718770",                                    &
&     "ccris 9391",                                     &
&     "dtxsid9023966"                                   /


!2-HEPTANONE
!--------------------------------------
data id_list(40) / 40 /
data name_list(40) / "2-heptanone" /
data eps(40) / 11.657999999999999_wp /
data refr(40) / 1.408800000000000_wp /
data A(40) / 0.000000000000000_wp /
data B(40) / 0.510000000000000_wp /
data g(40) / 37.600000000000001_wp /
data rho(40) / 820.000000000000000_wp /
data alias_list(:,40) / &
&     "2-heptanone",                                    &
&     "heptan-2-one",                                   &
&     "110-43-0",                                       &
&     "methyl pentyl ketone",                           &
&     "butylacetone",                                   &
&     "amyl methyl ketone",                             &
&     "methyl amyl ketone",                             &
&     "methyl n-amyl ketone",                           &
&     "n-amyl methyl ketone",                           &
&     "n-pentyl methyl ketone"                          /


!2-HEXANONE
!--------------------------------------
data id_list(41) / 41 /
data name_list(41) / "2-hexanone" /
data eps(41) / 14.135999999999999_wp /
data refr(41) / 1.400700000000000_wp /
data A(41) / 0.000000000000000_wp /
data B(41) / 0.510000000000000_wp /
data g(41) / 36.630000000000003_wp /
data rho(41) / 811.000000000000000_wp /
data alias_list(:,41) / &
&     "2-hexanone",                                     &
&     "hexan-2-one",                                    &
&     "591-78-6",                                       &
&     "butyl methyl ketone",                            &
&     "methyl butyl ketone",                            &
&     "2-oxohexane",                                    &
&     "propylacetone",                                  &
&     "n-butyl methyl ketone",                          &
&     "methyl n-butyl ketone",                          &
&     "hexanone-2"                                      /


!2-METHOXYETHANOL
!--------------------------------------
data id_list(42) / 42 /
data name_list(42) / "2-methoxyethanol" /
data eps(42) / 17.199999999999999_wp /
data refr(42) / 1.402400000000000_wp /
data A(42) / 0.300000000000000_wp /
data B(42) / 0.840000000000000_wp /
data g(42) / 44.390000000000001_wp /
data rho(42) / 966.000000000000000_wp /
data alias_list(:,42) / &
&     "2-methoxyethanol",                               &
&     "109-86-4",                                       &
&     "methyl cellosolve",                              &
&     "ethylene glycol monomethyl ether",               &
&     "",                                               &
&     "methoxyethanol",                                 &
&     "monomethyl glycol",                              &
&     "2-methoxyethan-1-ol",                            &
&     "ethylene glycol methyl ether",                   &
&     "methylcellosolve"                                /


!2-METHYL-1-PROPANOL
!--------------------------------------
data id_list(43) / 43 /
data name_list(43) / "2-methyl-1-propanol" /
data eps(43) / 16.777000000000001_wp /
data refr(43) / 1.395500000000000_wp /
data A(43) / 0.370000000000000_wp /
data B(43) / 0.480000000000000_wp /
data g(43) / 32.380000000000003_wp /
data rho(43) / 802.000000000000000_wp /
data alias_list(:,43) / &
&     "isobutanol",                                     &
&     "2-methyl-1-propanol",                            &
&     "isobutyl alcohol",                               &
&     "2-methylpropan-1-ol",                            &
&     "78-83-1",                                        &
&     "2-methyl1-propanol",                          &
&     "isopropylcarbinol",                              &
&     "1-hydroxymethylpropane",                         &
&     "iso-butyl alcohol",                              &
&     "2-methylpropyl alcohol"                          /


!2-METHYL-2-PROPANOL
!--------------------------------------
data id_list(44) / 44 /
data name_list(44) / "2-methyl-2-propanol" /
data eps(44) / 12.470000000000001_wp /
data refr(44) / 1.387800000000000_wp /
data A(44) / 0.310000000000000_wp /
data B(44) / 0.600000000000000_wp /
data g(44) / 28.730000000000000_wp /
data rho(44) / 775.000000000000000_wp /
data alias_list(:,44) / &
&     "tert-butanol",                                   &
&     "tert-butyl alcohol",                             &
&     "2-methylpropan-2-ol",                            &
&     "75-65-0",                                        &
&     "2-methyl-2-propanol",                            &
&     "t-butyl alcohol",                                &
&     "trimethylcarbinol",                              &
&     "2-methyl2-propanol",                          &
&     "dimethylethanol",                                &
&     "tertiary-butanol"                                /


!2-METHYLPENTANE
!--------------------------------------
data id_list(45) / 45 /
data name_list(45) / "2-methylpentane" /
data eps(45) / 1.890000000000000_wp /
data refr(45) / 1.371500000000000_wp /
data A(45) / 0.000000000000000_wp /
data B(45) / 0.000000000000000_wp /
data g(45) / 24.300000000000001_wp /
data rho(45) / 659.000000000000000_wp /
data alias_list(:,45) / &
&     "2-methylpentane",                                &
&     "isohexane",                                      &
&     "107-83-5",                                       &
&     "",                                               &
&     "73513-42-5",                                     &
&     "2-methyl pentane",                               &
&     "1,1-dimethylbutane",                             &
&     "2-methyl-pentane",                               &
&     "dimethylpropylmethane",                          &
&     "methyl pentane"                                  /


!2-METHYLPYRIDINE
!--------------------------------------
data id_list(46) / 46 /
data name_list(46) / "2-methylpyridine" /
data eps(46) / 9.953300000000000_wp /
data refr(46) / 1.495700000000000_wp /
data A(46) / 0.000000000000000_wp /
data B(46) / 0.580000000000000_wp /
data g(46) / 47.500000000000000_wp /
data rho(46) / 944.000000000000000_wp /
data alias_list(:,46) / &
&     "2-methylpyridine",                               &
&     "2-picoline",                                     &
&     "109-06-8",                                       &
&     "o-picoline",                                     &
&     "alpha-picoline",                                 &
&     "",                                               &
&     "picoline",                                       &
&     "2-methyl-pyridine",                              &
&     "o-methylpyridine",                               &
&     ".alpha.-picoline"                                /


!2-NITROPROPANE
!--------------------------------------
data id_list(47) / 47 /
data name_list(47) / "2-nitropropane" /
data eps(47) / 25.654000000000000_wp /
data refr(47) / 1.394400000000000_wp /
data A(47) / 0.000000000000000_wp /
data B(47) / 0.330000000000000_wp /
data g(47) / 42.159999999999997_wp /
data rho(47) / 982.000000000000000_wp /
data alias_list(:,47) / &
&     "2-nitropropane",                                 &
&     "",                                               &
&     "sec-nitropropane",                               &
&     "2-nitro-propane",                                &
&     "isonitro propane",                               &
&     "",                                               &
&     "1-methylnitroethane",                            &
&     "nsc 5369",                                       &
&     "ccris 453",                                      &
&     "hsdb 1134"                                       /


!2-OCTANONE
!--------------------------------------
data id_list(48) / 48 /
data name_list(48) / "2-octanone" /
data eps(48) / 9.467800000000000_wp /
data refr(48) / 1.415100000000000_wp /
data A(48) / 0.000000000000000_wp /
data B(48) / 0.510000000000000_wp /
data g(48) / 37.289999999999999_wp /
data rho(48) / 820.000000000000000_wp /
data alias_list(:,48) / &
&     "2-octanone",                                     &
&     "octan-2-one",                                    &
&     "hexyl methyl ketone",                            &
&     "n-hexyl methyl ketone",                          &
&     "methyl hexyl ketone",                            &
&     "methyl n-hexyl ketone",                          &
&     "2-oxooctane",                                    &
&     "2-octanone (natural)",                           &
&     "fema no. 2802",                                  &
&     "fema number 2802"                                /


!2-PENTANONE
!--------------------------------------
data id_list(49) / 49 /
data name_list(49) / "2-pentanone" /
data eps(49) / 15.199999999999999_wp /
data refr(49) / 1.389500000000000_wp /
data A(49) / 0.000000000000000_wp /
data B(49) / 0.510000000000000_wp /
data g(49) / 33.460000000000001_wp /
data rho(49) / 806.000000000000000_wp /
data alias_list(:,49) / &
&     "2-pentanone",                                    &
&     "107-87-9",                                       &
&     "pentan-2-one",                                   &
&     "methyl propyl ketone",                           &
&     "ethyl acetone",                                  &
&     "pentanone-2",                                    &
&     "2-pentanone (natural)",                          &
&     "fema no. 2842",                                  &
&     "methyl n-propyl ketone",                         &
&     "n-propyl methyl ketone"                          /


!2-PROPANOL
!--------------------------------------
data id_list(50) / 50 /
data name_list(50) / "2-propanol" /
data eps(50) / 19.263999999999999_wp /
data refr(50) / 1.377600000000000_wp /
data A(50) / 0.330000000000000_wp /
data B(50) / 0.560000000000000_wp /
data g(50) / 30.129999999999999_wp /
data rho(50) / 785.000000000000000_wp /
data alias_list(:,50) / &
&     "isopropanol",                                    &
&     "isopropyl alcohol",                              &
&     "2-propanol",                                     &
&     "propan-2-ol",                                    &
&     "67-63-0",                                        &
&     "2-hydroxypropane",                               &
&     "alkolave",                                       &
&     "avantine",                                       &
&     "hartosol",                                       &
&     "dimethylcarbinol"                                /


!2-PROPEN-1-OL
!--------------------------------------
data id_list(51) / 51 /
data name_list(51) / "2-propen-1-ol" /
data eps(51) / 19.010999999999999_wp /
data refr(51) / 1.413500000000000_wp /
data A(51) / 0.380000000000000_wp /
data B(51) / 0.480000000000000_wp /
data g(51) / 36.390000000000001_wp /
data rho(51) / 854.000000000000000_wp /
data alias_list(:,51) / &
&     "allyl alcohol",                                  &
&     "107-18-6",                                       &
&     "prop-2-en-1-ol",                                 &
&     "vinylcarbinol",                                  &
&     "2-propenyl alcohol",                             &
&     "3-hydroxypropene",                               &
&     "2-propenol",                                     &
&     "1-propen-3-ol",                                  &
&     "vinyl carbinol",                                 &
&     "weed drench"                                     /


!E-2-PENTENE
!--------------------------------------
data id_list(52) / 52 /
data name_list(52) / "E-2-pentene" /
data eps(52) / 2.051000000000000_wp /
data refr(52) / 1.379300000000000_wp /
data A(52) / 0.000000000000000_wp /
data B(52) / 0.070000000000000_wp /
data g(52) / 23.620000000000001_wp /
data rho(52) / 649.000000000000000_wp /
data alias_list(:,52) / &
&     "trans-2-pentene",                                &
&     "646-04-8",                                       &
&     "(e)-2-pentene",                                  &
&     "(e)-pent-2-ene",                                 &
&     "2-pentene",                                      &
&     "2-pentene, (e)-",                                &
&     "trans-pent-2-ene",                               &
&     "2-pentene, (2e)-",                               &
&     "(2e)-2-pentene",                                 &
&     "pent-2-ene"                                      /


!3-METHYLPYRIDINE
!--------------------------------------
data id_list(53) / 53 /
data name_list(53) / "3-methylpyridine" /
data eps(53) / 11.645000000000000_wp /
data refr(53) / 1.504000000000000_wp /
data A(53) / 0.000000000000000_wp /
data B(53) / 0.540000000000000_wp /
data g(53) / 49.609999999999999_wp /
data rho(53) / 983.000000000000000_wp /
data alias_list(:,53) / &
&     "3-methylpyridine",                               &
&     "3-picoline",                                     &
&     "108-99-6",                                       &
&     "beta-picoline",                                  &
&     "m-picoline",                                     &
&     "m-methylpyridine",                               &
&     "b-picoline",                                     &
&     "beta-methylpyridine",                            &
&     "nsc 18251",                                      &
&     "3-mepy"                                          /


!3-PENTANONE
!--------------------------------------
data id_list(54) / 54 /
data name_list(54) / "3-pentanone" /
data eps(54) / 16.780000000000001_wp /
data refr(54) / 1.392400000000000_wp /
data A(54) / 0.000000000000000_wp /
data B(54) / 0.510000000000000_wp /
data g(54) / 35.609999999999999_wp /
data rho(54) / 813.000000000000000_wp /
data alias_list(:,54) / &
&     "3-pentanone",                                    &
&     "pentan-3-one",                                   &
&     "diethyl ketone",                                 &
&     "96-22-0",                                        &
&     "ethyl ketone",                                   &
&     "pentanone-3",                                    &
&     "nsc 8653",                                       &
&     "hsdb 5301",                                      &
&     "unii-9slz98m9nk",                                &
&     "einecs 202-490-3"                                /


!4-HEPTANONE
!--------------------------------------
data id_list(55) / 55 /
data name_list(55) / "4-heptanone" /
data eps(55) / 12.257000000000000_wp /
data refr(55) / 1.406900000000000_wp /
data A(55) / 0.000000000000000_wp /
data B(55) / 0.510000000000000_wp /
data g(55) / 35.979999999999997_wp /
data rho(55) / 817.000000000000000_wp /
data alias_list(:,55) / &
&     "4-heptanone",                                    &
&     "heptan-4-one",                                   &
&     "123-19-3",                                       &
&     "dipropyl ketone",                                &
&     "4-heptanone (natural)",                          &
&     "einecs 204-608-9",                               &
&     "un2710",                                         &
&     "unii-9bn582jq61",                                &
&     "brn 1699049",                                    &
&     "ai3-15181"                                       /


!4-METHYL-2-PENTANONE
!--------------------------------------
data id_list(56) / 56 /
data name_list(56) / "4-methyl-2-pentanone" /
data eps(56) / 12.887000000000000_wp /
data refr(56) / 1.396200000000000_wp /
data A(56) / 0.000000000000000_wp /
data B(56) / 0.510000000000000_wp /
data g(56) / 33.829999999999998_wp /
data rho(56) / 802.000000000000000_wp /
data alias_list(:,56) / &
&     "methyl isobutyl ketone",                         &
&     "4-methylpentan-2-one",                           &
&     "isopropylacetone",                               &
&     "isobutyl methyl ketone",                         &
&     "mibk",                                           &
&     "hexone",                                         &
&     "4-methyl-2-oxopentane",                          &
&     "methylisobutylketon",                            &
&     "isohexanone",                                    &
&     "shell mibk"                                      /


!4-METHYLPYRIDINE
!--------------------------------------
data id_list(57) / 57 /
data name_list(57) / "4-methylpyridine" /
data eps(57) / 11.957000000000001_wp /
data refr(57) / 1.503700000000000_wp /
data A(57) / 0.000000000000000_wp /
data B(57) / 0.540000000000000_wp /
data g(57) / 50.170000000000002_wp /
data rho(57) / 983.000000000000000_wp /
data alias_list(:,57) / &
&     "4-methylpyridine",                               &
&     "4-picoline",                                     &
&     "108-89-4",                                       &
&     "",                                               &
&     "gamma-picoline",                                 &
&     "p-picoline",                                     &
&     "p-methylpyridine",                               &
&     "4-methyl pyridine",                              &
&     "gamma-methylpyridine",                           &
&     "ba 35846"                                        /


!5-NONANONE
!--------------------------------------
data id_list(58) / 58 /
data name_list(58) / "5-nonanone" /
data eps(58) / 10.600000000000000_wp /
data refr(58) / 1.419500000000000_wp /
data A(58) / 0.000000000000000_wp /
data B(58) / 0.510000000000000_wp /
data g(58) / 37.829999999999998_wp /
data rho(58) / 826.000000000000000_wp /
data alias_list(:,58) / &
&     "5-nonanone",                                     &
&     "nonan-5-one",                                    &
&     "dibutyl ketone",                                 &
&     "di-n-butyl ketone",                              &
&     "hsdb 921",                                       &
&     "502-56-7",                                       &
&     "unii-v8b2y1bz3s",                                &
&     "einecs 207-946-5",                               &
&     "nsc 14761",                                      &
&     "(n-c4h9)2co"                                     /


!ACETIC ACID
!--------------------------------------
data id_list(59) / 59 /
data name_list(59) / "Acetic acid" /
data eps(59) / 6.252800000000000_wp /
data refr(59) / 1.372000000000000_wp /
data A(59) / 0.610000000000000_wp /
data B(59) / 0.440000000000000_wp /
data g(59) / 39.009999999999998_wp /
data rho(59) / 1044.599999999999909_wp /
data alias_list(:,59) / &
&     "acetic acid",                                    &
&     "ethanoic acid",                                  &
&     "ethylic acid",                                   &
&     "vinegar acid",                                   &
&     "methanecarboxylic acid",                         &
&     "essigsaeure",                                    &
&     "acide acetique",                                 &
&     "azijnzuur",                                      &
&     "aceticum acidum",                                &
&     "64-19-7"                                         /


!ACETONE
!--------------------------------------
data id_list(60) / 60 /
data name_list(60) / "Acetone" /
data eps(60) / 20.492999999999999_wp /
data refr(60) / 1.358800000000000_wp /
data A(60) / 0.040000000000000_wp /
data B(60) / 0.490000000000000_wp /
data g(60) / 33.770000000000003_wp /
data rho(60) / 784.500000000000000_wp /
data alias_list(:,60) / &
&     "acetone",                                        &
&     "67-64-1",                                        &
&     "propanone",                                      &
&     "dimethyl ketone",                                &
&     "propan-2-one",                                   &
&     "pyroacetic ether",                               &
&     "dimethylformaldehyde",                           &
&     "beta-ketopropane",                               &
&     "dimethylketal",                                  &
&     "chevron acetone"                                 /


!ACETONITRILE
!--------------------------------------
data id_list(61) / 61 /
data name_list(61) / "Acetonitrile" /
data eps(61) / 35.688000000000002_wp /
data refr(61) / 1.344200000000000_wp /
data A(61) / 0.070000000000000_wp /
data B(61) / 0.320000000000000_wp /
data g(61) / 41.250000000000000_wp /
data rho(61) / 785.700000000000045_wp /
data alias_list(:,61) / &
&     "acetonitrile",                                   &
&     "75-05-8",                                        &
&     "cyanomethane",                                   &
&     "methyl cyanide",                                 &
&     "ethanenitrile",                                  &
&     "ethyl nitrile",                                  &
&     "",                                               &
&     "methanecarbonitrile",                            &
&     "acetonitril",                                    &
&     "cyanure de methyl"                               /


!ACETOPHENONE
!--------------------------------------
data id_list(62) / 62 /
data name_list(62) / "Acetophenone" /
data eps(62) / 17.440000000000001_wp /
data refr(62) / 1.537200000000000_wp /
data A(62) / 0.000000000000000_wp /
data B(62) / 0.480000000000000_wp /
data g(62) / 56.189999999999998_wp /
data rho(62) / 1028.00_wp /
data alias_list(:,62) / &
&     "acetophenone",                                   &
&     "98-86-2",                                        &
&     "1-phenylethanone",                               &
&     "phenyl methyl ketone",                           &
&     "methyl phenyl ketone",                           &
&     "acetylbenzene",                                  &
&     "hypnone",                                        &
&     "benzoyl methide",                                &
&     "acetophenon",                                    &
&     "acetylbenzol"                                    /


!ANILINE
!--------------------------------------
data id_list(63) / 63 /
data name_list(63) / "Aniline" /
data eps(63) / 6.888200000000000_wp /
data refr(63) / 1.586300000000000_wp /
data A(63) / 0.260000000000000_wp /
data B(63) / 0.410000000000000_wp /
data g(63) / 60.619999999999997_wp /
data rho(63) / 1022.000000000000000_wp /
data alias_list(:,63) / &
&     "aniline",                                        &
&     "benzenamine",                                    &
&     "phenylamine",                                    &
&     "62-53-3",                                        &
&     "aminobenzene",                                   &
&     "aminophen",                                      &
&     "arylamine",                                      &
&     "kyanol",                                         &
&     "anilin",                                         &
&     "cyanol"                                          /


!ANISOLE
!--------------------------------------
data id_list(64) / 64 /
data name_list(64) / "Anisole" /
data eps(64) / 4.224700000000000_wp /
data refr(64) / 1.517400000000000_wp /
data A(64) / 0.000000000000000_wp /
data B(64) / 0.290000000000000_wp /
data g(64) / 50.520000000000003_wp /
data rho(64) / 995.000_wp /
data alias_list(:,64) / &
&     "anisole",                                        &
&     "100-66-3",                                       &
&     "methyl phenyl ether",                            &
&     "anisol",                                         &
&     "phenyl methyl ether",                            &
&     "phenoxymethane",                                 &
&     "anizol",                                         &
&     "phenol methyl ether",                            &
&     "ether, methyl phenyl",                           &
&     "benzene, methoxy"                                /


!BENZALDEHYDE
!--------------------------------------
data id_list(65) / 65 /
data name_list(65) / "Benzaldehyde" /
data eps(65) / 18.219999999999999_wp /
data refr(65) / 1.546300000000000_wp /
data A(65) / 0.000000000000000_wp /
data B(65) / 0.390000000000000_wp /
data g(65) / 54.689999999999998_wp /
data rho(65) / 1040.000000000000000_wp /
data alias_list(:,65) / &
&     "benzaldehyde",                                   &
&     "100-52-7",                                       &
&     "benzoic aldehyde",                               &
&     "phenylmethanal",                                 &
&     "benzenecarboxaldehyde",                          &
&     "benzenecarbonal",                                &
&     "benzenemethylal",                                &
&     "benzaldehyde ffc",                               &
&     "benzene carbaldehyde",                           &
&     "benzene carboxaldehyde"                          /


!BENZENE
!--------------------------------------
data id_list(66) / 66 /
data name_list(66) / "Benzene" /
data eps(66) / 2.270600000000000_wp /
data refr(66) / 1.501100000000000_wp /
data A(66) / 0.000000000000000_wp /
data B(66) / 0.140000000000000_wp /
data g(66) / 40.619999999999997_wp /
data rho(66) / 876.500000000000000_wp /
data alias_list(:,66) / &
&     "benzene",                                        &
&     "benzol",                                         &
&     "71-43-2",                                        &
&     "cyclohexatriene",                                &
&     "benzole",                                        &
&     "pyrobenzole",                                    &
&     "benzine",                                        &
&     "benzen",                                         &
&     "coal naphtha",                                   &
&     "pyrobenzol"                                      /


!BENZONITRILE
!--------------------------------------
data id_list(67) / 67 /
data name_list(67) / "Benzonitrile" /
data eps(67) / 25.591999999999999_wp /
data refr(67) / 1.528900000000000_wp /
data A(67) / 0.000000000000000_wp /
data B(67) / 0.330000000000000_wp /
data g(67) / 55.829999999999998_wp /
data rho(67) / 1000.0_wp /
data alias_list(:,67) / &
&     "benzonitrile",                                   &
&     "100-47-0",                                       &
&     "cyanobenzene",                                   &
&     "phenyl cyanide",                                 &
&     "benzenenitrile",                                 &
&     "benzoic acid nitrile",                           &
&     "",                                               &
&     "benzenecarbonitrile",                            &
&     "phenylcyanide",                                  &
&     "fenylkyanid"                                     /


!BENZYL ALCOHOL
!--------------------------------------
data id_list(68) / 68 /
data name_list(68) / "Benzyl alcohol" /
data eps(68) / 12.457000000000001_wp /
data refr(68) / 1.539600000000000_wp /
data A(68) / 0.330000000000000_wp /
data B(68) / 0.560000000000000_wp /
data g(68) / 52.960000000000001_wp /
data rho(68) / 1045.000000000000000_wp /
data alias_list(:,68) / &
&     "benzyl alcohol",                                 &
&     "phenylmethanol",                                 &
&     "100-51-6",                                       &
&     "phenylcarbinol",                                 &
&     "benzoyl alcohol",                                &
&     "benzenecarbinol",                                &
&     "phenylmethyl alcohol",                           &
&     "(hydroxymethyl)benzene",                         &
&     "phenolcarbinol",                                 &
&     "alcool benzylique"                               /


!BROMOBENZENE
!--------------------------------------
data id_list(69) / 69 /
data name_list(69) / "Bromobenzene" /
data eps(69) / 5.395400000000000_wp /
data refr(69) / 1.559700000000000_wp /
data A(69) / 0.000000000000000_wp /
data B(69) / 0.090000000000000_wp /
data g(69) / 50.719999999999999_wp /
data rho(69) / 1495.0_wp /
data alias_list(:,69) / &
&     "bromobenzene",                                   &
&     "108-86-1",                                       &
&     "phenyl bromide",                                 &
&     "monobromobenzene",                               &
&     "phbr",                                           &
&     "nci-c55492",                                     &
&     "c6h5br",                                         &
&     "bromobenzol",                                    &
&     "hsdb 47",                                        &
&     "phenylbromide"                                   /


!BROMOETHANE
!--------------------------------------
data id_list(70) / 70 /
data name_list(70) / "Bromoethane" /
data eps(70) / 9.010000000000000_wp /
data refr(70) / 1.423900000000000_wp /
data A(70) / 0.000000000000000_wp /
data B(70) / 0.120000000000000_wp /
data g(70) / 34.000000000000000_wp /
data rho(70) / 1460.000000000000000_wp /
data alias_list(:,70) / &
&     "bromoethane",                                    &
&     "74-96-4",                                        &
&     "ethyl bromide",                                  &
&     "",                                               &
&     "1-bromoethane",                                  &
&     "monobromoethane",                                &
&     "bromic ether",                                   &
&     "hydrobromic ether",                              &
&     "bromure d'ethyle",                               &
&     "etylu bromek"                                    /


!BROMOFORM
!--------------------------------------
data id_list(71) / 71 /
data name_list(71) / "Bromoform" /
data eps(71) / 4.248800000000000_wp /
data refr(71) / 1.600500000000000_wp /
data A(71) / 0.150000000000000_wp /
data B(71) / 0.060000000000000_wp /
data g(71) / 64.579999999999998_wp /
data rho(71) / 2891.199999999999818_wp /
data alias_list(:,71) / &
&     "bromoform",                                      &
&     "tribromomethane",                                &
&     "75-25-2",                                        &
&     "",                                               &
&     "tribrommethan",                                  &
&     "methenyl tribromide",                            &
&     "methyl tribromide",                              &
&     "bromoforme",                                     &
&     "bromoformio",                                    &
&     "tribrommethaan"                                  /


!BUTANAL
!--------------------------------------
data id_list(72) / 72 /
data name_list(72) / "Butanal" /
data eps(72) / 13.449999999999999_wp /
data refr(72) / 1.384300000000000_wp /
data A(72) / 0.000000000000000_wp /
data B(72) / 0.450000000000000_wp /
data g(72) / 35.060000000000002_wp /
data rho(72) / 800.000000000000000_wp /
data alias_list(:,72) / &
&     "butyraldehyde",                                  &
&     "butanal",                                        &
&     "123-72-8",                                       &
&     "n-butyraldehyde",                                &
&     "butyral",                                        &
&     "1-butanal",                                      &
&     "butyric aldehyde",                               &
&     "butaldehyde",                                    &
&     "butanaldehyde",                                  &
&     "butal"                                           /


!BUTANOIC ACID
!--------------------------------------
data id_list(73) / 73 /
data name_list(73) / "Butanoic acid" /
data eps(73) / 2.993100000000000_wp /
data refr(73) / 1.398000000000000_wp /
data A(73) / 0.600000000000000_wp /
data B(73) / 0.450000000000000_wp /
data g(73) / 37.490000000000002_wp /
data rho(73) / 1051.000000000000000_wp /
data alias_list(:,73) / &
&     "butyric acid",                                   &
&     "butanoic acid",                                  &
&     "107-92-6",                                       &
&     "n-butanoic acid",                                &
&     "propylformic acid",                              &
&     "ethylacetic acid",                               &
&     "1-propanecarboxylic acid",                       &
&     "butanic acid",                                   &
&     "1-butyric acid",                                 &
&     "buttersaeure"                                    /


!BUTANONE
!--------------------------------------
data id_list(74) / 74 /
data name_list(74) / "Butanone" /
data eps(74) / 18.245999999999999_wp /
data refr(74) / 1.378800000000000_wp /
data A(74) / 0.000000000000000_wp /
data B(74) / 0.510000000000000_wp /
data g(74) / 34.500000000000000_wp /
data rho(74) / 799.899999999999977_wp /
data alias_list(:,74) / &
&     "2-butanone",                                     &
&     "methyl ethyl ketone",                            &
&     "butan-2-one",                                    &
&     "78-93-3",                                        &
&     "ethyl methyl ketone",                            &
&     "methylethyl ketone",                             &
&     "meetco",                                         &
&     "methyl acetone",                                 &
&     "methylethylketone",                              &
&     "3-butanone"                                      /


!BUTYRONITRILE
!--------------------------------------
data id_list(75) / 75 /
data name_list(75) / "Butyronitrile" /
data eps(75) / 24.291000000000000_wp /
data refr(75) / 1.384200000000000_wp /
data A(75) / 0.000000000000000_wp /
data B(75) / 0.360000000000000_wp /
data g(75) / 38.750000000000000_wp /
data rho(75) / 794.000000000000000_wp /
data alias_list(:,75) / &
&     "butyronitrile",                                  &
&     "butanenitrile",                                  &
&     "n-butyronitrile",                                &
&     "n-propyl cyanide",                               &
&     "n-butanitrile",                                  &
&     "hsdb 5013",                                      &
&     "einecs 203-700-6",                               &
&     "unii-o3v36v0w0m",                                &
&     "un2411",                                         &
&     "109-74-0"                                        /


!BUTYL ETHANOATE
!--------------------------------------
data id_list(76) / 76 /
data name_list(76) / "Butyl ethanoate" /
data eps(76) / 4.994100000000000_wp /
data refr(76) / 1.394100000000000_wp /
data A(76) / 0.000000000000000_wp /
data B(76) / 0.450000000000000_wp /
data g(76) / 35.810000000000002_wp /
data rho(76) / 882.000000000000000_wp /
data alias_list(:,76) / &
&     "butyl acetate",                                  &
&     "123-86-4",                                       &
&     "n-butyl acetate",                                &
&     "acetic acid, butyl ester",                       &
&     "butyl ethanoate",                                &
&     "acetic acid butyl ester",                        &
&     "1-acetoxybutane",                                &
&     "butile(acetati di)",                             &
&     "butyl ester of acetic acid",                     &
&     "n-butyl acetate (natural)"                       /


!BUTYLAMINE
!--------------------------------------
data id_list(77) / 77 /
data name_list(77) / "Butylamine" /
data eps(77) / 4.617800000000000_wp /
data refr(77) / 1.403100000000000_wp /
data A(77) / 0.160000000000000_wp /
data B(77) / 0.610000000000000_wp /
data g(77) / 33.740000000000002_wp /
data rho(77) / 740.000000000000000_wp /
data alias_list(:,77) / &
&     "butylamine",                                     &
&     "n-butylamine",                                   &
&     "butan-1-amine",                                  &
&     "1-butanamine",                                   &
&     "1-aminobutane",                                  &
&     "1-butylamine",                                   &
&     "butanamine",                                     &
&     "n-butyl amine",                                  &
&     "nbutylamine",                                 &
&     "fema number 3130"                                /


!N-BUTYLBENZENE
!--------------------------------------
data id_list(78) / 78 /
data name_list(78) / "N-butylbenzene" /
data eps(78) / 2.360000000000000_wp /
data refr(78) / 1.489800000000000_wp /
data A(78) / 0.000000000000000_wp /
data B(78) / 0.150000000000000_wp /
data g(78) / 41.329999999999998_wp /
data rho(78) / 860.100000000000023_wp /
data alias_list(:,78) / &
&     "butylbenzene",                                   &
&     "n-butylbenzene",                                 &
&     "104-51-8",                                       &
&     "1-phenylbutane",                                 &
&     "",                                               &
&     "1-butylbenzene",                                 &
&     "hsdb 7211",                                      &
&     "nsc 8465",                                       &
&     "einecs 203-209-7",                               &
&     "brn 1903395"                                     /


!SEC-BUTYLBENZENE
!--------------------------------------
data id_list(79) / 79 /
data name_list(79) / "Sec-butylbenzene" /
data eps(79) / 2.344600000000000_wp /
data refr(79) / 1.489500000000000_wp /
data A(79) / 0.000000000000000_wp /
data B(79) / 0.160000000000000_wp /
data g(79) / 40.350000000000001_wp /
data rho(79) / 879.000000000000000_wp /
data alias_list(:,79) / &
&     "sec-butylbenzene",                               &
&     "2-phenylbutane",                                 &
&     "(1-methylpropyl)benzene",                        &
&     "benzene, (1-methylpropyl)-",                     &
&     "135-98-8",                                       &
&     "secondary butylbenzene",                         &
&     "butan-2-ylbenzene",                              &
&     "s-butylbenzene",                                 &
&     "hsdb 7212",                                      &
&     "unii-b70i0rsx3j"                                 /


!TERT-BUTYLBENZENE
!--------------------------------------
data id_list(80) / 80 /
data name_list(80) / "Tert-butylbenzene" /
data eps(80) / 2.344700000000000_wp /
data refr(80) / 1.492700000000000_wp /
data A(80) / 0.000000000000000_wp /
data B(80) / 0.160000000000000_wp /
data g(80) / 39.780000000000001_wp /
data rho(80) / 879.000000000000000_wp /
data alias_list(:,80) / &
&     "tert-butylbenzene",                              &
&     "98-06-6",                                        &
&     "t-butylbenzene",                                 &
&     "2-methyl-2-phenylpropane",                       &
&     "pseudobutylbenzene",                             &
&     "phenyltrimethylmethane",                         &
&     "trimethylphenylmethane",                         &
&     "",                                               &
&     "dimethylethylbenzene",                           &
&     "1,1-dimethylethylbenzene"                        /


!CARBON DISULFIDE
!--------------------------------------
data id_list(81) / 81 /
data name_list(81) / "Carbon disulfide" /
data eps(81) / 2.610500000000000_wp /
data refr(81) / 1.631900000000000_wp /
data A(81) / 0.000000000000000_wp /
data B(81) / 0.070000000000000_wp /
data g(81) / 45.450000000000003_wp /
data rho(81) / 1292.70_wp /
data alias_list(:,81) / &
&     "carbon disulfide",                               &
&     "75-15-0",                                        &
&     "carbon bisulfide",                               &
&     "carbon bisulphide",                              &
&     "dithiocarbonic anhydride",                       &
&     "schwefelkohlenstoff",                            &
&     "weeviltox",                                      &
&     "carbondisulfide",                                &
&     "cs2",                                            &
&     "sulphocarbonic anhydride"                        /


!CARBON TETRACHLORIDE
!--------------------------------------
data id_list(82) / 82 /
data name_list(82) / "Carbon tetrachloride" /
data eps(82) / 2.228000000000000_wp /
data refr(82) / 1.460100000000000_wp /
data A(82) / 0.000000000000000_wp /
data B(82) / 0.000000000000000_wp /
data g(82) / 38.039999999999999_wp /
data rho(82) / 1594.000000000000000_wp /
data alias_list(:,82) / &
&     "carbon tetrachloride",                           &
&     "tetrachloromethane",                             &
&     "56-23-5",                                        &
&     "perchloromethane",                               &
&     "tetrasol",                                       &
&     "benzinoform",                                    &
&     "necatorine",                                     &
&     "tetrafinol",                                     &
&     "vermoestricid",                                  &
&     "carbontet"                                         /


!CHLOROBENZENE
!--------------------------------------
data id_list(83) / 83 /
data name_list(83) / "Chlorobenzene" /
data eps(83) / 5.696800000000000_wp /
data refr(83) / 1.524100000000000_wp /
data A(83) / 0.000000000000000_wp /
data B(83) / 0.070000000000000_wp /
data g(83) / 47.479999999999997_wp /
data rho(83) / 1105.799999999999955_wp /
data alias_list(:,83) / &
&     "chlorobenzene",                                  &
&     "chlorobenzol",                                   &
&     "",                                               &
&     "chloro-benzene",                                 &
&     "monochlorobenzene",                              &
&     "chloro benzene",                                 &
&     "caswell no. 183a",                               &
&     "i p carrier t 40",                               &
&     "abluton t30",                                    &
&     "cp 27"                                           /


!CHLOROFORM
!--------------------------------------
data id_list(84) / 84 /
data name_list(84) / "Chloroform" /
data eps(84) / 4.711300000000000_wp /
data refr(84) / 1.445900000000000_wp /
data A(84) / 0.150000000000000_wp /
data B(84) / 0.020000000000000_wp /
data g(84) / 38.390000000000001_wp /
data rho(84) / 1478.799999999999955_wp /
data alias_list(:,84) / &
&     "chloroform",                                     &
&     "trichloromethane",                               &
&     "67-66-3",                                        &
&     "trichlormethan",                                 &
&     "formyl trichloride",                             &
&     "trichloroform",                                  &
&     "methenyl trichloride",                           &
&     "chloroforme",                                    &
&     "chcl3",                                          &
&     "r 20 (refrigerant)"                              /


!A-CHLOROTOLUENE
!--------------------------------------
data id_list(85) / 85 /
data name_list(85) / "A-chlorotoluene" /
data eps(85) / 6.717500000000000_wp /
data refr(85) / 1.539100000000000_wp /
data A(85) / 0.000000000000000_wp /
data B(85) / 0.330000000000000_wp /
data g(85) / 53.039999999999999_wp /
data rho(85) / 1100.000000000000000_wp /
data alias_list(:,85) / &
&     "benzyl chloride",                                &
&     "(chloromethyl)benzene",                          &
&     "100-44-7",                                       &
&     "chloromethylbenzene",                            &
&     "benzylchloride",                                 &
&     "alpha-chlorotoluene",                            &
&     "benzylchlorid",                                  &
&     "tolyl chloride",                                 &
&     "chlorure de benzyle",                            &
&     "alpha-chlortoluol"                               /


!O-CHLOROTOLUENE
!--------------------------------------
data id_list(86) / 86 /
data name_list(86) / "O-chlorotoluene" /
data eps(86) / 4.633100000000000_wp /
data refr(86) / 1.526800000000000_wp /
data A(86) / 0.000000000000000_wp /
data B(86) / 0.070000000000000_wp /
data g(86) / 47.430000000000000_wp /
data rho(86) / 879.000000000000000_wp /
data alias_list(:,86) / &
&     "2-chlorotoluene",                                &
&     "1-chloro-2-methylbenzene",                       &
&     "o-chlorotoluene",                                &
&     "95-49-8",                                        &
&     "",                                               &
&     "nsc 8766",                                       &
&     "un2238",                                         &
&     "ccris 7785",                                     &
&     "dtxsid8023977",                                  &
&     "hsdb 5291"                                       /


!M-CRESOL
!--------------------------------------
data id_list(87) / 87 /
data name_list(87) / "M-cresol" /
data eps(87) / 12.440000000000000_wp /
data refr(87) / 1.543800000000000_wp /
data A(87) / 0.570000000000000_wp /
data B(87) / 0.340000000000000_wp /
data g(87) / 51.369999999999997_wp /
data rho(87) / 1034.0_wp /
data alias_list(:,87) / &
&     "m-cresol",                                       &
&     "3-methylphenol",                                 &
&     "108-39-4",                                       &
&     "metacresol",                                     &
&     "",                                               &
&     "3-hydroxytoluene",                               &
&     "meta-cresol",                                    &
&     "3-cresol",                                       &
&     "m-methylphenol",                                 &
&     "m-kresol"                                        /


!O-CRESOL
!--------------------------------------
data id_list(88) / 88 /
data name_list(88) / "O-cresol" /
data eps(88) / 6.760000000000000_wp /
data refr(88) / 1.536100000000000_wp /
data A(88) / 0.520000000000000_wp /
data B(88) / 0.300000000000000_wp /
data g(88) / 53.109999999999999_wp /
data rho(88) / 1047.000000000000000_wp /
data alias_list(:,88) / &
&     "o-cresol",                                       &
&     "2-methylphenol",                                 &
&     "95-48-7",                                        &
&     "orthocresol",                                    &
&     "2-hydroxytoluene",                               &
&     "",                                               &
&     "2-cresol",                                       &
&     "o-methylphenol",                                 &
&     "o-cresylic acid",                                &
&     "o-oxytoluene"                                    /


!CYCLOHEXANE
!--------------------------------------
data id_list(89) / 89 /
data name_list(89) / "Cyclohexane" /
data eps(89) / 2.016500000000000_wp /
data refr(89) / 1.426600000000000_wp /
data A(89) / 0.000000000000000_wp /
data B(89) / 0.000000000000000_wp /
data g(89) / 35.479999999999997_wp /
data rho(89) / 773.899999999999977_wp /
data alias_list(:,89) / &
&     "cyclohexane",                                    &
&     "110-82-7",                                       &
&     "hexamethylene",                                  &
&     "hexahydrobenzene",                               &
&     "hexanaphthene",                                  &
&     "cyclohexan",                                     &
&     "cykloheksan",                                    &
&     "",                                               &
&     "cicloesano",                                     &
&     "cyclohexaan"                                     /


!CYCLOHEXANONE
!--------------------------------------
data id_list(90) / 90 /
data name_list(90) / "Cyclohexanone" /
data eps(90) / 15.619000000000000_wp /
data refr(90) / 1.450700000000000_wp /
data A(90) / 0.000000000000000_wp /
data B(90) / 0.560000000000000_wp /
data g(90) / 49.759999999999998_wp /
data rho(90) / 945.000000000000000_wp /
data alias_list(:,90) / &
&     "cyclohexanone",                                  &
&     "108-94-1",                                       &
&     "ketohexamethylene",                              &
&     "pimelic ketone",                                 &
&     "sextone",                                        &
&     "nadone",                                         &
&     "anone",                                          &
&     "cyclohexanon",                                   &
&     "hexanon",                                        &
&     "hytrol o"                                        /


!CYCLOPENTANE
!--------------------------------------
data id_list(91) / 91 /
data name_list(91) / "Cyclopentane" /
data eps(91) / 1.960800000000000_wp /
data refr(91) / 1.406500000000000_wp /
data A(91) / 0.000000000000000_wp /
data B(91) / 0.000000000000000_wp /
data g(91) / 31.489999999999998_wp /
data rho(91) / 746.000000000000000_wp /
data alias_list(:,91) / &
&     "cyclopentane",                                   &
&     "287-92-3",                                       &
&     "pentamethylene",                                 &
&     "ciclopentano",                                   &
&     "cyclopentan",                                    &
&     "zyklopentan",                                    &
&     "hsdb 62",                                        &
&     "cyclopentanes",                                  &
&     "unii-t86pb90rnu",                                &
&     "einecs 206-016-6"                                /


!CYCLOPENTANOL
!--------------------------------------
data id_list(92) / 92 /
data name_list(92) / "Cyclopentanol" /
data eps(92) / 16.989000000000001_wp /
data refr(92) / 1.453000000000000_wp /
data A(92) / 0.320000000000000_wp /
data B(92) / 0.560000000000000_wp /
data g(92) / 46.799999999999997_wp /
data rho(92) / 949.000000000000000_wp /
data alias_list(:,92) / &
&     "cyclopentanol",                                  &
&     "96-41-3",                                        &
&     "cyclopentyl alcohol",                            &
&     "hydroxycyclopentane",                            &
&     "1-cyclopentanol",                                &
&     "un2244",                                         &
&     "hsdb 2821",                                      &
&     "einecs 202-504-8",                               &
&     "unii-1l43q07tbu",                                &
&     "nsc 49117"                                       /


!CYCLOPENTANONE
!--------------------------------------
data id_list(93) / 93 /
data name_list(93) / "Cyclopentanone" /
data eps(93) / 13.580000000000000_wp /
data refr(93) / 1.436600000000000_wp /
data A(93) / 0.000000000000000_wp /
data B(93) / 0.520000000000000_wp /
data g(93) / 47.210000000000001_wp /
data rho(93) / 951.000000000000000_wp /
data alias_list(:,93) / &
&     "cyclopentanone",                                 &
&     "120-92-3",                                       &
&     "adipic ketone",                                  &
&     "ketocyclopentane",                               &
&     "ketopentamethylene",                             &
&     "dumasin",                                        &
&     "adipinketon",                                    &
&     "oxocyclopentane",                                &
&     "adipin keton",                                   &
&     "nsc 4122"                                        /


!DECALIN
!--------------------------------------
data id_list(94) / 94 /
data name_list(94) / "Decalin" /
data eps(94) / 2.196000000000000_wp /
data refr(94) / 1.475300000000000_wp /
data A(94) / 0.000000000000000_wp /
data B(94) / 0.000000000000000_wp /
data g(94) / 43.820000000000000_wp /
data rho(94) / 890.000000000000000_wp /
data alias_list(:,94) / &
&     "decalin",                                        &
&     "decahydronaphthalene",                           &
&     "91-17-8",                                        &
&     "perhydronaphthalene",                            &
&     "dekalin",                                        &
&     "naphthane",                                      &
&     "naphthan",                                       &
&     "dekalina",                                       &
&     "bicyclo[4.4.0]decane",                           &
&     ""                                                /


!CIS-DECALIN
!--------------------------------------
data id_list(95) / 95 /
data name_list(95) / "Cis-decalin" /
data eps(95) / 2.213900000000000_wp /
data refr(95) / 1.481000000000000_wp /
data A(95) / 0.000000000000000_wp /
data B(95) / 0.000000000000000_wp /
data g(95) / 45.450000000000003_wp /
data rho(95) / 890.000000000000000_wp /
data alias_list(:,95) / &
&     "cis-decalin",                                    &
&     "cis-decahydronaphthalene",                       &
&     "493-01-6",                                       &
&     "cis-bicyclo[4.4.0]decane",                       &
&     "",                                               &
&     "",                                               &
&     "",                                               &
&     "",                                               &
&     "",                                               &
&     ""                                                /


!N-DECANE
!--------------------------------------
data id_list(96) / 96 /
data name_list(96) / "N-decane" /
data eps(96) / 1.984600000000000_wp /
data refr(96) / 1.410200000000000_wp /
data A(96) / 0.000000000000000_wp /
data B(96) / 0.000000000000000_wp /
data g(96) / 33.640000000000001_wp /
data rho(96) / 730.000_wp /
data alias_list(:,96) / &
&     "decane",                                         &
&     "n-decane",                                       &
&     "124-18-5",                                       &
&     "decyl hydride",                                  &
&     "hsdb 63",                                        &
&     "ccris 653",                                      &
&     "nsc 8781",                                       &
&     "einecs 204-686-4",                               &
&     "un2247",                                         &
&     "brn 1696981"                                     /


!DIBROMOMETHANE
!--------------------------------------
data id_list(97) / 97 /
data name_list(97) / "Dibromomethane" /
data eps(97) / 7.227300000000000_wp /
data refr(97) / 1.542000000000000_wp /
data A(97) / 0.100000000000000_wp /
data B(97) / 0.100000000000000_wp /
data g(97) / 56.210000000000001_wp /
data rho(97) / 2477.000000000000000_wp /
data alias_list(:,97) / &
&     "dibromomethane",                                 &
&     "74-95-3",                                        &
&     "methylene bromide",                              &
&     "",                                               &
&     "methylene dibromide",                            &
&     "ch2br2",                                         &
&     "dibrommethan",                                   &
&     "methylenbromid",                                 &
&     "rcra waste number u068",                         &
&     "ccris 939"                                       /


!DIBUTYLETHER
!--------------------------------------
data id_list(98) / 98 /
data name_list(98) / "Dibutylether" /
data eps(98) / 3.047300000000000_wp /
data refr(98) / 1.399200000000000_wp /
data A(98) / 0.000000000000000_wp /
data B(98) / 0.450000000000000_wp /
data g(98) / 35.979999999999997_wp /
data rho(98) / 770.0_wp /
data alias_list(:,98) / &
&     "butyl ether",                                    &
&     "dibutyl ether",                                  &
&     "142-96-1",                                       &
&     "1-butoxybutane",                                 &
&     "butane, 1,1'-oxybis-",                           &
&     "n-butyl ether",                                  &
&     "1,1'-oxydibutane",                               &
&     "ccris 6010",                                     &
&     "hsdb 306",                                       &
&     "1-butoxy-butane"                                 /


!O-DICHLOROBENZENE
!--------------------------------------
data id_list(99) / 99 /
data name_list(99) / "O-dichlorobenzene" /
data eps(99) / 9.994899999999999_wp /
data refr(99) / 1.551500000000000_wp /
data A(99) / 0.000000000000000_wp /
data B(99) / 0.040000000000000_wp /
data g(99) / 52.719999999999999_wp /
data rho(99) / 1306.000000000000000_wp /
data alias_list(:,99) / &
&     "1,2-dichlorobenzene",                            &
&     "o-dichlorobenzene",                              &
&     "95-50-1",                                        &
&     "ortho-dichlorobenzene",                          &
&     "o-dichlorbenzol",                                &
&     "2-dichlorobenzene",                              &
&     "chloroben",                                      &
&     "dilantin db",                                    &
&     "odcb",                                           &
&     "o-dichlorobenzol"                                /


!E-1,2-DICHLOROETHENE
!--------------------------------------
data id_list(100) / 100 /
data name_list(100) / "E-1,2-dichloroethene" /
data eps(100) / 2.140000000000000_wp /
data refr(100) / 1.445400000000000_wp /
data A(100) / 0.090000000000000_wp /
data B(100) / 0.050000000000000_wp /
data g(100) / 37.130000000000003_wp /
data rho(100) / 1257.000000000000000_wp /
data alias_list(:,100) / &
&     "trans-1,2-dichloroethylene",                     &
&     "156-60-5",                                       &
&     "trans-1,2-dichloroethene",                       &
&     "(e)-1,2-dichloroethylene",                       &
&     "1,2-trans-dichloroethylene",                     &
&     "ethene, 1,2-dichloro-, (1e)-",                   &
&     "trans-acetylene dichloride",                     &
&     "ethene, 1,2-dichloro-, (e)-",                    &
&     "rcra waste number u079",                         &
&     "ethylene, 1,2-dichloro-, (e)-"                   /


!Z-1,2-DICHLOROETHENE
!--------------------------------------
data id_list(101) / 101 /
data name_list(101) / "Z-1,2-dichloroethene" /
data eps(101) / 9.199999999999999_wp /
data refr(101) / 1.449000000000000_wp /
data A(101) / 0.110000000000000_wp /
data B(101) / 0.050000000000000_wp /
data g(101) / 39.799999999999997_wp /
data rho(101) / 1284.000000000000000_wp /
data alias_list(:,101) / &
&     "cis-1,2-dichloroethylene",                       &
&     "cis-1,2-dichloroethene",                         &
&     "156-59-2",                                       &
&     "(z)-1,2-dichloroethylene",                       &
&     "cis-dichloroethylene",                           &
&     "acetalyne dichloride",                           &
&     "acetylene dichloride, cis-",                     &
&     "ethene, 1,2-dichloro-, (z)-",                    &
&     "ethylene, 1,2-dichloro-, (z)-",                  &
&     "cis-1,2-dce"                                     /


!DICHLOROMETHANE
!--------------------------------------
data id_list(102) / 102 /
data name_list(102) / "Dichloromethane" /
data eps(102) / 8.930000000000000_wp /
data refr(102) / 1.424200000000000_wp /
data A(102) / 0.100000000000000_wp /
data B(102) / 0.050000000000000_wp /
data g(102) / 39.149999999999999_wp /
data rho(102) / 1322.000000000000000_wp /
data alias_list(:,102) / &
&     "dichloromethane",                                &
&     "methylene chloride",                             &
&     "75-09-2",                                        &
&     "methylene dichloride",                           &
&     "",                                               &
&     "methylene bichloride",                           &
&     "methane dichloride",                             &
&     "ch2cl2",                                         &
&     "dcm",                                            &
&     "narkotil"                                        /


!DIETHYL ETHER
!--------------------------------------
data id_list(103) / 103 /
data name_list(103) / "Diethyl ether" /
data eps(103) / 4.240000000000000_wp /
data refr(103) / 1.352600000000000_wp /
data A(103) / 0.000000000000000_wp /
data B(103) / 0.410000000000000_wp /
data g(103) / 23.960000000000001_wp /
data rho(103) / 713.000000000000000_wp /
data alias_list(:,103) / &
&     "diethyl ether",                                  &
&     "ether",                                          &
&     "ethyl ether",                                    &
&     "60-29-7",                                        &
&     "pronarcol",                                      &
&     "diethyl oxide",                                  &
&     "aether",                                         &
&     "diethylether",                                   &
&     "solvent ether",                                  &
&     "3-oxapentane"                                    /


!DIETHYL SULFIDE
!--------------------------------------
data id_list(104) / 104 /
data name_list(104) / "Diethyl sulfide" /
data eps(104) / 5.723000000000000_wp /
data refr(104) / 1.443000000000000_wp /
data A(104) / 0.000000000000000_wp /
data B(104) / 0.320000000000000_wp /
data g(104) / 35.359999999999999_wp /
data rho(104) / 837.000000000000000_wp /
data alias_list(:,104) / &
&     "diethyl sulfide",                                &
&     "ethyl sulfide",                                  &
&     "352-93-2",                                       &
&     "ethyl thioether",                                &
&     "ethylsulfanylethane",                            &
&     "3-thiapentane",                                  &
&     "thioethyl ether",                                &
&     "ethylthioethane",                                &
&     "diethylthioether",                               &
&     "diethyl sulphide"                                /


!DIETHYLAMINE
!--------------------------------------
data id_list(105) / 105 /
data name_list(105) / "Diethylamine" /
data eps(105) / 3.576600000000000_wp /
data refr(105) / 1.386400000000000_wp /
data A(105) / 0.080000000000000_wp /
data B(105) / 0.690000000000000_wp /
data g(105) / 28.570000000000000_wp /
data rho(105) / 707.000000000000000_wp /
data alias_list(:,105) / &
&     "diethylamine",                                   &
&     "109-89-7",                                       &
&     "n-ethylethanamine",                              &
&     "n,n-diethylamine",                               &
&     "diethamine",                                     &
&     "diaethylamin",                                   &
&     "dietilamina",                                    &
&     "dwuetyloamina",                                  &
&     "et2nh",                                          &
&     "ccris 4792"                                      /


!DIIODOMETHANE
!--------------------------------------
data id_list(106) / 106 /
data name_list(106) / "Diiodomethane" /
data eps(106) / 5.320000000000000_wp /
data refr(106) / 1.742500000000000_wp /
data A(106) / 0.050000000000000_wp /
data B(106) / 0.230000000000000_wp /
data g(106) / 95.250000000000000_wp /
data rho(106) / 3325.00_wp /
data alias_list(:,106) / &
&     "diiodomethane",                                  &
&     "75-11-6",                                        &
&     "methylene iodide",                               &
&     "",                                               &
&     "methylene diiodide",                             &
&     "mi-gee",                                         &
&     "dijodmethan",                                    &
&     "methylenjodid",                                  &
&     "diiodo-methane",                                 &
&     "ch2i2"                                           /


!DIISOPROPYL ETHER
!--------------------------------------
data id_list(107) / 107 /
data name_list(107) / "Diisopropyl ether" /
data eps(107) / 3.380000000000000_wp /
data refr(107) / 1.367900000000000_wp /
data A(107) / 0.000000000000000_wp /
data B(107) / 0.410000000000000_wp /
data g(107) / 24.859999999999999_wp /
data rho(107) / 724.000000000000000_wp /
data alias_list(:,107) / &
&     "diisopropyl ether",                              &
&     "isopropyl ether",                                &
&     "108-20-3",                                       &
&     "propane, 2,2'-oxybis-",                          &
&     "isopropylether",                                 &
&     "2,2'-oxydipropane",                              &
&     "2,2'-oxybis-propane",                            &
&     "hsdb 624",                                       &
&     "diisopropyl-ether",                              &
&     "diiospropyl ether"                               /


!CIS-1,2-DIMETHYLCYCLOHEXANE
!--------------------------------------
data id_list(108) / 108 /
data name_list(108) / "Cis-1,2-dimethylcyclohexane" /
data eps(108) / 2.060000000000000_wp /
data refr(108) / 1.436000000000000_wp /
data A(108) / 0.000000000000000_wp /
data B(108) / 0.000000000000000_wp /
data g(108) / 36.280000000000001_wp /
data rho(108) / 779.000000000000000_wp /
data alias_list(:,108) / &
&     "cis-1,2-dimethylcyclohexane",                    &
&     "2207-01-4",                                      &
&     "1,cis-2-dimethylcyclohexane",                    &
&     "cyclohexane, 1,2-dimethyl-, cis-",               &
&     "e1o9n97rtz",                                     &
&     "1,2-dimethylcyclohexane, cis-",                  &
&     "cyclohexane, 1,2-dimethyl-, (1r,2s)-rel-",       &
&     "nsc-74157",                                      &
&     "einecs 218-621-2",                               &
&     "nsc 74157"                                       /


!DIMETHYL DISULFIDE
!--------------------------------------
data id_list(109) / 109 /
data name_list(109) / "Dimethyl disulfide" /
data eps(109) / 9.600000000000000_wp /
data refr(109) / 1.528900000000000_wp /
data A(109) / 0.000000000000000_wp /
data B(109) / 0.280000000000000_wp /
data g(109) / 48.060000000000002_wp /
data rho(109) / 1092.000000000000000_wp /
data alias_list(:,109) / &
&     "dimethyl disulfide",                             &
&     "624-92-0",                                       &
&     "dimethyldisulfide",                              &
&     "dimethyl disulphide",                            &
&     "dmds",                                           &
&     "disulfide, dimethyl",                            &
&     "(methyldisulfanyl)methane",                      &
&     "2,3-dithiabutane",                               &
&     "methyldisulfide",                                &
&     "methyldithiomethane"                             /


!N,N-DIMETHYLACETAMIDE
!--------------------------------------
data id_list(110) / 110 /
data name_list(110) / "N,n-dimethylacetamide" /
data eps(110) / 37.780999999999999_wp /
data refr(110) / 1.438000000000000_wp /
data A(110) / 0.000000000000000_wp /
data B(110) / 0.780000000000000_wp /
data g(110) / 47.619999999999997_wp /
data rho(110) / 943.000000000000000_wp /
data alias_list(:,110) / &
&     "n,n-dimethylacetamide",                          &
&     "dimethylacetamide",                              &
&     "dmac",                                           &
&     "acetdimethylamide",                              &
&     "dimethyl acetamide",                             &
&     "n,n-dimethyl acetamide",                         &
&     "dimethylamide acetate",                          &
&     "n,n-dimethylethanamide",                         &
&     "dimethylacetone amide",                          &
&     "acetic acid, dimethylamide"                      /


!N,N-DIMETHYLFORMAMIDE
!--------------------------------------
data id_list(111) / 111 /
data name_list(111) / "N,n-dimethylformamide" /
data eps(111) / 37.219000000000001_wp /
data refr(111) / 1.430500000000000_wp /
data A(111) / 0.000000000000000_wp /
data B(111) / 0.740000000000000_wp /
data g(111) / 49.560000000000002_wp /
data rho(111) / 944.500000000000000_wp /
data alias_list(:,111) / &
&     "n,n-dimethylformamide",                          &
&     "dimethylformamide",                              &
&     "68-12-2",                                        &
&     "dimethyl formamide",                             &
&     "n,n-dimethylmethanamide",                        &
&     "n-formyldimethylamine",                          &
&     "formamide, n,n-dimethyl-",                       &
&     "dimethylformamid",                               &
&     "dmf",                                            &
&     "dimetilformamide"                                /


!DIMETHYLSULFOXIDE
!--------------------------------------
data id_list(112) / 112 /
data name_list(112) / "Dimethylsulfoxide" /
data eps(112) / 46.826000000000001_wp /
data refr(112) / 1.417000000000000_wp /
data A(112) / 0.000000000000000_wp /
data B(112) / 0.880000000000000_wp /
data g(112) / 61.780000000000001_wp /
data rho(112) / 1100.4_wp /
data alias_list(:,112) / &
&     "dimethyl sulfoxide",                             &
&     "dmso",                                           &
&     "methyl sulfoxide",                               &
&     "methylsulfinylmethane",                          &
&     "dimethylsulfoxide",                              &
&     "sulfinylbismethane",                          &
&     "demasorb",                                       &
&     "demsodrox",                                      &
&     "demavet",                                        &
&     "domoso"                                          /


!DIPHENYLETHER
!--------------------------------------
data id_list(113) / 113 /
data name_list(113) / "Diphenylether" /
data eps(113) / 3.730000000000000_wp /
data refr(113) / 1.578700000000000_wp /
data A(113) / 0.000000000000000_wp /
data B(113) / 0.200000000000000_wp /
data g(113) / 38.500000000000000_wp /
data rho(113) / 879.000000000000000_wp /
data alias_list(:,113) / &
&     "diphenyl ether",                                 &
&     "diphenyl oxide",                                 &
&     "101-84-8",                                       &
&     "phenyl ether",                                   &
&     "phenoxybenzene",                                 &
&     "oxydibenzene",                                   &
&     "phenyl oxide",                                   &
&     "diphenylether",                                  &
&     "oxybisbenzene",                                  &
&     "1,1'-oxydibenzene"                               /


!DIPROPYLAMINE
!--------------------------------------
data id_list(114) / 114 /
data name_list(114) / "Dipropylamine" /
data eps(114) / 2.911200000000000_wp /
data refr(114) / 1.405000000000000_wp /
data A(114) / 0.080000000000000_wp /
data B(114) / 0.690000000000000_wp /
data g(114) / 32.109999999999999_wp /
data rho(114) / 738.000000000000000_wp /
data alias_list(:,114) / &
&     "dipropylamine",                                  &
&     "142-84-7",                                       &
&     "di-n-propylamine",                               &
&     "n-propyl1-propanamine",                       &
&     "n-dipropylamine",                                &
&     "n-propyl-1-propanamine",                         &
&     "rcra waste number u110",                         &
&     "ccris 4805",                                     &
&     "hsdb 2644",                                      &
&     "einecs 205-565-9"                                /


!N-DODECANE
!--------------------------------------
data id_list(115) / 115 /
data name_list(115) / "N-dodecane" /
data eps(115) / 2.006000000000000_wp /
data refr(115) / 1.421600000000000_wp /
data A(115) / 0.000000000000000_wp /
data B(115) / 0.000000000000000_wp /
data g(115) / 35.850000000000001_wp /
data rho(115) / 749.50_wp /
data alias_list(:,115) / &
&     "dodecane",                                       &
&     "n-dodecane",                                     &
&     "112-40-3",                                       &
&     "dihexyl",                                        &
&     "bihexyl",                                        &
&     "adakane 12",                                     &
&     "n-dodecan",                                      &
&     "duodecane",                                      &
&     "ba 51-090453",                                   &
&     "nsc 8714"                                        /


!ETHANETHIOL
!--------------------------------------
data id_list(116) / 116 /
data name_list(116) / "Ethanethiol" /
data eps(116) / 6.667000000000000_wp /
data refr(116) / 1.431000000000000_wp /
data A(116) / 0.000000000000000_wp /
data B(116) / 0.240000000000000_wp /
data g(116) / 33.219999999999999_wp /
data rho(116) / 839.000000000000000_wp /
data alias_list(:,116) / &
&     "ethanethiol",                                    &
&     "ethyl mercaptan",                                &
&     "75-08-1",                                        &
&     "mercaptoethane",                                 &
&     "ethyl sulfhydrate",                              &
&     "thioethanol",                                    &
&     "ethyl thioalcohol",                              &
&     "thioethyl alcohol",                              &
&     "ethyl hydrosulfide",                             &
&     "aethylmercaptan"                                 /


!ETHANOL
!--------------------------------------
data id_list(117) / 117 /
data name_list(117) / "Ethanol" /
data eps(117) / 24.852000000000000_wp /
data refr(117) / 1.361100000000000_wp /
data A(117) / 0.370000000000000_wp /
data B(117) / 0.480000000000000_wp /
data g(117) / 31.620000000000001_wp /
data rho(117) / 789.000000000000000_wp /
data alias_list(:,117) / &
&     "ethanol",                                        &
&     "ethyl alcohol",                                  &
&     "alcohol",                                        &
&     "64-17-5",                                        &
&     "grain alcohol",                                  &
&     "methylcarbinol",                                 &
&     "ethyl hydrate",                                  &
&     "tecsol",                                         &
&     "algrain",                                        &
&     "anhydrol"                                        /


!ETHYL ACETATE
!--------------------------------------
data id_list(118) / 118 /
data name_list(118) / "Ethyl acetate" /
data eps(118) / 5.986700000000000_wp /
data refr(118) / 1.372300000000000_wp /
data A(118) / 0.000000000000000_wp /
data B(118) / 0.450000000000000_wp /
data g(118) / 33.670000000000002_wp /
data rho(118) / 895.000000000000000_wp /
data alias_list(:,118) / &
&     "ethyl acetate",                                  &
&     "141-78-6",                                       &
&     "ethyl ethanoate",                                &
&     "acetic acid ethyl ester",                        &
&     "acetoxyethane",                                  &
&     "vinegar naphtha",                                &
&     "acetic ether",                                   &
&     "ethyl acetic ester",                             &
&     "acetic acid, ethyl ester",                       &
&     "ethylacetate"                                    /


!ETHYL METHANOATE
!--------------------------------------
data id_list(119) / 119 /
data name_list(119) / "Ethyl methanoate" /
data eps(119) / 8.331000000000000_wp /
data refr(119) / 1.359900000000000_wp /
data A(119) / 0.000000000000000_wp /
data B(119) / 0.380000000000000_wp /
data g(119) / 33.359999999999999_wp /
data rho(119) / 974.000000000000000_wp /
data alias_list(:,119) / &
&     "ethyl formate",                                  &
&     "109-94-4",                                       &
&     "formic acid, ethyl ester",                       &
&     "areginal",                                       &
&     "ethyl methanoate",                               &
&     "ethyl formic ester",                             &
&     "aethylformiat",                                  &
&     "formic ether",                                   &
&     "ethylformiaat",                                  &
&     "mrowczan etylu"                                  /


!ETHYL PHENYL ETHER
!--------------------------------------
data id_list(120) / 120 /
data name_list(120) / "Ethyl phenyl ether" /
data eps(120) / 4.179700000000000_wp /
data refr(120) / 1.507600000000000_wp /
data A(120) / 0.000000000000000_wp /
data B(120) / 0.320000000000000_wp /
data g(120) / 46.649999999999999_wp /
data rho(120) / 967.0_wp /
data alias_list(:,120) / &
&     "phenetole",                                      &
&     "ethoxybenzene",                                  &
&     "103-73-1",                                       &
&     "",                                               &
&     "ethyl phenyl ether",                             &
&     "phenyl ethyl ether",                             &
&     "benzene, ethoxy",                                &
&     "phenoxyethane",                                  &
&     "mfcd00009090",                                   &
&     "ethyl phenylether"                               /


!ETHYLBENZENE
!--------------------------------------
data id_list(121) / 121 /
data name_list(121) / "Ethylbenzene" /
data eps(121) / 2.433900000000000_wp /
data refr(121) / 1.495900000000000_wp /
data A(121) / 0.000000000000000_wp /
data B(121) / 0.150000000000000_wp /
data g(121) / 41.380000000000003_wp /
data rho(121) / 867.000000000000000_wp /
data alias_list(:,121) / &
&     "ethylbenzene",                                   &
&     "100-41-4",                                       &
&     "phenylethane",                                   &
&     "",                                               &
&     "ethylbenzol",                                    &
&     "ethyl benzene",                                  &
&     "aethylbenzol",                                   &
&     "ethylenzene",                                    &
&     "ethylbenzeen",                                   &
&     "etilbenzene"                                     /


!FLUOROBENZENE
!--------------------------------------
data id_list(122) / 122 /
data name_list(122) / "Fluorobenzene" /
data eps(122) / 5.420000000000000_wp /
data refr(122) / 1.468400000000000_wp /
data A(122) / 0.000000000000000_wp /
data B(122) / 0.100000000000000_wp /
data g(122) / 38.369999999999997_wp /
data rho(122) / 1022.500000000000000_wp /
data alias_list(:,122) / &
&     "fluorobenzene",                                  &
&     "462-06-6",                                       &
&     "",                                               &
&     "monofluorobenzene",                              &
&     "phenyl fluoride",                                &
&     "fluorbenzol",                                    &
&     "einecs 207-321-7",                               &
&     "nsc 68416",                                      &
&     "chebi:5115",                                     &
&     "g3tsz68k12"                                      /


!FORMAMIDE
!--------------------------------------
data id_list(123) / 123 /
data name_list(123) / "Formamide" /
data eps(123) / 108.939999999999998_wp /
data refr(123) / 1.447200000000000_wp /
data A(123) / 0.620000000000000_wp /
data B(123) / 0.600000000000000_wp /
data g(123) / 82.079999999999998_wp /
data rho(123) / 1133.00_wp /
data alias_list(:,123) / &
&     "formamide",                                      &
&     "75-12-7",                                        &
&     "methanamide",                                    &
&     "carbamaldehyde",                                 &
&     "formic acid, amide",                             &
&     "formamid",                                       &
&     "methanoic acid, amide",                          &
&     "amid kyseliny mravenci",                         &
&     "nsc 748",                                        &
&     "hsdb 88"                                         /


!FORMIC ACID
!--------------------------------------
data id_list(124) / 124 /
data name_list(124) / "Formic acid" /
data eps(124) / 51.100000000000001_wp /
data refr(124) / 1.371400000000000_wp /
data A(124) / 0.750000000000000_wp /
data B(124) / 0.380000000000000_wp /
data g(124) / 53.439999999999998_wp /
data rho(124) / 1220.000000000000000_wp /
data alias_list(:,124) / &
&     "formic acid",                                    &
&     "64-18-6",                                        &
&     "methanoic acid",                                 &
&     "formylic acid",                                  &
&     "aminic acid",                                    &
&     "bilorin",                                        &
&     "hydrogen carboxylic acid",                       &
&     "formisoton",                                     &
&     "formira",                                        &
&     "myrmicyl"                                        /


!N-HEPTANE
!--------------------------------------
data id_list(125) / 125 /
data name_list(125) / "N-heptane" /
data eps(125) / 1.911300000000000_wp /
data refr(125) / 1.387800000000000_wp /
data A(125) / 0.000000000000000_wp /
data B(125) / 0.000000000000000_wp /
data g(125) / 28.280000000000001_wp /
data rho(125) / 684.000000000000000_wp /
data alias_list(:,125) / &
&     "heptane",                                        &
&     "n-heptane",                                      &
&     "142-82-5",                                       &
&     "heptan",                                         &
&     "heptyl hydride",                                 &
&     "dipropyl methane",                               &
&     "dipropylmethane",                                &
&     "gettysolve-c",                                   &
&     "skellysolve c",                                  &
&     "heptanen"                                        /


!N-HEXADECANE
!--------------------------------------
data id_list(126) / 126 /
data name_list(126) / "N-hexadecane" /
data eps(126) / 2.040200000000000_wp /
data refr(126) / 1.434500000000000_wp /
data A(126) / 0.000000000000000_wp /
data B(126) / 0.000000000000000_wp /
data g(126) / 38.930000000000000_wp /
data rho(126) / 770.0_wp /
data alias_list(:,126) / &
&     "hexadecane",                                     &
&     "n-hexadecane",                                   &
&     "544-76-3",                                       &
&     "n-cetane",                                       &
&     "hexadekan",                                      &
&     "cetan",                                          &
&     "zetan",                                          &
&     "ccris 5833",                                     &
&     "hsdb 6854",                                      &
&     "f8z00shp6q"                                      /


!N-HEXANE
!--------------------------------------
data id_list(127) / 127 /
data name_list(127) / "N-hexane" /
data eps(127) / 1.881900000000000_wp /
data refr(127) / 1.374900000000000_wp /
data A(127) / 0.000000000000000_wp /
data B(127) / 0.000000000000000_wp /
data g(127) / 25.750000000000000_wp /
data rho(127) / 659.000000000000000_wp /
data alias_list(:,127) / &
&     "hexane",                                         &
&     "n-hexane",                                       &
&     "110-54-3",                                       &
&     "esani",                                          &
&     "gettysolve-b",                                   &
&     "skellysolve b",                                  &
&     "hexyl hydride",                                  &
&     "hexan",                                          &
&     "dipropyl",                                       &
&     "hexanen"                                         /


!HEXANOIC ACID
!--------------------------------------
data id_list(128) / 128 /
data name_list(128) / "Hexanoic acid" /
data eps(128) / 2.600000000000000_wp /
data refr(128) / 1.416300000000000_wp /
data A(128) / 0.600000000000000_wp /
data B(128) / 0.450000000000000_wp /
data g(128) / 39.649999999999999_wp /
data rho(128) / 1051.000000000000000_wp /
data alias_list(:,128) / &
&     "hexanoic acid",                                  &
&     "caproic acid",                                   &
&     "142-62-1",                                       &
&     "n-caproic acid",                                 &
&     "n-hexanoic acid",                                &
&     "capronic acid",                                  &
&     "1-hexanoic acid",                                &
&     "butylacetic acid",                               &
&     "pentylformic acid",                              &
&     "hexoic acid"                                     /


!IODOBENZENE
!--------------------------------------
data id_list(129) / 129 /
data name_list(129) / "Iodobenzene" /
data eps(129) / 4.547000000000000_wp /
data refr(129) / 1.620000000000000_wp /
data A(129) / 0.000000000000000_wp /
data B(129) / 0.120000000000000_wp /
data g(129) / 55.719999999999999_wp /
data rho(129) / 1808.000000000000000_wp /
data alias_list(:,129) / &
&     "iodobenzene",                                    &
&     "",                                               &
&     "phenyl iodide",                                  &
&     "benzene iodide",                                 &
&     "iodinebenzol",                                   &
&     "iodo-benzene",                                   &
&     "iodo benzene",                                   &
&     "benzene, iodo",                                  &
&     "unii-9hk5l7ybbr",                                &
&     "9hk5l7ybbr"                                      /


!IODOETHANE
!--------------------------------------
data id_list(130) / 130 /
data name_list(130) / "Iodoethane" /
data eps(130) / 7.617700000000000_wp /
data refr(130) / 1.513300000000000_wp /
data A(130) / 0.000000000000000_wp /
data B(130) / 0.150000000000000_wp /
data g(130) / 40.960000000000001_wp /
data rho(130) / 1940.000000000000000_wp /
data alias_list(:,130) / &
&     "iodoethane",                                     &
&     "ethyl iodide",                                   &
&     "",                                               &
&     "1-iodoethane",                                   &
&     "c2h5i",                                          &
&     "nsc 8825",                                       &
&     "einecs 200-833-1",                               &
&     "unii-59po05d39l",                                &
&     "ai3-28593",                                      &
&     "59po05d39l"                                      /


!IODOMETHANE
!--------------------------------------
data id_list(131) / 131 /
data name_list(131) / "Iodomethane" /
data eps(131) / 6.865000000000000_wp /
data refr(131) / 1.538000000000000_wp /
data A(131) / 0.000000000000000_wp /
data B(131) / 0.130000000000000_wp /
data g(131) / 43.670000000000002_wp /
data rho(131) / 2280.000000000000000_wp /
data alias_list(:,131) / &
&     "iodomethane",                                    &
&     "methyl iodide",                                  &
&     "74-88-4",                                        &
&     "monoiodomethane",                                &
&     "",                                               &
&     "methyljodid",                                    &
&     "jod-methan",                                     &
&     "methyliodide",                                   &
&     "iodometano",                                     &
&     "joodmethaan"                                     /


!ISOPROPYLBENZENE
!--------------------------------------
data id_list(132) / 132 /
data name_list(132) / "Isopropylbenzene" /
data eps(132) / 2.371200000000000_wp /
data refr(132) / 1.491500000000000_wp /
data A(132) / 0.000000000000000_wp /
data B(132) / 0.160000000000000_wp /
data g(132) / 39.850000000000001_wp /
data rho(132) / 866.000000000000000_wp /
data alias_list(:,132) / &
&     "cumene",                                         &
&     "isopropylbenzene",                               &
&     "98-82-8",                                        &
&     "2-phenylpropane",                                &
&     "(1-methylethyl)benzene",                         &
&     "cumol",                                          &
&     "isopropylbenzol",                                &
&     "cumeen",                                         &
&     "isopropilbenzene",                               &
&     "isopropylbenzeen"                                /


!P-ISOPROPYLTOLUENE
!--------------------------------------
data id_list(133) / 133 /
data name_list(133) / "P-isopropyltoluene" /
data eps(133) / 2.232200000000000_wp /
data refr(133) / 1.490900000000000_wp /
data A(133) / 0.000000000000000_wp /
data B(133) / 0.190000000000000_wp /
data g(133) / 38.340000000000003_wp /
data rho(133) / 879.000000000000000_wp /
data alias_list(:,133) / &
&     "p-cymene",                                       &
&     "99-87-6",                                        &
&     "4-isopropyltoluene",                             &
&     "p-isopropyltoluene",                             &
&     "dolcymene",                                      &
&     "para-cymene",                                    &
&     "p-cymol",                                        &
&     "paracymene",                                     &
&     "1-isopropyl-4-methylbenzene",                    &
&     "camphogen"                                       /


!MESITYLENE
!--------------------------------------
data id_list(134) / 134 /
data name_list(134) / "Mesitylene" /
data eps(134) / 2.265000000000000_wp /
data refr(134) / 1.499400000000000_wp /
data A(134) / 0.000000000000000_wp /
data B(134) / 0.190000000000000_wp /
data g(134) / 39.649999999999999_wp /
data rho(134) / 863.70_wp /
data alias_list(:,134) / &
&     "mesitylene",                                     &
&     "1,3,5-trimethylbenzene",                         &
&     "108-67-8",                                       &
&     "sym-trimethylbenzene",                           &
&     "3,5-dimethyltoluene",                            &
&     "fleet-x",                                        &
&     "trimethylbenzol",                                &
&     "s-trimethylbenzene",                             &
&     "2,4,6-trimethylbenzene",                         &
&     "nsc 9273"                                        /


!METHANOL
!--------------------------------------
data id_list(135) / 135 /
data name_list(135) / "Methanol" /
data eps(135) / 32.613000000000000_wp /
data refr(135) / 1.328800000000000_wp /
data A(135) / 0.430000000000000_wp /
data B(135) / 0.470000000000000_wp /
data g(135) / 31.770000000000000_wp /
data rho(135) / 791.000000000000000_wp /
data alias_list(:,135) / &
&     "methanol",                                       &
&     "methyl alcohol",                                 &
&     "67-56-1",                                        &
&     "wood alcohol",                                   &
&     "carbinol",                                       &
&     "wood naphtha",                                   &
&     "methylol",                                       &
&     "methyl hydroxide",                               &
&     "methylalkohol",                                  &
&     "monohydroxymethane"                              /


!METHYL BENZOATE
!--------------------------------------
data id_list(136) / 136 /
data name_list(136) / "Methyl benzoate" /
data eps(136) / 6.736700000000000_wp /
data refr(136) / 1.516400000000000_wp /
data A(136) / 0.000000000000000_wp /
data B(136) / 0.460000000000000_wp /
data g(136) / 53.500000000000000_wp /
data rho(136) / 879.000000000000000_wp /
data alias_list(:,136) / &
&     "methyl benzoate",                                &
&     "93-58-3",                                        &
&     "methylbenzoate",                                 &
&     "benzoic acid, methyl ester",                     &
&     "benzoic acid methyl ester",                      &
&     "clorius",                                        &
&     "methyl benzenecarboxylate",                      &
&     "essence of niobe",                               &
&     "oxidate le",                                     &
&     "fema no. 2683"                                   /


!METHYL BUTANOATE
!--------------------------------------
data id_list(137) / 137 /
data name_list(137) / "Methyl butanoate" /
data eps(137) / 5.560700000000000_wp /
data refr(137) / 1.387800000000000_wp /
data A(137) / 0.000000000000000_wp /
data B(137) / 0.450000000000000_wp /
data g(137) / 35.439999999999998_wp /
data rho(137) / 898.000000000000000_wp /
data alias_list(:,137) / &
&     "methyl butyrate",                                &
&     "623-42-7",                                       &
&     "methyl butanoate",                               &
&     "methyl n-butyrate",                              &
&     "butyric acid, methyl ester",                     &
&     "methyl n-butanoate",                             &
&     "methyl-n-butyrate",                              &
&     "fema no. 2693",                                  &
&     "methyl butyrate (natural)",                      &
&     "nsc 9380"                                        /


!METHYL ETHANOATE
!--------------------------------------
data id_list(138) / 138 /
data name_list(138) / "Methyl ethanoate" /
data eps(138) / 6.861500000000000_wp /
data refr(138) / 1.361400000000000_wp /
data A(138) / 0.000000000000000_wp /
data B(138) / 0.450000000000000_wp /
data g(138) / 35.590000000000003_wp /
data rho(138) / 1051.000000000000000_wp /
data alias_list(:,138) / &
&     "methyl acetate",                                 &
&     "79-20-9",                                        &
&     "methyl ethanoate",                               &
&     "acetic acid, methyl ester",                      &
&     "acetic acid methyl ester",                       &
&     "methyl acetic ester",                            &
&     "hsdb 95",                                        &
&     "ch3cooch3",                                      &
&     "fema no. 2676",                                  &
&     "fema number 2676"                                /


!METHYL METHANOATE
!--------------------------------------
data id_list(139) / 139 /
data name_list(139) / "Methyl methanoate" /
data eps(139) / 8.837700000000000_wp /
data refr(139) / 1.343300000000000_wp /
data A(139) / 0.000000000000000_wp /
data B(139) / 0.380000000000000_wp /
data g(139) / 35.060000000000002_wp /
data rho(139) / 974.000000000000000_wp /
data alias_list(:,139) / &
&     "methyl formate",                                 &
&     "107-31-3",                                       &
&     "formic acid, methyl ester",                      &
&     "methyl methanoate",                              &
&     "formic acid methyl ester",                       &
&     "methylformiat",                                  &
&     "formiate de methyle",                            &
&     "methylformiaat",                                 &
&     "mravencan methylnaty",                           &
&     "caswell no. 570"                                 /


!METHYL PROPANOATE
!--------------------------------------
data id_list(140) / 140 /
data name_list(140) / "Methyl propanoate" /
data eps(140) / 6.077700000000000_wp /
data refr(140) / 1.377500000000000_wp /
data A(140) / 0.000000000000000_wp /
data B(140) / 0.450000000000000_wp /
data g(140) / 35.180000000000000_wp /
data rho(140) / 915.000000000000000_wp /
data alias_list(:,140) / &
&     "methyl propionate",                              &
&     "554-12-1",                                       &
&     "methyl propylate",                               &
&     "propionate de methyle",                          &
&     "fema no. 2742",                                  &
&     "fema number 2742",                               &
&     "methyl propionate (natural)",                    &
&     "nsc 9375",                                       &
&     "hsdb 5688",                                      &
&     "einecs 209-060-4"                                /


!N-METHYLANILINE
!--------------------------------------
data id_list(141) / 141 /
data name_list(141) / "N-methylaniline" /
data eps(141) / 5.960000000000000_wp /
data refr(141) / 1.568400000000000_wp /
data A(141) / 0.170000000000000_wp /
data B(141) / 0.430000000000000_wp /
data g(141) / 53.109999999999999_wp /
data rho(141) / 1022.000000000000000_wp /
data alias_list(:,141) / &
&     "n-methylaniline",                                &
&     "100-61-8",                                       &
&     "methylaniline",                                  &
&     "n-methylbenzenamine",                            &
&     "n-methyl aniline",                               &
&     "methylphenylamine",                              &
&     "",                                               &
&     "n-phenylmethylamine",                            &
&     "(methylamino)benzene",                           &
&     "monomethyl aniline"                              /


!METHYLCYCLOHEXANE
!--------------------------------------
data id_list(142) / 142 /
data name_list(142) / "Methylcyclohexane" /
data eps(142) / 2.024000000000000_wp /
data refr(142) / 1.423100000000000_wp /
data A(142) / 0.000000000000000_wp /
data B(142) / 0.000000000000000_wp /
data g(142) / 33.520000000000003_wp /
data rho(142) / 779.000000000000000_wp /
data alias_list(:,142) / &
&     "methylcyclohexane",                              &
&     "108-87-2",                                       &
&     "hexahydrotoluene",                               &
&     "",                                               &
&     "cyclohexylmethane",                              &
&     "toluene hexahydride",                            &
&     "hexahydroxytoluene",                             &
&     "sextone b",                                      &
&     "",                                               &
&     "methyl cyclohexane"                              /


!N-METHYLFORMAMIDE
!--------------------------------------
data id_list(143) / 143 /
data name_list(143) / "N-methylformamide" /
data eps(143) / 181.560000000000002_wp /
data refr(143) / 1.431900000000000_wp /
data A(143) / 0.400000000000000_wp /
data B(143) / 0.550000000000000_wp /
data g(143) / 55.439999999999998_wp /
data rho(143) / 1011.000000000000000_wp /
data alias_list(:,143) / &
&     "n-methylformamide",                              &
&     "123-39-7",                                       &
&     "methylformamide",                                &
&     "",                                               &
&     "monomethylformamide",                            &
&     "n-methyl-formamide",                             &
&     "n-monomethylformamide",                          &
&     "nsc 3051",                                       &
&     "ek 7011",                                        &
&     "hconhch3"                                        /


!NITROBENZENE
!--------------------------------------
data id_list(144) / 144 /
data name_list(144) / "Nitrobenzene" /
data eps(144) / 34.808999999999997_wp /
data refr(144) / 1.556200000000000_wp /
data A(144) / 0.000000000000000_wp /
data B(144) / 0.280000000000000_wp /
data g(144) / 57.539999999999999_wp /
data rho(144) / 1199.0_wp /
data alias_list(:,144) / &
&     "nitrobenzene",                                   &
&     "98-95-3",                                        &
&     "nitrobenzol",                                    &
&     "",                                               &
&     "nitro-benzene",                                  &
&     "essence of mirbane",                             &
&     "nitrobenzeen",                                   &
&     "nitrobenzen",                                    &
&     "mononitrobenzene",                               &
&     "essence of myrbane"                              /


!NITROETHANE
!--------------------------------------
data id_list(145) / 145 /
data name_list(145) / "Nitroethane" /
data eps(145) / 28.289999999999999_wp /
data refr(145) / 1.391700000000000_wp /
data A(145) / 0.020000000000000_wp /
data B(145) / 0.330000000000000_wp /
data g(145) / 46.250000000000000_wp /
data rho(145) / 1054.0_wp /
data alias_list(:,145) / &
&     "nitroethane",                                    &
&     "79-24-3",                                        &
&     "1-nitroethane",                                  &
&     "nitroethan",                                     &
&     "nitroetan",                                      &
&     "ccris 3088",                                     &
&     "hsdb 105",                                       &
&     "dtxsid8020969",                                  &
&     "unii-6kel3zau0v",                                &
&     "6kel3zau0v"                                      /


!NITROMETHANE
!--------------------------------------
data id_list(146) / 146 /
data name_list(146) / "Nitromethane" /
data eps(146) / 36.561999999999998_wp /
data refr(146) / 1.381700000000000_wp /
data A(146) / 0.060000000000000_wp /
data B(146) / 0.310000000000000_wp /
data g(146) / 52.579999999999998_wp /
data rho(146) / 1382.000000000000000_wp /
data alias_list(:,146) / &
&     "nitromethane",                                   &
&     "75-52-5",                                        &
&     "",                                               &
&     "nitrocarbol",                                    &
&     "nitrometan",                                     &
&     "ch3no2",                                         &
&     "nsc 428",                                        &
&     "meno2",                                          &
&     "ccris 1205",                                     &
&     "hsdb 106"                                        /


!O-NITROTOLUENE
!--------------------------------------
data id_list(147) / 147 /
data name_list(147) / "O-nitrotoluene" /
data eps(147) / 25.669000000000000_wp /
data refr(147) / 1.545000000000000_wp /
data A(147) / 0.000000000000000_wp /
data B(147) / 0.270000000000000_wp /
data g(147) / 59.119999999999997_wp /
data rho(147) / 1161.000000000000000_wp /
data alias_list(:,147) / &
&     "2-nitrotoluene",                                 &
&     "1-methyl-2-nitrobenzene",                        &
&     "88-72-2",                                        &
&     "o-nitrotoluene",                                 &
&     "nitrotoluene",                                   &
&     "o-nitrotoluol",                                  &
&     "o-methylnitrobenzene",                           &
&     "",                                               &
&     "2-methyl-1-nitrobenzene",                        &
&     "2-methylnitrobenzene"                            /


!N-NONANE
!--------------------------------------
data id_list(148) / 148 /
data name_list(148) / "N-nonane" /
data eps(148) / 1.960500000000000_wp /
data refr(148) / 1.405400000000000_wp /
data A(148) / 0.000000000000000_wp /
data B(148) / 0.000000000000000_wp /
data g(148) / 32.210000000000001_wp /
data rho(148) / 718.000000000000000_wp /
data alias_list(:,148) / &
&     "nonane",                                         &
&     "n-nonane",                                       &
&     "111-84-2",                                       &
&     "nonyl hydride",                                  &
&     "shellsol 140",                                   &
&     "nonan",                                          &
&     "ccris 6081",                                     &
&     "hsdb 107",                                       &
&     "einecs 203-913-4",                               &
&     "unii-t9w3vh6g10"                                 /


!N-OCTANE
!--------------------------------------
data id_list(149) / 149 /
data name_list(149) / "N-octane" /
data eps(149) / 1.940600000000000_wp /
data refr(149) / 1.397400000000000_wp /
data A(149) / 0.000000000000000_wp /
data B(149) / 0.000000000000000_wp /
data g(149) / 30.430000000000000_wp /
data rho(149) / 703.000000000000000_wp /
data alias_list(:,149) / &
&     "octane",                                         &
&     "n-octane",                                       &
&     "111-65-9",                                       &
&     "oktan",                                          &
&     "oktanen",                                        &
&     "ottani",                                         &
&     "n-oktan",                                        &
&     "hsdb 108",                                       &
&     "unii-x1rv0b2fjv",                                &
&     "x1rv0b2fjv"                                      /


!N-PENTADECANE
!--------------------------------------
data id_list(150) / 150 /
data name_list(150) / "N-pentadecane" /
data eps(150) / 2.033300000000000_wp /
data refr(150) / 1.431500000000000_wp /
data A(150) / 0.000000000000000_wp /
data B(150) / 0.000000000000000_wp /
data g(150) / 38.340000000000003_wp /
data rho(150) / 768.500000000000000_wp /
data alias_list(:,150) / &
&     "pentadecane",                                    &
&     "n-pentadecane",                                  &
&     "629-62-9",                                       &
&     "pentadekan",                                     &
&     "npentadecane",                                &
&     "hsdb 5729",                                      &
&     "einecs 211-098-1",                               &
&     "nsc 172781",                                     &
&     "unii-16h6k2s8m2",                                &
&     "brn 1698194"                                     /


!PENTANAL
!--------------------------------------
data id_list(151) / 151 /
data name_list(151) / "Pentanal" /
data eps(151) / 10.000000000000000_wp /
data refr(151) / 1.394400000000000_wp /
data A(151) / 0.000000000000000_wp /
data B(151) / 0.450000000000000_wp /
data g(151) / 36.619999999999997_wp /
data rho(151) / 810.000000000000000_wp /
data alias_list(:,151) / &
&     "valeraldehyde",                                  &
&     "pentanal",                                       &
&     "110-62-3",                                       &
&     "n-pentanal",                                     &
&     "n-valeraldehyde",                                &
&     "valeric aldehyde",                               &
&     "valeral",                                        &
&     "valeryl aldehyde",                               &
&     "amylaldehyde",                                   &
&     "amyl aldehyde"                                   /


!N-PENTANE
!--------------------------------------
data id_list(152) / 152 /
data name_list(152) / "N-pentane" /
data eps(152) / 1.837100000000000_wp /
data refr(152) / 1.357500000000000_wp /
data A(152) / 0.000000000000000_wp /
data B(152) / 0.000000000000000_wp /
data g(152) / 22.300000000000001_wp /
data rho(152) / 626.000000000000000_wp /
data alias_list(:,152) / &
&     "pentane",                                        &
&     "n-pentane",                                      &
&     "109-66-0",                                       &
&     "pentan",                                         &
&     "skellysolve a",                                  &
&     "pentanen",                                       &
&     "pentani",                                        &
&     "amyl hydride",                                   &
&     "pentanes",                                       &
&     "tetrafume"                                       /


!PENTANOIC ACID
!--------------------------------------
data id_list(153) / 153 /
data name_list(153) / "Pentanoic acid" /
data eps(153) / 2.692400000000000_wp /
data refr(153) / 1.408500000000000_wp /
data A(153) / 0.600000000000000_wp /
data B(153) / 0.450000000000000_wp /
data g(153) / 38.399999999999999_wp /
data rho(153) / 1051.000000000000000_wp /
data alias_list(:,153) / &
&     "valeric acid",                                   &
&     "pentanoic acid",                                 &
&     "n-valeric acid",                                 &
&     "n-pentanoic acid",                               &
&     "valerianic acid",                                &
&     "1-butanecarboxylic acid",                        &
&     "propylacetic acid",                              &
&     "butanecarboxylic acid",                          &
&     "pentoic acid",                                   &
&     "kyselina valerova"                               /


!PENTYL ETHANOATE
!--------------------------------------
data id_list(154) / 154 /
data name_list(154) / "Pentyl ethanoate" /
data eps(154) / 4.729700000000000_wp /
data refr(154) / 1.402300000000000_wp /
data A(154) / 0.000000000000000_wp /
data B(154) / 0.450000000000000_wp /
data g(154) / 36.229999999999997_wp /
data rho(154) / 1051.000000000000000_wp /
data alias_list(:,154) / &
&     "amyl acetate",                                   &
&     "pentyl acetate",                                 &
&     "628-63-7",                                       &
&     "n-amyl acetate",                                 &
&     "n-pentyl acetate",                               &
&     "acetic acid, pentyl ester",                      &
&     "amyl acetic ester",                              &
&     "1-pentyl acetate",                               &
&     "birnenoel",                                      &
&     "n-pentyl ethanoate"                              /


!PENTYLAMINE
!--------------------------------------
data id_list(155) / 155 /
data name_list(155) / "Pentylamine" /
data eps(155) / 4.201000000000000_wp /
data refr(155) / 1.448000000000000_wp /
data A(155) / 0.160000000000000_wp /
data B(155) / 0.610000000000000_wp /
data g(155) / 35.539999999999999_wp /
data rho(155) / 626.000000000000000_wp /
data alias_list(:,155) / &
&     "amylamine",                                      &
&     "pentylamine",                                    &
&     "110-58-7",                                       &
&     "1-pentylamine",                                  &
&     "pentan-1-amine",                                 &
&     "n-amylamine",                                    &
&     "1-aminopentane",                                 &
&     "n-pentylamine",                                  &
&     "1-pentanamine",                                  &
&     "monoamylamine"                                   /


!PERFLUOROBENZENE
!--------------------------------------
data id_list(156) / 156 /
data name_list(156) / "Perfluorobenzene" /
data eps(156) / 2.029000000000000_wp /
data refr(156) / 1.377700000000000_wp /
data A(156) / 0.000000000000000_wp /
data B(156) / 0.000000000000000_wp /
data g(156) / 31.739999999999998_wp /
data rho(156) / 1610.000000000000000_wp /
data alias_list(:,156) / &
&     "hexafluorobenzene",                              &
&     "392-56-3",                                       &
&     "perfluorobenzene",                               &
&     "1,2,3,4,5,6-hexafluorobenzene",                  &
&     "",                                               &
&     "cp 28",                                          &
&     "hexafluorbenzol",                                &
&     "einecs 206-876-2",                               &
&     "nsc 21628",                                      &
&     "cmc18t611k"                                      /


!PROPANAL
!--------------------------------------
data id_list(157) / 157 /
data name_list(157) / "Propanal" /
data eps(157) / 18.500000000000000_wp /
data refr(157) / 1.363600000000000_wp /
data A(157) / 0.000000000000000_wp /
data B(157) / 0.450000000000000_wp /
data g(157) / 32.479999999999997_wp /
data rho(157) / 805.000000000000000_wp /
data alias_list(:,157) / &
&     "propionaldehyde",                                &
&     "propanal",                                       &
&     "123-38-6",                                       &
&     "propanaldehyde",                                 &
&     "propaldehyde",                                   &
&     "methylacetaldehyde",                             &
&     "n-propanal",                                     &
&     "propylaldehyde",                                 &
&     "propional",                                      &
&     "propionic aldehyde"                              /


!PROPANOIC ACID
!--------------------------------------
data id_list(158) / 158 /
data name_list(158) / "Propanoic acid" /
data eps(158) / 3.440000000000000_wp /
data refr(158) / 1.386900000000000_wp /
data A(158) / 0.600000000000000_wp /
data B(158) / 0.450000000000000_wp /
data g(158) / 37.710000000000001_wp /
data rho(158) / 1051.000000000000000_wp /
data alias_list(:,158) / &
&     "propionic acid",                                 &
&     "propanoic acid",                                 &
&     "ethylformic acid",                               &
&     "methylacetic acid",                              &
&     "carboxyethane",                                  &
&     "metacetonic acid",                               &
&     "ethanecarboxylic acid",                          &
&     "pseudoacetic acid",                              &
&     "luprosil",                                       &
&     "monoprop"                                        /


!PROPIONITRILE
!--------------------------------------
data id_list(159) / 159 /
data name_list(159) / "Propionitrile" /
data eps(159) / 29.324000000000002_wp /
data refr(159) / 1.365500000000000_wp /
data A(159) / 0.020000000000000_wp /
data B(159) / 0.360000000000000_wp /
data g(159) / 38.500000000000000_wp /
data rho(159) / 772.000000000000000_wp /
data alias_list(:,159) / &
&     "propionitrile",                                  &
&     "ethyl cyanide",                                  &
&     "107-12-0",                                       &
&     "propiononitrile",                                &
&     "cyanoethane",                                    &
&     "propylnitrile",                                  &
&     "propionic nitrile",                              &
&     "ether cyanatus",                                 &
&     "hydrocyanic ether",                              &
&     "propannitril"                                    /


!PROPYL ETHANOATE
!--------------------------------------
data id_list(160) / 160 /
data name_list(160) / "Propyl ethanoate" /
data eps(160) / 5.520500000000000_wp /
data refr(160) / 1.384200000000000_wp /
data A(160) / 0.000000000000000_wp /
data B(160) / 0.450000000000000_wp /
data g(160) / 34.259999999999998_wp /
data rho(160) / 1051.000000000000000_wp /
data alias_list(:,160) / &
&     "propyl acetate",                                 &
&     "109-60-4",                                       &
&     "n-propyl acetate",                               &
&     "acetic acid, propyl ester",                      &
&     "propyl ethanoate",                               &
&     "1-acetoxypropane",                               &
&     "1-propyl acetate",                               &
&     "n-propyl ethanoate",                             &
&     "octan propylu",                                  &
&     "acetic acid n-propyl ester"                      /


!PROPYLAMINE
!--------------------------------------
data id_list(161) / 161 /
data name_list(161) / "Propylamine" /
data eps(161) / 4.991200000000000_wp /
data refr(161) / 1.387000000000000_wp /
data A(161) / 0.160000000000000_wp /
data B(161) / 0.610000000000000_wp /
data g(161) / 31.309999999999999_wp /
data rho(161) / 719.000000000000000_wp /
data alias_list(:,161) / &
&     "propylamine",                                    &
&     "propan-1-amine",                                 &
&     "107-10-8",                                       &
&     "1-propylamine",                                  &
&     "propanamine",                                    &
&     "1-aminopropane",                                 &
&     "mono-n-propylamine",                             &
&     "monopropylamine",                                &
&     "rcra waste number u194",                         &
&     "propan-1-ylamine"                                /


!PYRIDINE
!--------------------------------------
data id_list(162) / 162 /
data name_list(162) / "Pyridine" /
data eps(162) / 12.978000000000000_wp /
data refr(162) / 1.509500000000000_wp /
data A(162) / 0.000000000000000_wp /
data B(162) / 0.520000000000000_wp /
data g(162) / 52.619999999999997_wp /
data rho(162) / 982.000000000000000_wp /
data alias_list(:,162) / &
&     "pyridine",                                       &
&     "azabenzene",                                     &
&     "110-86-1",                                       &
&     "pyridin",                                        &
&     "piridina",                                       &
&     "pirydyna",                                       &
&     "rcra waste number u196",                         &
&     "caswell no. 717",                                &
&     "nci-c55301",                                     &
&     "fema no. 2966"                                   /


!TETRACHLOROETHENE
!--------------------------------------
data id_list(163) / 163 /
data name_list(163) / "Tetrachloroethene" /
data eps(163) / 2.268000000000000_wp /
data refr(163) / 1.505300000000000_wp /
data A(163) / 0.000000000000000_wp /
data B(163) / 0.000000000000000_wp /
data g(163) / 45.189999999999998_wp /
data rho(163) / 1630.000000000000000_wp /
data alias_list(:,163) / &
&     "tetrachloroethylene",                            &
&     "tetrachloroethene",                              &
&     "127-18-4",                                       &
&     "perchloroethylene",                              &
&     "",                                               &
&     "carbon dichloride",                              &
&     "",                                               &
&     "nema, veterinary",                               &
&     "caswell no. 827",                                &
&     "perclene tg"                                     /


!TETRAHYDROFURAN
!--------------------------------------
data id_list(164) / 164 /
data name_list(164) / "Tetrahydrofuran" /
data eps(164) / 7.425700000000000_wp /
data refr(164) / 1.405000000000000_wp /
data A(164) / 0.000000000000000_wp /
data B(164) / 0.480000000000000_wp /
data g(164) / 39.439999999999998_wp /
data rho(164) / 883.299999999999955_wp /
data alias_list(:,164) / &
&     "tetrahydrofuran",                                &
&     "109-99-9",                                       &
&     "oxolane",                                        &
&     "",                                               &
&     "furanidine",                                     &
&     "hydrofuran",                                     &
&     "tetramethylene oxide",                           &
&     "thf",                                            &
&     "1,4-epoxybutane",                                &
&     "tetrahydrofuranne"                               /


!TETRAHYDROTHIOPHENE-S,S-DIOXIDE
!--------------------------------------
data id_list(165) / 165 /
data name_list(165) / "Tetrahydrothiophene-s,s-dioxide" /
data eps(165) / 43.962000000000003_wp /
data refr(165) / 1.483300000000000_wp /
data A(165) / 0.000000000000000_wp /
data B(165) / 0.880000000000000_wp /
data g(165) / 87.489999999999995_wp /
data rho(165) / 1261.000000000000000_wp /
data alias_list(:,165) / &
&     "sulfolane",                                      &
&     "126-33-0",                                       &
&     "tetramethylene sulfone",                         &
&     "tetrahydrothiophene 1,1-dioxide",                &
&     "sulfolan",                                       &
&     "thiophene, tetrahydro-, 1,1-dioxide",            &
&     "1,1-dioxothiolan",                               &
&     "sulpholane",                                     &
&     "sulfalone",                                      &
&     "sulphoxaline"                                    /


!TETRALIN
!--------------------------------------
data id_list(166) / 166 /
data name_list(166) / "Tetralin" /
data eps(166) / 2.771000000000000_wp /
data refr(166) / 1.541300000000000_wp /
data A(166) / 0.000000000000000_wp /
data B(166) / 0.190000000000000_wp /
data g(166) / 47.740000000000002_wp /
data rho(166) / 974.000000000000000_wp /
data alias_list(:,166) / &
&     "1,2,3,4-tetrahydronaphthalene",                  &
&     "tetralin",                                       &
&     "tetrahydronaphthalene",                          &
&     "bacticin",                                       &
&     "",                                               &
&     "caswell no. 842a",                               &
&     "ccris 3564",                                     &
&     "hsdb 127",                                       &
&     "unii-ft6xmi58yq",                                &
&     "delta(sup 5,7,9)-naphthantriene"                 /


!THIOPHENE
!--------------------------------------
data id_list(167) / 167 /
data name_list(167) / "Thiophene" /
data eps(167) / 2.727000000000000_wp /
data refr(167) / 1.528900000000000_wp /
data A(167) / 0.000000000000000_wp /
data B(167) / 0.150000000000000_wp /
data g(167) / 44.159999999999997_wp /
data rho(167) / 1051.000000000000000_wp /
data alias_list(:,167) / &
&     "thiophene",                                      &
&     "110-02-1",                                       &
&     "thiofuran",                                      &
&     "thiole",                                         &
&     "thiophen",                                       &
&     "thiacyclopentadiene",                            &
&     "thiotetrole",                                    &
&     "thiofurfuran",                                   &
&     "divinylene sulfide",                             &
&     "thiaphene"                                       /


!THIOPHENOL
!--------------------------------------
data id_list(168) / 168 /
data name_list(168) / "Thiophenol" /
data eps(168) / 4.272800000000000_wp /
data refr(168) / 1.589300000000000_wp /
data A(168) / 0.090000000000000_wp /
data B(168) / 0.160000000000000_wp /
data g(168) / 55.240000000000002_wp /
data rho(168) / 879.000000000000000_wp /
data alias_list(:,168) / &
&     "benzenethiol",                                   &
&     "thiophenol",                                     &
&     "phenyl mercaptan",                               &
&     "phenylmercaptan",                                &
&     "thiophenate",                                    &
&     "fema no. 3616",                                  &
&     "ccris 8922",                                     &
&     "hsdb 5387",                                      &
&     "einecs 203-635-3",                               &
&     "un2337"                                          /


!TOLUENE
!--------------------------------------
data id_list(169) / 169 /
data name_list(169) / "Toluene" /
data eps(169) / 2.374100000000000_wp /
data refr(169) / 1.496100000000000_wp /
data A(169) / 0.000000000000000_wp /
data B(169) / 0.140000000000000_wp /
data g(169) / 40.200000000000003_wp /
data rho(169) / 867.000000000000000_wp /
data alias_list(:,169) / &
&     "toluene",                                        &
&     "methylbenzene",                                  &
&     "108-88-3",                                       &
&     "toluol",                                         &
&     "phenylmethane",                                  &
&     "methacide",                                      &
&     "methylbenzol",                                   &
&     "antisal 1a",                                     &
&     "toluen",                                         &
&     "tolu-sol"                                        /


!TRANS-DECALIN
!--------------------------------------
data id_list(170) / 170 /
data name_list(170) / "Trans-decalin" /
data eps(170) / 2.178100000000000_wp /
data refr(170) / 1.469500000000000_wp /
data A(170) / 0.000000000000000_wp /
data B(170) / 0.000000000000000_wp /
data g(170) / 42.189999999999998_wp /
data rho(170) / 890.000000000000000_wp /
data alias_list(:,170) / &
&     "trans-decalin",                                  &
&     "trans-decahydronaphthalene",                     &
&     "493-02-7",                                       &
&     "trans-bicyclo[4.4.0]decane",                     &
&     "",                                               &
&     "",                                               &
&     "",                                               &
&     "",                                               &
&     "",                                               &
&     ""                                                /


!TRIBUTYLPHOSPHATE
!--------------------------------------
data id_list(171) / 171 /
data name_list(171) / "Tributylphosphate" /
data eps(171) / 8.178100000000001_wp /
data refr(171) / 1.422400000000000_wp /
data A(171) / 0.000000000000000_wp /
data B(171) / 1.210000000000000_wp /
data g(171) / 27.550000000000001_wp /
data rho(171) / 982.000000000000000_wp /
data alias_list(:,171) / &
&     "tributyl phosphate",                             &
&     "126-73-8",                                       &
&     "tri-n-butyl phosphate",                          &
&     "tributylphosphate",                              &
&     "phosphoric acid tributyl ester",                 &
&     "disflamoll tb",                                  &
&     "phosphoric acid, tributyl ester",                &
&     "tributoxyphosphine oxide",                       &
&     "tri-n-butylphosphate",                           &
&     "butyl phosphate, ((buo)3po)"                     /


!TRICHLOROETHENE
!--------------------------------------
data id_list(172) / 172 /
data name_list(172) / "Trichloroethene" /
data eps(172) / 3.422000000000000_wp /
data refr(172) / 1.477300000000000_wp /
data A(172) / 0.080000000000000_wp /
data B(172) / 0.030000000000000_wp /
data g(172) / 41.450000000000003_wp /
data rho(172) / 1463.000000000000000_wp /
data alias_list(:,172) / &
&     "trichloroethylene",                              &
&     "trichloroethene",                                &
&     "79-01-6",                                        &
&     "1,1,2-trichloroethene",                          &
&     "",                                               &
&     "ethylene trichloride",                           &
&     "1,1,2-trichloroethylene",                        &
&     "ethinyl trichloride",                            &
&     "densinfluat",                                    &
&     "germalgene"                                      /


!TRIETHYLAMINE
!--------------------------------------
data id_list(173) / 173 /
data name_list(173) / "Triethylamine" /
data eps(173) / 2.383200000000000_wp /
data refr(173) / 1.401000000000000_wp /
data A(173) / 0.000000000000000_wp /
data B(173) / 0.790000000000000_wp /
data g(173) / 29.100000000000001_wp /
data rho(173) / 728.000000000000000_wp /
data alias_list(:,173) / &
&     "triethylamine",                                  &
&     "121-44-8",                                       &
&     "n,n-diethylethanamine",                          &
&     "(diethylamino)ethane",                           &
&     "ethanamine, n,n-diethyl-",                       &
&     "triaethylamin",                                  &
&     "triethylamin",                                   &
&     "trietilamina",                                   &
&     "n,n,n-triethylamine",                            &
&     "diethylaminoethane"                              /


!N-UNDECANE
!--------------------------------------
data id_list(174) / 174 /
data name_list(174) / "N-undecane" /
data eps(174) / 1.991000000000000_wp /
data refr(174) / 1.439800000000000_wp /
data A(174) / 0.000000000000000_wp /
data B(174) / 0.000000000000000_wp /
data g(174) / 34.850000000000001_wp /
data rho(174) / 740.100000000000023_wp /
data alias_list(:,174) / &
&     "undecane",                                       &
&     "n-undecane",                                     &
&     "1120-21-4",                                      &
&     "hendecane",                                      &
&     "n-hendecane",                                    &
&     "ccris 3796",                                     &
&     "hendekan",                                       &
&     "undekan",                                        &
&     "hsdb 5791",                                      &
&     "unii-jv0qt00nue"                                 /


!WATER
!--------------------------------------
data id_list(175) / 175 /
data name_list(175) / "Water" /
data eps(175) / 78.355000000000004_wp /
data refr(175) / 1.332800000000000_wp /
data A(175) / 0.350000000000000_wp /
data B(175) / 0.380000000000000_wp /
data g(175) / 72.700000000000003_wp /
data rho(175) / 998.000000000000000_wp /
data alias_list(:,175) / &
&     "water",                                          &
&     "7732-18-5",                                      &
&     "dihydrogen oxide",                               &
&     "water, deionized",                               &
&     "oxidane",                                        &
&     "aqua",                                           &
&     "dihydrogen monoxide",                            &
&     "deionized water",                                &
&     "h2o",                                            &
&     "agua"                                            /


!FURANE
!--------------------------------------
data id_list(176) / 176 /
data name_list(176) / "Furane" /
data eps(176) / 2.9500000000000_wp /
data refr(176) / 1.421400000000000_wp /
data A(176) / 0.000000000000000_wp /
data B(176) / 0.160000000000000_wp /
data g(176) / 40.320000000000000_wp /
data rho(176) / 937.100000000000000_wp /
data alias_list(:,176) / &
&     "Divinylene oxide",                               &
&     "furane",                                         &
&     "Tetrole",                                        &
&     "",                                               &
&     "",                                               &
&     "",                                               &
&     "",                                               &
&     "",                                               &
&     "",                                               &
&     "Furfuran"                                        /


!M-XYLENE
!--------------------------------------
data id_list(177) / 177 /
data name_list(177) / "M-xylene" /
data eps(177) / 2.347800000000000_wp /
data refr(177) / 1.497200000000000_wp /
data A(177) / 0.000000000000000_wp /
data B(177) / 0.160000000000000_wp /
data g(177) / 40.979999999999997_wp /
data rho(177) / 868.000000000000000_wp /
data alias_list(:,177) / &
&     "m-xylene",                                       &
&     "108-38-3",                                       &
&     "1,3-dimethylbenzene",                            &
&     "1,3-xylene",                                     &
&     "meta-xylene",                                    &
&     "m-xylol",                                        &
&     "m-dimethylbenzene",                              &
&     "m-methyltoluene",                                &
&     "",                                               &
&     "3-xylene"                                        /


!O-XYLENE
!--------------------------------------
data id_list(178) / 178 /
data name_list(178) / "O-xylene" /
data eps(178) / 2.545400000000000_wp /
data refr(178) / 1.505500000000000_wp /
data A(178) / 0.000000000000000_wp /
data B(178) / 0.160000000000000_wp /
data g(178) / 42.829999999999998_wp /
data rho(178) / 897.000000000000000_wp /
data alias_list(:,178) / &
&     "o-xylene",                                       &
&     "ortho-xylene",                                   &
&     "o-methyltoluene",                                &
&     "o-dimethylbenzene",                              &
&     "1,2-dimethylbenzene",                            &
&     "1,2-dimethylbenzol",                             &
&     "2-methyltoluene",                                &
&     "orthoxylene",                                    &
&     "xylene",                                         &
&     "chebi:28063"                                     /


!P-XYLENE
!--------------------------------------
data id_list(179) / 179 /
data name_list(179) / "P-xylene" /
data eps(179) / 2.270500000000000_wp /
data refr(179) / 1.495800000000000_wp /
data A(179) / 0.000000000000000_wp /
data B(179) / 0.160000000000000_wp /
data g(179) / 40.320000000000000_wp /
data rho(179) / 861.000000000000000_wp /
data alias_list(:,179) / &
&     "p-xylene",                                       &
&     "1,4-dimethylbenzene",                            &
&     "para-xylene",                                    &
&     "106-42-3",                                       &
&     "1,4-xylene",                                     &
&     "p-methyltoluene",                                &
&     "p-dimethylbenzene",                              &
&     "p-xylol",                                        &
&     "",                                               &
&     "4-xylene"                                        /

!PHENOL
!--------------------------------------
data id_list(180) / 180 /
data name_list(180) / "Phenol" /
data eps(180) / 2.270500000000000_wp /
data refr(180) / 1.495800000000000_wp /
data A(180) / 0.000000000000000_wp /
data B(180) / 0.160000000000000_wp /
data g(180) / 40.320000000000000_wp /
data rho(180) / 861.000000000000000_wp /
data alias_list(:,180) / &
&     "phenol",                                         &
&     "carbolic acid",                                  &
&     "phenolic acid",                                  &
&     "benzenol",                                       &
&     "108-95-2",                                       &
&     "",                                               &
&     "",                                               &
&     "",                                               &
&     "",                                               &
&     ""                                                /