!> Abstract molecular partition scheme
!>
!> Generated by moist_dev/tools/maths/grid/generate_partitions.py
!> Edit the generator in moist_dev and regenerate; no runtime Python dependency
module moist_math_grid_3d_kernel_base
   use mctc_env, only: wp, error_type
   implicit none(type, external)
   private

   public :: moist_math_grid_3d_partition_type

   !> Pair switch, single-owner batches and whole-grid derivative drivers of one partition
   !>
   !> Settings live in the extension; drivers dispatch once per call, switch loops are inlined
   type, abstract :: moist_math_grid_3d_partition_type
   contains
      !> Pair-switch weight
      procedure(partition_eval_i), deferred :: eval
      !> Fused pair-switch weight and first derivative
      procedure(partition_eval_with_derivative_i), deferred :: eval_with_derivative
      !> Fused pair-switch weight and first two derivatives
      procedure(partition_eval_with_second_derivative_i), deferred :: eval_with_second_derivative
      !> Normalized weights of one owner at fixed points
      procedure(partition_owner_weights_i), deferred :: owner_weights
      !> Contract one owner's partition adjoints at fixed points
      procedure(partition_owner_gradient_i), deferred :: owner_gradient
      !> Directional derivative of one owner's partition reverse contraction
      procedure(partition_owner_hessian_vector_i), deferred :: owner_hessian_vector
      !> Evaluate all owners and quadrature weights in one prepared pass
      procedure(partition_grid_weights_i), deferred :: grid_weights
      !> Contract all point and weight adjoints with owner motion
      procedure(partition_grid_gradient_i), deferred :: grid_gradient
      !> Contract point, weight and Gaussian-width adjoints with owner motion
      procedure(partition_grid_gaussian_gradient_i), deferred :: grid_gaussian_gradient
      !> Contract nuclear curvature with one prepared directional pass
      procedure(partition_grid_hessian_vector_i), deferred :: grid_hessian_vector
      !> Assemble dense nuclear curvature with one geometry, scratch and worker team
      procedure(partition_grid_hessian_i), deferred :: grid_hessian
   end type moist_math_grid_3d_partition_type

   abstract interface

      !> Pair-switch weight
      !>
      !> @param[in] self Configured partition scheme
      !> @param[in] x Pair coordinate
      pure function partition_eval_i(self, x) result(s)
         import :: moist_math_grid_3d_partition_type, wp
         implicit none(type, external)
         !> Configured partition scheme
         class(moist_math_grid_3d_partition_type), intent(in) :: self
         !> Pair coordinate
         real(wp), intent(in) :: x
         !> Pair-switch weight
         real(wp) :: s
      end function partition_eval_i

      !> Fused pair-switch weight and first derivative
      !>
      !> @param[in] self Configured partition scheme
      !> @param[in] x Pair coordinate
      !> @param[out] s Pair-switch weight
      !> @param[out] ds First pair-coordinate derivative
      pure subroutine partition_eval_with_derivative_i(self, x, s, ds)
         import :: moist_math_grid_3d_partition_type, wp
         implicit none(type, external)
         !> Configured partition scheme
         class(moist_math_grid_3d_partition_type), intent(in) :: self
         !> Pair coordinate
         real(wp), intent(in) :: x
         !> Pair-switch weight
         real(wp), intent(out) :: s
         !> First derivative
         real(wp), intent(out) :: ds
      end subroutine partition_eval_with_derivative_i

      !> Fused pair-switch weight and first two derivatives
      !>
      !> @param[in] self Configured partition scheme
      !> @param[in] x Pair coordinate
      !> @param[out] s Pair-switch weight
      !> @param[out] ds First pair-coordinate derivative
      !> @param[out] d2s Second pair-coordinate derivative; zero at endpoints
      pure subroutine partition_eval_with_second_derivative_i(self, x, s, ds, d2s)
         import :: moist_math_grid_3d_partition_type, wp
         implicit none(type, external)
         !> Configured partition scheme
         class(moist_math_grid_3d_partition_type), intent(in) :: self
         !> Pair coordinate
         real(wp), intent(in) :: x
         !> Pair-switch weight
         real(wp), intent(out) :: s
         !> First derivative
         real(wp), intent(out) :: ds
         !> Second derivative
         real(wp), intent(out) :: d2s
      end subroutine partition_eval_with_second_derivative_i

      !> Normalized weights of one owner at fixed points
      !>
      !> @param[in] self Configured partition scheme
      !> @param[in]  owner       Owner index in [1,nat]
      !> @param[in]  points      Sample points in bohr
      !> @param[in]  xyz         Atomic positions in bohr
      !> @param[in]  numbers     Atomic numbers
      !> @param[out] w           Normalized owner weights
      !> @param[in]  nthreads    Optional thread count; absent takes omp_get_max_threads
      subroutine partition_owner_weights_i(self, owner, points, xyz, numbers, w, nthreads)
         import :: moist_math_grid_3d_partition_type, wp
         implicit none(type, external)
         !> Configured partition scheme
         class(moist_math_grid_3d_partition_type), intent(in) :: self
         !> Owner index
         integer, intent(in) :: owner
         !> Sample points
         real(wp), intent(in) :: points(:, :)
         !> Atomic positions
         real(wp), intent(in) :: xyz(:, :)
         !> Atomic numbers
         integer, intent(in) :: numbers(:)
         !> Owner weights
         real(wp), intent(out) :: w(:)
         !> Thread count
         integer, intent(in), optional :: nthreads
      end subroutine partition_owner_weights_i

      !> Contract one owner's partition adjoints at fixed points
      !>
      !> @param[in] self Configured partition scheme
      !> @param[in] owner Owner index in [1, nat]
      !> @param[in] points Sample positions (3, npts), bohr
      !> @param[in] xyz Nuclear positions (3, nat), bohr
      !> @param[in] numbers Atomic numbers (nat)
      !> @param[in] seed Owner-partition energy adjoints (npts)
      !> @param[in,out] gradient Nuclear-gradient accumulator (3, nat)
      !> @param[out] point_gradient Point-position adjoints (3, npts)
      !> @param[out] error Allocation failure
      !> @param[in] nthreads Optional worker count
      subroutine partition_owner_gradient_i(self, owner, points, xyz, numbers, seed, gradient, &
         & point_gradient, error, nthreads)
         import :: moist_math_grid_3d_partition_type, wp, error_type
         implicit none(type, external)
         !> Configured partition scheme
         class(moist_math_grid_3d_partition_type), intent(in) :: self
         !> Owner index
         integer, intent(in) :: owner
         !> Sample positions
         real(wp), intent(in) :: points(:, :)
         !> Nuclear positions
         real(wp), intent(in) :: xyz(:, :)
         !> Atomic numbers
         integer, intent(in) :: numbers(:)
         !> Owner-partition adjoints
         real(wp), intent(in) :: seed(:)
         !> Nuclear-gradient accumulator
         real(wp), intent(inout) :: gradient(:, :)
         !> Point-position adjoints
         real(wp), intent(out) :: point_gradient(:, :)
         !> Allocation failure
         type(error_type), allocatable, intent(out) :: error
         !> Worker count
         integer, intent(in), optional :: nthreads
      end subroutine partition_owner_gradient_i

      !> Directional derivative of one owner's partition reverse contraction
      !>
      !> @param[in] self Configured partition scheme
      !> @param[in] owner Owner index in [1, nat]
      !> @param[in] points Sample positions (3, npts), bohr
      !> @param[in] xyz Nuclear positions (3, nat), bohr
      !> @param[in] numbers Atomic numbers (nat)
      !> @param[in] seed Fixed owner-partition adjoints (npts)
      !> @param[in] direction Nuclear displacement direction (3, nat)
      !> @param[in] point_direction Common point displacement direction (3)
      !> @param[in,out] hessian_vector Nuclear Hessian-vector accumulator (3, nat)
      !> @param[out] point_hessian_vector Point Hessian-vector contributions (3, npts)
      !> @param[out] error Allocation failure or coincident elliptic centers
      !> @param[in] nthreads Optional worker count
      subroutine partition_owner_hessian_vector_i(self, owner, points, xyz, numbers, seed, direction, &
         & point_direction, hessian_vector, point_hessian_vector, error, nthreads)
         import :: moist_math_grid_3d_partition_type, wp, error_type
         implicit none(type, external)
         !> Configured partition scheme
         class(moist_math_grid_3d_partition_type), intent(in) :: self
         !> Owner index
         integer, intent(in) :: owner
         !> Sample positions
         real(wp), intent(in) :: points(:, :)
         !> Nuclear positions
         real(wp), intent(in) :: xyz(:, :)
         !> Atomic numbers
         integer, intent(in) :: numbers(:)
         !> Fixed partition adjoints
         real(wp), intent(in) :: seed(:)
         !> Nuclear displacement direction
         real(wp), intent(in) :: direction(:, :)
         !> Common point displacement direction
         real(wp), intent(in) :: point_direction(:)
         !> Nuclear Hessian-vector accumulator
         real(wp), intent(inout) :: hessian_vector(:, :)
         !> Point Hessian-vector contributions
         real(wp), intent(out) :: point_hessian_vector(:, :)
         !> Invalid geometry or allocation failure
         type(error_type), allocatable, intent(out) :: error
         !> Worker count
         integer, intent(in), optional :: nthreads
      end subroutine partition_owner_hessian_vector_i

      !> Evaluate all owners and quadrature weights in one prepared pass
      !>
      !> @param[in] self Configured partition scheme
      !> @param[in] points Sample positions (3, ng), bohr
      !> @param[in] xyz Nuclear positions (3, nat), bohr
      !> @param[in] numbers Atomic numbers (nat)
      !> @param[in] owners Point owners (ng), in [1, nat]
      !> @param[in] atomic_w Fixed atomic quadrature weights (ng), bohr**3
      !> @param[out] w Integration weights (ng), bohr**3
      !> @param[out] partition_w Normalized owner-partition weights (ng)
      !> @param[out] error Invalid geometry, allocation or non-finite contraction
      !> @param[in] nthreads Optional worker count; enclosing teams use one worker
      subroutine partition_grid_weights_i(self, points, xyz, numbers, owners, atomic_w, w, partition_w, &
         & error, nthreads)
         import :: moist_math_grid_3d_partition_type, wp, error_type
         implicit none(type, external)
         !> Configured partition scheme
         class(moist_math_grid_3d_partition_type), intent(in) :: self
         !> Sample positions (3, ng), bohr
         real(wp), intent(in) :: points(:, :)
         !> Nuclear positions (3, nat), bohr
         real(wp), intent(in) :: xyz(:, :)
         !> Atomic numbers (nat)
         integer, intent(in) :: numbers(:)
         !> Point owners (ng), in [1, nat]
         integer, intent(in) :: owners(:)
         !> Fixed atomic quadrature weights (ng), bohr**3
         real(wp), intent(in) :: atomic_w(:)
         !> Integration weights (ng), bohr**3
         real(wp), intent(out) :: w(:)
         !> Normalized owner-partition weights (ng)
         real(wp), intent(out) :: partition_w(:)
         !> Invalid geometry, allocation or non-finite contraction
         type(error_type), intent(out), allocatable :: error
         !> Optional worker count; enclosing teams use one worker
         integer, intent(in), optional :: nthreads
      end subroutine partition_grid_weights_i

      !> Contract all point and weight adjoints with owner motion
      !>
      !> @param[in] self Configured partition scheme
      !> @param[in] points Sample positions (3, ng), bohr
      !> @param[in] xyz Nuclear positions (3, nat), bohr
      !> @param[in] numbers Atomic numbers (nat)
      !> @param[in] owners Point owners (ng), in [1, nat]
      !> @param[in] atomic_w Fixed atomic quadrature weights (ng), bohr**3
      !> @param[in] adjoint_xyz Point-position adjoints (3, ng)
      !> @param[in] adjoint_w Integration-weight adjoints (ng)
      !> @param[in,out] gradient Nuclear-gradient accumulator (3, nat)
      !> @param[out] error Invalid geometry, allocation or non-finite contraction
      !> @param[in] nthreads Optional worker count; enclosing teams use one worker
      subroutine partition_grid_gradient_i(self, points, xyz, numbers, owners, atomic_w, adjoint_xyz, &
         & adjoint_w, gradient, error, nthreads)
         import :: moist_math_grid_3d_partition_type, wp, error_type
         implicit none(type, external)
         !> Configured partition scheme
         class(moist_math_grid_3d_partition_type), intent(in) :: self
         !> Sample positions (3, ng), bohr
         real(wp), intent(in) :: points(:, :)
         !> Nuclear positions (3, nat), bohr
         real(wp), intent(in) :: xyz(:, :)
         !> Atomic numbers (nat)
         integer, intent(in) :: numbers(:)
         !> Point owners (ng), in [1, nat]
         integer, intent(in) :: owners(:)
         !> Fixed atomic quadrature weights (ng), bohr**3
         real(wp), intent(in) :: atomic_w(:)
         !> Point-position adjoints (3, ng)
         real(wp), intent(in) :: adjoint_xyz(:, :)
         !> Integration-weight adjoints (ng)
         real(wp), intent(in) :: adjoint_w(:)
         !> Nuclear-gradient accumulator (3, nat)
         real(wp), intent(inout) :: gradient(:, :)
         !> Invalid geometry, allocation or non-finite contraction
         type(error_type), intent(out), allocatable :: error
         !> Optional worker count; enclosing teams use one worker
         integer, intent(in), optional :: nthreads
      end subroutine partition_grid_gradient_i

      !> Contract point, weight and Gaussian-width adjoints with owner motion
      !>
      !> @param[in] self Configured partition scheme
      !> @param[in] points Sample positions (3, ng), bohr
      !> @param[in] xyz Nuclear positions (3, nat), bohr
      !> @param[in] numbers Atomic numbers (nat)
      !> @param[in] owners Point owners (ng), in [1, nat]
      !> @param[in] atomic_w Fixed atomic quadrature weights (ng), bohr**3
      !> @param[in] adjoint_xyz Point-position adjoints (3, ng)
      !> @param[in] adjoint_w Integration-weight adjoints (ng)
      !> @param[in] adjoint_xi Gaussian-width adjoints (ng)
      !> @param[in] xi0 Gaussian exponents (ng), inverse bohr
      !> @param[in] weights Positive realized integration weights (ng), bohr**3
      !> @param[in,out] gradient Nuclear-gradient accumulator (3, nat)
      !> @param[out] error Invalid geometry, allocation or non-finite contraction
      !> @param[in] nthreads Optional worker count; enclosing teams use one worker
      subroutine partition_grid_gaussian_gradient_i(self, points, xyz, numbers, owners, atomic_w, &
         & adjoint_xyz, adjoint_w, adjoint_xi, xi0, weights, gradient, error, nthreads)
         import :: moist_math_grid_3d_partition_type, wp, error_type
         implicit none(type, external)
         !> Configured partition scheme
         class(moist_math_grid_3d_partition_type), intent(in) :: self
         !> Sample positions (3, ng), bohr
         real(wp), intent(in) :: points(:, :)
         !> Nuclear positions (3, nat), bohr
         real(wp), intent(in) :: xyz(:, :)
         !> Atomic numbers (nat)
         integer, intent(in) :: numbers(:)
         !> Point owners (ng), in [1, nat]
         integer, intent(in) :: owners(:)
         !> Fixed atomic quadrature weights (ng), bohr**3
         real(wp), intent(in) :: atomic_w(:)
         !> Point-position adjoints (3, ng)
         real(wp), intent(in) :: adjoint_xyz(:, :)
         !> Integration-weight adjoints (ng)
         real(wp), intent(in) :: adjoint_w(:)
         !> Gaussian-width adjoints (ng)
         real(wp), intent(in) :: adjoint_xi(:)
         !> Gaussian exponents (ng), inverse bohr
         real(wp), intent(in) :: xi0(:)
         !> Positive realized integration weights (ng), bohr**3
         real(wp), intent(in) :: weights(:)
         !> Nuclear-gradient accumulator (3, nat)
         real(wp), intent(inout) :: gradient(:, :)
         !> Invalid geometry, allocation or non-finite contraction
         type(error_type), intent(out), allocatable :: error
         !> Optional worker count; enclosing teams use one worker
         integer, intent(in), optional :: nthreads
      end subroutine partition_grid_gaussian_gradient_i

      !> Contract nuclear curvature with one prepared directional pass
      !>
      !> @param[in] self Configured partition scheme
      !> @param[in] points Sample positions (3, ng), bohr
      !> @param[in] xyz Nuclear positions (3, nat), bohr
      !> @param[in] numbers Atomic numbers (nat)
      !> @param[in] owners Point owners (ng), in [1, nat]
      !> @param[in] atomic_w Fixed atomic quadrature weights (ng), bohr**3
      !> @param[in] adjoint_w Integration-weight adjoints (ng)
      !> @param[in] direction Nuclear displacement direction (3, nat)
      !> @param[in,out] hessian_vector Nuclear Hessian-vector accumulator (3, nat)
      !> @param[out] error Invalid geometry, allocation or non-finite contraction
      !> @param[in] nthreads Optional worker count; enclosing teams use one worker
      subroutine partition_grid_hessian_vector_i(self, points, xyz, numbers, owners, atomic_w, adjoint_w, &
         & direction, hessian_vector, error, nthreads)
         import :: moist_math_grid_3d_partition_type, wp, error_type
         implicit none(type, external)
         !> Configured partition scheme
         class(moist_math_grid_3d_partition_type), intent(in) :: self
         !> Sample positions (3, ng), bohr
         real(wp), intent(in) :: points(:, :)
         !> Nuclear positions (3, nat), bohr
         real(wp), intent(in) :: xyz(:, :)
         !> Atomic numbers (nat)
         integer, intent(in) :: numbers(:)
         !> Point owners (ng), in [1, nat]
         integer, intent(in) :: owners(:)
         !> Fixed atomic quadrature weights (ng), bohr**3
         real(wp), intent(in) :: atomic_w(:)
         !> Integration-weight adjoints (ng)
         real(wp), intent(in) :: adjoint_w(:)
         !> Nuclear displacement direction (3, nat)
         real(wp), intent(in) :: direction(:, :)
         !> Nuclear Hessian-vector accumulator (3, nat)
         real(wp), intent(inout) :: hessian_vector(:, :)
         !> Invalid geometry, allocation or non-finite contraction
         type(error_type), intent(out), allocatable :: error
         !> Optional worker count; enclosing teams use one worker
         integer, intent(in), optional :: nthreads
      end subroutine partition_grid_hessian_vector_i

      !> Assemble dense nuclear curvature with one geometry, scratch and worker team
      !>
      !> @param[in] self Configured partition scheme
      !> @param[in] points Sample positions (3, ng), bohr
      !> @param[in] xyz Nuclear positions (3, nat), bohr
      !> @param[in] numbers Atomic numbers (nat)
      !> @param[in] owners Point owners (ng), in [1, nat]
      !> @param[in] atomic_w Fixed atomic quadrature weights (ng), bohr**3
      !> @param[in] adjoint_w Integration-weight adjoints (ng)
      !> @param[in,out] hessian Nuclear Hessian accumulator (3, nat, 3, nat)
      !> @param[out] error Invalid geometry, allocation or non-finite contraction
      !> @param[in] nthreads Optional worker count; enclosing teams use one worker
      subroutine partition_grid_hessian_i(self, points, xyz, numbers, owners, atomic_w, adjoint_w, hessian, &
         & error, nthreads)
         import :: moist_math_grid_3d_partition_type, wp, error_type
         implicit none(type, external)
         !> Configured partition scheme
         class(moist_math_grid_3d_partition_type), intent(in) :: self
         !> Sample positions (3, ng), bohr
         real(wp), intent(in) :: points(:, :)
         !> Nuclear positions (3, nat), bohr
         real(wp), intent(in) :: xyz(:, :)
         !> Atomic numbers (nat)
         integer, intent(in) :: numbers(:)
         !> Point owners (ng), in [1, nat]
         integer, intent(in) :: owners(:)
         !> Fixed atomic quadrature weights (ng), bohr**3
         real(wp), intent(in) :: atomic_w(:)
         !> Integration-weight adjoints (ng)
         real(wp), intent(in) :: adjoint_w(:)
         !> Nuclear Hessian accumulator (3, nat, 3, nat)
         real(wp), intent(inout) :: hessian(:, :, :, :)
         !> Invalid geometry, allocation or non-finite contraction
         type(error_type), intent(out), allocatable :: error
         !> Optional worker count; enclosing teams use one worker
         integer, intent(in), optional :: nthreads
      end subroutine partition_grid_hessian_i
   end interface

end module moist_math_grid_3d_kernel_base
