!> Whole-grid Cartesian derivatives of linear centroid motion
!>
!> Generated by moist_dev/tools/maths/grid/generate_partitions.py
!> Edit the generator in moist_dev and regenerate; no runtime Python dependency
module moist_math_grid_3d_kernel_cartesian
   use mctc_env, only: wp, error_type, fatal_error
   use, intrinsic :: ieee_arithmetic, only: ieee_is_finite
   implicit none(type, external)
   private

   public :: cartesian_grid_gradient, cartesian_grid_hessian_vector, cartesian_grid_hessian

contains

   !> Contract centroid-following point motion; weights and widths constant
   !>
   !> Unchecked shapes; caller validates realized state and adjoint channels
   !> Nuclear accumulators committed only after a finite contraction
   !>
   !> @param[in] adjoint_xyz Point-position adjoints (3, ng)
   !> @param[in,out] gradient Nuclear-gradient accumulator (3, nat)
   !> @param[out] error Invalid geometry, allocation or non-finite contraction
   subroutine cartesian_grid_gradient(adjoint_xyz, gradient, error)
      !> Point-position adjoints (3, ng)
      real(wp), intent(in) :: adjoint_xyz(:, :)
      !> Nuclear-gradient accumulator (3, nat)
      real(wp), intent(inout) :: gradient(:, :)
      !> Invalid geometry, allocation or non-finite contraction
      type(error_type), intent(out), allocatable :: error

      real(wp) :: contribution(3)
      integer :: a

      contribution = sum(adjoint_xyz, dim=2)/real(size(gradient, 2), wp)
      if (.not. all(ieee_is_finite(contribution))) then
         call fatal_error(error, "Cartesian gradient: non-finite contraction")
         return
      end if
      do a = 1, size(gradient, 2)
         gradient(:, a) = gradient(:, a) + contribution
      end do
   end subroutine cartesian_grid_gradient

   !> Zero curvature of linear centroid motion and constant weights
   !>
   !> Unchecked shapes; caller validates realized state and adjoint channels
   !> Nuclear accumulators committed only after a finite contraction
   !>
   !> @param[in,out] hessian_vector Nuclear Hessian-vector accumulator (3, nat)
   subroutine cartesian_grid_hessian_vector(hessian_vector)
      !> Nuclear Hessian-vector accumulator (3, nat)
      real(wp), intent(inout) :: hessian_vector(:, :)

      ! Exact zero contribution; preserve the caller's accumulator
   end subroutine cartesian_grid_hessian_vector

   !> Zero curvature of linear centroid motion and constant weights
   !>
   !> Unchecked shapes; caller validates realized state and adjoint channels
   !> Nuclear accumulators committed only after a finite contraction
   !>
   !> @param[in,out] hessian Nuclear Hessian accumulator (3, nat, 3, nat)
   subroutine cartesian_grid_hessian(hessian)
      !> Nuclear Hessian accumulator (3, nat, 3, nat)
      real(wp), intent(inout) :: hessian(:, :, :, :)

      ! Exact zero contribution; preserve the caller's accumulator
   end subroutine cartesian_grid_hessian

end module moist_math_grid_3d_kernel_cartesian
