!> Fuzzy power-Voronoi partition
!>
!> Generated by moist_dev/tools/maths/grid/generate_partitions.py
!> Edit the generator in moist_dev and regenerate; no runtime Python dependency
module moist_math_grid_3d_kernel_pvoronoi
   use mctc_env, only: wp, error_type, fatal_error
   use moist_data_atomicrad, only: covalent_rad
   use, intrinsic :: ieee_arithmetic, only: ieee_is_finite
   use moist_math_grid_3d_kernel_base, only: moist_math_grid_3d_partition_type
!$ use omp_lib, only: omp_get_max_threads, omp_get_thread_num, omp_in_parallel
   implicit none(type, external)
   private

   public :: pvoronoi_partition_type, default_power_width

   !> Default switch setting
   real(wp), parameter :: default_power_width = 1.0_wp

   !> Fuzzy power-Voronoi partition with its switch settings
   type, extends(moist_math_grid_3d_partition_type) :: pvoronoi_partition_type
      !> Power-coordinate half-width (> 0), bohr**2
      real(wp) :: width = default_power_width
      !> Optional fixed power radii (nat), bohr; covalent radii when unallocated
      real(wp), allocatable :: radii(:)
   contains
      !> Pair-switch weight
      procedure :: eval => pvoronoi_eval
      !> Fused pair-switch weight and first derivative
      procedure :: eval_with_derivative => pvoronoi_eval_with_derivative
      !> Fused pair-switch weight and first two derivatives
      procedure :: eval_with_second_derivative => pvoronoi_eval_with_second_derivative
      !> Normalized weights of one owner at fixed points
      procedure :: owner_weights => pvoronoi_owner_weights
      !> Contract one owner's partition adjoints at fixed points
      procedure :: owner_gradient => pvoronoi_owner_gradient
      !> Directional derivative of one owner's partition reverse contraction
      procedure :: owner_hessian_vector => pvoronoi_owner_hessian_vector
      !> Evaluate all owners and quadrature weights in one prepared pass
      procedure :: grid_weights => pvoronoi_grid_weights
      !> Contract all point and weight adjoints with owner motion
      procedure :: grid_gradient => pvoronoi_grid_gradient
      !> Contract point, weight and Gaussian-width adjoints with owner motion
      procedure :: grid_gaussian_gradient => pvoronoi_grid_gaussian_gradient
      !> Contract nuclear curvature with one prepared directional pass
      procedure :: grid_hessian_vector => pvoronoi_grid_hessian_vector
      !> Assemble dense nuclear curvature with one geometry, scratch and worker team
      procedure :: grid_hessian => pvoronoi_grid_hessian
   end type pvoronoi_partition_type

contains

   !> Stable bump switch through pair-coordinate order 0
   !>
   !> @param[in] self Configured partition scheme
   !> @param[in] x Pair coordinate
   pure function pvoronoi_eval(self, x) result(s)
      !> Configured partition scheme
      class(pvoronoi_partition_type), intent(in) :: self
      !> Pair coordinate
      real(wp), intent(in) :: x
      !> Pair-switch weight
      real(wp) :: s
      real(wp) :: u, d, e

      s = 0.0_wp
      if (abs(x) >= 1.0_wp) then
         if (x < 0.0_wp) s = 1.0_wp
         return
      end if
      u = abs(x)
      d = (1.0_wp - u)*(1.0_wp + u)
      e = exp(-2.0_wp*u/d)
      s = e*(1.0_wp/(1.0_wp + e))
      if (x < 0.0_wp) then
         s = 1.0_wp - s
      end if
   end function pvoronoi_eval

   !> Stable bump switch through pair-coordinate order 1
   !>
   !> @param[in] self Configured partition scheme
   !> @param[in] x Pair coordinate
   !> @param[out] s Pair-switch weight
   !> @param[out] ds First pair-coordinate derivative
   pure subroutine pvoronoi_eval_with_derivative(self, x, s, ds)
      !> Configured partition scheme
      class(pvoronoi_partition_type), intent(in) :: self
      !> Pair coordinate
      real(wp), intent(in) :: x
      !> Pair-switch weight
      real(wp), intent(out) :: s
      !> First derivative
      real(wp), intent(out) :: ds
      real(wp) :: u, d, e, c0

      s = 0.0_wp
      ds = 0.0_wp
      if (abs(x) >= 1.0_wp) then
         if (x < 0.0_wp) s = 1.0_wp
         return
      end if
      u = abs(x)
      d = (1.0_wp - u)*(1.0_wp + u)
      e = exp(-2.0_wp*u/d)
      c0 = 1.0_wp + e
      s = e*(1.0_wp/c0)
      ds = e*(1.0_wp/c0**2)*(1.0_wp/d**2)*(-2.0_wp - 2.0_wp*u**2)
      if (x < 0.0_wp) then
         s = 1.0_wp - s
      end if
   end subroutine pvoronoi_eval_with_derivative

   !> Stable bump switch through pair-coordinate order 2
   !>
   !> @param[in] self Configured partition scheme
   !> @param[in] x Pair coordinate
   !> @param[out] s Pair-switch weight
   !> @param[out] ds First pair-coordinate derivative
   !> @param[out] d2s Second pair-coordinate derivative; zero at endpoints
   pure subroutine pvoronoi_eval_with_second_derivative(self, x, s, ds, d2s)
      !> Configured partition scheme
      class(pvoronoi_partition_type), intent(in) :: self
      !> Pair coordinate
      real(wp), intent(in) :: x
      !> Pair-switch weight
      real(wp), intent(out) :: s
      !> First derivative
      real(wp), intent(out) :: ds
      !> Second derivative
      real(wp), intent(out) :: d2s
      real(wp) :: u, d, e, c0, c1, c2, c3, c4

      s = 0.0_wp
      ds = 0.0_wp
      d2s = 0.0_wp
      if (abs(x) >= 1.0_wp) then
         if (x < 0.0_wp) s = 1.0_wp
         return
      end if
      u = abs(x)
      d = (1.0_wp - u)*(1.0_wp + u)
      e = exp(-2.0_wp*u/d)
      c0 = 1.0_wp + e
      c1 = (1.0_wp/c0)
      c2 = u**2
      c3 = -2.0_wp - 2.0_wp*c2
      c4 = e*(1.0_wp/c0**2)
      s = c1*e
      ds = c3*c4*(1.0_wp/d**2)
      d2s = c4*(-4.0_wp*u*(1.0_wp/d**3)*(3.0_wp + c2) + c1*c3**2*(1.0_wp/d**4)*(1.0_wp - e))
      if (x < 0.0_wp) then
         s = 1.0_wp - s
         d2s = -d2s
      end if
   end subroutine pvoronoi_eval_with_second_derivative

   !> Evaluate all owners and quadrature weights in one prepared pass
   !>
   !> Unchecked shapes, finite inputs, valid owners and switch settings required
   !> Nuclear accumulators committed only after a finite contraction
   !>
   !> @param[in] self Configured partition scheme
   !> @param[in] points Sample positions (3, ng), bohr
   !> @param[in] xyz Nuclear positions (3, nat), bohr
   !> @param[in] numbers Atomic numbers (nat)
   !> @param[in] owners Point owners (ng), in [1, nat]
   !> @param[in] atomic_w Fixed atomic quadrature weights (ng), bohr**3
   !> @param[out] w Integration weights (ng), bohr**3
   !> @param[out] partition_w Normalized owner-partition weights (ng)
   !> @param[out] error Invalid geometry, allocation or non-finite contraction
   !> @param[in] nthreads Optional worker count; enclosing teams use one worker
   subroutine pvoronoi_grid_weights(self, points, xyz, numbers, owners, atomic_w, w, partition_w, &
      & error, nthreads)
      !> Configured partition scheme
      class(pvoronoi_partition_type), intent(in) :: self
      !> Sample positions (3, ng), bohr
      real(wp), intent(in) :: points(:, :)
      !> Nuclear positions (3, nat), bohr
      real(wp), intent(in) :: xyz(:, :)
      !> Atomic numbers (nat)
      integer, intent(in) :: numbers(:)
      !> Point owners (ng), in [1, nat]
      integer, intent(in) :: owners(:)
      !> Fixed atomic quadrature weights (ng), bohr**3
      real(wp), intent(in) :: atomic_w(:)
      !> Integration weights (ng), bohr**3
      real(wp), intent(out) :: w(:)
      !> Normalized owner-partition weights (ng)
      real(wp), intent(out) :: partition_w(:)
      !> Invalid geometry, allocation or non-finite contraction
      type(error_type), intent(out), allocatable :: error
      !> Optional worker count; enclosing teams use one worker
      integer, intent(in), optional :: nthreads

      real(wp), allocatable :: pair_a(:, :), dist(:, :), probs(:, :)
      real(wp) :: point(3), peak, half_width
      integer :: nat, ng, nt, slot, ip, owner, stat, i

      nat = size(numbers)
      ng = size(owners)
      if (ng == 0) return
      half_width = self%width
      nt = 1
!$    if (.not. omp_in_parallel()) then
!$       nt = omp_get_max_threads()
!$       if (present(nthreads)) then
!$          if (nthreads > 0) nt = nthreads
!$       end if
!$       nt = min(nt, ng)
!$    end if
      allocate (pair_a(nat, nat), stat=stat)
      if (stat == 0) allocate (dist(nat, nt), stat=stat)
      if (stat == 0) allocate (probs(nat, nt), stat=stat)
      if (stat /= 0) then
         call fatal_error(error, "pvoronoi grid: cannot allocate weights scratch")
         return
      end if
      block
         real(wp) :: radius(size(numbers))
         integer :: ia, ja

         radius = covalent_rad(numbers)
         if (allocated(self%radii)) then
            if (size(self%radii) /= size(numbers)) then
               call fatal_error(error, "pvoronoi partition: radii needs one entry per atom")
               return
            end if
            radius = self%radii
         end if
         pair_a = 0.0_wp
         do ia = 1, size(numbers)
            do ja = 1, ia - 1
               pair_a(ja, ia) = (radius(ja) - radius(ia))*(radius(ja) + radius(ia))
               pair_a(ia, ja) = -pair_a(ja, ia)
            end do
         end do
      end block
      !$omp parallel num_threads(nt) default(none) &
      !$omp shared(points, xyz, owners, atomic_w, pair_a, dist, probs, nat, ng, half_width, w, &
      !$omp    & partition_w) private(slot, ip, owner, point, i, peak)
      slot = 1
!$    slot = omp_get_thread_num() + 1
      !$omp do schedule(static, 64)
      do ip = 1, ng
         owner = owners(ip)
         point = points(:, ip)
         if (nat == 1) then
            partition_w(ip) = 1.0_wp
         else
            probs(owner, slot) = pvoronoi_cell_log(owner, point, xyz, dist(:, slot), pair_a, half_width)
            if (probs(owner, slot) == -huge(1.0_wp)) then
               partition_w(ip) = 0.0_wp
            else
               do i = 1, nat
                  if (i /= owner) then
                     probs(i, slot) = pvoronoi_cell_log(i, point, xyz, dist(:, slot), pair_a, half_width)
                  end if
               end do
               peak = maxval(probs(:, slot))
               partition_w(ip) = exp(probs(owner, slot) - peak)/sum(exp(probs(:, slot) - peak))
            end if
         end if
         w(ip) = atomic_w(ip)*partition_w(ip)
      end do
      !$omp end do
      !$omp end parallel
      if (.not. all(ieee_is_finite(w))) then
         call fatal_error(error, "pvoronoi grid: non-finite integration weights")
      end if
   end subroutine pvoronoi_grid_weights

   !> Contract all point and weight adjoints with owner motion
   !>
   !> Unchecked shapes, finite inputs, valid owners and switch settings required
   !> Nuclear accumulators committed only after a finite contraction
   !>
   !> @param[in] self Configured partition scheme
   !> @param[in] points Sample positions (3, ng), bohr
   !> @param[in] xyz Nuclear positions (3, nat), bohr
   !> @param[in] numbers Atomic numbers (nat)
   !> @param[in] owners Point owners (ng), in [1, nat]
   !> @param[in] atomic_w Fixed atomic quadrature weights (ng), bohr**3
   !> @param[in] adjoint_xyz Point-position adjoints (3, ng)
   !> @param[in] adjoint_w Integration-weight adjoints (ng)
   !> @param[in,out] gradient Nuclear-gradient accumulator (3, nat)
   !> @param[out] error Invalid geometry, allocation or non-finite contraction
   !> @param[in] nthreads Optional worker count; enclosing teams use one worker
   subroutine pvoronoi_grid_gradient(self, points, xyz, numbers, owners, atomic_w, adjoint_xyz, &
      & adjoint_w, gradient, error, nthreads)
      !> Configured partition scheme
      class(pvoronoi_partition_type), intent(in) :: self
      !> Sample positions (3, ng), bohr
      real(wp), intent(in) :: points(:, :)
      !> Nuclear positions (3, nat), bohr
      real(wp), intent(in) :: xyz(:, :)
      !> Atomic numbers (nat)
      integer, intent(in) :: numbers(:)
      !> Point owners (ng), in [1, nat]
      integer, intent(in) :: owners(:)
      !> Fixed atomic quadrature weights (ng), bohr**3
      real(wp), intent(in) :: atomic_w(:)
      !> Point-position adjoints (3, ng)
      real(wp), intent(in) :: adjoint_xyz(:, :)
      !> Integration-weight adjoints (ng)
      real(wp), intent(in) :: adjoint_w(:)
      !> Nuclear-gradient accumulator (3, nat)
      real(wp), intent(inout) :: gradient(:, :)
      !> Invalid geometry, allocation or non-finite contraction
      type(error_type), intent(out), allocatable :: error
      !> Optional worker count; enclosing teams use one worker
      integer, intent(in), optional :: nthreads

      real(wp), allocatable :: pair_a(:, :), dist(:, :), probs(:, :), workers(:, :, :), local(:, :)
      real(wp) :: point(3), seed, point_response(3), half_width
      integer :: nat, ng, nt, slot, ip, owner, stat

      nat = size(numbers)
      ng = size(owners)
      if (ng == 0) return
      half_width = self%width
      nt = 1
!$    if (.not. omp_in_parallel()) then
!$       nt = omp_get_max_threads()
!$       if (present(nthreads)) then
!$          if (nthreads > 0) nt = nthreads
!$       end if
!$       nt = min(nt, ng)
!$    end if
      allocate (pair_a(nat, nat), stat=stat)
      if (stat == 0) allocate (dist(nat, nt), stat=stat)
      if (stat == 0) allocate (probs(nat, nt), stat=stat)
      if (stat == 0) allocate (workers(3, nat, nt), stat=stat)
      if (stat == 0) allocate (local(3, nat), stat=stat)
      if (stat /= 0) then
         call fatal_error(error, "pvoronoi grid: cannot allocate gradient scratch")
         return
      end if
      block
         real(wp) :: radius(size(numbers))
         integer :: ia, ja

         radius = covalent_rad(numbers)
         if (allocated(self%radii)) then
            if (size(self%radii) /= size(numbers)) then
               call fatal_error(error, "pvoronoi partition: radii needs one entry per atom")
               return
            end if
            radius = self%radii
         end if
         pair_a = 0.0_wp
         do ia = 1, size(numbers)
            do ja = 1, ia - 1
               pair_a(ja, ia) = (radius(ja) - radius(ia))*(radius(ja) + radius(ia))
               pair_a(ia, ja) = -pair_a(ja, ia)
            end do
         end do
      end block
      workers = 0.0_wp
      !$omp parallel num_threads(nt) default(none) &
      !$omp shared(points, xyz, owners, atomic_w, pair_a, dist, probs, nat, ng, half_width, adjoint_w, &
      !$omp    & workers, adjoint_xyz) private(slot, ip, owner, point, seed, point_response)
      slot = 1
!$    slot = omp_get_thread_num() + 1
      !$omp do schedule(static, 64)
      do ip = 1, ng
         owner = owners(ip)
         point = points(:, ip)
         seed = atomic_w(ip)*adjoint_w(ip)
         point_response = 0.0_wp
         if (seed /= 0.0_wp .and. nat > 1) then
            point_math: block
               real(wp) :: peak, owner_seed, log_seed, nu, s, ds, factor
               integer :: i, j

               associate (dist => dist(:, slot), probs => probs(:, slot), gradient => workers(:, :, slot), &
                  & point_gradient => point_response, width => half_width)
                  point_gradient = 0.0_wp
                  dist = 0.0_wp
                  do i = 1, size(dist)
                     probs(i) = pvoronoi_cell_log(i, point, xyz, dist, pair_a, width)
                  end do
                  if (probs(owner) == -huge(1.0_wp)) exit point_math
                  peak = maxval(probs)
                  probs = exp(probs - peak)
                  probs = probs/sum(probs)
                  owner_seed = seed*probs(owner)
                  do i = 1, size(dist)
                     log_seed = -owner_seed*probs(i)
                     if (i == owner) then
                        ! Sum other probabilities to retain derivatives of tiny partition tails
                        log_seed = owner_seed*(sum(probs(:i - 1)) + sum(probs(i + 1:)))
                     end if
                     if (log_seed == 0.0_wp) cycle
                     do j = 1, size(dist)
                        if (j == i) cycle
                        nu = (dot_product((point - xyz(:, i)) + (point - xyz(:, j)), &
                           & xyz(:, j) - xyz(:, i)) + pair_a(j, i))/width
                        block
                           real(wp) :: u, d, e, c0

                           s = 0.0_wp
                           ds = 0.0_wp
                           if (abs(nu) >= 1.0_wp) then
                              if (nu < 0.0_wp) s = 1.0_wp
                           else
                              u = abs(nu)
                              d = (1.0_wp - u)*(1.0_wp + u)
                              e = exp(-2.0_wp*u/d)
                              c0 = 1.0_wp + e
                              s = e*(1.0_wp/c0)
                              ds = e*(1.0_wp/c0**2)*(1.0_wp/d**2)*(-2.0_wp - 2.0_wp*u**2)
                              if (nu < 0.0_wp) then
                                 s = 1.0_wp - s
                              end if
                           end if
                        end block
                        if (s <= 0.0_wp .or. ds == 0.0_wp) cycle
                        factor = (log_seed/s)*ds
                        factor = 2.0_wp*factor/width
                        point_gradient = point_gradient + factor*(xyz(:, j) - xyz(:, i))
                        gradient(:, i) = gradient(:, i) - factor*(point - xyz(:, i))
                        gradient(:, j) = gradient(:, j) + factor*(point - xyz(:, j))
                     end do
                  end do
               end associate
            end block point_math
         end if
         workers(:, owner, slot) = workers(:, owner, slot) + point_response + adjoint_xyz(:, ip)
      end do
      !$omp end do
      !$omp end parallel
      local = 0.0_wp
      do slot = 1, nt
         local = local + workers(:, :, slot)
      end do
      if (.not. all(ieee_is_finite(local))) then
         call fatal_error(error, "pvoronoi grid: non-finite gradient contraction")
         return
      end if
      gradient = gradient + local
   end subroutine pvoronoi_grid_gradient

   !> Contract point, weight and Gaussian-width adjoints with owner motion
   !>
   !> Unchecked shapes, finite inputs, valid owners and switch settings required
   !> Nuclear accumulators committed only after a finite contraction
   !>
   !> @param[in] self Configured partition scheme
   !> @param[in] points Sample positions (3, ng), bohr
   !> @param[in] xyz Nuclear positions (3, nat), bohr
   !> @param[in] numbers Atomic numbers (nat)
   !> @param[in] owners Point owners (ng), in [1, nat]
   !> @param[in] atomic_w Fixed atomic quadrature weights (ng), bohr**3
   !> @param[in] adjoint_xyz Point-position adjoints (3, ng)
   !> @param[in] adjoint_w Integration-weight adjoints (ng)
   !> @param[in] adjoint_xi Gaussian-width adjoints (ng)
   !> @param[in] xi0 Gaussian exponents (ng), inverse bohr
   !> @param[in] weights Positive realized integration weights (ng), bohr**3
   !> @param[in,out] gradient Nuclear-gradient accumulator (3, nat)
   !> @param[out] error Invalid geometry, allocation or non-finite contraction
   !> @param[in] nthreads Optional worker count; enclosing teams use one worker
   subroutine pvoronoi_grid_gaussian_gradient(self, points, xyz, numbers, owners, atomic_w, &
      & adjoint_xyz, adjoint_w, adjoint_xi, xi0, weights, gradient, error, nthreads)
      !> Configured partition scheme
      class(pvoronoi_partition_type), intent(in) :: self
      !> Sample positions (3, ng), bohr
      real(wp), intent(in) :: points(:, :)
      !> Nuclear positions (3, nat), bohr
      real(wp), intent(in) :: xyz(:, :)
      !> Atomic numbers (nat)
      integer, intent(in) :: numbers(:)
      !> Point owners (ng), in [1, nat]
      integer, intent(in) :: owners(:)
      !> Fixed atomic quadrature weights (ng), bohr**3
      real(wp), intent(in) :: atomic_w(:)
      !> Point-position adjoints (3, ng)
      real(wp), intent(in) :: adjoint_xyz(:, :)
      !> Integration-weight adjoints (ng)
      real(wp), intent(in) :: adjoint_w(:)
      !> Gaussian-width adjoints (ng)
      real(wp), intent(in) :: adjoint_xi(:)
      !> Gaussian exponents (ng), inverse bohr
      real(wp), intent(in) :: xi0(:)
      !> Positive realized integration weights (ng), bohr**3
      real(wp), intent(in) :: weights(:)
      !> Nuclear-gradient accumulator (3, nat)
      real(wp), intent(inout) :: gradient(:, :)
      !> Invalid geometry, allocation or non-finite contraction
      type(error_type), intent(out), allocatable :: error
      !> Optional worker count; enclosing teams use one worker
      integer, intent(in), optional :: nthreads

      real(wp), allocatable :: pair_a(:, :), dist(:, :), probs(:, :), workers(:, :, :), local(:, :)
      real(wp) :: point(3), seed, point_response(3), half_width
      integer :: nat, ng, nt, slot, ip, owner, stat

      nat = size(numbers)
      ng = size(owners)
      if (ng == 0) return
      half_width = self%width
      nt = 1
!$    if (.not. omp_in_parallel()) then
!$       nt = omp_get_max_threads()
!$       if (present(nthreads)) then
!$          if (nthreads > 0) nt = nthreads
!$       end if
!$       nt = min(nt, ng)
!$    end if
      allocate (pair_a(nat, nat), stat=stat)
      if (stat == 0) allocate (dist(nat, nt), stat=stat)
      if (stat == 0) allocate (probs(nat, nt), stat=stat)
      if (stat == 0) allocate (workers(3, nat, nt), stat=stat)
      if (stat == 0) allocate (local(3, nat), stat=stat)
      if (stat /= 0) then
         call fatal_error(error, "pvoronoi grid: cannot allocate gaussian_gradient scratch")
         return
      end if
      block
         real(wp) :: radius(size(numbers))
         integer :: ia, ja

         radius = covalent_rad(numbers)
         if (allocated(self%radii)) then
            if (size(self%radii) /= size(numbers)) then
               call fatal_error(error, "pvoronoi partition: radii needs one entry per atom")
               return
            end if
            radius = self%radii
         end if
         pair_a = 0.0_wp
         do ia = 1, size(numbers)
            do ja = 1, ia - 1
               pair_a(ja, ia) = (radius(ja) - radius(ia))*(radius(ja) + radius(ia))
               pair_a(ia, ja) = -pair_a(ja, ia)
            end do
         end do
      end block
      workers = 0.0_wp
      !$omp parallel num_threads(nt) default(none) &
      !$omp shared(points, xyz, owners, atomic_w, pair_a, dist, probs, nat, ng, half_width, adjoint_w, &
      !$omp    & workers, adjoint_xyz, adjoint_xi, xi0, weights) private(slot, ip, owner, point, seed, &
      !$omp    & point_response)
      slot = 1
!$    slot = omp_get_thread_num() + 1
      !$omp do schedule(static, 64)
      do ip = 1, ng
         owner = owners(ip)
         point = points(:, ip)
         seed = atomic_w(ip)*adjoint_w(ip)
         ! Width term only with a width adjoint: xi0/w overflows for tiny retained weights
         if (adjoint_xi(ip) /= 0.0_wp) then
            seed = atomic_w(ip)*(adjoint_w(ip) + adjoint_xi(ip)*((-1.0_wp/3.0_wp)*xi0(ip)*(1.0_wp/weights(ip))))
         end if
         point_response = 0.0_wp
         if (seed /= 0.0_wp .and. nat > 1) then
            point_math: block
               real(wp) :: peak, owner_seed, log_seed, nu, s, ds, factor
               integer :: i, j

               associate (dist => dist(:, slot), probs => probs(:, slot), gradient => workers(:, :, slot), &
                  & point_gradient => point_response, width => half_width)
                  point_gradient = 0.0_wp
                  dist = 0.0_wp
                  do i = 1, size(dist)
                     probs(i) = pvoronoi_cell_log(i, point, xyz, dist, pair_a, width)
                  end do
                  if (probs(owner) == -huge(1.0_wp)) exit point_math
                  peak = maxval(probs)
                  probs = exp(probs - peak)
                  probs = probs/sum(probs)
                  owner_seed = seed*probs(owner)
                  do i = 1, size(dist)
                     log_seed = -owner_seed*probs(i)
                     if (i == owner) then
                        ! Sum other probabilities to retain derivatives of tiny partition tails
                        log_seed = owner_seed*(sum(probs(:i - 1)) + sum(probs(i + 1:)))
                     end if
                     if (log_seed == 0.0_wp) cycle
                     do j = 1, size(dist)
                        if (j == i) cycle
                        nu = (dot_product((point - xyz(:, i)) + (point - xyz(:, j)), &
                           & xyz(:, j) - xyz(:, i)) + pair_a(j, i))/width
                        block
                           real(wp) :: u, d, e, c0

                           s = 0.0_wp
                           ds = 0.0_wp
                           if (abs(nu) >= 1.0_wp) then
                              if (nu < 0.0_wp) s = 1.0_wp
                           else
                              u = abs(nu)
                              d = (1.0_wp - u)*(1.0_wp + u)
                              e = exp(-2.0_wp*u/d)
                              c0 = 1.0_wp + e
                              s = e*(1.0_wp/c0)
                              ds = e*(1.0_wp/c0**2)*(1.0_wp/d**2)*(-2.0_wp - 2.0_wp*u**2)
                              if (nu < 0.0_wp) then
                                 s = 1.0_wp - s
                              end if
                           end if
                        end block
                        if (s <= 0.0_wp .or. ds == 0.0_wp) cycle
                        factor = (log_seed/s)*ds
                        factor = 2.0_wp*factor/width
                        point_gradient = point_gradient + factor*(xyz(:, j) - xyz(:, i))
                        gradient(:, i) = gradient(:, i) - factor*(point - xyz(:, i))
                        gradient(:, j) = gradient(:, j) + factor*(point - xyz(:, j))
                     end do
                  end do
               end associate
            end block point_math
         end if
         workers(:, owner, slot) = workers(:, owner, slot) + point_response + adjoint_xyz(:, ip)
      end do
      !$omp end do
      !$omp end parallel
      local = 0.0_wp
      do slot = 1, nt
         local = local + workers(:, :, slot)
      end do
      if (.not. all(ieee_is_finite(local))) then
         call fatal_error(error, "pvoronoi grid: non-finite gaussian_gradient contraction")
         return
      end if
      gradient = gradient + local
   end subroutine pvoronoi_grid_gaussian_gradient

   !> Contract nuclear curvature with one prepared directional pass
   !>
   !> Unchecked shapes, finite inputs, valid owners and switch settings required
   !> Nuclear accumulators committed only after a finite contraction
   !>
   !> @param[in] self Configured partition scheme
   !> @param[in] points Sample positions (3, ng), bohr
   !> @param[in] xyz Nuclear positions (3, nat), bohr
   !> @param[in] numbers Atomic numbers (nat)
   !> @param[in] owners Point owners (ng), in [1, nat]
   !> @param[in] atomic_w Fixed atomic quadrature weights (ng), bohr**3
   !> @param[in] adjoint_w Integration-weight adjoints (ng)
   !> @param[in] direction Nuclear displacement direction (3, nat)
   !> @param[in,out] hessian_vector Nuclear Hessian-vector accumulator (3, nat)
   !> @param[out] error Invalid geometry, allocation or non-finite contraction
   !> @param[in] nthreads Optional worker count; enclosing teams use one worker
   subroutine pvoronoi_grid_hessian_vector(self, points, xyz, numbers, owners, atomic_w, adjoint_w, &
      & direction, hessian_vector, error, nthreads)
      !> Configured partition scheme
      class(pvoronoi_partition_type), intent(in) :: self
      !> Sample positions (3, ng), bohr
      real(wp), intent(in) :: points(:, :)
      !> Nuclear positions (3, nat), bohr
      real(wp), intent(in) :: xyz(:, :)
      !> Atomic numbers (nat)
      integer, intent(in) :: numbers(:)
      !> Point owners (ng), in [1, nat]
      integer, intent(in) :: owners(:)
      !> Fixed atomic quadrature weights (ng), bohr**3
      real(wp), intent(in) :: atomic_w(:)
      !> Integration-weight adjoints (ng)
      real(wp), intent(in) :: adjoint_w(:)
      !> Nuclear displacement direction (3, nat)
      real(wp), intent(in) :: direction(:, :)
      !> Nuclear Hessian-vector accumulator (3, nat)
      real(wp), intent(inout) :: hessian_vector(:, :)
      !> Invalid geometry, allocation or non-finite contraction
      type(error_type), intent(out), allocatable :: error
      !> Optional worker count; enclosing teams use one worker
      integer, intent(in), optional :: nthreads

      real(wp), allocatable :: pair_a(:, :), dist(:, :), probs(:, :), log_t(:, :), workers(:, :, :), &
         & local(:, :)
      real(wp) :: point(3), seed, point_response(3), half_width
      integer :: nat, ng, nt, slot, ip, owner, stat

      nat = size(numbers)
      ng = size(owners)
      if (ng == 0) return
      if (nat == 1 .or. all(atomic_w*adjoint_w == 0.0_wp)) return
      if (all(direction == 0.0_wp)) return
      half_width = self%width
      nt = 1
!$    if (.not. omp_in_parallel()) then
!$       nt = omp_get_max_threads()
!$       if (present(nthreads)) then
!$          if (nthreads > 0) nt = nthreads
!$       end if
!$       nt = min(nt, ng)
!$    end if
      allocate (pair_a(nat, nat), stat=stat)
      if (stat == 0) allocate (dist(nat, nt), stat=stat)
      if (stat == 0) allocate (probs(nat, nt), stat=stat)
      if (stat == 0) allocate (log_t(nat, nt), stat=stat)
      if (stat == 0) allocate (workers(3, nat, nt), stat=stat)
      if (stat == 0) allocate (local(3, nat), stat=stat)
      if (stat /= 0) then
         call fatal_error(error, "pvoronoi grid: cannot allocate hessian_vector scratch")
         return
      end if
      block
         real(wp) :: radius(size(numbers))
         integer :: ia, ja

         radius = covalent_rad(numbers)
         if (allocated(self%radii)) then
            if (size(self%radii) /= size(numbers)) then
               call fatal_error(error, "pvoronoi partition: radii needs one entry per atom")
               return
            end if
            radius = self%radii
         end if
         pair_a = 0.0_wp
         do ia = 1, size(numbers)
            do ja = 1, ia - 1
               pair_a(ja, ia) = (radius(ja) - radius(ia))*(radius(ja) + radius(ia))
               pair_a(ia, ja) = -pair_a(ja, ia)
            end do
         end do
      end block
      workers = 0.0_wp
      !$omp parallel num_threads(nt) default(none) &
      !$omp shared(points, xyz, owners, atomic_w, pair_a, dist, probs, nat, ng, half_width, adjoint_w, &
      !$omp    & workers, log_t, direction) private(slot, ip, owner, point, seed, point_response)
      slot = 1
!$    slot = omp_get_thread_num() + 1
      !$omp do schedule(static, 64)
      do ip = 1, ng
         owner = owners(ip)
         point = points(:, ip)
         seed = atomic_w(ip)*adjoint_w(ip)
         point_response = 0.0_wp
         if (seed /= 0.0_wp) then
            point_math: block
               real(wp) :: positions(3, 3), tangent(3, 3), g(3, 3), h(3, 3), contribution(3, 3)
               real(wp) :: nu, nu_t, s, ds, d2s, peak, q, qt, alpha, alpha_t, log_p_t, first, second, beta, beta_t
               integer :: i, j, k

               associate (dist => dist(:, slot), probs => probs(:, slot), hessian_vector => workers(:, :, &
                  & slot), point_hessian_vector => point_response, log_t => log_t(:, slot), &
                  & point_direction => direction(:, owner), width => half_width)
                  point_hessian_vector = 0.0_wp
                  dist = 0.0_wp
                  positions(:, 1) = point
                  tangent(:, 1) = point_direction
                  probs = 0.0_wp
                  log_t = 0.0_wp
                  do i = 1, size(dist)
                     positions(:, 2) = xyz(:, i)
                     tangent(:, 2) = direction(:, i)
                     do j = 1, size(dist)
                        if (j == i) cycle
                        positions(:, 3) = xyz(:, j)
                        tangent(:, 3) = direction(:, j)
                        ! Coordinate order 1: power
                        block
                           real(wp) :: c0, c1, c2, c3, c4, c5, c6, c7, c8, c9

                           nu = (dot_product((positions(:, 1) - positions(:, 2)) + (positions(:, 1) - positions(:, 3)), &
                              & positions(:, 3) - positions(:, 2)) + pair_a(j, i))/width
                           c0 = (1.0_wp/width)
                           c1 = 2.0_wp*positions(1, 2)
                           c2 = -2.0_wp*positions(1, 3)
                           c3 = 2.0_wp*positions(2, 2)
                           c4 = -2.0_wp*positions(2, 3)
                           c5 = 2.0_wp*positions(3, 2)
                           c6 = -2.0_wp*positions(3, 3)
                           c7 = 2.0_wp*positions(1, 1)
                           c8 = 2.0_wp*positions(2, 1)
                           c9 = 2.0_wp*positions(3, 1)
                           g(1, 1) = c0*(-c1 - c2)
                           g(2, 1) = c0*(-c3 - c4)
                           g(3, 1) = c0*(-c5 - c6)
                           g(1, 2) = c0*(c1 - c7)
                           g(2, 2) = c0*(c3 - c8)
                           g(3, 2) = c0*(c5 - c9)
                           g(1, 3) = c0*(c2 + c7)
                           g(2, 3) = c0*(c4 + c8)
                           g(3, 3) = c0*(c6 + c9)
                        end block
                        block
                           real(wp) :: u, d, e, c0

                           s = 0.0_wp
                           ds = 0.0_wp
                           if (abs(nu) >= 1.0_wp) then
                              if (nu < 0.0_wp) s = 1.0_wp
                           else
                              u = abs(nu)
                              d = (1.0_wp - u)*(1.0_wp + u)
                              e = exp(-2.0_wp*u/d)
                              c0 = 1.0_wp + e
                              s = e*(1.0_wp/c0)
                              ds = e*(1.0_wp/c0**2)*(1.0_wp/d**2)*(-2.0_wp - 2.0_wp*u**2)
                              if (nu < 0.0_wp) then
                                 s = 1.0_wp - s
                              end if
                           end if
                        end block
                        if (s <= 0.0_wp) then
                           probs(i) = -huge(1.0_wp)
                           log_t(i) = 0.0_wp
                           exit
                        end if
                        probs(i) = probs(i) + log(s)
                        log_t(i) = log_t(i) + (ds/s)*sum(g*tangent)
                     end do
                  end do
                  if (probs(owner) == -huge(1.0_wp)) exit point_math
                  peak = maxval(probs)
                  probs = exp(probs - peak)
                  probs = probs/sum(probs)
                  q = seed*probs(owner)
                  qt = q*sum(probs*(log_t(owner) - log_t))
                  do i = 1, size(dist)
                     log_p_t = sum(probs*(log_t(i) - log_t))
                     alpha = -q*probs(i)
                     alpha_t = -qt*probs(i) - q*probs(i)*log_p_t
                     if (i == owner) then
                        beta = 0.0_wp
                        beta_t = 0.0_wp
                        do k = 1, size(dist)
                           if (k == owner) cycle
                           beta = beta + probs(k)
                           beta_t = beta_t + probs(k)*sum(probs*(log_t(k) - log_t))
                        end do
                        alpha = q*beta
                        alpha_t = qt*beta + q*beta_t
                     end if
                     if (alpha == 0.0_wp .and. alpha_t == 0.0_wp) cycle
                     positions(:, 2) = xyz(:, i)
                     tangent(:, 2) = direction(:, i)
                     do j = 1, size(dist)
                        if (j == i) cycle
                        positions(:, 3) = xyz(:, j)
                        tangent(:, 3) = direction(:, j)
                        ! Coordinate order 2: power
                        block
                           real(wp) :: c0, c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15, c16, c17, c18, &
                              & c19

                           nu = (dot_product((positions(:, 1) - positions(:, 2)) + (positions(:, 1) - positions(:, 3)), &
                              & positions(:, 3) - positions(:, 2)) + pair_a(j, i))/width
                           c0 = (1.0_wp/width)
                           c1 = 2.0_wp*positions(1, 2)
                           c2 = -2.0_wp*positions(1, 3)
                           c3 = 2.0_wp*positions(2, 2)
                           c4 = -2.0_wp*positions(2, 3)
                           c5 = 2.0_wp*positions(3, 2)
                           c6 = -2.0_wp*positions(3, 3)
                           c7 = 2.0_wp*positions(1, 1)
                           c8 = 2.0_wp*positions(2, 1)
                           c9 = 2.0_wp*positions(3, 1)
                           c10 = 2.0_wp*c0
                           c11 = c10*tangent(1, 2)
                           c12 = -c10*tangent(1, 3)
                           c13 = c10*tangent(2, 2)
                           c14 = -c10*tangent(2, 3)
                           c15 = c10*tangent(3, 2)
                           c16 = -c10*tangent(3, 3)
                           c17 = c10*tangent(1, 1)
                           c18 = c10*tangent(2, 1)
                           c19 = c10*tangent(3, 1)
                           g(1, 1) = c0*(-c1 - c2)
                           g(2, 1) = c0*(-c3 - c4)
                           g(3, 1) = c0*(-c5 - c6)
                           g(1, 2) = c0*(c1 - c7)
                           g(2, 2) = c0*(c3 - c8)
                           g(3, 2) = c0*(c5 - c9)
                           g(1, 3) = c0*(c2 + c7)
                           g(2, 3) = c0*(c4 + c8)
                           g(3, 3) = c0*(c6 + c9)
                           h(1, 1) = -c11 - c12
                           h(2, 1) = -c13 - c14
                           h(3, 1) = -c15 - c16
                           h(1, 2) = c11 - c17
                           h(2, 2) = c13 - c18
                           h(3, 2) = c15 - c19
                           h(1, 3) = c12 + c17
                           h(2, 3) = c14 + c18
                           h(3, 3) = c16 + c19
                        end block
                        block
                           real(wp) :: u, d, e, c0, c1, c2, c3, c4

                           s = 0.0_wp
                           ds = 0.0_wp
                           d2s = 0.0_wp
                           if (abs(nu) >= 1.0_wp) then
                              if (nu < 0.0_wp) s = 1.0_wp
                           else
                              u = abs(nu)
                              d = (1.0_wp - u)*(1.0_wp + u)
                              e = exp(-2.0_wp*u/d)
                              c0 = 1.0_wp + e
                              c1 = (1.0_wp/c0)
                              c2 = u**2
                              c3 = -2.0_wp - 2.0_wp*c2
                              c4 = e*(1.0_wp/c0**2)
                              s = c1*e
                              ds = c3*c4*(1.0_wp/d**2)
                              d2s = c4*(-4.0_wp*u*(1.0_wp/d**3)*(3.0_wp + c2) + c1*c3**2*(1.0_wp/d**4)*(1.0_wp - e))
                              if (nu < 0.0_wp) then
                                 s = 1.0_wp - s
                                 d2s = -d2s
                              end if
                           end if
                        end block
                        if (s <= 0.0_wp) cycle
                        first = ds/s
                        second = d2s/s - first*first
                        nu_t = sum(g*tangent)
                        contribution = (alpha_t*first + alpha*second*nu_t)*g + alpha*first*h
                        point_hessian_vector = point_hessian_vector + contribution(:, 1)
                        hessian_vector(:, i) = hessian_vector(:, i) + contribution(:, 2)
                        hessian_vector(:, j) = hessian_vector(:, j) + contribution(:, 3)
                     end do
                  end do
               end associate
            end block point_math
         end if
         workers(:, owner, slot) = workers(:, owner, slot) + point_response
      end do
      !$omp end do
      !$omp end parallel
      local = 0.0_wp
      do slot = 1, nt
         local = local + workers(:, :, slot)
      end do
      if (.not. all(ieee_is_finite(local))) then
         call fatal_error(error, "pvoronoi grid: non-finite hessian_vector contraction")
         return
      end if
      hessian_vector = hessian_vector + local
   end subroutine pvoronoi_grid_hessian_vector

   !> Assemble dense nuclear curvature with one geometry, scratch and worker team
   !>
   !> Unchecked shapes, finite inputs, valid owners and switch settings required
   !> Nuclear accumulators committed only after a finite contraction
   !>
   !> @param[in] self Configured partition scheme
   !> @param[in] points Sample positions (3, ng), bohr
   !> @param[in] xyz Nuclear positions (3, nat), bohr
   !> @param[in] numbers Atomic numbers (nat)
   !> @param[in] owners Point owners (ng), in [1, nat]
   !> @param[in] atomic_w Fixed atomic quadrature weights (ng), bohr**3
   !> @param[in] adjoint_w Integration-weight adjoints (ng)
   !> @param[in,out] hessian Nuclear Hessian accumulator (3, nat, 3, nat)
   !> @param[out] error Invalid geometry, allocation or non-finite contraction
   !> @param[in] nthreads Optional worker count; enclosing teams use one worker
   subroutine pvoronoi_grid_hessian(self, points, xyz, numbers, owners, atomic_w, adjoint_w, &
      & hessian, error, nthreads)
      !> Configured partition scheme
      class(pvoronoi_partition_type), intent(in) :: self
      !> Sample positions (3, ng), bohr
      real(wp), intent(in) :: points(:, :)
      !> Nuclear positions (3, nat), bohr
      real(wp), intent(in) :: xyz(:, :)
      !> Atomic numbers (nat)
      integer, intent(in) :: numbers(:)
      !> Point owners (ng), in [1, nat]
      integer, intent(in) :: owners(:)
      !> Fixed atomic quadrature weights (ng), bohr**3
      real(wp), intent(in) :: atomic_w(:)
      !> Integration-weight adjoints (ng)
      real(wp), intent(in) :: adjoint_w(:)
      !> Nuclear Hessian accumulator (3, nat, 3, nat)
      real(wp), intent(inout) :: hessian(:, :, :, :)
      !> Invalid geometry, allocation or non-finite contraction
      type(error_type), intent(out), allocatable :: error
      !> Optional worker count; enclosing teams use one worker
      integer, intent(in), optional :: nthreads

      real(wp), allocatable :: pair_a(:, :), dist(:, :), probs(:, :), log_t(:, :), workers(:, :, :), &
         & local_h(:, :, :, :), basis(:, :, :)
      real(wp) :: point(3), seed, point_response(3), half_width
      integer :: nat, ng, nt, slot, ip, owner, stat, atom, component, worker

      nat = size(numbers)
      ng = size(owners)
      if (ng == 0) return
      if (nat == 1 .or. all(atomic_w*adjoint_w == 0.0_wp)) return
      half_width = self%width
      nt = 1
!$    if (.not. omp_in_parallel()) then
!$       nt = omp_get_max_threads()
!$       if (present(nthreads)) then
!$          if (nthreads > 0) nt = nthreads
!$       end if
!$       nt = min(nt, ng)
!$    end if
      allocate (pair_a(nat, nat), stat=stat)
      if (stat == 0) allocate (dist(nat, nt), stat=stat)
      if (stat == 0) allocate (probs(nat, nt), stat=stat)
      if (stat == 0) allocate (log_t(nat, nt), stat=stat)
      if (stat == 0) allocate (workers(3, nat, nt), stat=stat)
      if (stat == 0) allocate (local_h(3, nat, 3, nat), stat=stat)
      if (stat == 0) allocate (basis(3, nat, nt), stat=stat)
      if (stat /= 0) then
         call fatal_error(error, "pvoronoi grid: cannot allocate hessian scratch")
         return
      end if
      block
         real(wp) :: radius(size(numbers))
         integer :: ia, ja

         radius = covalent_rad(numbers)
         if (allocated(self%radii)) then
            if (size(self%radii) /= size(numbers)) then
               call fatal_error(error, "pvoronoi partition: radii needs one entry per atom")
               return
            end if
            radius = self%radii
         end if
         pair_a = 0.0_wp
         do ia = 1, size(numbers)
            do ja = 1, ia - 1
               pair_a(ja, ia) = (radius(ja) - radius(ia))*(radius(ja) + radius(ia))
               pair_a(ia, ja) = -pair_a(ja, ia)
            end do
         end do
      end block
      workers = 0.0_wp
      !$omp parallel num_threads(nt) default(none) &
      !$omp shared(points, xyz, owners, atomic_w, pair_a, dist, probs, nat, ng, half_width, adjoint_w, &
      !$omp    & workers, log_t, local_h, basis, nt) private(slot, ip, owner, point, seed, point_response, &
      !$omp    & atom, component, worker)
      slot = 1
!$    slot = omp_get_thread_num() + 1
      do atom = 1, nat
         do component = 1, 3
            basis(:, :, slot) = 0.0_wp
            basis(component, atom, slot) = 1.0_wp
            workers(:, :, slot) = 0.0_wp
            !$omp do schedule(static, 64)
            do ip = 1, ng
               owner = owners(ip)
               point = points(:, ip)
               seed = atomic_w(ip)*adjoint_w(ip)
               point_response = 0.0_wp
               if (seed /= 0.0_wp) then
                  point_math: block
                     real(wp) :: positions(3, 3), tangent(3, 3), g(3, 3), h(3, 3), contribution(3, 3)
                     real(wp) :: nu, nu_t, s, ds, d2s, peak, q, qt, alpha, alpha_t, log_p_t, first, second, beta, beta_t
                     integer :: i, j, k

                     associate (dist => dist(:, slot), probs => probs(:, slot), hessian_vector => workers(:, :, &
                        & slot), point_hessian_vector => point_response, log_t => log_t(:, slot), direction => &
                        & basis(:, :, slot), point_direction => basis(:, owner, slot), width => half_width)
                        point_hessian_vector = 0.0_wp
                        dist = 0.0_wp
                        positions(:, 1) = point
                        tangent(:, 1) = point_direction
                        probs = 0.0_wp
                        log_t = 0.0_wp
                        do i = 1, size(dist)
                           positions(:, 2) = xyz(:, i)
                           tangent(:, 2) = direction(:, i)
                           do j = 1, size(dist)
                              if (j == i) cycle
                              positions(:, 3) = xyz(:, j)
                              tangent(:, 3) = direction(:, j)
                              ! Coordinate order 1: power
                              block
                                 real(wp) :: c0, c1, c2, c3, c4, c5, c6, c7, c8, c9

                                 nu = (dot_product((positions(:, 1) - positions(:, 2)) + (positions(:, 1) - positions(:, 3)), &
                                    & positions(:, 3) - positions(:, 2)) + pair_a(j, i))/width
                                 c0 = (1.0_wp/width)
                                 c1 = 2.0_wp*positions(1, 2)
                                 c2 = -2.0_wp*positions(1, 3)
                                 c3 = 2.0_wp*positions(2, 2)
                                 c4 = -2.0_wp*positions(2, 3)
                                 c5 = 2.0_wp*positions(3, 2)
                                 c6 = -2.0_wp*positions(3, 3)
                                 c7 = 2.0_wp*positions(1, 1)
                                 c8 = 2.0_wp*positions(2, 1)
                                 c9 = 2.0_wp*positions(3, 1)
                                 g(1, 1) = c0*(-c1 - c2)
                                 g(2, 1) = c0*(-c3 - c4)
                                 g(3, 1) = c0*(-c5 - c6)
                                 g(1, 2) = c0*(c1 - c7)
                                 g(2, 2) = c0*(c3 - c8)
                                 g(3, 2) = c0*(c5 - c9)
                                 g(1, 3) = c0*(c2 + c7)
                                 g(2, 3) = c0*(c4 + c8)
                                 g(3, 3) = c0*(c6 + c9)
                              end block
                              block
                                 real(wp) :: u, d, e, c0

                                 s = 0.0_wp
                                 ds = 0.0_wp
                                 if (abs(nu) >= 1.0_wp) then
                                    if (nu < 0.0_wp) s = 1.0_wp
                                 else
                                    u = abs(nu)
                                    d = (1.0_wp - u)*(1.0_wp + u)
                                    e = exp(-2.0_wp*u/d)
                                    c0 = 1.0_wp + e
                                    s = e*(1.0_wp/c0)
                                    ds = e*(1.0_wp/c0**2)*(1.0_wp/d**2)*(-2.0_wp - 2.0_wp*u**2)
                                    if (nu < 0.0_wp) then
                                       s = 1.0_wp - s
                                    end if
                                 end if
                              end block
                              if (s <= 0.0_wp) then
                                 probs(i) = -huge(1.0_wp)
                                 log_t(i) = 0.0_wp
                                 exit
                              end if
                              probs(i) = probs(i) + log(s)
                              log_t(i) = log_t(i) + (ds/s)*sum(g*tangent)
                           end do
                        end do
                        if (probs(owner) == -huge(1.0_wp)) exit point_math
                        peak = maxval(probs)
                        probs = exp(probs - peak)
                        probs = probs/sum(probs)
                        q = seed*probs(owner)
                        qt = q*sum(probs*(log_t(owner) - log_t))
                        do i = 1, size(dist)
                           log_p_t = sum(probs*(log_t(i) - log_t))
                           alpha = -q*probs(i)
                           alpha_t = -qt*probs(i) - q*probs(i)*log_p_t
                           if (i == owner) then
                              beta = 0.0_wp
                              beta_t = 0.0_wp
                              do k = 1, size(dist)
                                 if (k == owner) cycle
                                 beta = beta + probs(k)
                                 beta_t = beta_t + probs(k)*sum(probs*(log_t(k) - log_t))
                              end do
                              alpha = q*beta
                              alpha_t = qt*beta + q*beta_t
                           end if
                           if (alpha == 0.0_wp .and. alpha_t == 0.0_wp) cycle
                           positions(:, 2) = xyz(:, i)
                           tangent(:, 2) = direction(:, i)
                           do j = 1, size(dist)
                              if (j == i) cycle
                              positions(:, 3) = xyz(:, j)
                              tangent(:, 3) = direction(:, j)
                              ! Coordinate order 2: power
                              block
                                 real(wp) :: c0, c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15, c16, c17, c18, &
                                    & c19

                                 nu = (dot_product((positions(:, 1) - positions(:, 2)) + (positions(:, 1) - positions(:, 3)), &
                                    & positions(:, 3) - positions(:, 2)) + pair_a(j, i))/width
                                 c0 = (1.0_wp/width)
                                 c1 = 2.0_wp*positions(1, 2)
                                 c2 = -2.0_wp*positions(1, 3)
                                 c3 = 2.0_wp*positions(2, 2)
                                 c4 = -2.0_wp*positions(2, 3)
                                 c5 = 2.0_wp*positions(3, 2)
                                 c6 = -2.0_wp*positions(3, 3)
                                 c7 = 2.0_wp*positions(1, 1)
                                 c8 = 2.0_wp*positions(2, 1)
                                 c9 = 2.0_wp*positions(3, 1)
                                 c10 = 2.0_wp*c0
                                 c11 = c10*tangent(1, 2)
                                 c12 = -c10*tangent(1, 3)
                                 c13 = c10*tangent(2, 2)
                                 c14 = -c10*tangent(2, 3)
                                 c15 = c10*tangent(3, 2)
                                 c16 = -c10*tangent(3, 3)
                                 c17 = c10*tangent(1, 1)
                                 c18 = c10*tangent(2, 1)
                                 c19 = c10*tangent(3, 1)
                                 g(1, 1) = c0*(-c1 - c2)
                                 g(2, 1) = c0*(-c3 - c4)
                                 g(3, 1) = c0*(-c5 - c6)
                                 g(1, 2) = c0*(c1 - c7)
                                 g(2, 2) = c0*(c3 - c8)
                                 g(3, 2) = c0*(c5 - c9)
                                 g(1, 3) = c0*(c2 + c7)
                                 g(2, 3) = c0*(c4 + c8)
                                 g(3, 3) = c0*(c6 + c9)
                                 h(1, 1) = -c11 - c12
                                 h(2, 1) = -c13 - c14
                                 h(3, 1) = -c15 - c16
                                 h(1, 2) = c11 - c17
                                 h(2, 2) = c13 - c18
                                 h(3, 2) = c15 - c19
                                 h(1, 3) = c12 + c17
                                 h(2, 3) = c14 + c18
                                 h(3, 3) = c16 + c19
                              end block
                              block
                                 real(wp) :: u, d, e, c0, c1, c2, c3, c4

                                 s = 0.0_wp
                                 ds = 0.0_wp
                                 d2s = 0.0_wp
                                 if (abs(nu) >= 1.0_wp) then
                                    if (nu < 0.0_wp) s = 1.0_wp
                                 else
                                    u = abs(nu)
                                    d = (1.0_wp - u)*(1.0_wp + u)
                                    e = exp(-2.0_wp*u/d)
                                    c0 = 1.0_wp + e
                                    c1 = (1.0_wp/c0)
                                    c2 = u**2
                                    c3 = -2.0_wp - 2.0_wp*c2
                                    c4 = e*(1.0_wp/c0**2)
                                    s = c1*e
                                    ds = c3*c4*(1.0_wp/d**2)
                                    d2s = c4*(-4.0_wp*u*(1.0_wp/d**3)*(3.0_wp + c2) + c1*c3**2*(1.0_wp/d**4)*(1.0_wp - e))
                                    if (nu < 0.0_wp) then
                                       s = 1.0_wp - s
                                       d2s = -d2s
                                    end if
                                 end if
                              end block
                              if (s <= 0.0_wp) cycle
                              first = ds/s
                              second = d2s/s - first*first
                              nu_t = sum(g*tangent)
                              contribution = (alpha_t*first + alpha*second*nu_t)*g + alpha*first*h
                              point_hessian_vector = point_hessian_vector + contribution(:, 1)
                              hessian_vector(:, i) = hessian_vector(:, i) + contribution(:, 2)
                              hessian_vector(:, j) = hessian_vector(:, j) + contribution(:, 3)
                           end do
                        end do
                     end associate
                  end block point_math
               end if
               workers(:, owner, slot) = workers(:, owner, slot) + point_response
            end do
            !$omp end do
            !$omp single
            local_h(:, :, component, atom) = 0.0_wp
            do worker = 1, nt
               local_h(:, :, component, atom) = local_h(:, :, component, atom) + workers(:, :, worker)
            end do
            !$omp end single
         end do
      end do
      !$omp end parallel
      if (.not. all(ieee_is_finite(local_h))) then
         call fatal_error(error, "pvoronoi grid: non-finite hessian contraction")
         return
      end if
      hessian = hessian + local_h
   end subroutine pvoronoi_grid_hessian

   ! Self-contained paths with fused coordinate and switch algebra

   !> Owner weights from pair cells, normalized in log space to avoid product underflow
   !>
   !> - Unchecked shapes: points (3,npts), xyz (3,nat), numbers (nat), w (npts)
   !> - Valid owner, atomic numbers and switch parameters required
   !> - Power width selects (q_i-q_j)/width, q_i=|r-R_i|**2-radius_i**2
   !> - Power coordinates have no distance norms or geometry-dependent minima
   !> - Point threading suppressed inside an enclosing OpenMP team
   !>
   !> @param[in] self Configured partition scheme
   !> @param[in]  owner       Owner index in [1,nat]
   !> @param[in]  points      Sample points in bohr
   !> @param[in]  xyz         Atomic positions in bohr
   !> @param[in]  numbers     Atomic numbers
   !> @param[out] w           Normalized owner weights
   !> @param[in]  nthreads    Optional thread count; absent takes omp_get_max_threads
   subroutine pvoronoi_owner_weights(self, owner, points, xyz, numbers, w, nthreads)
      !> Configured partition scheme
      class(pvoronoi_partition_type), intent(in) :: self
      !> Owner index
      integer, intent(in) :: owner
      !> Sample points
      real(wp), intent(in) :: points(:, :)
      !> Atomic positions
      real(wp), intent(in) :: xyz(:, :)
      !> Atomic numbers
      integer, intent(in) :: numbers(:)
      !> Owner weights
      real(wp), intent(out) :: w(:)
      !> Thread count
      integer, intent(in), optional :: nthreads

      real(wp), allocatable :: pair_a(:, :), dist(:), logs(:)
      real(wp) :: width, peak, point(3)
      integer :: nat, npts, i, ip, nt

      nat = size(xyz, 2)
      npts = size(points, 2)
      if (npts == 0) return
      if (nat == 1) then
         w = 1.0_wp
         return
      end if
      width = self%width
      allocate (pair_a(nat, nat))
      block
         real(wp) :: radius(size(numbers))
         integer :: ia, ja

         radius = covalent_rad(numbers)
         if (allocated(self%radii)) then
            if (size(self%radii) /= size(numbers)) then
               error stop "pvoronoi partition: radii needs one entry per atom"
            end if
            radius = self%radii
         end if
         pair_a = 0.0_wp
         do ia = 1, size(numbers)
            do ja = 1, ia - 1
               pair_a(ja, ia) = (radius(ja) - radius(ia))*(radius(ja) + radius(ia))
               pair_a(ia, ja) = -pair_a(ja, ia)
            end do
         end do
      end block

      nt = 1
!$    if (.not. omp_in_parallel()) then
!$       nt = omp_get_max_threads()
!$       if (present(nthreads)) then
!$          if (nthreads > 0) nt = nthreads
!$       end if
!$       nt = min(nt, npts)
!$    end if
      !$omp parallel num_threads(nt) default(none) &
      !$omp shared(owner, points, xyz, pair_a, width, w, nat, npts) &
      !$omp private(ip, i, dist, logs, peak, point)
      allocate (dist(nat), logs(nat))
      !$omp do schedule(dynamic, 64)
      do ip = 1, npts
         point = points(:, ip)
         dist = 0.0_wp
         logs(owner) = pvoronoi_cell_log(owner, point, xyz, dist, pair_a, width)
         if (logs(owner) == -huge(1.0_wp)) then
            w(ip) = 0.0_wp
            cycle
         end if
         do i = 1, nat
            if (i /= owner) then
               logs(i) = pvoronoi_cell_log(i, point, xyz, dist, pair_a, width)
            end if
         end do
         peak = maxval(logs)
         w(ip) = exp(logs(owner) - peak)/sum(exp(logs - peak))
      end do
      !$omp end do
      deallocate (dist, logs)
      !$omp end parallel

   end subroutine pvoronoi_owner_weights
   !> Contract partition adjoints into point and fixed-point nuclear gradients
   !>
   !> - Log-space normalization shared with the forward pass
   !> - Caller supplies point motion; shapes and atomic numbers unchecked
   !>
   !> @param[in] self Configured partition scheme
   !> @param[in] owner Owner index in [1, nat]
   !> @param[in] points Sample positions (3, npts), bohr
   !> @param[in] xyz Nuclear positions (3, nat), bohr
   !> @param[in] numbers Atomic numbers (nat)
   !> @param[in] seed Owner-partition energy adjoints (npts)
   !> @param[in,out] gradient Nuclear-gradient accumulator (3, nat)
   !> @param[out] point_gradient Point-position adjoints (3, npts)
   !> @param[out] error Allocation failure
   !> @param[in] nthreads Optional worker count
   subroutine pvoronoi_owner_gradient(self, owner, points, xyz, numbers, seed, gradient, &
      & point_gradient, error, nthreads)
      !> Configured partition scheme
      class(pvoronoi_partition_type), intent(in) :: self
      !> Owner index
      integer, intent(in) :: owner
      !> Sample positions
      real(wp), intent(in) :: points(:, :)
      !> Nuclear positions
      real(wp), intent(in) :: xyz(:, :)
      !> Atomic numbers
      integer, intent(in) :: numbers(:)
      !> Owner-partition adjoints
      real(wp), intent(in) :: seed(:)
      !> Nuclear-gradient accumulator
      real(wp), intent(inout) :: gradient(:, :)
      !> Point-position adjoints
      real(wp), intent(out) :: point_gradient(:, :)
      !> Allocation failure
      type(error_type), allocatable, intent(out) :: error
      !> Worker count
      integer, intent(in), optional :: nthreads

      real(wp), allocatable :: pair_a(:, :), dist(:, :), logs(:, :)
      real(wp), allocatable :: grad_threads(:, :, :)
      real(wp) :: width
      integer :: nat, npts, nt, thread_slot, ip, stat

      nat = size(numbers)
      npts = size(seed)
      point_gradient = 0.0_wp
      if (nat == 1 .or. npts == 0 .or. all(seed == 0.0_wp)) return
      nt = 1
!$    if (.not. omp_in_parallel()) then
!$       nt = omp_get_max_threads()
!$       if (present(nthreads)) then
!$          if (nthreads > 0) nt = nthreads
!$       end if
!$       nt = min(nt, npts)
!$    end if
      width = self%width
      allocate (pair_a(nat, nat), stat=stat)
      if (stat == 0) allocate (dist(nat, nt), stat=stat)
      if (stat == 0) allocate (logs(nat, nt), stat=stat)
      if (stat == 0) allocate (grad_threads(3, nat, nt), stat=stat)
      if (stat /= 0) then
         call fatal_error(error, "partition gradient: cannot allocate reverse scratch")
         return
      end if
      block
         real(wp) :: radius(size(numbers))
         integer :: ia, ja

         radius = covalent_rad(numbers)
         if (allocated(self%radii)) then
            if (size(self%radii) /= size(numbers)) then
               call fatal_error(error, "pvoronoi partition: radii needs one entry per atom")
               return
            end if
            radius = self%radii
         end if
         pair_a = 0.0_wp
         do ia = 1, size(numbers)
            do ja = 1, ia - 1
               pair_a(ja, ia) = (radius(ja) - radius(ia))*(radius(ja) + radius(ia))
               pair_a(ia, ja) = -pair_a(ja, ia)
            end do
         end do
      end block
      grad_threads = 0.0_wp
      !$omp parallel num_threads(nt) default(none) &
      !$omp shared(owner, points, xyz, seed, pair_a, dist, logs, &
      !$omp width, grad_threads, point_gradient, npts) private(thread_slot, ip)
      thread_slot = 1
!$    thread_slot = omp_get_thread_num() + 1
      !$omp do schedule(static, 64)
      do ip = 1, npts
         if (seed(ip) == 0.0_wp) cycle
         call pvoronoi_point_gradient(owner, points(:, ip), xyz, seed(ip), pair_a, &
            & width, dist(:, thread_slot), logs(:, thread_slot), &
            & grad_threads(:, :, thread_slot), point_gradient(:, ip))
      end do
      !$omp end do
      !$omp end parallel
      do thread_slot = 1, nt
         gradient = gradient + grad_threads(:, :, thread_slot)
      end do
   end subroutine pvoronoi_owner_gradient

   !> Directional derivative of the partition reverse contraction
   !>
   !> @param[in] self Configured partition scheme
   !> @param[in] owner Owner index in [1, nat]
   !> @param[in] points Sample positions (3, npts), bohr
   !> @param[in] xyz Nuclear positions (3, nat), bohr
   !> @param[in] numbers Atomic numbers (nat)
   !> @param[in] seed Fixed owner-partition adjoints (npts)
   !> @param[in] direction Nuclear displacement direction (3, nat)
   !> @param[in] point_direction Common point displacement direction (3)
   !> @param[in,out] hessian_vector Nuclear Hessian-vector accumulator (3, nat)
   !> @param[out] point_hessian_vector Point Hessian-vector contributions (3, npts)
   !> @param[out] error Allocation failure or coincident elliptic centers
   !> @param[in] nthreads Optional worker count
   subroutine pvoronoi_owner_hessian_vector(self, owner, points, xyz, numbers, seed, direction, &
      & point_direction, hessian_vector, point_hessian_vector, error, nthreads)
      !> Configured partition scheme
      class(pvoronoi_partition_type), intent(in) :: self
      !> Owner index
      integer, intent(in) :: owner
      !> Sample positions
      real(wp), intent(in) :: points(:, :)
      !> Nuclear positions
      real(wp), intent(in) :: xyz(:, :)
      !> Atomic numbers
      integer, intent(in) :: numbers(:)
      !> Fixed partition adjoints
      real(wp), intent(in) :: seed(:)
      !> Nuclear displacement direction
      real(wp), intent(in) :: direction(:, :)
      !> Common point displacement direction
      real(wp), intent(in) :: point_direction(:)
      !> Nuclear Hessian-vector accumulator
      real(wp), intent(inout) :: hessian_vector(:, :)
      !> Point Hessian-vector contributions
      real(wp), intent(out) :: point_hessian_vector(:, :)
      !> Invalid geometry or allocation failure
      type(error_type), allocatable, intent(out) :: error
      !> Worker count
      integer, intent(in), optional :: nthreads

      real(wp), allocatable :: pair_a(:, :), dist(:, :), probs(:, :), log_t(:, :), workers(:, :, :)
      real(wp) :: width
      integer :: nat, npts, nt, slot, ip, stat

      nat = size(numbers)
      npts = size(seed)
      point_hessian_vector = 0.0_wp
      if (nat == 1 .or. npts == 0 .or. all(seed == 0.0_wp)) return
      nt = 1
!$    if (.not. omp_in_parallel()) then
!$       nt = omp_get_max_threads()
!$       if (present(nthreads)) then
!$          if (nthreads > 0) nt = nthreads
!$       end if
!$       nt = min(nt, npts)
!$    end if
      width = self%width
      allocate (pair_a(nat, nat), stat=stat)
      if (stat == 0) allocate (dist(nat, nt), stat=stat)
      if (stat == 0) allocate (probs(nat, nt), stat=stat)
      if (stat == 0) allocate (log_t(nat, nt), stat=stat)
      if (stat == 0) allocate (workers(3, nat, nt), stat=stat)
      if (stat /= 0) then
         call fatal_error(error, "partition Hessian: cannot allocate scratch")
         return
      end if
      block
         real(wp) :: radius(size(numbers))
         integer :: ia, ja

         radius = covalent_rad(numbers)
         if (allocated(self%radii)) then
            if (size(self%radii) /= size(numbers)) then
               call fatal_error(error, "pvoronoi partition: radii needs one entry per atom")
               return
            end if
            radius = self%radii
         end if
         pair_a = 0.0_wp
         do ia = 1, size(numbers)
            do ja = 1, ia - 1
               pair_a(ja, ia) = (radius(ja) - radius(ia))*(radius(ja) + radius(ia))
               pair_a(ia, ja) = -pair_a(ja, ia)
            end do
         end do
      end block
      workers = 0.0_wp
      !$omp parallel num_threads(nt) default(none) &
      !$omp shared(owner, points, xyz, seed, direction, point_direction, pair_a, &
      !$omp dist, probs, log_t, width, workers, point_hessian_vector, npts) private(slot, ip)
      slot = 1
!$    slot = omp_get_thread_num() + 1
      !$omp do schedule(static, 64)
      do ip = 1, npts
         if (seed(ip) == 0.0_wp) cycle
         call pvoronoi_point_hessian_vector(owner, points(:, ip), xyz, seed(ip), direction, point_direction, &
            & pair_a, width, dist(:, slot), probs(:, slot), log_t(:, slot), &
            & workers(:, :, slot), point_hessian_vector(:, ip))
      end do
      !$omp end do
      !$omp end parallel
      do slot = 1, nt
         hessian_vector = hessian_vector + workers(:, :, slot)
      end do
   end subroutine pvoronoi_owner_hessian_vector
   !> Forward-over-reverse normalized owner weight without per-point nuclear Jacobians
   !>
   !> @param[in] owner Owner index
   !> @param[in] point Sample position (3)
   !> @param[in] xyz Nuclear positions (3, nat)
   !> @param[in] seed Fixed partition adjoint
   !> @param[in] direction Nuclear tangent (3, nat)
   !> @param[in] point_direction Point tangent (3)
   !> @param[in] pair_a Fixed pair adjustments (nat, nat)
   !> @param[in] width Power half-width
   !> @param[out] dist Distance scratch (nat)
   !> @param[out] probs Normalized probability scratch (nat)
   !> @param[out] log_t Log-product tangent scratch (nat)
   !> @param[in,out] hessian_vector Explicit nuclear Hessian-vector accumulator (3, nat)
   !> @param[out] point_hessian_vector Point Hessian-vector contribution (3)
   pure subroutine pvoronoi_point_hessian_vector(owner, point, xyz, seed, direction, point_direction, &
         & pair_a, width, dist, probs, log_t, hessian_vector, point_hessian_vector)
      !> Owner index
      integer, intent(in) :: owner
      !> Sample position
      real(wp), intent(in) :: point(3)
      !> Nuclear positions
      real(wp), intent(in) :: xyz(:, :)
      !> Fixed partition adjoint
      real(wp), intent(in) :: seed
      !> Nuclear tangent
      real(wp), intent(in) :: direction(:, :)
      !> Point tangent
      real(wp), intent(in) :: point_direction(:)
      !> Fixed pair adjustments
      real(wp), intent(in) :: pair_a(:, :)
      !> Power half-width
      real(wp), intent(in) :: width
      !> Distance scratch
      real(wp), intent(out) :: dist(:)
      !> Normalized probabilities
      real(wp), intent(out) :: probs(:)
      !> Log-product tangents
      real(wp), intent(out) :: log_t(:)
      !> Explicit nuclear Hessian-vector accumulator
      real(wp), intent(inout) :: hessian_vector(:, :)
      !> Point Hessian-vector contribution
      real(wp), intent(out) :: point_hessian_vector(:)

      real(wp) :: positions(3, 3), tangent(3, 3), g(3, 3), h(3, 3), contribution(3, 3)
      real(wp) :: nu, nu_t, s, ds, d2s, peak, q, qt, alpha, alpha_t, log_p_t, first, second, beta, beta_t
      integer :: i, j, k

      point_hessian_vector = 0.0_wp
      dist = 0.0_wp
      positions(:, 1) = point
      tangent(:, 1) = point_direction
      probs = 0.0_wp
      log_t = 0.0_wp
      do i = 1, size(dist)
         positions(:, 2) = xyz(:, i)
         tangent(:, 2) = direction(:, i)
         do j = 1, size(dist)
            if (j == i) cycle
            positions(:, 3) = xyz(:, j)
            tangent(:, 3) = direction(:, j)
            ! Coordinate order 1: power
            block
               real(wp) :: c0, c1, c2, c3, c4, c5, c6, c7, c8, c9

               nu = (dot_product((positions(:, 1) - positions(:, 2)) + (positions(:, 1) - positions(:, 3)), &
                  & positions(:, 3) - positions(:, 2)) + pair_a(j, i))/width
               c0 = (1.0_wp/width)
               c1 = 2.0_wp*positions(1, 2)
               c2 = -2.0_wp*positions(1, 3)
               c3 = 2.0_wp*positions(2, 2)
               c4 = -2.0_wp*positions(2, 3)
               c5 = 2.0_wp*positions(3, 2)
               c6 = -2.0_wp*positions(3, 3)
               c7 = 2.0_wp*positions(1, 1)
               c8 = 2.0_wp*positions(2, 1)
               c9 = 2.0_wp*positions(3, 1)
               g(1, 1) = c0*(-c1 - c2)
               g(2, 1) = c0*(-c3 - c4)
               g(3, 1) = c0*(-c5 - c6)
               g(1, 2) = c0*(c1 - c7)
               g(2, 2) = c0*(c3 - c8)
               g(3, 2) = c0*(c5 - c9)
               g(1, 3) = c0*(c2 + c7)
               g(2, 3) = c0*(c4 + c8)
               g(3, 3) = c0*(c6 + c9)
            end block
            block
               real(wp) :: u, d, e, c0

               s = 0.0_wp
               ds = 0.0_wp
               if (abs(nu) >= 1.0_wp) then
                  if (nu < 0.0_wp) s = 1.0_wp
               else
                  u = abs(nu)
                  d = (1.0_wp - u)*(1.0_wp + u)
                  e = exp(-2.0_wp*u/d)
                  c0 = 1.0_wp + e
                  s = e*(1.0_wp/c0)
                  ds = e*(1.0_wp/c0**2)*(1.0_wp/d**2)*(-2.0_wp - 2.0_wp*u**2)
                  if (nu < 0.0_wp) then
                     s = 1.0_wp - s
                  end if
               end if
            end block
            if (s <= 0.0_wp) then
               probs(i) = -huge(1.0_wp)
               log_t(i) = 0.0_wp
               exit
            end if
            probs(i) = probs(i) + log(s)
            log_t(i) = log_t(i) + (ds/s)*sum(g*tangent)
         end do
      end do
      if (probs(owner) == -huge(1.0_wp)) return
      peak = maxval(probs)
      probs = exp(probs - peak)
      probs = probs/sum(probs)
      q = seed*probs(owner)
      qt = q*sum(probs*(log_t(owner) - log_t))
      do i = 1, size(dist)
         log_p_t = sum(probs*(log_t(i) - log_t))
         alpha = -q*probs(i)
         alpha_t = -qt*probs(i) - q*probs(i)*log_p_t
         if (i == owner) then
            beta = 0.0_wp
            beta_t = 0.0_wp
            do k = 1, size(dist)
               if (k == owner) cycle
               beta = beta + probs(k)
               beta_t = beta_t + probs(k)*sum(probs*(log_t(k) - log_t))
            end do
            alpha = q*beta
            alpha_t = qt*beta + q*beta_t
         end if
         if (alpha == 0.0_wp .and. alpha_t == 0.0_wp) cycle
         positions(:, 2) = xyz(:, i)
         tangent(:, 2) = direction(:, i)
         do j = 1, size(dist)
            if (j == i) cycle
            positions(:, 3) = xyz(:, j)
            tangent(:, 3) = direction(:, j)
            ! Coordinate order 2: power
            block
               real(wp) :: c0, c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15, c16, c17, c18, &
                  & c19

               nu = (dot_product((positions(:, 1) - positions(:, 2)) + (positions(:, 1) - positions(:, 3)), &
                  & positions(:, 3) - positions(:, 2)) + pair_a(j, i))/width
               c0 = (1.0_wp/width)
               c1 = 2.0_wp*positions(1, 2)
               c2 = -2.0_wp*positions(1, 3)
               c3 = 2.0_wp*positions(2, 2)
               c4 = -2.0_wp*positions(2, 3)
               c5 = 2.0_wp*positions(3, 2)
               c6 = -2.0_wp*positions(3, 3)
               c7 = 2.0_wp*positions(1, 1)
               c8 = 2.0_wp*positions(2, 1)
               c9 = 2.0_wp*positions(3, 1)
               c10 = 2.0_wp*c0
               c11 = c10*tangent(1, 2)
               c12 = -c10*tangent(1, 3)
               c13 = c10*tangent(2, 2)
               c14 = -c10*tangent(2, 3)
               c15 = c10*tangent(3, 2)
               c16 = -c10*tangent(3, 3)
               c17 = c10*tangent(1, 1)
               c18 = c10*tangent(2, 1)
               c19 = c10*tangent(3, 1)
               g(1, 1) = c0*(-c1 - c2)
               g(2, 1) = c0*(-c3 - c4)
               g(3, 1) = c0*(-c5 - c6)
               g(1, 2) = c0*(c1 - c7)
               g(2, 2) = c0*(c3 - c8)
               g(3, 2) = c0*(c5 - c9)
               g(1, 3) = c0*(c2 + c7)
               g(2, 3) = c0*(c4 + c8)
               g(3, 3) = c0*(c6 + c9)
               h(1, 1) = -c11 - c12
               h(2, 1) = -c13 - c14
               h(3, 1) = -c15 - c16
               h(1, 2) = c11 - c17
               h(2, 2) = c13 - c18
               h(3, 2) = c15 - c19
               h(1, 3) = c12 + c17
               h(2, 3) = c14 + c18
               h(3, 3) = c16 + c19
            end block
            block
               real(wp) :: u, d, e, c0, c1, c2, c3, c4

               s = 0.0_wp
               ds = 0.0_wp
               d2s = 0.0_wp
               if (abs(nu) >= 1.0_wp) then
                  if (nu < 0.0_wp) s = 1.0_wp
               else
                  u = abs(nu)
                  d = (1.0_wp - u)*(1.0_wp + u)
                  e = exp(-2.0_wp*u/d)
                  c0 = 1.0_wp + e
                  c1 = (1.0_wp/c0)
                  c2 = u**2
                  c3 = -2.0_wp - 2.0_wp*c2
                  c4 = e*(1.0_wp/c0**2)
                  s = c1*e
                  ds = c3*c4*(1.0_wp/d**2)
                  d2s = c4*(-4.0_wp*u*(1.0_wp/d**3)*(3.0_wp + c2) + c1*c3**2*(1.0_wp/d**4)*(1.0_wp - e))
                  if (nu < 0.0_wp) then
                     s = 1.0_wp - s
                     d2s = -d2s
                  end if
               end if
            end block
            if (s <= 0.0_wp) cycle
            first = ds/s
            second = d2s/s - first*first
            nu_t = sum(g*tangent)
            contribution = (alpha_t*first + alpha*second*nu_t)*g + alpha*first*h
            point_hessian_vector = point_hessian_vector + contribution(:, 1)
            hessian_vector(:, i) = hessian_vector(:, i) + contribution(:, 2)
            hessian_vector(:, j) = hessian_vector(:, j) + contribution(:, 3)
         end do
      end do
   end subroutine pvoronoi_point_hessian_vector

   !> Reverse one normalized owner weight without a nuclear Jacobian
   !>
   !> @param[in] owner Owner index
   !> @param[in] point Sample position (3), bohr
   !> @param[in] xyz Nuclear positions (3, nat), bohr
   !> @param[in] seed Owner-partition adjoint
   !> @param[in] pair_a Fixed pair size adjustments
   !> @param[in] width Power-coordinate half-width, bohr**2
   !> @param[out] dist Point-to-nucleus distance scratch (nat)
   !> @param[out] probs Normalized cell-product scratch (nat)
   !> @param[in,out] gradient Explicit nuclear-gradient accumulator (3, nat)
   !> @param[out] point_gradient Point-position adjoint (3)
   pure subroutine pvoronoi_point_gradient(owner, point, xyz, seed, pair_a, &
         & width, dist, probs, gradient, point_gradient)
      !> Owner index
      integer, intent(in) :: owner
      !> Sample position
      real(wp), intent(in) :: point(3)
      !> Nuclear positions
      real(wp), intent(in) :: xyz(:, :)
      !> Owner-partition adjoint
      real(wp), intent(in) :: seed
      !> Fixed pair adjustments
      real(wp), intent(in) :: pair_a(:, :)
      !> Power half-width
      real(wp), intent(in) :: width
      !> Distance scratch
      real(wp), intent(out) :: dist(:)
      !> Normalized cell products
      real(wp), intent(out) :: probs(:)
      !> Explicit nuclear-gradient accumulator
      real(wp), intent(inout) :: gradient(:, :)
      !> Point-position adjoint
      real(wp), intent(out) :: point_gradient(:)

      real(wp) :: peak, owner_seed, log_seed, nu, s, ds, factor
      integer :: i, j

      point_gradient = 0.0_wp
      dist = 0.0_wp
      do i = 1, size(dist)
         probs(i) = pvoronoi_cell_log(i, point, xyz, dist, pair_a, width)
      end do
      if (probs(owner) == -huge(1.0_wp)) return
      peak = maxval(probs)
      probs = exp(probs - peak)
      probs = probs/sum(probs)
      owner_seed = seed*probs(owner)
      do i = 1, size(dist)
         log_seed = -owner_seed*probs(i)
         if (i == owner) then
            ! Sum other probabilities to retain derivatives of tiny partition tails
            log_seed = owner_seed*(sum(probs(:i - 1)) + sum(probs(i + 1:)))
         end if
         if (log_seed == 0.0_wp) cycle
         do j = 1, size(dist)
            if (j == i) cycle
            nu = (dot_product((point - xyz(:, i)) + (point - xyz(:, j)), &
               & xyz(:, j) - xyz(:, i)) + pair_a(j, i))/width
            block
               real(wp) :: u, d, e, c0

               s = 0.0_wp
               ds = 0.0_wp
               if (abs(nu) >= 1.0_wp) then
                  if (nu < 0.0_wp) s = 1.0_wp
               else
                  u = abs(nu)
                  d = (1.0_wp - u)*(1.0_wp + u)
                  e = exp(-2.0_wp*u/d)
                  c0 = 1.0_wp + e
                  s = e*(1.0_wp/c0)
                  ds = e*(1.0_wp/c0**2)*(1.0_wp/d**2)*(-2.0_wp - 2.0_wp*u**2)
                  if (nu < 0.0_wp) then
                     s = 1.0_wp - s
                  end if
               end if
            end block
            if (s <= 0.0_wp .or. ds == 0.0_wp) cycle
            factor = (log_seed/s)*ds
            factor = 2.0_wp*factor/width
            point_gradient = point_gradient + factor*(xyz(:, j) - xyz(:, i))
            gradient(:, i) = gradient(:, i) - factor*(point - xyz(:, i))
            gradient(:, j) = gradient(:, j) + factor*(point - xyz(:, j))
         end do
      end do
   end subroutine pvoronoi_point_gradient

   !> Logarithm of one cell product
   !>
   !> @param[in] ia      Atom index
   !> @param[in] point   Sample point in bohr, shape (3)
   !> @param[in] xyz     Atomic positions in bohr, shape (3,nat)
   !> @param[in] dist    Point-to-atom distances in bohr, shape (nat)
   !> @param[in] pair_a  Pair size adjustments or power offsets, shape (nat,nat)
   !> @param[in] width   Power-coordinate half-width in bohr**2
   pure function pvoronoi_cell_log(ia, point, xyz, dist, pair_a, width) result(value)
      !> Atom index
      integer, intent(in) :: ia
      !> Sample point
      real(wp), intent(in) :: point(3)
      !> Atomic positions
      real(wp), intent(in) :: xyz(:, :)
      !> Point-to-atom distances
      real(wp), intent(in) :: dist(:)
      !> Pair size adjustments or power offsets
      real(wp), intent(in) :: pair_a(:, :)
      !> Power-coordinate half-width
      real(wp), intent(in) :: width
      !> Log cell product or -huge for zero
      real(wp) :: value

      integer :: ja
      real(wp) :: nu, s

      value = 0.0_wp
      do ja = 1, size(dist)
         if (ja == ia) cycle
         ! Difference of powers without cancellation between squared distances
         nu = (dot_product((point - xyz(:, ia)) + (point - xyz(:, ja)), &
            & xyz(:, ja) - xyz(:, ia)) + pair_a(ja, ia))/width
         block
            real(wp) :: u, d, e

            s = 0.0_wp
            if (abs(nu) >= 1.0_wp) then
               if (nu < 0.0_wp) s = 1.0_wp
            else
               u = abs(nu)
               d = (1.0_wp - u)*(1.0_wp + u)
               e = exp(-2.0_wp*u/d)
               s = e*(1.0_wp/(1.0_wp + e))
               if (nu < 0.0_wp) then
                  s = 1.0_wp - s
               end if
            end if
         end block
         if (s <= 0.0_wp) then
            value = -huge(1.0_wp)
            return
         end if
         value = value + log(s)
      end do
   end function pvoronoi_cell_log

end module moist_math_grid_3d_kernel_pvoronoi
