!> Stratmann-Scuseria-Frisch partition
!>
!> AUTO-GENERATED by generate_partitions.py-- DO NOT EDIT BY HAND.
module moist_math_grid_3d_kernel_ssf
   use mctc_env, only: wp, error_type, fatal_error
   use moist_data_atomicrad, only: covalent_rad
   use, intrinsic :: ieee_arithmetic, only: ieee_is_finite
   use moist_math_grid_3d_kernel_base, only: moist_math_grid_3d_partition_type
!$ use omp_lib, only: omp_get_max_threads, omp_get_thread_num, omp_in_parallel
   implicit none(type, external)
   private

   public :: ssf_partition_type, default_ssf_a

   !> Default switch setting
   real(wp), parameter :: default_ssf_a = 0.64_wp

   !> Stratmann-Scuseria-Frisch partition with its switch settings
   type, extends(moist_math_grid_3d_partition_type) :: ssf_partition_type
      !> SSF half-width in (0, 1]
      real(wp) :: a = default_ssf_a
   contains
      !> Pair-switch weight
      procedure :: eval => ssf_eval
      !> Fused pair-switch weight and first derivative
      procedure :: eval_with_derivative => ssf_eval_with_derivative
      !> Fused pair-switch weight and first two derivatives
      procedure :: eval_with_second_derivative => ssf_eval_with_second_derivative
      !> Normalized weights of one owner at fixed points
      procedure :: owner_weights => ssf_owner_weights
      !> Contract one owner's partition adjoints at fixed points
      procedure :: owner_gradient => ssf_owner_gradient
      !> Directional derivative of one owner's partition reverse contraction
      procedure :: owner_hessian_vector => ssf_owner_hessian_vector
      !> Evaluate all owners and quadrature weights in one prepared pass
      procedure :: grid_weights => ssf_grid_weights
      !> Contract all point and weight adjoints with owner motion
      procedure :: grid_gradient => ssf_grid_gradient
      !> Contract point, weight and Gaussian-width adjoints with owner motion
      procedure :: grid_gaussian_gradient => ssf_grid_gaussian_gradient
      !> Contract nuclear curvature with one prepared directional pass
      procedure :: grid_hessian_vector => ssf_grid_hessian_vector
      !> Assemble dense nuclear curvature with one geometry, scratch and worker team
      procedure :: grid_hessian => ssf_grid_hessian
   end type ssf_partition_type

contains

   !> Stable ssf switch through pair-coordinate order 0
   !>
   !> @param[in] self Configured partition scheme
   !> @param[in] x Pair coordinate
   pure function ssf_eval(self, x) result(s)
      !> Configured partition scheme
      class(ssf_partition_type), intent(in) :: self
      !> Pair coordinate
      real(wp), intent(in) :: x
      !> Pair-switch weight
      real(wp) :: s
      real(wp) :: t

      s = 0.0_wp
      if (abs((x/self%a)) >= 1.0_wp) then
         if ((x/self%a) < 0.0_wp) s = 1.0_wp
         return
      end if
      t = 0.5_wp*(1.0_wp - abs((x/self%a)))
      s = t**4*(35.0_wp + t*(-84.0_wp + t*(70.0_wp - 20.0_wp*t)))
      if ((x/self%a) < 0.0_wp) then
         s = 1.0_wp - s
      end if
   end function ssf_eval

   !> Stable ssf switch through pair-coordinate order 1
   !>
   !> @param[in] self Configured partition scheme
   !> @param[in] x Pair coordinate
   !> @param[out] s Pair-switch weight
   !> @param[out] ds First pair-coordinate derivative
   pure subroutine ssf_eval_with_derivative(self, x, s, ds)
      !> Configured partition scheme
      class(ssf_partition_type), intent(in) :: self
      !> Pair coordinate
      real(wp), intent(in) :: x
      !> Pair-switch weight
      real(wp), intent(out) :: s
      !> First derivative
      real(wp), intent(out) :: ds
      real(wp) :: t

      s = 0.0_wp
      ds = 0.0_wp
      if (abs((x/self%a)) >= 1.0_wp) then
         if ((x/self%a) < 0.0_wp) s = 1.0_wp
         return
      end if
      t = 0.5_wp*(1.0_wp - abs((x/self%a)))
      s = t**4*(35.0_wp + t*(-84.0_wp + t*(70.0_wp - 20.0_wp*t)))
      ds = 70.0_wp*t**3*(-1.0_wp + t)**3
      if ((x/self%a) < 0.0_wp) then
         s = 1.0_wp - s
      end if
      ds = ds/self%a
   end subroutine ssf_eval_with_derivative

   !> Stable ssf switch through pair-coordinate order 2
   !>
   !> @param[in] self Configured partition scheme
   !> @param[in] x Pair coordinate
   !> @param[out] s Pair-switch weight
   !> @param[out] ds First pair-coordinate derivative
   !> @param[out] d2s Second pair-coordinate derivative; zero at endpoints
   pure subroutine ssf_eval_with_second_derivative(self, x, s, ds, d2s)
      !> Configured partition scheme
      class(ssf_partition_type), intent(in) :: self
      !> Pair coordinate
      real(wp), intent(in) :: x
      !> Pair-switch weight
      real(wp), intent(out) :: s
      !> First derivative
      real(wp), intent(out) :: ds
      !> Second derivative
      real(wp), intent(out) :: d2s
      real(wp) :: t, c0

      s = 0.0_wp
      ds = 0.0_wp
      d2s = 0.0_wp
      if (abs((x/self%a)) >= 1.0_wp) then
         if ((x/self%a) < 0.0_wp) s = 1.0_wp
         return
      end if
      t = 0.5_wp*(1.0_wp - abs((x/self%a)))
      c0 = -1.0_wp + t
      s = t**4*(35.0_wp + t*(-84.0_wp + t*(70.0_wp - 20.0_wp*t)))
      ds = 70.0_wp*c0**3*t**3
      d2s = -105.0_wp*c0**2*t**2*(-1.0_wp + 2.0_wp*t)
      if ((x/self%a) < 0.0_wp) then
         s = 1.0_wp - s
         d2s = -d2s
      end if
      ds = ds/self%a
      d2s = d2s/self%a**2
   end subroutine ssf_eval_with_second_derivative

   !> Evaluate all owners and quadrature weights in one prepared pass
   !>
   !> Unchecked shapes, finite inputs, valid owners and switch settings required
   !> Nuclear accumulators committed only after a finite contraction
   !> @param[in] self Configured partition scheme
   !> @param[in] points Sample positions (3, ng), bohr
   !> @param[in] xyz Nuclear positions (3, nat), bohr
   !> @param[in] numbers Atomic numbers (nat)
   !> @param[in] owners Point owners (ng), in [1, nat]
   !> @param[in] atomic_w Fixed atomic quadrature weights (ng), bohr**3
   !> @param[out] w Integration weights (ng), bohr**3
   !> @param[out] partition_w Normalized owner-partition weights (ng)
   !> @param[out] error Invalid geometry, allocation or non-finite contraction
   !> @param[in] nthreads Optional worker count; enclosing teams use one worker
   subroutine ssf_grid_weights(self, points, xyz, numbers, owners, atomic_w, w, partition_w, error, &
      & nthreads)
      !> Configured partition scheme
      class(ssf_partition_type), intent(in) :: self
      !> Sample positions (3, ng), bohr
      real(wp), intent(in) :: points(:, :)
      !> Nuclear positions (3, nat), bohr
      real(wp), intent(in) :: xyz(:, :)
      !> Atomic numbers (nat)
      integer, intent(in) :: numbers(:)
      !> Point owners (ng), in [1, nat]
      integer, intent(in) :: owners(:)
      !> Fixed atomic quadrature weights (ng), bohr**3
      real(wp), intent(in) :: atomic_w(:)
      !> Integration weights (ng), bohr**3
      real(wp), intent(out) :: w(:)
      !> Normalized owner-partition weights (ng)
      real(wp), intent(out) :: partition_w(:)
      !> Invalid geometry, allocation or non-finite contraction
      type(error_type), intent(out), allocatable :: error
      !> Optional worker count; enclosing teams use one worker
      integer, intent(in), optional :: nthreads

      real(wp), allocatable :: pair_r(:, :), pair_a(:, :), dist(:, :), probs(:, :)
      real(wp) :: point(3), peak
      integer :: nat, ng, nt, slot, ip, owner, stat, i

      nat = size(numbers)
      ng = size(owners)
      if (ng == 0) return
      nt = 1
!$    if (.not. omp_in_parallel()) then
!$       nt = omp_get_max_threads()
!$       if (present(nthreads)) then
!$          if (nthreads > 0) nt = nthreads
!$       end if
!$       nt = min(nt, ng)
!$    end if
      allocate (pair_r(nat, nat), stat=stat)
      if (stat == 0) allocate (pair_a(nat, nat), stat=stat)
      if (stat == 0) allocate (dist(nat, nt), stat=stat)
      if (stat == 0) allocate (probs(nat, nt), stat=stat)
      if (stat /= 0) then
         call fatal_error(error, "ssf grid: cannot allocate weights scratch")
         return
      end if
      block
         real(wp) :: radius(size(numbers))
         real(wp) :: chi, u
         integer :: ia, ja

         radius = covalent_rad(numbers)
         pair_r = 0.0_wp
         pair_a = 0.0_wp
         do ia = 1, size(numbers)
            do ja = 1, ia - 1
               pair_r(ja, ia) = norm2(xyz(:, ia) - xyz(:, ja))
               chi = radius(ia)/radius(ja)
               u = (chi - 1.0_wp)/(chi + 1.0_wp)
               pair_a(ja, ia) = max(-0.5_wp, min(0.5_wp, u/(u*u - 1.0_wp)))
               pair_r(ia, ja) = pair_r(ja, ia)
               pair_a(ia, ja) = -pair_a(ja, ia)
            end do
         end do
      end block
      !$omp parallel num_threads(nt) default(none) &
      !$omp shared(points, xyz, owners, atomic_w, pair_a, dist, probs, nat, ng, pair_r, self, w, &
      !$omp    & partition_w) private(slot, ip, owner, point, i, peak)
      slot = 1
!$    slot = omp_get_thread_num() + 1
      !$omp do schedule(static, 64)
      do ip = 1, ng
         owner = owners(ip)
         point = points(:, ip)
         if (nat == 1) then
            partition_w(ip) = 1.0_wp
         else
            do i = 1, nat
               dist(i, slot) = norm2(point - xyz(:, i))
            end do
            probs(owner, slot) = ssf_cell_log(owner, dist(:, slot), pair_r, pair_a, self)
            if (probs(owner, slot) == -huge(1.0_wp)) then
               partition_w(ip) = 0.0_wp
            else
               do i = 1, nat
                  if (i /= owner) then
                     probs(i, slot) = ssf_cell_log(i, dist(:, slot), pair_r, pair_a, self)
                  end if
               end do
               peak = maxval(probs(:, slot))
               partition_w(ip) = exp(probs(owner, slot) - peak)/sum(exp(probs(:, slot) - peak))
            end if
         end if
         w(ip) = atomic_w(ip)*partition_w(ip)
      end do
      !$omp end do
      !$omp end parallel
      if (.not. all(ieee_is_finite(w))) then
         call fatal_error(error, "ssf grid: non-finite integration weights")
      end if
   end subroutine ssf_grid_weights

   !> Contract all point and weight adjoints with owner motion
   !>
   !> Unchecked shapes, finite inputs, valid owners and switch settings required
   !> Nuclear accumulators committed only after a finite contraction
   !> @param[in] self Configured partition scheme
   !> @param[in] points Sample positions (3, ng), bohr
   !> @param[in] xyz Nuclear positions (3, nat), bohr
   !> @param[in] numbers Atomic numbers (nat)
   !> @param[in] owners Point owners (ng), in [1, nat]
   !> @param[in] atomic_w Fixed atomic quadrature weights (ng), bohr**3
   !> @param[in] adjoint_xyz Point-position adjoints (3, ng)
   !> @param[in] adjoint_w Integration-weight adjoints (ng)
   !> @param[in,out] gradient Nuclear-gradient accumulator (3, nat)
   !> @param[out] error Invalid geometry, allocation or non-finite contraction
   !> @param[in] nthreads Optional worker count; enclosing teams use one worker
   subroutine ssf_grid_gradient(self, points, xyz, numbers, owners, atomic_w, adjoint_xyz, &
      & adjoint_w, gradient, error, nthreads)
      !> Configured partition scheme
      class(ssf_partition_type), intent(in) :: self
      !> Sample positions (3, ng), bohr
      real(wp), intent(in) :: points(:, :)
      !> Nuclear positions (3, nat), bohr
      real(wp), intent(in) :: xyz(:, :)
      !> Atomic numbers (nat)
      integer, intent(in) :: numbers(:)
      !> Point owners (ng), in [1, nat]
      integer, intent(in) :: owners(:)
      !> Fixed atomic quadrature weights (ng), bohr**3
      real(wp), intent(in) :: atomic_w(:)
      !> Point-position adjoints (3, ng)
      real(wp), intent(in) :: adjoint_xyz(:, :)
      !> Integration-weight adjoints (ng)
      real(wp), intent(in) :: adjoint_w(:)
      !> Nuclear-gradient accumulator (3, nat)
      real(wp), intent(inout) :: gradient(:, :)
      !> Invalid geometry, allocation or non-finite contraction
      type(error_type), intent(out), allocatable :: error
      !> Optional worker count; enclosing teams use one worker
      integer, intent(in), optional :: nthreads

      real(wp), allocatable :: pair_r(:, :), pair_a(:, :), dist(:, :), probs(:, :), workers(:, :, &
         & :), local(:, :)
      real(wp) :: point(3), seed, point_response(3)
      integer :: nat, ng, nt, slot, ip, owner, stat

      nat = size(numbers)
      ng = size(owners)
      if (ng == 0) return
      nt = 1
!$    if (.not. omp_in_parallel()) then
!$       nt = omp_get_max_threads()
!$       if (present(nthreads)) then
!$          if (nthreads > 0) nt = nthreads
!$       end if
!$       nt = min(nt, ng)
!$    end if
      allocate (pair_r(nat, nat), stat=stat)
      if (stat == 0) allocate (pair_a(nat, nat), stat=stat)
      if (stat == 0) allocate (dist(nat, nt), stat=stat)
      if (stat == 0) allocate (probs(nat, nt), stat=stat)
      if (stat == 0) allocate (workers(3, nat, nt), stat=stat)
      if (stat == 0) allocate (local(3, nat), stat=stat)
      if (stat /= 0) then
         call fatal_error(error, "ssf grid: cannot allocate gradient scratch")
         return
      end if
      block
         real(wp) :: radius(size(numbers))
         real(wp) :: chi, u
         integer :: ia, ja

         radius = covalent_rad(numbers)
         pair_r = 0.0_wp
         pair_a = 0.0_wp
         do ia = 1, size(numbers)
            do ja = 1, ia - 1
               pair_r(ja, ia) = norm2(xyz(:, ia) - xyz(:, ja))
               chi = radius(ia)/radius(ja)
               u = (chi - 1.0_wp)/(chi + 1.0_wp)
               pair_a(ja, ia) = max(-0.5_wp, min(0.5_wp, u/(u*u - 1.0_wp)))
               pair_r(ia, ja) = pair_r(ja, ia)
               pair_a(ia, ja) = -pair_a(ja, ia)
            end do
         end do
      end block
      workers = 0.0_wp
      !$omp parallel num_threads(nt) default(none) &
      !$omp shared(points, xyz, owners, atomic_w, pair_a, dist, probs, nat, ng, pair_r, self, adjoint_w, &
      !$omp    & workers, adjoint_xyz) private(slot, ip, owner, point, seed, point_response)
      slot = 1
!$    slot = omp_get_thread_num() + 1
      !$omp do schedule(static, 64)
      do ip = 1, ng
         owner = owners(ip)
         point = points(:, ip)
         seed = atomic_w(ip)*adjoint_w(ip)
         point_response = 0.0_wp
         if (seed /= 0.0_wp .and. nat > 1) then
            point_math: block
               real(wp) :: peak, owner_seed, log_seed, mu, nu, s, ds, factor
               real(wp) :: ui(3), uj(3), axis(3)
               integer :: i, j

               associate (dist => dist(:, slot), probs => probs(:, slot), gradient => workers(:, :, slot), &
                  & point_gradient => point_response)
                  point_gradient = 0.0_wp
                  dist = 0.0_wp
                  do i = 1, size(dist)
                     dist(i) = norm2(point - xyz(:, i))
                  end do
                  do i = 1, size(dist)
                     probs(i) = ssf_cell_log(i, dist, pair_r, pair_a, self)
                  end do
                  if (probs(owner) == -huge(1.0_wp)) exit point_math
                  peak = maxval(probs)
                  probs = exp(probs - peak)
                  probs = probs/sum(probs)
                  owner_seed = seed*probs(owner)
                  do i = 1, size(dist)
                     log_seed = -owner_seed*probs(i)
                     if (i == owner) then
                        ! Sum other probabilities to retain derivatives of tiny partition tails
                        log_seed = owner_seed*(sum(probs(:i - 1)) + sum(probs(i + 1:)))
                     end if
                     if (log_seed == 0.0_wp) cycle
                     do j = 1, size(dist)
                        if (j == i) cycle
                        if (pair_r(j, i) <= 0.0_wp) cycle
                        mu = max(-1.0_wp, min(1.0_wp, (dist(i) - dist(j))/pair_r(j, i)))
                        nu = mu + pair_a(j, i)*(1.0_wp - mu*mu)
                        block
                           real(wp) :: t

                           s = 0.0_wp
                           ds = 0.0_wp
                           if (abs((nu/self%a)) >= 1.0_wp) then
                              if ((nu/self%a) < 0.0_wp) s = 1.0_wp
                           else
                              t = 0.5_wp*(1.0_wp - abs((nu/self%a)))
                              s = t**4*(35.0_wp + t*(-84.0_wp + t*(70.0_wp - 20.0_wp*t)))
                              ds = 70.0_wp*t**3*(-1.0_wp + t)**3
                              if ((nu/self%a) < 0.0_wp) then
                                 s = 1.0_wp - s
                              end if
                           end if
                           ds = ds/self%a
                        end block
                        if (s <= 0.0_wp .or. ds == 0.0_wp) cycle
                        factor = (log_seed/s)*ds
                        if (abs(mu) >= 1.0_wp) cycle
                        factor = factor*(1.0_wp - 2.0_wp*pair_a(j, i)*mu)/pair_r(j, i)
                        ui = 0.0_wp
                        uj = 0.0_wp
                        if (dist(i) > 0.0_wp) ui = (point - xyz(:, i))/dist(i)
                        if (dist(j) > 0.0_wp) uj = (point - xyz(:, j))/dist(j)
                        axis = (xyz(:, i) - xyz(:, j))/pair_r(j, i)
                        point_gradient = point_gradient + factor*(ui - uj)
                        gradient(:, i) = gradient(:, i) - factor*(ui + mu*axis)
                        gradient(:, j) = gradient(:, j) + factor*(uj + mu*axis)
                     end do
                  end do
               end associate
            end block point_math
         end if
         workers(:, owner, slot) = workers(:, owner, slot) + point_response + adjoint_xyz(:, ip)
      end do
      !$omp end do
      !$omp end parallel
      local = 0.0_wp
      do slot = 1, nt
         local = local + workers(:, :, slot)
      end do
      if (.not. all(ieee_is_finite(local))) then
         call fatal_error(error, "ssf grid: non-finite gradient contraction")
         return
      end if
      gradient = gradient + local
   end subroutine ssf_grid_gradient

   !> Contract point, weight and Gaussian-width adjoints with owner motion
   !>
   !> Unchecked shapes, finite inputs, valid owners and switch settings required
   !> Nuclear accumulators committed only after a finite contraction
   !> @param[in] self Configured partition scheme
   !> @param[in] points Sample positions (3, ng), bohr
   !> @param[in] xyz Nuclear positions (3, nat), bohr
   !> @param[in] numbers Atomic numbers (nat)
   !> @param[in] owners Point owners (ng), in [1, nat]
   !> @param[in] atomic_w Fixed atomic quadrature weights (ng), bohr**3
   !> @param[in] adjoint_xyz Point-position adjoints (3, ng)
   !> @param[in] adjoint_w Integration-weight adjoints (ng)
   !> @param[in] adjoint_xi Gaussian-width adjoints (ng)
   !> @param[in] xi0 Gaussian exponents (ng), inverse bohr
   !> @param[in] weights Positive realized integration weights (ng), bohr**3
   !> @param[in,out] gradient Nuclear-gradient accumulator (3, nat)
   !> @param[out] error Invalid geometry, allocation or non-finite contraction
   !> @param[in] nthreads Optional worker count; enclosing teams use one worker
   subroutine ssf_grid_gaussian_gradient(self, points, xyz, numbers, owners, atomic_w, adjoint_xyz, &
      & adjoint_w, adjoint_xi, xi0, weights, gradient, error, nthreads)
      !> Configured partition scheme
      class(ssf_partition_type), intent(in) :: self
      !> Sample positions (3, ng), bohr
      real(wp), intent(in) :: points(:, :)
      !> Nuclear positions (3, nat), bohr
      real(wp), intent(in) :: xyz(:, :)
      !> Atomic numbers (nat)
      integer, intent(in) :: numbers(:)
      !> Point owners (ng), in [1, nat]
      integer, intent(in) :: owners(:)
      !> Fixed atomic quadrature weights (ng), bohr**3
      real(wp), intent(in) :: atomic_w(:)
      !> Point-position adjoints (3, ng)
      real(wp), intent(in) :: adjoint_xyz(:, :)
      !> Integration-weight adjoints (ng)
      real(wp), intent(in) :: adjoint_w(:)
      !> Gaussian-width adjoints (ng)
      real(wp), intent(in) :: adjoint_xi(:)
      !> Gaussian exponents (ng), inverse bohr
      real(wp), intent(in) :: xi0(:)
      !> Positive realized integration weights (ng), bohr**3
      real(wp), intent(in) :: weights(:)
      !> Nuclear-gradient accumulator (3, nat)
      real(wp), intent(inout) :: gradient(:, :)
      !> Invalid geometry, allocation or non-finite contraction
      type(error_type), intent(out), allocatable :: error
      !> Optional worker count; enclosing teams use one worker
      integer, intent(in), optional :: nthreads

      real(wp), allocatable :: pair_r(:, :), pair_a(:, :), dist(:, :), probs(:, :), workers(:, :, &
         & :), local(:, :)
      real(wp) :: point(3), seed, point_response(3)
      integer :: nat, ng, nt, slot, ip, owner, stat

      nat = size(numbers)
      ng = size(owners)
      if (ng == 0) return
      nt = 1
!$    if (.not. omp_in_parallel()) then
!$       nt = omp_get_max_threads()
!$       if (present(nthreads)) then
!$          if (nthreads > 0) nt = nthreads
!$       end if
!$       nt = min(nt, ng)
!$    end if
      allocate (pair_r(nat, nat), stat=stat)
      if (stat == 0) allocate (pair_a(nat, nat), stat=stat)
      if (stat == 0) allocate (dist(nat, nt), stat=stat)
      if (stat == 0) allocate (probs(nat, nt), stat=stat)
      if (stat == 0) allocate (workers(3, nat, nt), stat=stat)
      if (stat == 0) allocate (local(3, nat), stat=stat)
      if (stat /= 0) then
         call fatal_error(error, "ssf grid: cannot allocate gaussian_gradient scratch")
         return
      end if
      block
         real(wp) :: radius(size(numbers))
         real(wp) :: chi, u
         integer :: ia, ja

         radius = covalent_rad(numbers)
         pair_r = 0.0_wp
         pair_a = 0.0_wp
         do ia = 1, size(numbers)
            do ja = 1, ia - 1
               pair_r(ja, ia) = norm2(xyz(:, ia) - xyz(:, ja))
               chi = radius(ia)/radius(ja)
               u = (chi - 1.0_wp)/(chi + 1.0_wp)
               pair_a(ja, ia) = max(-0.5_wp, min(0.5_wp, u/(u*u - 1.0_wp)))
               pair_r(ia, ja) = pair_r(ja, ia)
               pair_a(ia, ja) = -pair_a(ja, ia)
            end do
         end do
      end block
      workers = 0.0_wp
      !$omp parallel num_threads(nt) default(none) &
      !$omp shared(points, xyz, owners, atomic_w, pair_a, dist, probs, nat, ng, pair_r, self, adjoint_w, &
      !$omp    & workers, adjoint_xyz, adjoint_xi, xi0, weights) private(slot, ip, owner, point, seed, &
      !$omp    & point_response)
      slot = 1
!$    slot = omp_get_thread_num() + 1
      !$omp do schedule(static, 64)
      do ip = 1, ng
         owner = owners(ip)
         point = points(:, ip)
         seed = atomic_w(ip)*(adjoint_w(ip) + adjoint_xi(ip)*((-1.0_wp/3.0_wp)*xi0(ip)*(1.0_wp/weights(ip))))
         point_response = 0.0_wp
         if (seed /= 0.0_wp .and. nat > 1) then
            point_math: block
               real(wp) :: peak, owner_seed, log_seed, mu, nu, s, ds, factor
               real(wp) :: ui(3), uj(3), axis(3)
               integer :: i, j

               associate (dist => dist(:, slot), probs => probs(:, slot), gradient => workers(:, :, slot), &
                  & point_gradient => point_response)
                  point_gradient = 0.0_wp
                  dist = 0.0_wp
                  do i = 1, size(dist)
                     dist(i) = norm2(point - xyz(:, i))
                  end do
                  do i = 1, size(dist)
                     probs(i) = ssf_cell_log(i, dist, pair_r, pair_a, self)
                  end do
                  if (probs(owner) == -huge(1.0_wp)) exit point_math
                  peak = maxval(probs)
                  probs = exp(probs - peak)
                  probs = probs/sum(probs)
                  owner_seed = seed*probs(owner)
                  do i = 1, size(dist)
                     log_seed = -owner_seed*probs(i)
                     if (i == owner) then
                        ! Sum other probabilities to retain derivatives of tiny partition tails
                        log_seed = owner_seed*(sum(probs(:i - 1)) + sum(probs(i + 1:)))
                     end if
                     if (log_seed == 0.0_wp) cycle
                     do j = 1, size(dist)
                        if (j == i) cycle
                        if (pair_r(j, i) <= 0.0_wp) cycle
                        mu = max(-1.0_wp, min(1.0_wp, (dist(i) - dist(j))/pair_r(j, i)))
                        nu = mu + pair_a(j, i)*(1.0_wp - mu*mu)
                        block
                           real(wp) :: t

                           s = 0.0_wp
                           ds = 0.0_wp
                           if (abs((nu/self%a)) >= 1.0_wp) then
                              if ((nu/self%a) < 0.0_wp) s = 1.0_wp
                           else
                              t = 0.5_wp*(1.0_wp - abs((nu/self%a)))
                              s = t**4*(35.0_wp + t*(-84.0_wp + t*(70.0_wp - 20.0_wp*t)))
                              ds = 70.0_wp*t**3*(-1.0_wp + t)**3
                              if ((nu/self%a) < 0.0_wp) then
                                 s = 1.0_wp - s
                              end if
                           end if
                           ds = ds/self%a
                        end block
                        if (s <= 0.0_wp .or. ds == 0.0_wp) cycle
                        factor = (log_seed/s)*ds
                        if (abs(mu) >= 1.0_wp) cycle
                        factor = factor*(1.0_wp - 2.0_wp*pair_a(j, i)*mu)/pair_r(j, i)
                        ui = 0.0_wp
                        uj = 0.0_wp
                        if (dist(i) > 0.0_wp) ui = (point - xyz(:, i))/dist(i)
                        if (dist(j) > 0.0_wp) uj = (point - xyz(:, j))/dist(j)
                        axis = (xyz(:, i) - xyz(:, j))/pair_r(j, i)
                        point_gradient = point_gradient + factor*(ui - uj)
                        gradient(:, i) = gradient(:, i) - factor*(ui + mu*axis)
                        gradient(:, j) = gradient(:, j) + factor*(uj + mu*axis)
                     end do
                  end do
               end associate
            end block point_math
         end if
         workers(:, owner, slot) = workers(:, owner, slot) + point_response + adjoint_xyz(:, ip)
      end do
      !$omp end do
      !$omp end parallel
      local = 0.0_wp
      do slot = 1, nt
         local = local + workers(:, :, slot)
      end do
      if (.not. all(ieee_is_finite(local))) then
         call fatal_error(error, "ssf grid: non-finite gaussian_gradient contraction")
         return
      end if
      gradient = gradient + local
   end subroutine ssf_grid_gaussian_gradient

   !> Contract nuclear curvature with one prepared directional pass
   !>
   !> Unchecked shapes, finite inputs, valid owners and switch settings required
   !> Nuclear accumulators committed only after a finite contraction
   !> @param[in] self Configured partition scheme
   !> @param[in] points Sample positions (3, ng), bohr
   !> @param[in] xyz Nuclear positions (3, nat), bohr
   !> @param[in] numbers Atomic numbers (nat)
   !> @param[in] owners Point owners (ng), in [1, nat]
   !> @param[in] atomic_w Fixed atomic quadrature weights (ng), bohr**3
   !> @param[in] adjoint_w Integration-weight adjoints (ng)
   !> @param[in] direction Nuclear displacement direction (3, nat)
   !> @param[in,out] hessian_vector Nuclear Hessian-vector accumulator (3, nat)
   !> @param[out] error Invalid geometry, allocation or non-finite contraction
   !> @param[in] nthreads Optional worker count; enclosing teams use one worker
   subroutine ssf_grid_hessian_vector(self, points, xyz, numbers, owners, atomic_w, adjoint_w, &
      & direction, hessian_vector, error, nthreads)
      !> Configured partition scheme
      class(ssf_partition_type), intent(in) :: self
      !> Sample positions (3, ng), bohr
      real(wp), intent(in) :: points(:, :)
      !> Nuclear positions (3, nat), bohr
      real(wp), intent(in) :: xyz(:, :)
      !> Atomic numbers (nat)
      integer, intent(in) :: numbers(:)
      !> Point owners (ng), in [1, nat]
      integer, intent(in) :: owners(:)
      !> Fixed atomic quadrature weights (ng), bohr**3
      real(wp), intent(in) :: atomic_w(:)
      !> Integration-weight adjoints (ng)
      real(wp), intent(in) :: adjoint_w(:)
      !> Nuclear displacement direction (3, nat)
      real(wp), intent(in) :: direction(:, :)
      !> Nuclear Hessian-vector accumulator (3, nat)
      real(wp), intent(inout) :: hessian_vector(:, :)
      !> Invalid geometry, allocation or non-finite contraction
      type(error_type), intent(out), allocatable :: error
      !> Optional worker count; enclosing teams use one worker
      integer, intent(in), optional :: nthreads

      real(wp), allocatable :: pair_r(:, :), pair_a(:, :), dist(:, :), probs(:, :), log_t(:, :), &
         & workers(:, :, :), local(:, :)
      real(wp) :: point(3), seed, point_response(3)
      integer :: nat, ng, nt, slot, ip, owner, stat, i, j

      nat = size(numbers)
      ng = size(owners)
      if (ng == 0) return
      if (nat == 1 .or. all(atomic_w*adjoint_w == 0.0_wp)) return
      if (all(direction == 0.0_wp)) return
      nt = 1
!$    if (.not. omp_in_parallel()) then
!$       nt = omp_get_max_threads()
!$       if (present(nthreads)) then
!$          if (nthreads > 0) nt = nthreads
!$       end if
!$       nt = min(nt, ng)
!$    end if
      allocate (pair_r(nat, nat), stat=stat)
      if (stat == 0) allocate (pair_a(nat, nat), stat=stat)
      if (stat == 0) allocate (dist(nat, nt), stat=stat)
      if (stat == 0) allocate (probs(nat, nt), stat=stat)
      if (stat == 0) allocate (log_t(nat, nt), stat=stat)
      if (stat == 0) allocate (workers(3, nat, nt), stat=stat)
      if (stat == 0) allocate (local(3, nat), stat=stat)
      if (stat /= 0) then
         call fatal_error(error, "ssf grid: cannot allocate hessian_vector scratch")
         return
      end if
      block
         real(wp) :: radius(size(numbers))
         real(wp) :: chi, u
         integer :: ia, ja

         radius = covalent_rad(numbers)
         pair_r = 0.0_wp
         pair_a = 0.0_wp
         do ia = 1, size(numbers)
            do ja = 1, ia - 1
               pair_r(ja, ia) = norm2(xyz(:, ia) - xyz(:, ja))
               chi = radius(ia)/radius(ja)
               u = (chi - 1.0_wp)/(chi + 1.0_wp)
               pair_a(ja, ia) = max(-0.5_wp, min(0.5_wp, u/(u*u - 1.0_wp)))
               pair_r(ia, ja) = pair_r(ja, ia)
               pair_a(ia, ja) = -pair_a(ja, ia)
            end do
         end do
      end block
      do i = 1, nat
         do j = 1, i - 1
            if (pair_r(i, j) <= 0.0_wp) then
               call fatal_error(error, "grid Hessian: coincident elliptic centers are not differentiable")
               return
            end if
         end do
      end do
      workers = 0.0_wp
      !$omp parallel num_threads(nt) default(none) &
      !$omp shared(points, xyz, owners, atomic_w, pair_a, dist, probs, nat, ng, pair_r, self, adjoint_w, &
      !$omp    & workers, log_t, direction) private(slot, ip, owner, point, seed, point_response)
      slot = 1
!$    slot = omp_get_thread_num() + 1
      !$omp do schedule(static, 64)
      do ip = 1, ng
         owner = owners(ip)
         point = points(:, ip)
         seed = atomic_w(ip)*adjoint_w(ip)
         point_response = 0.0_wp
         if (seed /= 0.0_wp) then
            point_math: block
               real(wp) :: positions(3, 3), tangent(3, 3), g(3, 3), h(3, 3), contribution(3, 3)
               real(wp) :: nu, nu_t, s, ds, d2s, peak, q, qt, alpha, alpha_t, log_p_t, first, second, beta, beta_t
               integer :: i, j, k

               associate (dist => dist(:, slot), probs => probs(:, slot), hessian_vector => workers(:, :, &
                  & slot), point_hessian_vector => point_response, log_t => log_t(:, slot), &
                  & point_direction => direction(:, owner))
                  point_hessian_vector = 0.0_wp
                  dist = 0.0_wp
                  do i = 1, size(dist)
                     dist(i) = norm2(point - xyz(:, i))
                  end do
                  positions(:, 1) = point
                  tangent(:, 1) = point_direction
                  probs = 0.0_wp
                  log_t = 0.0_wp
                  do i = 1, size(dist)
                     positions(:, 2) = xyz(:, i)
                     tangent(:, 2) = direction(:, i)
                     do j = 1, size(dist)
                        if (j == i) cycle
                        positions(:, 3) = xyz(:, j)
                        tangent(:, 3) = direction(:, j)
                        ! Coordinate order 1: elliptic
                        block
                           real(wp) :: mu, r, a, unit(3, 3), mg(3)
                           real(wp) :: c0

                           g = 0.0_wp
                           r = pair_r(j, i)
                           a = pair_a(j, i)
                           mu = max(-1.0_wp, min(1.0_wp, (dist(i) - dist(j))/r))
                           nu = mu + a*(1.0_wp - mu*mu)
                           if (abs(mu) < 1.0_wp) then
                              unit = 0.0_wp
                              if (dist(i) > 0.0_wp) unit(:, 1) = (positions(:, 1) - positions(:, 2))/dist(i)
                              if (dist(j) > 0.0_wp) unit(:, 2) = (positions(:, 1) - positions(:, 3))/dist(j)
                              unit(:, 3) = (positions(:, 2) - positions(:, 3))/r
                              c0 = (1.0_wp/r)*(-1.0_wp + 2.0_wp*a*mu)
                              mg(1) = -c0
                              mg(2) = c0
                              mg(3) = c0*mu
                              g(:, 1) = mg(1)*unit(:, 1) + mg(2)*unit(:, 2)
                              g(:, 2) = -mg(1)*unit(:, 1) + mg(3)*unit(:, 3)
                              g(:, 3) = -mg(2)*unit(:, 2) - mg(3)*unit(:, 3)
                           end if
                        end block
                        block
                           real(wp) :: t

                           s = 0.0_wp
                           ds = 0.0_wp
                           if (abs((nu/self%a)) >= 1.0_wp) then
                              if ((nu/self%a) < 0.0_wp) s = 1.0_wp
                           else
                              t = 0.5_wp*(1.0_wp - abs((nu/self%a)))
                              s = t**4*(35.0_wp + t*(-84.0_wp + t*(70.0_wp - 20.0_wp*t)))
                              ds = 70.0_wp*t**3*(-1.0_wp + t)**3
                              if ((nu/self%a) < 0.0_wp) then
                                 s = 1.0_wp - s
                              end if
                           end if
                           ds = ds/self%a
                        end block
                        if (s <= 0.0_wp) then
                           probs(i) = -huge(1.0_wp)
                           log_t(i) = 0.0_wp
                           exit
                        end if
                        probs(i) = probs(i) + log(s)
                        log_t(i) = log_t(i) + (ds/s)*sum(g*tangent)
                     end do
                  end do
                  if (probs(owner) == -huge(1.0_wp)) exit point_math
                  peak = maxval(probs)
                  probs = exp(probs - peak)
                  probs = probs/sum(probs)
                  q = seed*probs(owner)
                  qt = q*sum(probs*(log_t(owner) - log_t))
                  do i = 1, size(dist)
                     log_p_t = sum(probs*(log_t(i) - log_t))
                     alpha = -q*probs(i)
                     alpha_t = -qt*probs(i) - q*probs(i)*log_p_t
                     if (i == owner) then
                        beta = 0.0_wp
                        beta_t = 0.0_wp
                        do k = 1, size(dist)
                           if (k == owner) cycle
                           beta = beta + probs(k)
                           beta_t = beta_t + probs(k)*sum(probs*(log_t(k) - log_t))
                        end do
                        alpha = q*beta
                        alpha_t = qt*beta + q*beta_t
                     end if
                     if (alpha == 0.0_wp .and. alpha_t == 0.0_wp) cycle
                     positions(:, 2) = xyz(:, i)
                     tangent(:, 2) = direction(:, i)
                     do j = 1, size(dist)
                        if (j == i) cycle
                        positions(:, 3) = xyz(:, j)
                        tangent(:, 3) = direction(:, j)
                        ! Coordinate order 2: elliptic
                        block
                           real(wp) :: mu, r, a, unit(3, 3), mg(3)
                           real(wp) :: unit_t(3, 3), delta(3, 3), metric_t(3), mh(3)
                           integer :: c
                           real(wp) :: c0, c1, c2, c3, c4, c5, c6

                           g = 0.0_wp
                           h = 0.0_wp
                           r = pair_r(j, i)
                           a = pair_a(j, i)
                           mu = max(-1.0_wp, min(1.0_wp, (dist(i) - dist(j))/r))
                           nu = mu + a*(1.0_wp - mu*mu)
                           if (abs(mu) < 1.0_wp) then
                              unit = 0.0_wp
                              if (dist(i) > 0.0_wp) unit(:, 1) = (positions(:, 1) - positions(:, 2))/dist(i)
                              if (dist(j) > 0.0_wp) unit(:, 2) = (positions(:, 1) - positions(:, 3))/dist(j)
                              unit(:, 3) = (positions(:, 2) - positions(:, 3))/r
                              unit_t = 0.0_wp
                              delta(:, 1) = tangent(:, 1) - tangent(:, 2)
                              delta(:, 2) = tangent(:, 1) - tangent(:, 3)
                              delta(:, 3) = tangent(:, 2) - tangent(:, 3)
                              do c = 1, 3
                                 metric_t(c) = dot_product(unit(:, c), delta(:, c))
                              end do
                              if (dist(i) > 0.0_wp) unit_t(:, 1) = (delta(:, 1) - unit(:, 1)*metric_t(1))/dist(i)
                              if (dist(j) > 0.0_wp) unit_t(:, 2) = (delta(:, 2) - unit(:, 2)*metric_t(2))/dist(j)
                              unit_t(:, 3) = (delta(:, 3) - unit(:, 3)*metric_t(3))/r
                              c0 = 2.0_wp*a
                              c1 = (1.0_wp/r)*(-1.0_wp + c0*mu)
                              c2 = (1.0_wp/r**2)
                              c3 = metric_t(3)*mu
                              c4 = 4.0_wp*a
                              c5 = c2*(metric_t(3) + c0*metric_t(1) - c0*metric_t(2) - c3*c4)
                              c6 = c4*mu
                              mg(1) = -c1
                              mg(2) = c1
                              mg(3) = c1*mu
                              mh(1) = -c5
                              mh(2) = c5
                              mh(3) = c2*(metric_t(2) - metric_t(1) + 2.0_wp*c3 + c6*metric_t(1) - c6*metric_t(2) - &
                                 & 6.0_wp*metric_t(3)*a*mu**2)
                              g(:, 1) = mg(1)*unit(:, 1) + mg(2)*unit(:, 2)
                              g(:, 2) = -mg(1)*unit(:, 1) + mg(3)*unit(:, 3)
                              g(:, 3) = -mg(2)*unit(:, 2) - mg(3)*unit(:, 3)
                              h(:, 1) = mh(1)*unit(:, 1) + mg(1)*unit_t(:, 1) + mh(2)*unit(:, 2) + mg(2)*unit_t(:, 2)
                              h(:, 2) = -mh(1)*unit(:, 1) - mg(1)*unit_t(:, 1) + mh(3)*unit(:, 3) + mg(3)*unit_t(:, 3)
                              h(:, 3) = -mh(2)*unit(:, 2) - mg(2)*unit_t(:, 2) - mh(3)*unit(:, 3) - mg(3)*unit_t(:, 3)
                           end if
                        end block
                        block
                           real(wp) :: t, c0

                           s = 0.0_wp
                           ds = 0.0_wp
                           d2s = 0.0_wp
                           if (abs((nu/self%a)) >= 1.0_wp) then
                              if ((nu/self%a) < 0.0_wp) s = 1.0_wp
                           else
                              t = 0.5_wp*(1.0_wp - abs((nu/self%a)))
                              c0 = -1.0_wp + t
                              s = t**4*(35.0_wp + t*(-84.0_wp + t*(70.0_wp - 20.0_wp*t)))
                              ds = 70.0_wp*c0**3*t**3
                              d2s = -105.0_wp*c0**2*t**2*(-1.0_wp + 2.0_wp*t)
                              if ((nu/self%a) < 0.0_wp) then
                                 s = 1.0_wp - s
                                 d2s = -d2s
                              end if
                           end if
                           ds = ds/self%a
                           d2s = d2s/self%a**2
                        end block
                        if (s <= 0.0_wp) cycle
                        first = ds/s
                        second = d2s/s - first*first
                        nu_t = sum(g*tangent)
                        contribution = (alpha_t*first + alpha*second*nu_t)*g + alpha*first*h
                        point_hessian_vector = point_hessian_vector + contribution(:, 1)
                        hessian_vector(:, i) = hessian_vector(:, i) + contribution(:, 2)
                        hessian_vector(:, j) = hessian_vector(:, j) + contribution(:, 3)
                     end do
                  end do
               end associate
            end block point_math
         end if
         workers(:, owner, slot) = workers(:, owner, slot) + point_response
      end do
      !$omp end do
      !$omp end parallel
      local = 0.0_wp
      do slot = 1, nt
         local = local + workers(:, :, slot)
      end do
      if (.not. all(ieee_is_finite(local))) then
         call fatal_error(error, "ssf grid: non-finite hessian_vector contraction")
         return
      end if
      hessian_vector = hessian_vector + local
   end subroutine ssf_grid_hessian_vector

   !> Assemble dense nuclear curvature with one geometry, scratch and worker team
   !>
   !> Unchecked shapes, finite inputs, valid owners and switch settings required
   !> Nuclear accumulators committed only after a finite contraction
   !> @param[in] self Configured partition scheme
   !> @param[in] points Sample positions (3, ng), bohr
   !> @param[in] xyz Nuclear positions (3, nat), bohr
   !> @param[in] numbers Atomic numbers (nat)
   !> @param[in] owners Point owners (ng), in [1, nat]
   !> @param[in] atomic_w Fixed atomic quadrature weights (ng), bohr**3
   !> @param[in] adjoint_w Integration-weight adjoints (ng)
   !> @param[in,out] hessian Nuclear Hessian accumulator (3, nat, 3, nat)
   !> @param[out] error Invalid geometry, allocation or non-finite contraction
   !> @param[in] nthreads Optional worker count; enclosing teams use one worker
   subroutine ssf_grid_hessian(self, points, xyz, numbers, owners, atomic_w, adjoint_w, hessian, &
      & error, nthreads)
      !> Configured partition scheme
      class(ssf_partition_type), intent(in) :: self
      !> Sample positions (3, ng), bohr
      real(wp), intent(in) :: points(:, :)
      !> Nuclear positions (3, nat), bohr
      real(wp), intent(in) :: xyz(:, :)
      !> Atomic numbers (nat)
      integer, intent(in) :: numbers(:)
      !> Point owners (ng), in [1, nat]
      integer, intent(in) :: owners(:)
      !> Fixed atomic quadrature weights (ng), bohr**3
      real(wp), intent(in) :: atomic_w(:)
      !> Integration-weight adjoints (ng)
      real(wp), intent(in) :: adjoint_w(:)
      !> Nuclear Hessian accumulator (3, nat, 3, nat)
      real(wp), intent(inout) :: hessian(:, :, :, :)
      !> Invalid geometry, allocation or non-finite contraction
      type(error_type), intent(out), allocatable :: error
      !> Optional worker count; enclosing teams use one worker
      integer, intent(in), optional :: nthreads

      real(wp), allocatable :: pair_r(:, :), pair_a(:, :), dist(:, :), probs(:, :), log_t(:, :), &
         & workers(:, :, :), local_h(:, :, :, :), basis(:, :, :)
      real(wp) :: point(3), seed, point_response(3)
      integer :: nat, ng, nt, slot, ip, owner, stat, i, j, atom, component, worker

      nat = size(numbers)
      ng = size(owners)
      if (ng == 0) return
      if (nat == 1 .or. all(atomic_w*adjoint_w == 0.0_wp)) return
      nt = 1
!$    if (.not. omp_in_parallel()) then
!$       nt = omp_get_max_threads()
!$       if (present(nthreads)) then
!$          if (nthreads > 0) nt = nthreads
!$       end if
!$       nt = min(nt, ng)
!$    end if
      allocate (pair_r(nat, nat), stat=stat)
      if (stat == 0) allocate (pair_a(nat, nat), stat=stat)
      if (stat == 0) allocate (dist(nat, nt), stat=stat)
      if (stat == 0) allocate (probs(nat, nt), stat=stat)
      if (stat == 0) allocate (log_t(nat, nt), stat=stat)
      if (stat == 0) allocate (workers(3, nat, nt), stat=stat)
      if (stat == 0) allocate (local_h(3, nat, 3, nat), stat=stat)
      if (stat == 0) allocate (basis(3, nat, nt), stat=stat)
      if (stat /= 0) then
         call fatal_error(error, "ssf grid: cannot allocate hessian scratch")
         return
      end if
      block
         real(wp) :: radius(size(numbers))
         real(wp) :: chi, u
         integer :: ia, ja

         radius = covalent_rad(numbers)
         pair_r = 0.0_wp
         pair_a = 0.0_wp
         do ia = 1, size(numbers)
            do ja = 1, ia - 1
               pair_r(ja, ia) = norm2(xyz(:, ia) - xyz(:, ja))
               chi = radius(ia)/radius(ja)
               u = (chi - 1.0_wp)/(chi + 1.0_wp)
               pair_a(ja, ia) = max(-0.5_wp, min(0.5_wp, u/(u*u - 1.0_wp)))
               pair_r(ia, ja) = pair_r(ja, ia)
               pair_a(ia, ja) = -pair_a(ja, ia)
            end do
         end do
      end block
      do i = 1, nat
         do j = 1, i - 1
            if (pair_r(i, j) <= 0.0_wp) then
               call fatal_error(error, "grid Hessian: coincident elliptic centers are not differentiable")
               return
            end if
         end do
      end do
      workers = 0.0_wp
      !$omp parallel num_threads(nt) default(none) &
      !$omp shared(points, xyz, owners, atomic_w, pair_a, dist, probs, nat, ng, pair_r, self, adjoint_w, &
      !$omp    & workers, log_t, local_h, basis, nt) private(slot, ip, owner, point, seed, point_response, &
      !$omp    & atom, component, worker)
      slot = 1
!$    slot = omp_get_thread_num() + 1
      do atom = 1, nat
         do component = 1, 3
            basis(:, :, slot) = 0.0_wp
            basis(component, atom, slot) = 1.0_wp
            workers(:, :, slot) = 0.0_wp
            !$omp do schedule(static, 64)
            do ip = 1, ng
               owner = owners(ip)
               point = points(:, ip)
               seed = atomic_w(ip)*adjoint_w(ip)
               point_response = 0.0_wp
               if (seed /= 0.0_wp) then
                  point_math: block
                     real(wp) :: positions(3, 3), tangent(3, 3), g(3, 3), h(3, 3), contribution(3, 3)
                     real(wp) :: nu, nu_t, s, ds, d2s, peak, q, qt, alpha, alpha_t, log_p_t, first, second, beta, beta_t
                     integer :: i, j, k

                     associate (dist => dist(:, slot), probs => probs(:, slot), hessian_vector => workers(:, :, &
                        & slot), point_hessian_vector => point_response, log_t => log_t(:, slot), direction => &
                        & basis(:, :, slot), point_direction => basis(:, owner, slot))
                        point_hessian_vector = 0.0_wp
                        dist = 0.0_wp
                        do i = 1, size(dist)
                           dist(i) = norm2(point - xyz(:, i))
                        end do
                        positions(:, 1) = point
                        tangent(:, 1) = point_direction
                        probs = 0.0_wp
                        log_t = 0.0_wp
                        do i = 1, size(dist)
                           positions(:, 2) = xyz(:, i)
                           tangent(:, 2) = direction(:, i)
                           do j = 1, size(dist)
                              if (j == i) cycle
                              positions(:, 3) = xyz(:, j)
                              tangent(:, 3) = direction(:, j)
                              ! Coordinate order 1: elliptic
                              block
                                 real(wp) :: mu, r, a, unit(3, 3), mg(3)
                                 real(wp) :: c0

                                 g = 0.0_wp
                                 r = pair_r(j, i)
                                 a = pair_a(j, i)
                                 mu = max(-1.0_wp, min(1.0_wp, (dist(i) - dist(j))/r))
                                 nu = mu + a*(1.0_wp - mu*mu)
                                 if (abs(mu) < 1.0_wp) then
                                    unit = 0.0_wp
                                    if (dist(i) > 0.0_wp) unit(:, 1) = (positions(:, 1) - positions(:, 2))/dist(i)
                                    if (dist(j) > 0.0_wp) unit(:, 2) = (positions(:, 1) - positions(:, 3))/dist(j)
                                    unit(:, 3) = (positions(:, 2) - positions(:, 3))/r
                                    c0 = (1.0_wp/r)*(-1.0_wp + 2.0_wp*a*mu)
                                    mg(1) = -c0
                                    mg(2) = c0
                                    mg(3) = c0*mu
                                    g(:, 1) = mg(1)*unit(:, 1) + mg(2)*unit(:, 2)
                                    g(:, 2) = -mg(1)*unit(:, 1) + mg(3)*unit(:, 3)
                                    g(:, 3) = -mg(2)*unit(:, 2) - mg(3)*unit(:, 3)
                                 end if
                              end block
                              block
                                 real(wp) :: t

                                 s = 0.0_wp
                                 ds = 0.0_wp
                                 if (abs((nu/self%a)) >= 1.0_wp) then
                                    if ((nu/self%a) < 0.0_wp) s = 1.0_wp
                                 else
                                    t = 0.5_wp*(1.0_wp - abs((nu/self%a)))
                                    s = t**4*(35.0_wp + t*(-84.0_wp + t*(70.0_wp - 20.0_wp*t)))
                                    ds = 70.0_wp*t**3*(-1.0_wp + t)**3
                                    if ((nu/self%a) < 0.0_wp) then
                                       s = 1.0_wp - s
                                    end if
                                 end if
                                 ds = ds/self%a
                              end block
                              if (s <= 0.0_wp) then
                                 probs(i) = -huge(1.0_wp)
                                 log_t(i) = 0.0_wp
                                 exit
                              end if
                              probs(i) = probs(i) + log(s)
                              log_t(i) = log_t(i) + (ds/s)*sum(g*tangent)
                           end do
                        end do
                        if (probs(owner) == -huge(1.0_wp)) exit point_math
                        peak = maxval(probs)
                        probs = exp(probs - peak)
                        probs = probs/sum(probs)
                        q = seed*probs(owner)
                        qt = q*sum(probs*(log_t(owner) - log_t))
                        do i = 1, size(dist)
                           log_p_t = sum(probs*(log_t(i) - log_t))
                           alpha = -q*probs(i)
                           alpha_t = -qt*probs(i) - q*probs(i)*log_p_t
                           if (i == owner) then
                              beta = 0.0_wp
                              beta_t = 0.0_wp
                              do k = 1, size(dist)
                                 if (k == owner) cycle
                                 beta = beta + probs(k)
                                 beta_t = beta_t + probs(k)*sum(probs*(log_t(k) - log_t))
                              end do
                              alpha = q*beta
                              alpha_t = qt*beta + q*beta_t
                           end if
                           if (alpha == 0.0_wp .and. alpha_t == 0.0_wp) cycle
                           positions(:, 2) = xyz(:, i)
                           tangent(:, 2) = direction(:, i)
                           do j = 1, size(dist)
                              if (j == i) cycle
                              positions(:, 3) = xyz(:, j)
                              tangent(:, 3) = direction(:, j)
                              ! Coordinate order 2: elliptic
                              block
                                 real(wp) :: mu, r, a, unit(3, 3), mg(3)
                                 real(wp) :: unit_t(3, 3), delta(3, 3), metric_t(3), mh(3)
                                 integer :: c
                                 real(wp) :: c0, c1, c2, c3, c4, c5, c6

                                 g = 0.0_wp
                                 h = 0.0_wp
                                 r = pair_r(j, i)
                                 a = pair_a(j, i)
                                 mu = max(-1.0_wp, min(1.0_wp, (dist(i) - dist(j))/r))
                                 nu = mu + a*(1.0_wp - mu*mu)
                                 if (abs(mu) < 1.0_wp) then
                                    unit = 0.0_wp
                                    if (dist(i) > 0.0_wp) unit(:, 1) = (positions(:, 1) - positions(:, 2))/dist(i)
                                    if (dist(j) > 0.0_wp) unit(:, 2) = (positions(:, 1) - positions(:, 3))/dist(j)
                                    unit(:, 3) = (positions(:, 2) - positions(:, 3))/r
                                    unit_t = 0.0_wp
                                    delta(:, 1) = tangent(:, 1) - tangent(:, 2)
                                    delta(:, 2) = tangent(:, 1) - tangent(:, 3)
                                    delta(:, 3) = tangent(:, 2) - tangent(:, 3)
                                    do c = 1, 3
                                       metric_t(c) = dot_product(unit(:, c), delta(:, c))
                                    end do
                                    if (dist(i) > 0.0_wp) unit_t(:, 1) = (delta(:, 1) - unit(:, 1)*metric_t(1))/dist(i)
                                    if (dist(j) > 0.0_wp) unit_t(:, 2) = (delta(:, 2) - unit(:, 2)*metric_t(2))/dist(j)
                                    unit_t(:, 3) = (delta(:, 3) - unit(:, 3)*metric_t(3))/r
                                    c0 = 2.0_wp*a
                                    c1 = (1.0_wp/r)*(-1.0_wp + c0*mu)
                                    c2 = (1.0_wp/r**2)
                                    c3 = metric_t(3)*mu
                                    c4 = 4.0_wp*a
                                    c5 = c2*(metric_t(3) + c0*metric_t(1) - c0*metric_t(2) - c3*c4)
                                    c6 = c4*mu
                                    mg(1) = -c1
                                    mg(2) = c1
                                    mg(3) = c1*mu
                                    mh(1) = -c5
                                    mh(2) = c5
                                    mh(3) = c2*(metric_t(2) - metric_t(1) + 2.0_wp*c3 + c6*metric_t(1) - c6*metric_t(2) - &
                                       & 6.0_wp*metric_t(3)*a*mu**2)
                                    g(:, 1) = mg(1)*unit(:, 1) + mg(2)*unit(:, 2)
                                    g(:, 2) = -mg(1)*unit(:, 1) + mg(3)*unit(:, 3)
                                    g(:, 3) = -mg(2)*unit(:, 2) - mg(3)*unit(:, 3)
                                    h(:, 1) = mh(1)*unit(:, 1) + mg(1)*unit_t(:, 1) + mh(2)*unit(:, 2) + mg(2)*unit_t(:, 2)
                                    h(:, 2) = -mh(1)*unit(:, 1) - mg(1)*unit_t(:, 1) + mh(3)*unit(:, 3) + mg(3)*unit_t(:, 3)
                                    h(:, 3) = -mh(2)*unit(:, 2) - mg(2)*unit_t(:, 2) - mh(3)*unit(:, 3) - mg(3)*unit_t(:, 3)
                                 end if
                              end block
                              block
                                 real(wp) :: t, c0

                                 s = 0.0_wp
                                 ds = 0.0_wp
                                 d2s = 0.0_wp
                                 if (abs((nu/self%a)) >= 1.0_wp) then
                                    if ((nu/self%a) < 0.0_wp) s = 1.0_wp
                                 else
                                    t = 0.5_wp*(1.0_wp - abs((nu/self%a)))
                                    c0 = -1.0_wp + t
                                    s = t**4*(35.0_wp + t*(-84.0_wp + t*(70.0_wp - 20.0_wp*t)))
                                    ds = 70.0_wp*c0**3*t**3
                                    d2s = -105.0_wp*c0**2*t**2*(-1.0_wp + 2.0_wp*t)
                                    if ((nu/self%a) < 0.0_wp) then
                                       s = 1.0_wp - s
                                       d2s = -d2s
                                    end if
                                 end if
                                 ds = ds/self%a
                                 d2s = d2s/self%a**2
                              end block
                              if (s <= 0.0_wp) cycle
                              first = ds/s
                              second = d2s/s - first*first
                              nu_t = sum(g*tangent)
                              contribution = (alpha_t*first + alpha*second*nu_t)*g + alpha*first*h
                              point_hessian_vector = point_hessian_vector + contribution(:, 1)
                              hessian_vector(:, i) = hessian_vector(:, i) + contribution(:, 2)
                              hessian_vector(:, j) = hessian_vector(:, j) + contribution(:, 3)
                           end do
                        end do
                     end associate
                  end block point_math
               end if
               workers(:, owner, slot) = workers(:, owner, slot) + point_response
            end do
            !$omp end do
            !$omp single
            local_h(:, :, component, atom) = 0.0_wp
            do worker = 1, nt
               local_h(:, :, component, atom) = local_h(:, :, component, atom) + workers(:, :, worker)
            end do
            !$omp end single
         end do
      end do
      !$omp end parallel
      if (.not. all(ieee_is_finite(local_h))) then
         call fatal_error(error, "ssf grid: non-finite hessian contraction")
         return
      end if
      hessian = hessian + local_h
   end subroutine ssf_grid_hessian

   ! Self-contained paths with fused coordinate and switch algebra

   !> Owner weights from pair cells, normalized in log space to avoid product underflow
   !>
   !> - Unchecked shapes: points (3,npts), xyz (3,nat), numbers (nat), w (npts)
   !> - Valid owner, atomic numbers and switch parameters required
   !> - Default: size-adjusted elliptic coordinates, clipped to [-1,1]
   !> - Point threading suppressed inside an enclosing OpenMP team
   !>
   !> @param[in] self Configured partition scheme
   !> @param[in]  owner       Owner index in [1,nat]
   !> @param[in]  points      Sample points in bohr
   !> @param[in]  xyz         Atomic positions in bohr
   !> @param[in]  numbers     Atomic numbers
   !> @param[out] w           Normalized owner weights
   !> @param[in]  nthreads    Optional thread count; absent takes omp_get_max_threads
   subroutine ssf_owner_weights(self, owner, points, xyz, numbers, w, nthreads)
      !> Configured partition scheme
      class(ssf_partition_type), intent(in) :: self
      !> Owner index
      integer, intent(in) :: owner
      !> Sample points
      real(wp), intent(in) :: points(:, :)
      !> Atomic positions
      real(wp), intent(in) :: xyz(:, :)
      !> Atomic numbers
      integer, intent(in) :: numbers(:)
      !> Owner weights
      real(wp), intent(out) :: w(:)
      !> Thread count
      integer, intent(in), optional :: nthreads

      real(wp), allocatable :: pair_r(:, :), pair_a(:, :), dist(:), logs(:)
      real(wp) :: peak
      integer :: nat, npts, i, ip, nt

      nat = size(xyz, 2)
      npts = size(points, 2)
      if (npts == 0) return
      if (nat == 1) then
         w = 1.0_wp
         return
      end if
      allocate (pair_r(nat, nat), pair_a(nat, nat))
      block
         real(wp) :: radius(size(numbers))
         real(wp) :: chi, u
         integer :: ia, ja

         radius = covalent_rad(numbers)
         pair_r = 0.0_wp
         pair_a = 0.0_wp
         do ia = 1, size(numbers)
            do ja = 1, ia - 1
               pair_r(ja, ia) = norm2(xyz(:, ia) - xyz(:, ja))
               chi = radius(ia)/radius(ja)
               u = (chi - 1.0_wp)/(chi + 1.0_wp)
               pair_a(ja, ia) = max(-0.5_wp, min(0.5_wp, u/(u*u - 1.0_wp)))
               pair_r(ia, ja) = pair_r(ja, ia)
               pair_a(ia, ja) = -pair_a(ja, ia)
            end do
         end do
      end block

      nt = 1
!$    if (.not. omp_in_parallel()) then
!$       nt = omp_get_max_threads()
!$       if (present(nthreads)) then
!$          if (nthreads > 0) nt = nthreads
!$       end if
!$       nt = min(nt, npts)
!$    end if
      !$omp parallel num_threads(nt) default(none) &
      !$omp shared(owner, points, xyz, pair_r, pair_a, self, w, nat, npts) &
      !$omp private(ip, i, dist, logs, peak)
      allocate (dist(nat), logs(nat))
      !$omp do schedule(dynamic, 64)
      do ip = 1, npts
         dist = 0.0_wp
         do i = 1, nat
            dist(i) = norm2(points(:, ip) - xyz(:, i))
         end do
         logs(owner) = ssf_cell_log(owner, dist, pair_r, pair_a, self)
         if (logs(owner) == -huge(1.0_wp)) then
            w(ip) = 0.0_wp
            cycle
         end if
         do i = 1, nat
            if (i /= owner) then
               logs(i) = ssf_cell_log(i, dist, pair_r, pair_a, self)
            end if
         end do
         peak = maxval(logs)
         w(ip) = exp(logs(owner) - peak)/sum(exp(logs - peak))
      end do
      !$omp end do
      deallocate (dist, logs)
      !$omp end parallel

   end subroutine ssf_owner_weights
   !> Contract partition adjoints into point and fixed-point nuclear gradients
   !>
   !> - Log-space normalization shared with the forward pass
   !> - Caller supplies point motion; shapes and atomic numbers unchecked
   !>
   !> @param[in] self Configured partition scheme
   !> @param[in] owner Owner index in [1, nat]
   !> @param[in] points Sample positions (3, npts), bohr
   !> @param[in] xyz Nuclear positions (3, nat), bohr
   !> @param[in] numbers Atomic numbers (nat)
   !> @param[in] seed Owner-partition energy adjoints (npts)
   !> @param[in,out] gradient Nuclear-gradient accumulator (3, nat)
   !> @param[out] point_gradient Point-position adjoints (3, npts)
   !> @param[out] error Allocation failure
   !> @param[in] nthreads Optional worker count
   subroutine ssf_owner_gradient(self, owner, points, xyz, numbers, seed, gradient, point_gradient, &
      & error, nthreads)
      !> Configured partition scheme
      class(ssf_partition_type), intent(in) :: self
      !> Owner index
      integer, intent(in) :: owner
      !> Sample positions
      real(wp), intent(in) :: points(:, :)
      !> Nuclear positions
      real(wp), intent(in) :: xyz(:, :)
      !> Atomic numbers
      integer, intent(in) :: numbers(:)
      !> Owner-partition adjoints
      real(wp), intent(in) :: seed(:)
      !> Nuclear-gradient accumulator
      real(wp), intent(inout) :: gradient(:, :)
      !> Point-position adjoints
      real(wp), intent(out) :: point_gradient(:, :)
      !> Allocation failure
      type(error_type), allocatable, intent(out) :: error
      !> Worker count
      integer, intent(in), optional :: nthreads

      real(wp), allocatable :: pair_r(:, :), pair_a(:, :), dist(:, :), logs(:, :)
      real(wp), allocatable :: grad_threads(:, :, :)
      integer :: nat, npts, nt, thread_slot, ip, stat

      nat = size(numbers)
      npts = size(seed)
      point_gradient = 0.0_wp
      if (nat == 1 .or. npts == 0 .or. all(seed == 0.0_wp)) return
      nt = 1
!$    if (.not. omp_in_parallel()) then
!$       nt = omp_get_max_threads()
!$       if (present(nthreads)) then
!$          if (nthreads > 0) nt = nthreads
!$       end if
!$       nt = min(nt, npts)
!$    end if
      allocate (pair_r(nat, nat), stat=stat)
      if (stat == 0) allocate (pair_a(nat, nat), stat=stat)
      if (stat == 0) allocate (dist(nat, nt), stat=stat)
      if (stat == 0) allocate (logs(nat, nt), stat=stat)
      if (stat == 0) allocate (grad_threads(3, nat, nt), stat=stat)
      if (stat /= 0) then
         call fatal_error(error, "partition gradient: cannot allocate reverse scratch")
         return
      end if
      block
         real(wp) :: radius(size(numbers))
         real(wp) :: chi, u
         integer :: ia, ja

         radius = covalent_rad(numbers)
         pair_r = 0.0_wp
         pair_a = 0.0_wp
         do ia = 1, size(numbers)
            do ja = 1, ia - 1
               pair_r(ja, ia) = norm2(xyz(:, ia) - xyz(:, ja))
               chi = radius(ia)/radius(ja)
               u = (chi - 1.0_wp)/(chi + 1.0_wp)
               pair_a(ja, ia) = max(-0.5_wp, min(0.5_wp, u/(u*u - 1.0_wp)))
               pair_r(ia, ja) = pair_r(ja, ia)
               pair_a(ia, ja) = -pair_a(ja, ia)
            end do
         end do
      end block
      grad_threads = 0.0_wp
      !$omp parallel num_threads(nt) default(none) &
      !$omp shared(owner, points, xyz, seed, self, pair_r, pair_a, dist, logs, &
      !$omp grad_threads, point_gradient, npts) private(thread_slot, ip)
      thread_slot = 1
!$    thread_slot = omp_get_thread_num() + 1
      !$omp do schedule(static, 64)
      do ip = 1, npts
         if (seed(ip) == 0.0_wp) cycle
         call ssf_point_gradient(owner, points(:, ip), xyz, seed(ip), pair_r, pair_a, &
            & self, dist(:, thread_slot), logs(:, thread_slot), &
            & grad_threads(:, :, thread_slot), point_gradient(:, ip))
      end do
      !$omp end do
      !$omp end parallel
      do thread_slot = 1, nt
         gradient = gradient + grad_threads(:, :, thread_slot)
      end do
   end subroutine ssf_owner_gradient

   !> Directional derivative of the partition reverse contraction
   !>
   !> @param[in] self Configured partition scheme
   !> @param[in] owner Owner index in [1, nat]
   !> @param[in] points Sample positions (3, npts), bohr
   !> @param[in] xyz Nuclear positions (3, nat), bohr
   !> @param[in] numbers Atomic numbers (nat)
   !> @param[in] seed Fixed owner-partition adjoints (npts)
   !> @param[in] direction Nuclear displacement direction (3, nat)
   !> @param[in] point_direction Common point displacement direction (3)
   !> @param[in,out] hessian_vector Nuclear Hessian-vector accumulator (3, nat)
   !> @param[out] point_hessian_vector Point Hessian-vector contributions (3, npts)
   !> @param[out] error Allocation failure or coincident elliptic centers
   !> @param[in] nthreads Optional worker count
   subroutine ssf_owner_hessian_vector(self, owner, points, xyz, numbers, seed, direction, &
      & point_direction, hessian_vector, point_hessian_vector, error, nthreads)
      !> Configured partition scheme
      class(ssf_partition_type), intent(in) :: self
      !> Owner index
      integer, intent(in) :: owner
      !> Sample positions
      real(wp), intent(in) :: points(:, :)
      !> Nuclear positions
      real(wp), intent(in) :: xyz(:, :)
      !> Atomic numbers
      integer, intent(in) :: numbers(:)
      !> Fixed partition adjoints
      real(wp), intent(in) :: seed(:)
      !> Nuclear displacement direction
      real(wp), intent(in) :: direction(:, :)
      !> Common point displacement direction
      real(wp), intent(in) :: point_direction(:)
      !> Nuclear Hessian-vector accumulator
      real(wp), intent(inout) :: hessian_vector(:, :)
      !> Point Hessian-vector contributions
      real(wp), intent(out) :: point_hessian_vector(:, :)
      !> Invalid geometry or allocation failure
      type(error_type), allocatable, intent(out) :: error
      !> Worker count
      integer, intent(in), optional :: nthreads

      real(wp), allocatable :: pair_r(:, :), pair_a(:, :), dist(:, :), probs(:, :), log_t(:, :), workers(:, :, :)
      integer :: nat, npts, nt, slot, ip, i, j, stat

      nat = size(numbers)
      npts = size(seed)
      point_hessian_vector = 0.0_wp
      if (nat == 1 .or. npts == 0 .or. all(seed == 0.0_wp)) return
      nt = 1
!$    if (.not. omp_in_parallel()) then
!$       nt = omp_get_max_threads()
!$       if (present(nthreads)) then
!$          if (nthreads > 0) nt = nthreads
!$       end if
!$       nt = min(nt, npts)
!$    end if
      allocate (pair_r(nat, nat), stat=stat)
      if (stat == 0) allocate (pair_a(nat, nat), stat=stat)
      if (stat == 0) allocate (dist(nat, nt), stat=stat)
      if (stat == 0) allocate (probs(nat, nt), stat=stat)
      if (stat == 0) allocate (log_t(nat, nt), stat=stat)
      if (stat == 0) allocate (workers(3, nat, nt), stat=stat)
      if (stat /= 0) then
         call fatal_error(error, "partition Hessian: cannot allocate scratch")
         return
      end if
      block
         real(wp) :: radius(size(numbers))
         real(wp) :: chi, u
         integer :: ia, ja

         radius = covalent_rad(numbers)
         pair_r = 0.0_wp
         pair_a = 0.0_wp
         do ia = 1, size(numbers)
            do ja = 1, ia - 1
               pair_r(ja, ia) = norm2(xyz(:, ia) - xyz(:, ja))
               chi = radius(ia)/radius(ja)
               u = (chi - 1.0_wp)/(chi + 1.0_wp)
               pair_a(ja, ia) = max(-0.5_wp, min(0.5_wp, u/(u*u - 1.0_wp)))
               pair_r(ia, ja) = pair_r(ja, ia)
               pair_a(ia, ja) = -pair_a(ja, ia)
            end do
         end do
      end block
      do i = 1, nat
         do j = 1, i - 1
            if (pair_r(i, j) <= 0.0_wp) then
               call fatal_error(error, "partition Hessian: coincident elliptic centers are not differentiable")
               return
            end if
         end do
      end do
      workers = 0.0_wp
      !$omp parallel num_threads(nt) default(none) &
      !$omp shared(owner, points, xyz, seed, direction, point_direction, self, pair_r, pair_a, &
      !$omp dist, probs, log_t, workers, point_hessian_vector, npts) private(slot, ip)
      slot = 1
!$    slot = omp_get_thread_num() + 1
      !$omp do schedule(static, 64)
      do ip = 1, npts
         if (seed(ip) == 0.0_wp) cycle
         call ssf_point_hessian_vector(owner, points(:, ip), xyz, seed(ip), direction, point_direction, &
            & pair_r, pair_a, self, dist(:, slot), probs(:, slot), log_t(:, slot), &
            & workers(:, :, slot), point_hessian_vector(:, ip))
      end do
      !$omp end do
      !$omp end parallel
      do slot = 1, nt
         hessian_vector = hessian_vector + workers(:, :, slot)
      end do
   end subroutine ssf_owner_hessian_vector
   !> Forward-over-reverse normalized owner weight without per-point nuclear Jacobians
   !>
   !> @param[in] owner Owner index
   !> @param[in] point Sample position (3)
   !> @param[in] xyz Nuclear positions (3, nat)
   !> @param[in] seed Fixed partition adjoint
   !> @param[in] direction Nuclear tangent (3, nat)
   !> @param[in] point_direction Point tangent (3)
   !> @param[in] pair_r Pair distances (nat, nat)
   !> @param[in] pair_a Fixed pair adjustments (nat, nat)
   !> @param[in] cell Configured pair switch
   !> @param[out] dist Distance scratch (nat)
   !> @param[out] probs Normalized probability scratch (nat)
   !> @param[out] log_t Log-product tangent scratch (nat)
   !> @param[in,out] hessian_vector Explicit nuclear Hessian-vector accumulator (3, nat)
   !> @param[out] point_hessian_vector Point Hessian-vector contribution (3)
   pure subroutine ssf_point_hessian_vector(owner, point, xyz, seed, direction, point_direction, &
         & pair_r, pair_a, cell, dist, probs, log_t, hessian_vector, point_hessian_vector)
      !> Owner index
      integer, intent(in) :: owner
      !> Sample position
      real(wp), intent(in) :: point(3)
      !> Nuclear positions
      real(wp), intent(in) :: xyz(:, :)
      !> Fixed partition adjoint
      real(wp), intent(in) :: seed
      !> Nuclear tangent
      real(wp), intent(in) :: direction(:, :)
      !> Point tangent
      real(wp), intent(in) :: point_direction(:)
      !> Pair distances
      real(wp), intent(in) :: pair_r(:, :)
      !> Fixed pair adjustments
      real(wp), intent(in) :: pair_a(:, :)
      !> Configured pair switch
      type(ssf_partition_type), intent(in) :: cell
      !> Distance scratch
      real(wp), intent(out) :: dist(:)
      !> Normalized probabilities
      real(wp), intent(out) :: probs(:)
      !> Log-product tangents
      real(wp), intent(out) :: log_t(:)
      !> Explicit nuclear Hessian-vector accumulator
      real(wp), intent(inout) :: hessian_vector(:, :)
      !> Point Hessian-vector contribution
      real(wp), intent(out) :: point_hessian_vector(:)

      real(wp) :: positions(3, 3), tangent(3, 3), g(3, 3), h(3, 3), contribution(3, 3)
      real(wp) :: nu, nu_t, s, ds, d2s, peak, q, qt, alpha, alpha_t, log_p_t, first, second, beta, beta_t
      integer :: i, j, k

      point_hessian_vector = 0.0_wp
      dist = 0.0_wp
      do i = 1, size(dist)
         dist(i) = norm2(point - xyz(:, i))
      end do
      positions(:, 1) = point
      tangent(:, 1) = point_direction
      probs = 0.0_wp
      log_t = 0.0_wp
      do i = 1, size(dist)
         positions(:, 2) = xyz(:, i)
         tangent(:, 2) = direction(:, i)
         do j = 1, size(dist)
            if (j == i) cycle
            positions(:, 3) = xyz(:, j)
            tangent(:, 3) = direction(:, j)
            ! Coordinate order 1: elliptic
            block
               real(wp) :: mu, r, a, unit(3, 3), mg(3)
               real(wp) :: c0

               g = 0.0_wp
               r = pair_r(j, i)
               a = pair_a(j, i)
               mu = max(-1.0_wp, min(1.0_wp, (dist(i) - dist(j))/r))
               nu = mu + a*(1.0_wp - mu*mu)
               if (abs(mu) < 1.0_wp) then
                  unit = 0.0_wp
                  if (dist(i) > 0.0_wp) unit(:, 1) = (positions(:, 1) - positions(:, 2))/dist(i)
                  if (dist(j) > 0.0_wp) unit(:, 2) = (positions(:, 1) - positions(:, 3))/dist(j)
                  unit(:, 3) = (positions(:, 2) - positions(:, 3))/r
                  c0 = (1.0_wp/r)*(-1.0_wp + 2.0_wp*a*mu)
                  mg(1) = -c0
                  mg(2) = c0
                  mg(3) = c0*mu
                  g(:, 1) = mg(1)*unit(:, 1) + mg(2)*unit(:, 2)
                  g(:, 2) = -mg(1)*unit(:, 1) + mg(3)*unit(:, 3)
                  g(:, 3) = -mg(2)*unit(:, 2) - mg(3)*unit(:, 3)
               end if
            end block
            block
               real(wp) :: t

               s = 0.0_wp
               ds = 0.0_wp
               if (abs((nu/cell%a)) >= 1.0_wp) then
                  if ((nu/cell%a) < 0.0_wp) s = 1.0_wp
               else
                  t = 0.5_wp*(1.0_wp - abs((nu/cell%a)))
                  s = t**4*(35.0_wp + t*(-84.0_wp + t*(70.0_wp - 20.0_wp*t)))
                  ds = 70.0_wp*t**3*(-1.0_wp + t)**3
                  if ((nu/cell%a) < 0.0_wp) then
                     s = 1.0_wp - s
                  end if
               end if
               ds = ds/cell%a
            end block
            if (s <= 0.0_wp) then
               probs(i) = -huge(1.0_wp)
               log_t(i) = 0.0_wp
               exit
            end if
            probs(i) = probs(i) + log(s)
            log_t(i) = log_t(i) + (ds/s)*sum(g*tangent)
         end do
      end do
      if (probs(owner) == -huge(1.0_wp)) return
      peak = maxval(probs)
      probs = exp(probs - peak)
      probs = probs/sum(probs)
      q = seed*probs(owner)
      qt = q*sum(probs*(log_t(owner) - log_t))
      do i = 1, size(dist)
         log_p_t = sum(probs*(log_t(i) - log_t))
         alpha = -q*probs(i)
         alpha_t = -qt*probs(i) - q*probs(i)*log_p_t
         if (i == owner) then
            beta = 0.0_wp
            beta_t = 0.0_wp
            do k = 1, size(dist)
               if (k == owner) cycle
               beta = beta + probs(k)
               beta_t = beta_t + probs(k)*sum(probs*(log_t(k) - log_t))
            end do
            alpha = q*beta
            alpha_t = qt*beta + q*beta_t
         end if
         if (alpha == 0.0_wp .and. alpha_t == 0.0_wp) cycle
         positions(:, 2) = xyz(:, i)
         tangent(:, 2) = direction(:, i)
         do j = 1, size(dist)
            if (j == i) cycle
            positions(:, 3) = xyz(:, j)
            tangent(:, 3) = direction(:, j)
            ! Coordinate order 2: elliptic
            block
               real(wp) :: mu, r, a, unit(3, 3), mg(3)
               real(wp) :: unit_t(3, 3), delta(3, 3), metric_t(3), mh(3)
               integer :: c
               real(wp) :: c0, c1, c2, c3, c4, c5, c6

               g = 0.0_wp
               h = 0.0_wp
               r = pair_r(j, i)
               a = pair_a(j, i)
               mu = max(-1.0_wp, min(1.0_wp, (dist(i) - dist(j))/r))
               nu = mu + a*(1.0_wp - mu*mu)
               if (abs(mu) < 1.0_wp) then
                  unit = 0.0_wp
                  if (dist(i) > 0.0_wp) unit(:, 1) = (positions(:, 1) - positions(:, 2))/dist(i)
                  if (dist(j) > 0.0_wp) unit(:, 2) = (positions(:, 1) - positions(:, 3))/dist(j)
                  unit(:, 3) = (positions(:, 2) - positions(:, 3))/r
                  unit_t = 0.0_wp
                  delta(:, 1) = tangent(:, 1) - tangent(:, 2)
                  delta(:, 2) = tangent(:, 1) - tangent(:, 3)
                  delta(:, 3) = tangent(:, 2) - tangent(:, 3)
                  do c = 1, 3
                     metric_t(c) = dot_product(unit(:, c), delta(:, c))
                  end do
                  if (dist(i) > 0.0_wp) unit_t(:, 1) = (delta(:, 1) - unit(:, 1)*metric_t(1))/dist(i)
                  if (dist(j) > 0.0_wp) unit_t(:, 2) = (delta(:, 2) - unit(:, 2)*metric_t(2))/dist(j)
                  unit_t(:, 3) = (delta(:, 3) - unit(:, 3)*metric_t(3))/r
                  c0 = 2.0_wp*a
                  c1 = (1.0_wp/r)*(-1.0_wp + c0*mu)
                  c2 = (1.0_wp/r**2)
                  c3 = metric_t(3)*mu
                  c4 = 4.0_wp*a
                  c5 = c2*(metric_t(3) + c0*metric_t(1) - c0*metric_t(2) - c3*c4)
                  c6 = c4*mu
                  mg(1) = -c1
                  mg(2) = c1
                  mg(3) = c1*mu
                  mh(1) = -c5
                  mh(2) = c5
                  mh(3) = c2*(metric_t(2) - metric_t(1) + 2.0_wp*c3 + c6*metric_t(1) - c6*metric_t(2) - &
                     & 6.0_wp*metric_t(3)*a*mu**2)
                  g(:, 1) = mg(1)*unit(:, 1) + mg(2)*unit(:, 2)
                  g(:, 2) = -mg(1)*unit(:, 1) + mg(3)*unit(:, 3)
                  g(:, 3) = -mg(2)*unit(:, 2) - mg(3)*unit(:, 3)
                  h(:, 1) = mh(1)*unit(:, 1) + mg(1)*unit_t(:, 1) + mh(2)*unit(:, 2) + mg(2)*unit_t(:, 2)
                  h(:, 2) = -mh(1)*unit(:, 1) - mg(1)*unit_t(:, 1) + mh(3)*unit(:, 3) + mg(3)*unit_t(:, 3)
                  h(:, 3) = -mh(2)*unit(:, 2) - mg(2)*unit_t(:, 2) - mh(3)*unit(:, 3) - mg(3)*unit_t(:, 3)
               end if
            end block
            block
               real(wp) :: t, c0

               s = 0.0_wp
               ds = 0.0_wp
               d2s = 0.0_wp
               if (abs((nu/cell%a)) >= 1.0_wp) then
                  if ((nu/cell%a) < 0.0_wp) s = 1.0_wp
               else
                  t = 0.5_wp*(1.0_wp - abs((nu/cell%a)))
                  c0 = -1.0_wp + t
                  s = t**4*(35.0_wp + t*(-84.0_wp + t*(70.0_wp - 20.0_wp*t)))
                  ds = 70.0_wp*c0**3*t**3
                  d2s = -105.0_wp*c0**2*t**2*(-1.0_wp + 2.0_wp*t)
                  if ((nu/cell%a) < 0.0_wp) then
                     s = 1.0_wp - s
                     d2s = -d2s
                  end if
               end if
               ds = ds/cell%a
               d2s = d2s/cell%a**2
            end block
            if (s <= 0.0_wp) cycle
            first = ds/s
            second = d2s/s - first*first
            nu_t = sum(g*tangent)
            contribution = (alpha_t*first + alpha*second*nu_t)*g + alpha*first*h
            point_hessian_vector = point_hessian_vector + contribution(:, 1)
            hessian_vector(:, i) = hessian_vector(:, i) + contribution(:, 2)
            hessian_vector(:, j) = hessian_vector(:, j) + contribution(:, 3)
         end do
      end do
   end subroutine ssf_point_hessian_vector

   !> Reverse one normalized owner weight without a nuclear Jacobian
   !>
   !> @param[in] owner Owner index
   !> @param[in] point Sample position (3), bohr
   !> @param[in] xyz Nuclear positions (3, nat), bohr
   !> @param[in] seed Owner-partition adjoint
   !> @param[in] pair_r Pair distances (nat, nat), bohr
   !> @param[in] pair_a Fixed pair size adjustments
   !> @param[in] cell Pair-cell switch
   !> @param[out] dist Point-to-nucleus distance scratch (nat)
   !> @param[out] probs Normalized cell-product scratch (nat)
   !> @param[in,out] gradient Explicit nuclear-gradient accumulator (3, nat)
   !> @param[out] point_gradient Point-position adjoint (3)
   pure subroutine ssf_point_gradient(owner, point, xyz, seed, pair_r, pair_a, &
         & cell, dist, probs, gradient, point_gradient)
      !> Owner index
      integer, intent(in) :: owner
      !> Sample position
      real(wp), intent(in) :: point(3)
      !> Nuclear positions
      real(wp), intent(in) :: xyz(:, :)
      !> Owner-partition adjoint
      real(wp), intent(in) :: seed
      !> Pair distances
      real(wp), intent(in) :: pair_r(:, :)
      !> Fixed pair adjustments
      real(wp), intent(in) :: pair_a(:, :)
      !> Pair-cell switch
      type(ssf_partition_type), intent(in) :: cell
      !> Distance scratch
      real(wp), intent(out) :: dist(:)
      !> Normalized cell products
      real(wp), intent(out) :: probs(:)
      !> Explicit nuclear-gradient accumulator
      real(wp), intent(inout) :: gradient(:, :)
      !> Point-position adjoint
      real(wp), intent(out) :: point_gradient(:)

      real(wp) :: peak, owner_seed, log_seed, mu, nu, s, ds, factor
      real(wp) :: ui(3), uj(3), axis(3)
      integer :: i, j

      point_gradient = 0.0_wp
      dist = 0.0_wp
      do i = 1, size(dist)
         dist(i) = norm2(point - xyz(:, i))
      end do
      do i = 1, size(dist)
         probs(i) = ssf_cell_log(i, dist, pair_r, pair_a, cell)
      end do
      if (probs(owner) == -huge(1.0_wp)) return
      peak = maxval(probs)
      probs = exp(probs - peak)
      probs = probs/sum(probs)
      owner_seed = seed*probs(owner)
      do i = 1, size(dist)
         log_seed = -owner_seed*probs(i)
         if (i == owner) then
            ! Sum other probabilities to retain derivatives of tiny partition tails
            log_seed = owner_seed*(sum(probs(:i - 1)) + sum(probs(i + 1:)))
         end if
         if (log_seed == 0.0_wp) cycle
         do j = 1, size(dist)
            if (j == i) cycle
            if (pair_r(j, i) <= 0.0_wp) cycle
            mu = max(-1.0_wp, min(1.0_wp, (dist(i) - dist(j))/pair_r(j, i)))
            nu = mu + pair_a(j, i)*(1.0_wp - mu*mu)
            block
               real(wp) :: t

               s = 0.0_wp
               ds = 0.0_wp
               if (abs((nu/cell%a)) >= 1.0_wp) then
                  if ((nu/cell%a) < 0.0_wp) s = 1.0_wp
               else
                  t = 0.5_wp*(1.0_wp - abs((nu/cell%a)))
                  s = t**4*(35.0_wp + t*(-84.0_wp + t*(70.0_wp - 20.0_wp*t)))
                  ds = 70.0_wp*t**3*(-1.0_wp + t)**3
                  if ((nu/cell%a) < 0.0_wp) then
                     s = 1.0_wp - s
                  end if
               end if
               ds = ds/cell%a
            end block
            if (s <= 0.0_wp .or. ds == 0.0_wp) cycle
            factor = (log_seed/s)*ds
            if (abs(mu) >= 1.0_wp) cycle
            factor = factor*(1.0_wp - 2.0_wp*pair_a(j, i)*mu)/pair_r(j, i)
            ui = 0.0_wp
            uj = 0.0_wp
            if (dist(i) > 0.0_wp) ui = (point - xyz(:, i))/dist(i)
            if (dist(j) > 0.0_wp) uj = (point - xyz(:, j))/dist(j)
            axis = (xyz(:, i) - xyz(:, j))/pair_r(j, i)
            point_gradient = point_gradient + factor*(ui - uj)
            gradient(:, i) = gradient(:, i) - factor*(ui + mu*axis)
            gradient(:, j) = gradient(:, j) + factor*(uj + mu*axis)
         end do
      end do
   end subroutine ssf_point_gradient

   !> Logarithm of one cell product
   !>
   !> @param[in] ia      Atom index
   !> @param[in] dist    Point-to-atom distances in bohr, shape (nat)
   !> @param[in] pair_r  Pair distances in bohr, shape (nat,nat)
   !> @param[in] pair_a  Pair size adjustments or power offsets, shape (nat,nat)
   !> @param[in] cell    Pair-cell switch
   pure function ssf_cell_log(ia, dist, pair_r, pair_a, cell) result(value)
      !> Atom index
      integer, intent(in) :: ia
      !> Point-to-atom distances
      real(wp), intent(in) :: dist(:)
      !> Pair distances
      real(wp), intent(in) :: pair_r(:, :)
      !> Pair size adjustments or power offsets
      real(wp), intent(in) :: pair_a(:, :)
      !> Pair-cell switch
      type(ssf_partition_type), intent(in) :: cell
      !> Log cell product or -huge for zero
      real(wp) :: value

      integer :: ja
      real(wp) :: mu, nu, s

      value = 0.0_wp
      do ja = 1, size(dist)
         if (ja == ia) cycle
         if (pair_r(ja, ia) <= 0.0_wp) cycle
         mu = max(-1.0_wp, min(1.0_wp, (dist(ia) - dist(ja))/pair_r(ja, ia)))
         nu = mu + pair_a(ja, ia)*(1.0_wp - mu*mu)
         block
            real(wp) :: t

            s = 0.0_wp
            if (abs((nu/cell%a)) >= 1.0_wp) then
               if ((nu/cell%a) < 0.0_wp) s = 1.0_wp
            else
               t = 0.5_wp*(1.0_wp - abs((nu/cell%a)))
               s = t**4*(35.0_wp + t*(-84.0_wp + t*(70.0_wp - 20.0_wp*t)))
               if ((nu/cell%a) < 0.0_wp) then
                  s = 1.0_wp - s
               end if
            end if
         end block
         if (s <= 0.0_wp) then
            value = -huge(1.0_wp)
            return
         end if
         value = value + log(s)
      end do
   end function ssf_cell_log

end module moist_math_grid_3d_kernel_ssf
