!> Low-level CFC (COSMO Fine Cavity) pseudo-density kernel; AUTO-GENERATED by codegen_cfc_kernel.py
module moist_cavity_drop_lsf_cfc_kernel
   use mctc_env_accuracy, only: wp
   implicit none
   private

   public :: cfc_atomic_term_eval
   public :: cfc_pair_term_eval
   public :: cfc_log_lift

contains

   !> Accumulate one atom's contribution to PD and its derivatives.
   !>
   !> Computes exp(a1 * (s_a - 1)) with s_a = ||d_a|| / R_a and adds
   !> the value plus d^k_r PD (k = 1..max_deriv) into the supplied
   !> accumulators. The orchestrator (cfc.f90) is expected to zero
   !> the accumulators once per evaluation point and then call this
   !> routine for every atom.
   !>
   !> All derivatives are taken w.r.t. the field point r; since the
   !> expression depends on r only through d_a = r - r_a, gradients
   !> w.r.t. r and w.r.t. d_a coincide.
   !>
   !> @param[in]    d_a       Displacement r - r_a [3]
   !> @param[in]    R_a       Atom radius
   !> @param[in]    a1        Atomic-term exponent prefactor
   !> @param[in]    max_deriv Maximum derivative order (0..3)
   !> @param[inout] pd0       Pseudo-density accumulator
   !> @param[inout] pd1_r     d_i PD accumulator [3]
   !> @param[inout] pd2_rr    d_ij PD accumulator [3,3]
   !> @param[inout] pd3_rrr   d_ijk PD accumulator [3,3,3]
   pure subroutine cfc_atomic_term_eval(d_a, R_a, a1, max_deriv, pd0, pd1_r, pd2_rr, pd3_rrr)
      !> Displacement r - r_a [ndim]
      real(wp), intent(in) :: d_a(3)
      !> Atom radius R_a
      real(wp), intent(in) :: R_a
      !> Atomic-term exponent prefactor a1 (Klamt 2018: -15)
      real(wp), intent(in) :: a1
      !> Maximum derivative order to accumulate (0..3)
      integer, intent(in) :: max_deriv
      !> Pseudo-density value accumulator
      real(wp), intent(inout) :: pd0
      !> First-derivative accumulator d_i PD
      real(wp), intent(inout) :: pd1_r(3)
      !> Hessian accumulator d_ij PD (symmetric)
      real(wp), intent(inout) :: pd2_rr(3, 3)
      !> Third-derivative accumulator d_ijk PD (fully symmetric)
      real(wp), intent(inout) :: pd3_rrr(3, 3, 3)

      real(wp) :: t_d3_000, t_d3_001, t_d3_002, t_d3_011, t_d3_012, t_d3_022
      real(wp) :: t_d3_111, t_d3_112, t_d3_122, t_d3_222, x0, x1
      real(wp) :: x10, x11, x12, x13, x14, x15
      real(wp) :: x16, x17, x18, x19, x2, x20
      real(wp) :: x21, x22, x23, x24, x25, x26
      real(wp) :: x27, x28, x29, x3, x30, x31
      real(wp) :: x32, x4, x5, x6, x7, x8
      real(wp) :: x9

      if (max_deriv == 0) then
         pd0 = pd0 + (exp(-a1*(1.0d0 - sqrt((d_a(1)*d_a(1)) + (d_a(2)*d_a(2)) + (d_a(3)*d_a(3)))/R_a)))
      end if
      if (max_deriv == 1) then
         x0 = 1d0/R_a
         x1 = sqrt((d_a(1)*d_a(1)) + (d_a(2)*d_a(2)) + (d_a(3)*d_a(3)))
         x2 = exp(-a1*(-x0*x1 + 1.0d0))
         x3 = a1*x0*x2/x1
         pd0 = pd0 + (x2)
         pd1_r(1) = pd1_r(1) + (d_a(1)*x3)
         pd1_r(2) = pd1_r(2) + (d_a(2)*x3)
         pd1_r(3) = pd1_r(3) + (d_a(3)*x3)
      end if
      if (max_deriv == 2) then
         x0 = 1d0/R_a
         x1 = (d_a(1)*d_a(1))
         x2 = (d_a(2)*d_a(2))
         x3 = (d_a(3)*d_a(3))
         x4 = x1 + x2 + x3
         x5 = sqrt(x4)
         x6 = exp(-a1*(-x0*x5 + 1.0d0))
         x7 = 1d0/x5
         x8 = a1*x0
         x9 = x6*x8
         x10 = x7*x9
         x11 = x4**(-3.0d0/2.0d0)
         x12 = 1d0/x4
         x13 = x12*x8
         x14 = a1*x0*x12 - x11
         x15 = d_a(1)*x14*x9
         pd0 = pd0 + (x6)
         pd1_r(1) = pd1_r(1) + (d_a(1)*x10)
         pd1_r(2) = pd1_r(2) + (d_a(2)*x10)
         pd1_r(3) = pd1_r(3) + (d_a(3)*x10)
         pd2_rr(1, 1) = pd2_rr(1, 1) + (x9*(-x1*x11 + x1*x13 + x7))
         pd2_rr(1, 2) = pd2_rr(1, 2) + (d_a(2)*x15)
         pd2_rr(2, 1) = pd2_rr(2, 1) + (d_a(2)*x15)
         pd2_rr(1, 3) = pd2_rr(1, 3) + (d_a(3)*x15)
         pd2_rr(3, 1) = pd2_rr(3, 1) + (d_a(3)*x15)
         pd2_rr(2, 2) = pd2_rr(2, 2) + (x9*(-x11*x2 + x13*x2 + x7))
         pd2_rr(2, 3) = pd2_rr(2, 3) + (d_a(2)*d_a(3)*x14*x9)
         pd2_rr(3, 2) = pd2_rr(3, 2) + (d_a(2)*d_a(3)*x14*x9)
         pd2_rr(3, 3) = pd2_rr(3, 3) + (x9*(-x11*x3 + x13*x3 + x7))
      end if
      if (max_deriv == 3) then
         x0 = 1d0/R_a
         x1 = (d_a(1)*d_a(1))
         x2 = (d_a(2)*d_a(2))
         x3 = (d_a(3)*d_a(3))
         x4 = x1 + x2 + x3
         x5 = sqrt(x4)
         x6 = exp(-a1*(-x0*x5 + 1.0d0))
         x7 = 1d0/x5
         x8 = a1*x0
         x9 = x6*x8
         x10 = x7*x9
         x11 = x4**(-3.0d0/2.0d0)
         x12 = x1*x11
         x13 = 1d0/x4
         x14 = x13*x8
         x15 = a1*x0*x13 - x11
         x16 = d_a(1)*x9
         x17 = x15*x16
         x18 = x11*x2
         x19 = d_a(2)*x9
         x20 = x11*x3
         x21 = -3*x11 + 3*x14
         x22 = 3/x4**(5.0d0/2.0d0)
         x23 = (a1*a1)/(R_a*R_a)
         x24 = 3*x8/(x4*x4)
         x25 = x1*x22 - x1*x24 + x12*x23
         x26 = -x11 + x14
         x27 = x9*(x25 + x26)
         x28 = x18*x23 + x2*x22 - x2*x24
         x29 = x26 + x28
         x30 = x20*x23 + x22*x3 - x24*x3
         x31 = x26 + x30
         x32 = d_a(3)*x9
         pd0 = pd0 + (x6)
         pd1_r(1) = pd1_r(1) + (d_a(1)*x10)
         pd1_r(2) = pd1_r(2) + (d_a(2)*x10)
         pd1_r(3) = pd1_r(3) + (d_a(3)*x10)
         pd2_rr(1, 1) = pd2_rr(1, 1) + (x9*(x1*x14 - x12 + x7))
         pd2_rr(1, 2) = pd2_rr(1, 2) + (d_a(2)*x17)
         pd2_rr(2, 1) = pd2_rr(2, 1) + (d_a(2)*x17)
         pd2_rr(1, 3) = pd2_rr(1, 3) + (d_a(3)*x17)
         pd2_rr(3, 1) = pd2_rr(3, 1) + (d_a(3)*x17)
         pd2_rr(2, 2) = pd2_rr(2, 2) + (x9*(x14*x2 - x18 + x7))
         pd2_rr(2, 3) = pd2_rr(2, 3) + (d_a(3)*x15*x19)
         pd2_rr(3, 2) = pd2_rr(3, 2) + (d_a(3)*x15*x19)
         pd2_rr(3, 3) = pd2_rr(3, 3) + (x9*(x14*x3 - x20 + x7))
         t_d3_000 = (x16*(x21 + x25))
         pd3_rrr(1, 1, 1) = pd3_rrr(1, 1, 1) + t_d3_000
         t_d3_001 = (d_a(2)*x27)
         pd3_rrr(1, 1, 2) = pd3_rrr(1, 1, 2) + t_d3_001
         pd3_rrr(1, 2, 1) = pd3_rrr(1, 2, 1) + t_d3_001
         pd3_rrr(2, 1, 1) = pd3_rrr(2, 1, 1) + t_d3_001
         t_d3_002 = (d_a(3)*x27)
         pd3_rrr(1, 1, 3) = pd3_rrr(1, 1, 3) + t_d3_002
         pd3_rrr(1, 3, 1) = pd3_rrr(1, 3, 1) + t_d3_002
         pd3_rrr(3, 1, 1) = pd3_rrr(3, 1, 1) + t_d3_002
         t_d3_011 = (x16*x29)
         pd3_rrr(1, 2, 2) = pd3_rrr(1, 2, 2) + t_d3_011
         pd3_rrr(2, 1, 2) = pd3_rrr(2, 1, 2) + t_d3_011
         pd3_rrr(2, 2, 1) = pd3_rrr(2, 2, 1) + t_d3_011
         t_d3_012 = (d_a(2)*d_a(3)*x16*(x11*x23 + x22 - x24))
         pd3_rrr(1, 2, 3) = pd3_rrr(1, 2, 3) + t_d3_012
         pd3_rrr(1, 3, 2) = pd3_rrr(1, 3, 2) + t_d3_012
         pd3_rrr(2, 1, 3) = pd3_rrr(2, 1, 3) + t_d3_012
         pd3_rrr(2, 3, 1) = pd3_rrr(2, 3, 1) + t_d3_012
         pd3_rrr(3, 1, 2) = pd3_rrr(3, 1, 2) + t_d3_012
         pd3_rrr(3, 2, 1) = pd3_rrr(3, 2, 1) + t_d3_012
         t_d3_022 = (x16*x31)
         pd3_rrr(1, 3, 3) = pd3_rrr(1, 3, 3) + t_d3_022
         pd3_rrr(3, 1, 3) = pd3_rrr(3, 1, 3) + t_d3_022
         pd3_rrr(3, 3, 1) = pd3_rrr(3, 3, 1) + t_d3_022
         t_d3_111 = (x19*(x21 + x28))
         pd3_rrr(2, 2, 2) = pd3_rrr(2, 2, 2) + t_d3_111
         t_d3_112 = (x29*x32)
         pd3_rrr(2, 2, 3) = pd3_rrr(2, 2, 3) + t_d3_112
         pd3_rrr(2, 3, 2) = pd3_rrr(2, 3, 2) + t_d3_112
         pd3_rrr(3, 2, 2) = pd3_rrr(3, 2, 2) + t_d3_112
         t_d3_122 = (x19*x31)
         pd3_rrr(2, 3, 3) = pd3_rrr(2, 3, 3) + t_d3_122
         pd3_rrr(3, 2, 3) = pd3_rrr(3, 2, 3) + t_d3_122
         pd3_rrr(3, 3, 2) = pd3_rrr(3, 3, 2) + t_d3_122
         t_d3_222 = (x32*(x21 + x30))
         pd3_rrr(3, 3, 3) = pd3_rrr(3, 3, 3) + t_d3_222
      end if
   end subroutine cfc_atomic_term_eval

   !> Accumulate one pair's contribution to PD with per-d-vector
   !> derivative splits.
   !>
   !> Computes c (1 - s_a.s_b)^m exp(a2 (s_a + s_b - 2)) with m = 4
   !> baked into the symbolic differentiation, and accumulates the
   !> value together with derivatives taken separately w.r.t. the two
   !> displacement vectors d_a = r - r_a and d_b = r - r_b. The
   !> orchestrator (cfc.f90) recovers spatial-r and atom-position
   !> tensors from these via
   !>    dK/dr_i           = pd1_a_i + pd1_b_i
   !>    d^2K/dr_i dr_j    = pd2_aa_ij + pd2_bb_ij + pd2_ab_ij
   !>                        + pd2_ab_ji
   !>    d^3K/dr_i dr_j dr_k = pd3_aaa_ijk + pd3_bbb_ijk
   !>                        + 3*sym(pd3_aab) + 3*sym(pd3_abb)
   !> and dK/dr_A = -pd1_a, dK/dr_B = -pd1_b (analogous for higher
   !> orders).
   !>
   !> Index symmetries (caller-relevant):
   !>   pd2_aa, pd2_bb           : symmetric in (i, j)
   !>   pd2_ab                   : NOT symmetric; broadcast 9 entries
   !>   pd3_aaa, pd3_bbb         : fully symmetric in (i, j, k)
   !>   pd3_aab                  : symmetric in first two indices
   !>   pd3_abb                  : symmetric in last two indices
   !>
   !> @param[in]    d_a       Displacement r - r_a [3]
   !> @param[in]    d_b       Displacement r - r_b [3]
   !> @param[in]    R_a       Radius of atom a
   !> @param[in]    R_b       Radius of atom b
   !> @param[in]    a2        Pair-term exponent prefactor
   !> @param[in]    c_par     Pair-term coupling constant
   !> @param[in]    max_deriv Maximum derivative order (0..3)
   !> @param[inout] pd0       Pseudo-density accumulator
   !> @param[inout] pd1_a     dK/d(d_a)_i accumulator [3]
   !> @param[inout] pd1_b     dK/d(d_b)_i accumulator [3]
   !> @param[inout] pd2_aa    d^2K/d(d_a)_i d(d_a)_j accumulator [3,3]
   !> @param[inout] pd2_ab    d^2K/d(d_a)_i d(d_b)_j accumulator [3,3]
   !> @param[inout] pd2_bb    d^2K/d(d_b)_i d(d_b)_j accumulator [3,3]
   !> @param[inout] pd3_aaa   d^3K/d(d_a)^3 accumulator [3,3,3]
   !> @param[inout] pd3_aab   d^3K/d(d_a)_i d(d_a)_j d(d_b)_k [3,3,3]
   !> @param[inout] pd3_abb   d^3K/d(d_a)_i d(d_b)_j d(d_b)_k [3,3,3]
   !> @param[inout] pd3_bbb   d^3K/d(d_b)^3 accumulator [3,3,3]
   pure subroutine cfc_pair_term_eval(d_a, d_b, R_a, R_b, a2, c_par, &
                                      max_deriv, pd0, pd1_a, pd1_b, pd2_aa, pd2_ab, pd2_bb, &
                                      pd3_aaa, pd3_aab, pd3_abb, pd3_bbb)
      !> Displacement r - r_a [ndim]
      real(wp), intent(in) :: d_a(3)
      !> Displacement r - r_b [ndim]
      real(wp), intent(in) :: d_b(3)
      !> Radius of atom a
      real(wp), intent(in) :: R_a
      !> Radius of atom b
      real(wp), intent(in) :: R_b
      !> Pair-term exponent prefactor a2 (Klamt 2018: -9)
      real(wp), intent(in) :: a2
      !> Pair-term coupling constant c (Klamt 2018: 5)
      real(wp), intent(in) :: c_par
      !> Maximum derivative order to accumulate (0..3)
      integer, intent(in) :: max_deriv
      !> Pseudo-density value accumulator
      real(wp), intent(inout) :: pd0
      !> First-derivative accumulator dK/d(d_a)_i
      real(wp), intent(inout) :: pd1_a(3)
      !> First-derivative accumulator dK/d(d_b)_i
      real(wp), intent(inout) :: pd1_b(3)
      !> Second-derivative accumulator d^2K/d(d_a)_i d(d_a)_j (symmetric in i,j)
      real(wp), intent(inout) :: pd2_aa(3, 3)
      !> Second-derivative accumulator d^2K/d(d_a)_i d(d_b)_j (NOT symmetric)
      real(wp), intent(inout) :: pd2_ab(3, 3)
      !> Second-derivative accumulator d^2K/d(d_b)_i d(d_b)_j (symmetric in i,j)
      real(wp), intent(inout) :: pd2_bb(3, 3)
      !> Third-derivative accumulator d^3K/d(d_a)^3 (fully symmetric in i,j,k)
      real(wp), intent(inout) :: pd3_aaa(3, 3, 3)
      !> Third-derivative accumulator d^3K/d(d_a)_i d(d_a)_j d(d_b)_k (symmetric in i,j)
      real(wp), intent(inout) :: pd3_aab(3, 3, 3)
      !> Third-derivative accumulator d^3K/d(d_a)_i d(d_b)_j d(d_b)_k (symmetric in j,k)
      real(wp), intent(inout) :: pd3_abb(3, 3, 3)
      !> Third-derivative accumulator d^3K/d(d_b)^3 (fully symmetric in i,j,k)
      real(wp), intent(inout) :: pd3_bbb(3, 3, 3)

      real(wp) :: t2aa_00, t2aa_01, t2aa_02, t2aa_11, t2aa_12, t2aa_22
      real(wp) :: t2bb_00, t2bb_01, t2bb_02, t2bb_11, t2bb_12, t2bb_22
      real(wp) :: t3aaa_000, t3aaa_001, t3aaa_002, t3aaa_011, t3aaa_012, t3aaa_022
      real(wp) :: t3aaa_111, t3aaa_112, t3aaa_122, t3aaa_222, t3aab_000, t3aab_001
      real(wp) :: t3aab_002, t3aab_010, t3aab_011, t3aab_012, t3aab_020, t3aab_021
      real(wp) :: t3aab_022, t3aab_110, t3aab_111, t3aab_112, t3aab_120, t3aab_121
      real(wp) :: t3aab_122, t3aab_220, t3aab_221, t3aab_222, t3abb_000, t3abb_001
      real(wp) :: t3abb_002, t3abb_011, t3abb_012, t3abb_022, t3abb_100, t3abb_101
      real(wp) :: t3abb_102, t3abb_111, t3abb_112, t3abb_122, t3abb_200, t3abb_201
      real(wp) :: t3abb_202, t3abb_211, t3abb_212, t3abb_222, t3bbb_000, t3bbb_001
      real(wp) :: t3bbb_002, t3bbb_011, t3bbb_012, t3bbb_022, t3bbb_111, t3bbb_112
      real(wp) :: t3bbb_122, t3bbb_222, x0, x1, x10, x100
      real(wp) :: x101, x102, x103, x104, x105, x106
      real(wp) :: x107, x108, x109, x11, x110, x111
      real(wp) :: x112, x113, x114, x115, x116, x117
      real(wp) :: x118, x119, x12, x120, x121, x122
      real(wp) :: x123, x124, x125, x126, x127, x128
      real(wp) :: x129, x13, x130, x131, x132, x133
      real(wp) :: x134, x135, x136, x137, x138, x139
      real(wp) :: x14, x140, x141, x142, x143, x144
      real(wp) :: x145, x146, x147, x148, x149, x15
      real(wp) :: x150, x151, x152, x153, x154, x155
      real(wp) :: x156, x157, x158, x159, x16, x160
      real(wp) :: x161, x162, x163, x164, x165, x166
      real(wp) :: x167, x168, x169, x17, x170, x171
      real(wp) :: x172, x173, x174, x175, x176, x177
      real(wp) :: x178, x179, x18, x180, x181, x182
      real(wp) :: x183, x184, x185, x186, x187, x188
      real(wp) :: x189, x19, x190, x191, x192, x193
      real(wp) :: x194, x195, x196, x197, x198, x199
      real(wp) :: x2, x20, x200, x201, x202, x203
      real(wp) :: x204, x205, x206, x207, x208, x209
      real(wp) :: x21, x210, x211, x212, x213, x214
      real(wp) :: x215, x216, x217, x218, x219, x22
      real(wp) :: x220, x221, x222, x223, x224, x225
      real(wp) :: x226, x227, x228, x229, x23, x230
      real(wp) :: x231, x232, x233, x234, x235, x236
      real(wp) :: x237, x238, x239, x24, x240, x241
      real(wp) :: x242, x243, x244, x245, x246, x247
      real(wp) :: x248, x249, x25, x250, x251, x252
      real(wp) :: x253, x254, x255, x256, x257, x258
      real(wp) :: x259, x26, x260, x261, x262, x263
      real(wp) :: x264, x265, x266, x267, x268, x269
      real(wp) :: x27, x270, x271, x272, x273, x274
      real(wp) :: x275, x276, x277, x278, x279, x28
      real(wp) :: x280, x281, x282, x283, x284, x285
      real(wp) :: x286, x287, x288, x289, x29, x290
      real(wp) :: x291, x292, x293, x294, x295, x296
      real(wp) :: x297, x298, x299, x3, x30, x300
      real(wp) :: x301, x302, x303, x304, x305, x306
      real(wp) :: x307, x308, x309, x31, x310, x311
      real(wp) :: x312, x313, x314, x315, x316, x317
      real(wp) :: x318, x319, x32, x320, x321, x322
      real(wp) :: x323, x324, x325, x326, x327, x328
      real(wp) :: x329, x33, x330, x331, x332, x333
      real(wp) :: x334, x335, x336, x337, x338, x339
      real(wp) :: x34, x340, x341, x342, x343, x344
      real(wp) :: x345, x346, x347, x348, x349, x35
      real(wp) :: x350, x351, x352, x353, x354, x355
      real(wp) :: x356, x357, x358, x359, x36, x360
      real(wp) :: x361, x362, x363, x364, x365, x366
      real(wp) :: x367, x368, x369, x37, x370, x371
      real(wp) :: x372, x373, x374, x375, x376, x377
      real(wp) :: x378, x379, x38, x380, x381, x382
      real(wp) :: x383, x384, x385, x386, x387, x388
      real(wp) :: x39, x4, x40, x41, x42, x43
      real(wp) :: x44, x45, x46, x47, x48, x49
      real(wp) :: x5, x50, x51, x52, x53, x54
      real(wp) :: x55, x56, x57, x58, x59, x6
      real(wp) :: x60, x61, x62, x63, x64, x65
      real(wp) :: x66, x67, x68, x69, x7, x70
      real(wp) :: x71, x72, x73, x74, x75, x76
      real(wp) :: x77, x78, x79, x8, x80, x81
      real(wp) :: x82, x83, x84, x85, x86, x87
      real(wp) :: x88, x89, x9, x90, x91, x92
      real(wp) :: x93, x94, x95, x96, x97, x98
      real(wp) :: x99

      if (max_deriv == 0) then
         x0 = 1d0/R_a
         x1 = 1d0/R_b
         pd0 = pd0 + (c_par*((-x0*x1*(d_a(1)*d_b(1) + d_a(2)*d_b(2) + d_a(3)*d_b(3)) + 1)*(-x0*x1*(d_a(1)*d_b(1) + d_a(2) &
                                      *d_b(2) + d_a(3)*d_b(3)) + 1)*(-x0*x1*(d_a(1)*d_b(1) + d_a(2)*d_b(2) + d_a(3)*d_b(3)) + 1)*( &
                             -x0*x1*(d_a(1)*d_b(1) + d_a(2)*d_b(2) + d_a(3)*d_b(3)) + 1))*exp(a2*(x0*sqrt((d_a(1)* &
                                      d_a(1)) + (d_a(2)*d_a(2)) + (d_a(3)*d_a(3))) + x1*sqrt((d_b(1)*d_b(1)) + (d_b(2)*d_b(2)) + ( &
                                                                                                          d_b(3)*d_b(3))) - 2.0d0)))
      end if
      if (max_deriv == 1) then
         x0 = 1d0/R_a
         x1 = 1d0/R_b
         x2 = -x0*x1*(d_a(1)*d_b(1) + d_a(2)*d_b(2) + d_a(3)*d_b(3)) + 1
         x3 = sqrt((d_a(1)*d_a(1)) + (d_a(2)*d_a(2)) + (d_a(3)*d_a(3)))
         x4 = sqrt((d_b(1)*d_b(1)) + (d_b(2)*d_b(2)) + (d_b(3)*d_b(3)))
         x5 = c_par*exp(a2*(x0*x3 + x1*x4 - 2.0d0))
         x6 = 4*x1
         x7 = a2*x2
         x8 = x7/x3
         x9 = (x2*x2*x2)*x5
         x10 = x0*x9
         x11 = 4*x0
         x12 = x7/x4
         x13 = x1*x9
         pd0 = pd0 + ((x2*x2*x2*x2)*x5)
         pd1_a(1) = pd1_a(1) + (x10*(d_a(1)*x8 - d_b(1)*x6))
         pd1_a(2) = pd1_a(2) + (x10*(d_a(2)*x8 - d_b(2)*x6))
         pd1_a(3) = pd1_a(3) + (x10*(d_a(3)*x8 - d_b(3)*x6))
         pd1_b(1) = pd1_b(1) + (x13*(-d_a(1)*x11 + d_b(1)*x12))
         pd1_b(2) = pd1_b(2) + (x13*(-d_a(2)*x11 + d_b(2)*x12))
         pd1_b(3) = pd1_b(3) + (x13*(-d_a(3)*x11 + d_b(3)*x12))
      end if
      if (max_deriv == 2) then
         x0 = d_a(1)*d_b(1)
         x1 = d_a(2)*d_b(2)
         x2 = d_a(3)*d_b(3)
         x3 = 1d0/R_a
         x4 = 1d0/R_b
         x5 = x3*x4
         x6 = x5*(x0 + x1 + x2)
         x7 = 1 - x6
         x8 = (d_a(1)*d_a(1))
         x9 = (d_a(2)*d_a(2))
         x10 = (d_a(3)*d_a(3))
         x11 = x10 + x8 + x9
         x12 = sqrt(x11)
         x13 = (d_b(1)*d_b(1))
         x14 = (d_b(2)*d_b(2))
         x15 = (d_b(3)*d_b(3))
         x16 = x13 + x14 + x15
         x17 = sqrt(x16)
         x18 = c_par*exp(a2*(x12*x3 + x17*x4 - 2.0d0))
         x19 = 4*x4
         x20 = d_b(1)*x19
         x21 = a2*x7
         x22 = 1d0/x12
         x23 = d_a(1)*x22
         x24 = x21*x23
         x25 = x18*(x7*x7*x7)
         x26 = x25*x3
         x27 = d_b(2)*x19
         x28 = x21*x22
         x29 = d_a(2)*x28
         x30 = d_a(3)*x28
         x31 = 4*x3
         x32 = d_a(1)*x31
         x33 = 1d0/x17
         x34 = x21*x33
         x35 = d_b(1)*x34
         x36 = x25*x4
         x37 = d_a(2)*x31
         x38 = d_b(2)*x34
         x39 = d_b(3)*x34
         x40 = R_b**(-2)
         x41 = 12*x3*x40
         x42 = (x7*x7)
         x43 = a2*x42
         x44 = x22*x43
         x45 = x43/x11**(3.0d0/2.0d0)
         x46 = 8*x5
         x47 = x28*x46
         x48 = (a2*a2)
         x49 = 1d0/x11
         x50 = x3*x42
         x51 = x48*x49*x50
         x52 = x18*x50
         x53 = d_a(1)*x45
         x54 = 4*x5
         x55 = x24*x54
         x56 = d_b(1)*x54
         x57 = 12*x5
         x58 = x28*x31
         x59 = x19*x34
         x60 = x33*x42*x48
         x61 = x22*x60
         x62 = 4*x6 - 4
         x63 = x18*x42*x5
         x64 = d_b(1)*x57
         x65 = x23*x60
         x66 = -x20*x38 - x29*x32
         x67 = -x20*x39 - x30*x32
         x68 = d_b(2)*x57
         x69 = d_a(2)*x61
         x70 = -x27*x39 - x30*x37
         x71 = d_b(3)*x57
         x72 = d_a(3)*x61
         x73 = R_a**(-2)
         x74 = 12*x4*x73
         x75 = x33*x43
         x76 = x43/x16**(3.0d0/2.0d0)
         x77 = x34*x46
         x78 = 1d0/x16
         x79 = x4*x42
         x80 = x48*x78*x79
         x81 = x18*x79
         x82 = d_b(1)*x76
         x83 = d_a(1)*x54
         x84 = x35*x54
         pd0 = pd0 + (x18*(x7*x7*x7*x7))
         pd1_a(1) = pd1_a(1) + (x26*(-x20 + x24))
         pd1_a(2) = pd1_a(2) + (x26*(-x27 + x29))
         pd1_a(3) = pd1_a(3) + (x26*(-d_b(3)*x19 + x30))
         pd1_b(1) = pd1_b(1) + (x36*(-x32 + x35))
         pd1_b(2) = pd1_b(2) + (x36*(-x37 + x38))
         pd1_b(3) = pd1_b(3) + (x36*(-d_a(3)*x31 + x39))
         t2aa_00 = (x52*(-x0*x47 + x13*x41 + x44 - x45*x8 + x51*x8))
         pd2_aa(1, 1) = pd2_aa(1, 1) + t2aa_00
         t2aa_01 = (x52*(d_a(1)*d_a(2)*x3*x42*x48*x49 - d_a(2)*x53 + 12*d_b(1)*d_b(2)*x3*x40 - d_b(2)*x55 - &
                         x29*x56))
         pd2_aa(1, 2) = pd2_aa(1, 2) + t2aa_01
         pd2_aa(2, 1) = pd2_aa(2, 1) + t2aa_01
         t2aa_02 = (x52*(d_a(1)*d_a(3)*x3*x42*x48*x49 - d_a(3)*x53 + 12*d_b(1)*d_b(3)*x3*x40 - d_b(3)*x55 - &
                         x30*x56))
         pd2_aa(1, 3) = pd2_aa(1, 3) + t2aa_02
         pd2_aa(3, 1) = pd2_aa(3, 1) + t2aa_02
         t2aa_11 = (x52*(-x1*x47 + x14*x41 + x44 - x45*x9 + x51*x9))
         pd2_aa(2, 2) = pd2_aa(2, 2) + t2aa_11
         t2aa_12 = (x52*(d_a(2)*d_a(3)*x3*x42*x48*x49 - d_a(2)*d_a(3)*x45 + 12*d_b(2)*d_b(3)*x3*x40 - d_b(2)*x30* &
                         x54 - d_b(3)*x29*x54))
         pd2_aa(2, 3) = pd2_aa(2, 3) + t2aa_12
         pd2_aa(3, 2) = pd2_aa(3, 2) + t2aa_12
         t2aa_22 = (x52*(-x10*x45 + x10*x51 + x15*x41 - x2*x47 + x44))
         pd2_aa(3, 3) = pd2_aa(3, 3) + t2aa_22
         pd2_ab(1, 1) = pd2_ab(1, 1) + (x63*(x0*x57 + x0*x61 - x13*x59 - x58*x8 + x62))
         pd2_ab(1, 2) = pd2_ab(1, 2) + (x63*(d_a(2)*x64 + d_b(2)*x65 + x66))
         pd2_ab(1, 3) = pd2_ab(1, 3) + (x63*(d_a(3)*x64 + d_b(3)*x65 + x67))
         pd2_ab(2, 1) = pd2_ab(2, 1) + (x63*(d_a(1)*x68 + d_b(1)*x69 + x66))
         pd2_ab(2, 2) = pd2_ab(2, 2) + (x63*(x1*x57 + x1*x61 - x14*x59 - x58*x9 + x62))
         pd2_ab(2, 3) = pd2_ab(2, 3) + (x63*(d_a(3)*x68 + d_b(3)*x69 + x70))
         pd2_ab(3, 1) = pd2_ab(3, 1) + (x63*(d_a(1)*x71 + d_b(1)*x72 + x67))
         pd2_ab(3, 2) = pd2_ab(3, 2) + (x63*(d_a(2)*x71 + d_b(2)*x72 + x70))
         pd2_ab(3, 3) = pd2_ab(3, 3) + (x63*(-x10*x58 - x15*x59 + x2*x57 + x2*x61 + x62))
         t2bb_00 = (x81*(-x0*x77 - x13*x76 + x13*x80 + x74*x8 + x75))
         pd2_bb(1, 1) = pd2_bb(1, 1) + t2bb_00
         t2bb_01 = (x81*(12*d_a(1)*d_a(2)*x4*x73 - d_a(2)*x84 + d_b(1)*d_b(2)*x4*x42*x48*x78 - d_b(2)*x82 - &
                         x38*x83))
         pd2_bb(1, 2) = pd2_bb(1, 2) + t2bb_01
         pd2_bb(2, 1) = pd2_bb(2, 1) + t2bb_01
         t2bb_02 = (x81*(12*d_a(1)*d_a(3)*x4*x73 - d_a(3)*x84 + d_b(1)*d_b(3)*x4*x42*x48*x78 - d_b(3)*x82 - &
                         x39*x83))
         pd2_bb(1, 3) = pd2_bb(1, 3) + t2bb_02
         pd2_bb(3, 1) = pd2_bb(3, 1) + t2bb_02
         t2bb_11 = (x81*(-x1*x77 - x14*x76 + x14*x80 + x74*x9 + x75))
         pd2_bb(2, 2) = pd2_bb(2, 2) + t2bb_11
         t2bb_12 = (x81*(12*d_a(2)*d_a(3)*x4*x73 - d_a(2)*x39*x54 - d_a(3)*x38*x54 + d_b(2)*d_b(3)*x4*x42*x48* &
                         x78 - d_b(2)*d_b(3)*x76))
         pd2_bb(2, 3) = pd2_bb(2, 3) + t2bb_12
         pd2_bb(3, 2) = pd2_bb(3, 2) + t2bb_12
         t2bb_22 = (x81*(x10*x74 - x15*x76 + x15*x80 - x2*x77 + x75))
         pd2_bb(3, 3) = pd2_bb(3, 3) + t2bb_22
      end if
      if (max_deriv == 3) then
         x0 = d_a(1)*d_b(1)
         x1 = d_a(2)*d_b(2)
         x2 = d_a(3)*d_b(3)
         x3 = 1d0/R_a
         x4 = 1d0/R_b
         x5 = x3*x4
         x6 = x5*(x0 + x1 + x2)
         x7 = 1 - x6
         x8 = (d_a(1)*d_a(1))
         x9 = (d_a(2)*d_a(2))
         x10 = (d_a(3)*d_a(3))
         x11 = x10 + x8 + x9
         x12 = sqrt(x11)
         x13 = (d_b(1)*d_b(1))
         x14 = (d_b(2)*d_b(2))
         x15 = (d_b(3)*d_b(3))
         x16 = x13 + x14 + x15
         x17 = sqrt(x16)
         x18 = c_par*exp(a2*(x12*x3 + x17*x4 - 2.0d0))
         x19 = 4*x4
         x20 = d_b(1)*x19
         x21 = a2*x7
         x22 = 1d0/x12
         x23 = d_a(1)*x22
         x24 = x21*x23
         x25 = (x7*x7*x7)
         x26 = x18*x25
         x27 = x26*x3
         x28 = d_b(2)*x19
         x29 = x21*x22
         x30 = d_a(2)*x29
         x31 = d_b(3)*x19
         x32 = d_a(3)*x29
         x33 = 4*x3
         x34 = d_a(1)*x33
         x35 = 1d0/x17
         x36 = x21*x35
         x37 = d_b(1)*x36
         x38 = x26*x4
         x39 = d_a(2)*x33
         x40 = d_b(2)*x36
         x41 = d_a(3)*x33
         x42 = d_b(3)*x36
         x43 = R_b**(-2)
         x44 = x13*x43
         x45 = 12*x3
         x46 = x44*x45
         x47 = (x7*x7)
         x48 = a2*x47
         x49 = x22*x48
         x50 = x11**(-3.0d0/2.0d0)
         x51 = x48*x50
         x52 = x51*x8
         x53 = 8*x5
         x54 = x29*x53
         x55 = (a2*a2)
         x56 = x55*x8
         x57 = 1d0/x11
         x58 = x3*x47
         x59 = x57*x58
         x60 = x18*x58
         x61 = d_a(1)*x51
         x62 = d_a(2)*x61
         x63 = d_b(2)*x5
         x64 = 4*x24
         x65 = d_b(1)*x5
         x66 = 4*x65
         x67 = d_a(3)*x61
         x68 = d_b(3)*x5
         x69 = x43*x45
         x70 = x14*x69
         x71 = x51*x9
         x72 = x55*x59
         x73 = d_a(2)*d_a(3)
         x74 = x51*x73
         x75 = 4*x68
         x76 = 4*x63
         x77 = x15*x69
         x78 = x10*x51
         x79 = 12*x5
         x80 = x29*x33
         x81 = x19*x36
         x82 = x22*x35
         x83 = x47*x55
         x84 = x82*x83
         x85 = x0*x84
         x86 = 4*x6 - 4
         x87 = x47*x5
         x88 = x18*x87
         x89 = d_b(1)*x79
         x90 = x35*x83
         x91 = x23*x90
         x92 = d_b(2)*x91
         x93 = -x20*x40 - x30*x34
         x94 = d_b(3)*x91
         x95 = -x20*x42 - x32*x34
         x96 = d_b(2)*x79
         x97 = d_b(1)*x22
         x98 = x90*x97
         x99 = x1*x84
         x100 = d_a(2)*d_b(3)
         x101 = x100*x84
         x102 = -x28*x42 - x32*x39
         x103 = d_b(3)*x79
         x104 = d_a(3)*d_b(2)
         x105 = x104*x84
         x106 = x2*x84
         x107 = R_a**(-2)
         x108 = x107*x8
         x109 = 12*x4
         x110 = x108*x109
         x111 = x35*x48
         x112 = x16**(-3.0d0/2.0d0)
         x113 = x112*x48
         x114 = x113*x13
         x115 = x36*x53
         x116 = x13*x55
         x117 = 1d0/x16
         x118 = x4*x47
         x119 = x117*x118
         x120 = x118*x18
         x121 = d_b(1)*x113
         x122 = d_b(2)*x121
         x123 = 4*x5
         x124 = d_a(1)*x123
         x125 = x123*x37
         x126 = d_b(3)*x121
         x127 = x107*x109
         x128 = x127*x9
         x129 = x113*x14
         x130 = x119*x55
         x131 = d_b(2)*d_b(3)
         x132 = x113*x131
         x133 = d_a(2)*x123
         x134 = d_a(3)*x123
         x135 = x10*x127
         x136 = x113*x15
         x137 = (d_b(1)*d_b(1)*d_b(1))
         x138 = 24*x107
         x139 = x138/(R_b*R_b*R_b)
         x140 = a2*x25
         x141 = x140*x50
         x142 = d_a(1)*x141
         x143 = (d_a(1)*d_a(1)*d_a(1))
         x144 = 3*x140
         x145 = x144/x11**(5.0d0/2.0d0)
         x146 = x25*x55
         x147 = x3*x57
         x148 = x146*x147
         x149 = d_a(1)*x148
         x150 = x107*x143
         x151 = (a2*a2*a2)
         x152 = x151*x25
         x153 = x152*x50
         x154 = 3*x3/(x11*x11)
         x155 = x146*x154
         x156 = x107*x44
         x157 = x57*x83
         x158 = x18*x7
         x159 = x158*x3
         x160 = x13*x139
         x161 = x145*x8
         x162 = x108*x153
         x163 = x25*x56
         x164 = x154*x163
         x165 = x108*x157
         x166 = 12*x156
         x167 = d_a(2)*x0
         x168 = 8*x55
         x169 = x107*x118*x168*x57
         x170 = x51*x53
         x171 = x138*x43
         x172 = d_b(2)*x171
         x173 = x0*x172
         x174 = d_a(2)*x141
         x175 = d_a(2)*x146
         x176 = x147*x175
         x177 = 4*x49
         x178 = -x174 + x176 - x177*x63
         x179 = d_a(3)*x0
         x180 = d_b(3)*x171
         x181 = x0*x180
         x182 = d_a(3)*x141
         x183 = d_a(3)*x148
         x184 = -x177*x68 - x182 + x183
         x185 = d_b(1)*x139
         x186 = d_a(1)*x9
         x187 = x107*x153
         x188 = x107*x157
         x189 = x188*x20
         x190 = x107*x43
         x191 = x14*x190
         x192 = 12*x24
         x193 = d_a(1)*x169
         x194 = x53*x61
         x195 = d_b(1)*x171
         x196 = x1*x195
         x197 = -x142 + x149 - x177*x65
         x198 = d_a(1)*x73
         x199 = 12*x30
         x200 = d_b(1)*x190
         x201 = 12*x32
         x202 = d_a(1)*d_a(2)
         x203 = x188*x31
         x204 = d_a(1)*d_a(3)
         x205 = x188*x28
         x206 = d_a(1)*x10
         x207 = x15*x190
         x208 = x195*x2
         x209 = (d_b(2)*d_b(2)*d_b(2))
         x210 = (d_a(2)*d_a(2)*d_a(2))
         x211 = d_b(3)*x14
         x212 = d_a(3)*x9
         x213 = d_a(3)*x1
         x214 = x1*x180
         x215 = d_b(2)*x15
         x216 = d_a(2)*x10
         x217 = d_a(2)*x2
         x218 = x172*x2
         x219 = (d_b(3)*d_b(3)*d_b(3))
         x220 = (d_a(3)*d_a(3)*d_a(3))
         x221 = x138*x44
         x222 = 24*x7
         x223 = x45*x49
         x224 = x33*x51
         x225 = x36*x69
         x226 = 4*x83
         x227 = x226*x57
         x228 = x146*x35
         x229 = d_b(1)*x50
         x230 = x163*x35
         x231 = x147*x152*x35
         x232 = x116*x87
         x233 = x158*x5
         x234 = x230*x50
         x235 = 8*x63
         x236 = x39*x49
         x237 = -d_b(2)*x22*x25*x35*x55 + x236
         x238 = x108*x227
         x239 = -4*a2*d_a(2)*x3*x47*x50*x8 - 12*a2*d_b(2)*x13*x3*x35*x43*x7 + d_a(2)*x238
         x240 = 8*x68
         x241 = x41*x49
         x242 = -d_b(3)*x22*x25*x35*x55 + x241
         x243 = -4*a2*d_a(3)*x3*x47*x50*x8 - 12*a2*d_b(3)*x13*x3*x35*x43*x7 + d_a(3)*x238
         x244 = x0*x50
         x245 = x175*x35
         x246 = 4*x82
         x247 = x232*x246
         x248 = -12*d_b(2)*x3*x4*x7 + x236
         x249 = d_a(1)*x50
         x250 = x228*x249
         x251 = x123*x91
         x252 = x107*x227
         x253 = -4*a2*d_a(1)*x3*x47*x50*x9 - 12*a2*d_b(1)*x14*x3*x35*x43*x7 + x186*x252
         x254 = x34*x49
         x255 = -12*d_b(1)*x3*x4*x7 + x254
         x256 = -4*a2*d_a(1)*d_a(2)*d_a(3)*x3*x47*x50
         x257 = x198*x252
         x258 = -12*a2*d_b(1)*d_b(2)*d_b(3)*x3*x35*x43*x7
         x259 = -12*a2*d_a(2)*d_a(3)*d_b(1)*x107*x22*x4*x7 + x131*x251 + x256 + x257 + x258
         x260 = -12*a2*d_a(1)*d_a(3)*d_b(2)*x107*x22*x4*x7 + x101*x66
         x261 = -12*d_b(3)*x3*x4*x7 + x241
         x262 = -12*a2*d_a(1)*d_a(2)*d_b(3)*x107*x22*x4*x7 + x105*x66
         x263 = -4*a2*d_a(1)*x10*x3*x47*x50 - 12*a2*d_b(1)*x15*x3*x35*x43*x7 + x206*x252
         x264 = x14*x171
         x265 = x228*x9
         x266 = 8*x65
         x267 = -d_b(1)*x22*x25*x35*x55 + x254
         x268 = x222*x5
         x269 = d_b(2)*x4
         x270 = x138*x29
         x271 = x22*x228
         x272 = x265*x50
         x273 = x53*x84
         x274 = -4*a2*d_a(3)*x3*x47*x50*x9 - 12*a2*d_b(3)*x14*x3*x35*x43*x7 + x212*x252
         x275 = d_a(1)*x171
         x276 = d_a(3)*x14
         x277 = -4*a2*d_a(2)*x10*x3*x47*x50 - 12*a2*d_b(2)*x15*x3*x35*x43*x7 + x216*x252
         x278 = x15*x171
         x279 = x10*x228
         x280 = x279*x50
         x281 = d_b(3)*x4
         x282 = d_a(3)*x15
         x283 = 24*x43
         x284 = x108*x283
         x285 = x109*x111
         x286 = x113*x19
         x287 = x127*x29
         x288 = x137*x43
         x289 = x117*x226
         x290 = x112*x23
         x291 = x116*x25
         x292 = x117*x152*x4
         x293 = x0*x171
         x294 = d_a(2)*x293
         x295 = x112*x22
         x296 = x146*x295
         x297 = x0*x296
         x298 = x246*x56*x87
         x299 = d_b(2)*x117
         x300 = -12*a2*d_a(2)*x107*x22*x4*x7*x8 - 4*a2*d_b(2)*x112*x13*x4*x47 + x226*x299*x44
         x301 = x111*x28
         x302 = -12*d_a(2)*x3*x4*x7 + x301
         x303 = d_a(3)*x293
         x304 = -12*a2*d_a(3)*x107*x22*x4*x7*x8 - 4*a2*d_b(3)*x112*x13*x4*x47 + d_b(3)*x289*x44
         x305 = x111*x31
         x306 = -12*d_a(3)*x3*x4*x7 + x305
         x307 = x146*x290
         x308 = x53*x91
         x309 = x111*x20
         x310 = -d_a(1)*x22*x25*x35*x55 + x309
         x311 = x289*x43
         x312 = d_b(1)*x14
         x313 = -12*a2*d_a(1)*x107*x22*x4*x7*x9 - 4*a2*d_b(1)*x112*x14*x4*x47 + x311*x312
         x314 = -4*a2*d_b(1)*d_b(2)*d_b(3)*x112*x4*x47
         x315 = d_b(1)*x131
         x316 = x311*x315
         x317 = -12*a2*d_a(1)*d_a(2)*d_a(3)*x107*x22*x4*x7
         x318 = -12*a2*d_a(3)*d_b(1)*d_b(2)*x3*x35*x43*x7 + x133*x94 + x314 + x316 + x317
         x319 = -12*a2*d_a(2)*d_b(1)*d_b(3)*x3*x35*x43*x7 + x134*x92
         x320 = d_b(1)*x15
         x321 = -12*a2*d_a(1)*x10*x107*x22*x4*x7 - 4*a2*d_b(1)*x112*x15*x4*x47 + x311*x320
         x322 = x291*x295
         x323 = d_a(2)*x53
         x324 = -d_a(2)*x22*x25*x35*x55 + x301
         x325 = x1*x275
         x326 = x112*x97
         x327 = x146*x326
         x328 = x84*x9
         x329 = -12*d_a(1)*x3*x4*x7 + x309
         x330 = -12*a2*d_a(1)*d_b(2)*d_b(3)*x3*x35*x43*x7 + x66*x73*x84
         x331 = x283*x3
         x332 = x175*x295
         x333 = x22*x292
         x334 = x171*x213
         x335 = d_b(3)*x1
         x336 = -12*a2*d_a(3)*x107*x22*x4*x7*x9 - 4*a2*d_b(3)*x112*x14*x4*x47 + x211*x311
         x337 = -12*a2*d_a(2)*x10*x107*x22*x4*x7 - 4*a2*d_b(2)*x112*x15*x4*x47 + x215*x311
         x338 = d_a(3)*x53
         x339 = -d_a(3)*x22*x25*x35*x55 + x305
         x340 = x2*x275
         x341 = x10*x84
         x342 = x171*x217
         x343 = x283/(R_a*R_a*R_a)
         x344 = x112*x140
         x345 = d_b(1)*x344
         x346 = x144/x16**(5.0d0/2.0d0)
         x347 = x146*x4
         x348 = x117*x347
         x349 = d_b(1)*x348
         x350 = x112*x152
         x351 = d_a(1)*x111
         x352 = 3/(x16*x16)
         x353 = x347*x352
         x354 = x108*x43
         x355 = x117*x83
         x356 = x158*x4
         x357 = x343*x8
         x358 = x13*x346
         x359 = x350*x44
         x360 = x291*x352
         x361 = x355*x44
         x362 = 12*x354
         x363 = x299*x43
         x364 = x168*x58
         x365 = x363*x364
         x366 = x0*x113
         x367 = d_b(2)*x344
         x368 = x299*x347
         x369 = d_a(2)*x111
         x370 = -x123*x369 - x367 + x368
         x371 = x117*x364*x43
         x372 = d_b(3)*x344
         x373 = d_b(3)*x348
         x374 = d_a(3)*x111
         x375 = -x123*x374 - x372 + x373
         x376 = d_a(1)*x343
         x377 = x350*x43
         x378 = x355*x43
         x379 = x34*x378
         x380 = x190*x9
         x381 = 12*x37
         x382 = d_b(1)*x371
         x383 = x121*x53
         x384 = -x123*x351 - x345 + x349
         x385 = 12*x42
         x386 = 12*x40
         x387 = x378*x39
         x388 = x10*x190
         pd0 = pd0 + (x18*(x7*x7*x7*x7))
         pd1_a(1) = pd1_a(1) + (x27*(-x20 + x24))
         pd1_a(2) = pd1_a(2) + (x27*(-x28 + x30))
         pd1_a(3) = pd1_a(3) + (x27*(-x31 + x32))
         pd1_b(1) = pd1_b(1) + (x38*(-x34 + x37))
         pd1_b(2) = pd1_b(2) + (x38*(-x39 + x40))
         pd1_b(3) = pd1_b(3) + (x38*(-x41 + x42))
         t2aa_00 = (x60*(-x0*x54 + x46 + x49 - x52 + x56*x59))
         pd2_aa(1, 1) = pd2_aa(1, 1) + t2aa_00
         t2aa_01 = (x60*(d_a(1)*d_a(2)*x3*x47*x55*x57 + 12*d_b(1)*d_b(2)*x3*x43 - x30*x66 - x62 - x63* &
                         x64))
         pd2_aa(1, 2) = pd2_aa(1, 2) + t2aa_01
         pd2_aa(2, 1) = pd2_aa(2, 1) + t2aa_01
         t2aa_02 = (x60*(d_a(1)*d_a(3)*x3*x47*x55*x57 + 12*d_b(1)*d_b(3)*x3*x43 - x32*x66 - x64*x68 - &
                         x67))
         pd2_aa(1, 3) = pd2_aa(1, 3) + t2aa_02
         pd2_aa(3, 1) = pd2_aa(3, 1) + t2aa_02
         t2aa_11 = (x60*(-x1*x54 + x49 + x70 - x71 + x72*x9))
         pd2_aa(2, 2) = pd2_aa(2, 2) + t2aa_11
         t2aa_12 = (x60*(d_a(2)*d_a(3)*x3*x47*x55*x57 + 12*d_b(2)*d_b(3)*x3*x43 - x30*x75 - x32*x76 - &
                         x74))
         pd2_aa(2, 3) = pd2_aa(2, 3) + t2aa_12
         pd2_aa(3, 2) = pd2_aa(3, 2) + t2aa_12
         t2aa_22 = (x60*(x10*x72 - x2*x54 + x49 + x77 - x78))
         pd2_aa(3, 3) = pd2_aa(3, 3) + t2aa_22
         pd2_ab(1, 1) = pd2_ab(1, 1) + (x88*(x0*x79 - x13*x81 - x8*x80 + x85 + x86))
         pd2_ab(1, 2) = pd2_ab(1, 2) + (x88*(d_a(2)*x89 + x92 + x93))
         pd2_ab(1, 3) = pd2_ab(1, 3) + (x88*(d_a(3)*x89 + x94 + x95))
         pd2_ab(2, 1) = pd2_ab(2, 1) + (x88*(d_a(1)*x96 + d_a(2)*x98 + x93))
         pd2_ab(2, 2) = pd2_ab(2, 2) + (x88*(x1*x79 - x14*x81 - x80*x9 + x86 + x99))
         pd2_ab(2, 3) = pd2_ab(2, 3) + (x88*(d_a(3)*x96 + x101 + x102))
         pd2_ab(3, 1) = pd2_ab(3, 1) + (x88*(d_a(1)*x103 + d_a(3)*x98 + x95))
         pd2_ab(3, 2) = pd2_ab(3, 2) + (x88*(d_a(2)*x103 + x102 + x105))
         pd2_ab(3, 3) = pd2_ab(3, 3) + (x88*(-x10*x80 + x106 - x15*x81 + x2*x79 + x86))
         t2bb_00 = (x120*(-x0*x115 + x110 + x111 - x114 + x116*x119))
         pd2_bb(1, 1) = pd2_bb(1, 1) + t2bb_00
         t2bb_01 = (x120*(12*d_a(1)*d_a(2)*x107*x4 - d_a(2)*x125 + d_b(1)*d_b(2)*x117*x4*x47*x55 - x122 - &
                          x124*x40))
         pd2_bb(1, 2) = pd2_bb(1, 2) + t2bb_01
         pd2_bb(2, 1) = pd2_bb(2, 1) + t2bb_01
         t2bb_02 = (x120*(12*d_a(1)*d_a(3)*x107*x4 - d_a(3)*x125 + d_b(1)*d_b(3)*x117*x4*x47*x55 - x124*x42 &
                          - x126))
         pd2_bb(1, 3) = pd2_bb(1, 3) + t2bb_02
         pd2_bb(3, 1) = pd2_bb(3, 1) + t2bb_02
         t2bb_11 = (x120*(-x1*x115 + x111 + x128 - x129 + x130*x14))
         pd2_bb(2, 2) = pd2_bb(2, 2) + t2bb_11
         t2bb_12 = (x120*(12*d_a(2)*d_a(3)*x107*x4 + d_b(2)*d_b(3)*x117*x4*x47*x55 - x132 - x133*x42 - &
                          x134*x40))
         pd2_bb(2, 3) = pd2_bb(2, 3) + t2bb_12
         pd2_bb(3, 2) = pd2_bb(3, 2) + t2bb_12
         t2bb_22 = (x120*(x111 - x115*x2 + x130*x15 + x135 - x136))
         pd2_bb(3, 3) = pd2_bb(3, 3) + t2bb_22
         t3aaa_000 = (x159*(-d_b(1)*x110*x157 - x137*x139 - 3*x142 + x143*x145 - x143*x155 + 3* &
                            x149 + x150*x153 + 36*x156*x24 - x49*x89 + x52*x89))
         pd3_aaa(1, 1, 1) = pd3_aaa(1, 1, 1) + t3aaa_000
         t3aaa_001 = (x159*(d_a(2)*x161 + d_a(2)*x162 - d_a(2)*x164 - d_b(2)*x160 - x165*x28 + x166*x30 - &
                            x167*x169 + x167*x170 + x173*x29 + x178 + x52*x76))
         pd3_aaa(1, 1, 2) = pd3_aaa(1, 1, 2) + t3aaa_001
         pd3_aaa(1, 2, 1) = pd3_aaa(1, 2, 1) + t3aaa_001
         pd3_aaa(2, 1, 1) = pd3_aaa(2, 1, 1) + t3aaa_001
         t3aaa_002 = (x159*(d_a(3)*x161 + d_a(3)*x162 - d_a(3)*x164 - d_b(3)*x160 - x165*x31 + x166*x32 - &
                            x169*x179 + x170*x179 + x181*x29 + x184 + x52*x75))
         pd3_aaa(1, 1, 3) = pd3_aaa(1, 1, 3) + t3aaa_002
         pd3_aaa(1, 3, 1) = pd3_aaa(1, 3, 1) + t3aaa_002
         pd3_aaa(3, 1, 1) = pd3_aaa(3, 1, 1) + t3aaa_002
         t3aaa_011 = (x159*(-x1*x193 + x1*x194 - x14*x185 + x145*x186 - x155*x186 + x186*x187 &
                            - x189*x9 + x191*x192 + x196*x29 + x197 + x66*x71))
         pd3_aaa(1, 2, 2) = pd3_aaa(1, 2, 2) + t3aaa_011
         pd3_aaa(2, 1, 2) = pd3_aaa(2, 1, 2) + t3aaa_011
         pd3_aaa(2, 2, 1) = pd3_aaa(2, 2, 1) + t3aaa_011
         t3aaa_012 = (x159*(d_b(2)*x200*x201 + d_b(3)*x199*x200 - x131*x185 + x131*x190*x192 + x145* &
                            x198 - x155*x198 + x187*x198 - x189*x73 - x202*x203 - x204*x205 + &
                            x62*x75 + x66*x74 + x67*x76))
         pd3_aaa(1, 2, 3) = pd3_aaa(1, 2, 3) + t3aaa_012
         pd3_aaa(1, 3, 2) = pd3_aaa(1, 3, 2) + t3aaa_012
         pd3_aaa(2, 1, 3) = pd3_aaa(2, 1, 3) + t3aaa_012
         pd3_aaa(2, 3, 1) = pd3_aaa(2, 3, 1) + t3aaa_012
         pd3_aaa(3, 1, 2) = pd3_aaa(3, 1, 2) + t3aaa_012
         pd3_aaa(3, 2, 1) = pd3_aaa(3, 2, 1) + t3aaa_012
         t3aaa_022 = (x159*(-x10*x189 + x145*x206 - x15*x185 - x155*x206 + x187*x206 + x192* &
                            x207 - x193*x2 + x194*x2 + x197 + x208*x29 + x66*x78))
         pd3_aaa(1, 3, 3) = pd3_aaa(1, 3, 3) + t3aaa_022
         pd3_aaa(3, 1, 3) = pd3_aaa(3, 1, 3) + t3aaa_022
         pd3_aaa(3, 3, 1) = pd3_aaa(3, 3, 1) + t3aaa_022
         t3aaa_111 = (x159*(-d_b(2)*x128*x157 - x139*x209 + x145*x210 - x155*x210 - 3*x174 + 3* &
                            x176 + x187*x210 + 36*x191*x30 - x49*x96 + x71*x96))
         pd3_aaa(2, 2, 2) = pd3_aaa(2, 2, 2) + t3aaa_111
         t3aaa_112 = (x159*(-x139*x211 + x145*x212 - x155*x212 - x169*x213 + x170*x213 + x184 &
                            + x187*x212 + x191*x201 - x203*x9 + x214*x29 + x71*x75))
         pd3_aaa(2, 2, 3) = pd3_aaa(2, 2, 3) + t3aaa_112
         pd3_aaa(2, 3, 2) = pd3_aaa(2, 3, 2) + t3aaa_112
         pd3_aaa(3, 2, 2) = pd3_aaa(3, 2, 2) + t3aaa_112
         t3aaa_122 = (x159*(-x10*x154*x175 - x10*x205 - x139*x215 + x145*x216 - x169*x217 + &
                            x170*x217 + x178 + x187*x216 + x199*x207 + x218*x29 + x76*x78))
         pd3_aaa(2, 3, 3) = pd3_aaa(2, 3, 3) + t3aaa_122
         pd3_aaa(3, 2, 3) = pd3_aaa(3, 2, 3) + t3aaa_122
         pd3_aaa(3, 3, 2) = pd3_aaa(3, 3, 2) + t3aaa_122
         t3aaa_222 = (x159*(-d_b(3)*x135*x157 - x103*x49 + x103*x78 - x139*x219 + x145*x220 - &
                            x155*x220 - 3*x182 + 3*x183 + x187*x220 + 36*x207*x32))
         pd3_aaa(3, 3, 3) = pd3_aaa(3, 3, 3) + t3aaa_222
         t3aab_000 = (x233*(-d_a(1)*x221 - d_a(1)*x223 + 24*d_b(1)*x108*x29*x4 + d_b(1)*x231*x8 + x137* &
                            x225 + x143*x224 - x150*x227 + x222*x65 + x228*x97 - x229*x230 - &
                            8*x23*x232*x35))
         pd3_aab(1, 1, 1) = pd3_aab(1, 1, 1) + t3aab_000
         t3aab_001 = (x233*(24*a2*d_a(1)*d_a(2)*d_b(1)*x107*x22*x4*x7 - d_a(2)*x221 + d_b(2)*x151*x25*x3*x35* &
                            x57*x8 - d_b(2)*x234 - x235*x85 - x237 - x239))
         pd3_aab(1, 1, 2) = pd3_aab(1, 1, 2) + t3aab_001
         t3aab_002 = (x233*(24*a2*d_a(1)*d_a(3)*d_b(1)*x107*x22*x4*x7 - d_a(3)*x221 + d_b(3)*x151*x25*x3*x35* &
                            x57*x8 - d_b(3)*x234 - x240*x85 - x242 - x243))
         pd3_aab(1, 1, 3) = pd3_aab(1, 1, 3) + t3aab_002
         t3aab_010 = (x233*(12*a2*d_a(1)*d_a(2)*d_b(1)*x107*x22*x4*x7 + 12*a2*d_b(2)*x107*x22*x4*x7*x8 + &
                            d_a(1)*d_a(2)*d_b(1)*x151*x25*x3*x35*x57 - d_a(2)*x247 - x173 - x239 - x244* &
                            x245 - x248 - x76*x85))
         pd3_aab(1, 2, 1) = pd3_aab(1, 2, 1) + t3aab_010
         pd3_aab(2, 1, 1) = pd3_aab(2, 1, 1) + t3aab_010
         t3aab_011 = (x233*(12*a2*d_a(1)*d_a(2)*d_b(2)*x107*x22*x4*x7 + 12*a2*d_b(1)*x107*x22*x4*x7*x9 + &
                            d_a(1)*d_a(2)*d_b(2)*x151*x25*x3*x35*x57 - x1*x250 - x14*x251 - x196 - &
                            x253 - x255 - x66*x99))
         pd3_aab(1, 2, 2) = pd3_aab(1, 2, 2) + t3aab_011
         pd3_aab(2, 1, 2) = pd3_aab(2, 1, 2) + t3aab_011
         t3aab_012 = (x233*(d_a(1)*d_a(2)*d_b(3)*x151*x25*x3*x35*x57 - d_b(3)*x245*x249 - x104*x195 - x259 &
                            - x260))
         pd3_aab(1, 2, 3) = pd3_aab(1, 2, 3) + t3aab_012
         pd3_aab(2, 1, 3) = pd3_aab(2, 1, 3) + t3aab_012
         t3aab_020 = (x233*(12*a2*d_a(1)*d_a(3)*d_b(1)*x107*x22*x4*x7 + 12*a2*d_b(3)*x107*x22*x4*x7*x8 + &
                            d_a(1)*d_a(3)*d_b(1)*x151*x25*x3*x35*x57 - d_a(3)*x228*x244 - d_a(3)*x247 - x181 &
                            - x243 - x261 - x75*x85))
         pd3_aab(1, 3, 1) = pd3_aab(1, 3, 1) + t3aab_020
         pd3_aab(3, 1, 1) = pd3_aab(3, 1, 1) + t3aab_020
         t3aab_021 = (x233*(d_a(1)*d_a(3)*d_b(2)*x151*x25*x3*x35*x57 - x100*x195 - x104*x250 - x259 - &
                            x262))
         pd3_aab(1, 3, 2) = pd3_aab(1, 3, 2) + t3aab_021
         pd3_aab(3, 1, 2) = pd3_aab(3, 1, 2) + t3aab_021
         t3aab_022 = (x233*(12*a2*d_a(1)*d_a(3)*d_b(3)*x107*x22*x4*x7 + 12*a2*d_b(1)*x10*x107*x22*x4*x7 + &
                            d_a(1)*d_a(3)*d_b(3)*x151*x25*x3*x35*x57 - x106*x66 - x15*x251 - x2*x250 - &
                            x208 - x255 - x263))
         pd3_aab(1, 3, 3) = pd3_aab(1, 3, 3) + t3aab_022
         pd3_aab(3, 1, 3) = pd3_aab(3, 1, 3) + t3aab_022
         t3aab_110 = (x233*(24*a2*d_a(1)*d_a(2)*d_b(2)*x107*x22*x4*x7 - d_a(1)*x264 + d_b(1)*x151*x25*x3*x35* &
                            x57*x9 - x229*x265 - x253 - x266*x99 - x267))
         pd3_aab(2, 2, 1) = pd3_aab(2, 2, 1) + t3aab_110
         t3aab_111 = (x233*(-d_a(2)*x14*x273 - d_a(2)*x223 - d_a(2)*x264 + d_b(2)*x231*x9 + d_b(2)*x268 + d_b(2) &
                            *x271 - d_b(2)*x272 + x209*x225 + x210*x224 - x210*x252 + x269*x270* &
                            x9))
         pd3_aab(2, 2, 2) = pd3_aab(2, 2, 2) + t3aab_111
         t3aab_112 = (x233*(24*a2*d_a(2)*d_a(3)*d_b(2)*x107*x22*x4*x7 - d_a(3)*x264 + d_b(3)*x151*x25*x3*x35* &
                            x57*x9 - d_b(3)*x272 - x240*x99 - x242 - x274))
         pd3_aab(2, 2, 3) = pd3_aab(2, 2, 3) + t3aab_112
         t3aab_120 = (x233*(d_a(2)*d_a(3)*d_b(1)*x151*x25*x3*x35*x57 - x131*x275 - x228*x229*x73 - x256 &
                            - x257 - x258 - x260 - x262))
         pd3_aab(2, 3, 1) = pd3_aab(2, 3, 1) + t3aab_120
         pd3_aab(3, 2, 1) = pd3_aab(3, 2, 1) + t3aab_120
         t3aab_121 = (x233*(12*a2*d_a(2)*d_a(3)*d_b(2)*x107*x22*x4*x7 + 12*a2*d_b(3)*x107*x22*x4*x7*x9 + &
                            d_a(2)*d_a(3)*d_b(2)*x151*x25*x3*x35*x57 - x123*x276*x84 - x213*x228*x50 - &
                            x214 - x261 - x274 - x75*x99))
         pd3_aab(2, 3, 2) = pd3_aab(2, 3, 2) + t3aab_121
         pd3_aab(3, 2, 2) = pd3_aab(3, 2, 2) + t3aab_121
         t3aab_122 = (x233*(12*a2*d_a(2)*d_a(3)*d_b(3)*x107*x22*x4*x7 + 12*a2*d_b(2)*x10*x107*x22*x4*x7 + &
                            d_a(2)*d_a(3)*d_b(3)*x151*x25*x3*x35*x57 - x106*x76 - x133*x15*x84 - x2* &
                            x245*x50 - x218 - x248 - x277))
         pd3_aab(2, 3, 3) = pd3_aab(2, 3, 3) + t3aab_122
         pd3_aab(3, 2, 3) = pd3_aab(3, 2, 3) + t3aab_122
         t3aab_220 = (x233*(24*a2*d_a(1)*d_a(3)*d_b(3)*x107*x22*x4*x7 - d_a(1)*x278 + d_b(1)*x10*x151*x25*x3* &
                            x35*x57 - x106*x266 - x229*x279 - x263 - x267))
         pd3_aab(3, 3, 1) = pd3_aab(3, 3, 1) + t3aab_220
         t3aab_221 = (x233*(24*a2*d_a(2)*d_a(3)*d_b(3)*x107*x22*x4*x7 - d_a(2)*x278 + d_b(2)*x10*x151*x25*x3* &
                            x35*x57 - d_b(2)*x280 - x106*x235 - x237 - x277))
         pd3_aab(3, 3, 2) = pd3_aab(3, 3, 2) + t3aab_221
         t3aab_222 = (x233*(-d_a(3)*x223 - d_a(3)*x278 + d_b(3)*x10*x231 + d_b(3)*x268 + d_b(3)*x271 - d_b(3)* &
                            x280 + x10*x270*x281 + x219*x225 + x220*x224 - x220*x252 - x273* &
                            x282))
         pd3_aab(3, 3, 3) = pd3_aab(3, 3, 3) + t3aab_222
         t3abb_000 = (x233*(d_a(1)*x268 + 24*d_a(1)*x3*x36*x44 - d_b(1)*x284 - d_b(1)*x285 + x13*x23*x292 &
                            + x137*x286 + x143*x287 + x228*x23 - x266*x47*x56*x82 - x288*x289 &
                            - x290*x291))
         pd3_abb(1, 1, 1) = pd3_abb(1, 1, 1) + t3abb_000
         t3abb_001 = (x233*(12*a2*d_a(1)*d_b(1)*d_b(2)*x3*x35*x43*x7 + 12*a2*d_a(2)*x13*x3*x35*x43*x7 + &
                            d_a(1)*d_b(1)*d_b(2)*x117*x151*x22*x25*x4 - d_b(2)*x297 - d_b(2)*x298 - x133*x85 &
                            - x294 - x300 - x302))
         pd3_abb(1, 1, 2) = pd3_abb(1, 1, 2) + t3abb_001
         pd3_abb(1, 2, 1) = pd3_abb(1, 2, 1) + t3abb_001
         t3abb_002 = (x233*(12*a2*d_a(1)*d_b(1)*d_b(3)*x3*x35*x43*x7 + 12*a2*d_a(3)*x13*x3*x35*x43*x7 + &
                            d_a(1)*d_b(1)*d_b(3)*x117*x151*x22*x25*x4 - d_b(3)*x297 - d_b(3)*x298 - x134*x85 &
                            - x303 - x304 - x306))
         pd3_abb(1, 1, 3) = pd3_abb(1, 1, 3) + t3abb_002
         pd3_abb(1, 3, 1) = pd3_abb(1, 3, 1) + t3abb_002
         t3abb_011 = (x233*(24*a2*d_a(2)*d_b(1)*d_b(2)*x3*x35*x43*x7 + d_a(1)*x117*x14*x151*x22*x25*x4 - &
                            x1*x308 - x14*x307 - x195*x9 - x310 - x313))
         pd3_abb(1, 2, 2) = pd3_abb(1, 2, 2) + t3abb_011
         t3abb_012 = (x233*(d_a(1)*d_b(2)*d_b(3)*x117*x151*x22*x25*x4 - x131*x307 - x195*x73 - x318 - &
                            x319))
         pd3_abb(1, 2, 3) = pd3_abb(1, 2, 3) + t3abb_012
         pd3_abb(1, 3, 2) = pd3_abb(1, 3, 2) + t3abb_012
         t3abb_022 = (x233*(24*a2*d_a(3)*d_b(1)*d_b(3)*x3*x35*x43*x7 + d_a(1)*x117*x15*x151*x22*x25*x4 - &
                            x10*x195 - x15*x307 - x2*x308 - x310 - x321))
         pd3_abb(1, 3, 3) = pd3_abb(1, 3, 3) + t3abb_022
         t3abb_100 = (x233*(24*a2*d_a(1)*d_b(1)*d_b(2)*x3*x35*x43*x7 + d_a(2)*x117*x13*x151*x22*x25*x4 - &
                            d_a(2)*x322 - d_b(2)*x284 - x300 - x323*x85 - x324))
         pd3_abb(2, 1, 1) = pd3_abb(2, 1, 1) + t3abb_100
         t3abb_101 = (x233*(12*a2*d_a(1)*x14*x3*x35*x43*x7 + 12*a2*d_a(2)*d_b(1)*d_b(2)*x3*x35*x43*x7 + &
                            d_a(2)*d_b(1)*d_b(2)*x117*x151*x22*x25*x4 - x1*x251 - x1*x327 - x313 - &
                            x325 - x328*x66 - x329))
         pd3_abb(2, 1, 2) = pd3_abb(2, 1, 2) + t3abb_101
         pd3_abb(2, 2, 1) = pd3_abb(2, 2, 1) + t3abb_101
         t3abb_102 = (x233*(d_a(2)*d_b(1)*d_b(3)*x117*x151*x22*x25*x4 - d_b(3)*x175*x326 - x172*x204 - &
                            x318 - x330))
         pd3_abb(2, 1, 3) = pd3_abb(2, 1, 3) + t3abb_102
         pd3_abb(2, 3, 1) = pd3_abb(2, 3, 1) + t3abb_102
         t3abb_111 = (x233*(d_a(2)*x14*x331*x36 + d_a(2)*x14*x333 + d_a(2)*x268 - d_b(2)*x285 - x14*x332 - &
                            x172*x9 + x175*x82 + x209*x286 - x209*x311 + x210*x287 - x235* &
                            x328))
         pd3_abb(2, 2, 2) = pd3_abb(2, 2, 2) + t3abb_111
         t3abb_112 = (x233*(12*a2*d_a(2)*d_b(2)*d_b(3)*x3*x35*x43*x7 + 12*a2*d_a(3)*x14*x3*x35*x43*x7 + &
                            d_a(2)*d_b(2)*d_b(3)*x117*x151*x22*x25*x4 - x134*x99 - x296*x335 - x306 - &
                            x328*x75 - x334 - x336))
         pd3_abb(2, 2, 3) = pd3_abb(2, 2, 3) + t3abb_112
         pd3_abb(2, 3, 2) = pd3_abb(2, 3, 2) + t3abb_112
         t3abb_122 = (x233*(24*a2*d_a(3)*d_b(2)*d_b(3)*x3*x35*x43*x7 + d_a(2)*x117*x15*x151*x22*x25*x4 - &
                            x10*x172 - x106*x323 - x15*x332 - x324 - x337))
         pd3_abb(2, 3, 3) = pd3_abb(2, 3, 3) + t3abb_122
         t3abb_200 = (x233*(24*a2*d_a(1)*d_b(1)*d_b(3)*x3*x35*x43*x7 + d_a(3)*x117*x13*x151*x22*x25*x4 - &
                            d_a(3)*x322 - d_b(3)*x284 - x304 - x338*x85 - x339))
         pd3_abb(3, 1, 1) = pd3_abb(3, 1, 1) + t3abb_200
         t3abb_201 = (x233*(d_a(3)*d_b(1)*d_b(2)*x117*x151*x22*x25*x4 - x104*x327 - x180*x202 - x314 - &
                            x316 - x317 - x319 - x330))
         pd3_abb(3, 1, 2) = pd3_abb(3, 1, 2) + t3abb_201
         pd3_abb(3, 2, 1) = pd3_abb(3, 2, 1) + t3abb_201
         t3abb_202 = (x233*(12*a2*d_a(1)*x15*x3*x35*x43*x7 + 12*a2*d_a(3)*d_b(1)*d_b(3)*x3*x35*x43*x7 + &
                            d_a(3)*d_b(1)*d_b(3)*x117*x151*x22*x25*x4 - x2*x251 - x2*x327 - x321 - &
                            x329 - x340 - x341*x66))
         pd3_abb(3, 1, 3) = pd3_abb(3, 1, 3) + t3abb_202
         pd3_abb(3, 3, 1) = pd3_abb(3, 3, 1) + t3abb_202
         t3abb_211 = (x233*(24*a2*d_a(2)*d_b(2)*d_b(3)*x3*x35*x43*x7 + d_a(3)*x117*x14*x151*x22*x25*x4 - &
                            x180*x9 - x276*x296 - x336 - x338*x99 - x339))
         pd3_abb(3, 2, 2) = pd3_abb(3, 2, 2) + t3abb_211
         t3abb_212 = (x233*(12*a2*d_a(2)*x15*x3*x35*x43*x7 + 12*a2*d_a(3)*d_b(2)*d_b(3)*x3*x35*x43*x7 + &
                            d_a(3)*d_b(2)*d_b(3)*x117*x151*x22*x25*x4 - d_b(2)*x2*x296 - x106*x133 - x302 &
                            - x337 - x341*x76 - x342))
         pd3_abb(3, 2, 3) = pd3_abb(3, 2, 3) + t3abb_212
         pd3_abb(3, 3, 2) = pd3_abb(3, 3, 2) + t3abb_212
         t3abb_222 = (x233*(d_a(3)*x268 + d_a(3)*x271 - d_b(3)*x285 - x10*x180 + x219*x286 - x219*x311 &
                            + x220*x287 - x240*x341 - x282*x296 + x282*x331*x36 + x282*x333))
         pd3_abb(3, 3, 3) = pd3_abb(3, 3, 3) + t3abb_222
         t3bbb_000 = (x356*(d_a(1)*x114*x79 - d_a(1)*x355*x46 + x137*x346 - x137*x353 - x143*x343 + &
                            x288*x350 - 3*x345 + 3*x349 - x351*x79 + 36*x354*x37))
         pd3_bbb(1, 1, 1) = pd3_bbb(1, 1, 1) + t3bbb_000
         t3bbb_001 = (x356*(-d_a(2)*x357 + d_b(2)*x358 + d_b(2)*x359 - x0*x365 + x114*x133 + x235*x366 &
                            - x269*x360 + x294*x36 - x361*x39 + x362*x40 + x370))
         pd3_bbb(1, 1, 2) = pd3_bbb(1, 1, 2) + t3bbb_001
         pd3_bbb(1, 2, 1) = pd3_bbb(1, 2, 1) + t3bbb_001
         pd3_bbb(2, 1, 1) = pd3_bbb(2, 1, 1) + t3bbb_001
         t3bbb_002 = (x356*(-d_a(3)*x357 - d_b(3)*x0*x371 + d_b(3)*x358 + d_b(3)*x359 + x114*x134 + x240* &
                            x366 - x281*x360 + x303*x36 - x361*x41 + x362*x42 + x375))
         pd3_bbb(1, 1, 3) = pd3_bbb(1, 1, 3) + t3bbb_002
         pd3_bbb(1, 3, 1) = pd3_bbb(1, 3, 1) + t3bbb_002
         pd3_bbb(3, 1, 1) = pd3_bbb(3, 1, 1) + t3bbb_002
         t3bbb_011 = (x356*(-x1*x382 + x1*x383 + x124*x129 - x14*x379 + x312*x346 - x312*x353 &
                            + x312*x377 + x325*x36 - x376*x9 + x380*x381 + x384))
         pd3_bbb(1, 2, 2) = pd3_bbb(1, 2, 2) + t3bbb_011
         pd3_bbb(2, 1, 2) = pd3_bbb(2, 1, 2) + t3bbb_011
         pd3_bbb(2, 2, 1) = pd3_bbb(2, 2, 1) + t3bbb_011
         t3bbb_012 = (x356*(-d_b(1)*d_b(3)*x387 - d_b(1)*x363*x41*x83 + x122*x134 + x124*x132 + x126* &
                            x133 - x131*x379 + x190*x202*x385 + x190*x204*x386 + x190*x381* &
                            x73 + x315*x346 - x315*x353 + x315*x377 - x376*x73))
         pd3_bbb(1, 2, 3) = pd3_bbb(1, 2, 3) + t3bbb_012
         pd3_bbb(1, 3, 2) = pd3_bbb(1, 3, 2) + t3bbb_012
         pd3_bbb(2, 1, 3) = pd3_bbb(2, 1, 3) + t3bbb_012
         pd3_bbb(2, 3, 1) = pd3_bbb(2, 3, 1) + t3bbb_012
         pd3_bbb(3, 1, 2) = pd3_bbb(3, 1, 2) + t3bbb_012
         pd3_bbb(3, 2, 1) = pd3_bbb(3, 2, 1) + t3bbb_012
         t3bbb_022 = (x356*(-x10*x376 + x124*x136 - x15*x379 - x2*x382 + x2*x383 + x320*x346 - &
                            x320*x353 + x320*x377 + x340*x36 + x381*x388 + x384))
         pd3_bbb(1, 3, 3) = pd3_bbb(1, 3, 3) + t3bbb_022
         pd3_bbb(3, 1, 3) = pd3_bbb(3, 1, 3) + t3bbb_022
         pd3_bbb(3, 3, 1) = pd3_bbb(3, 3, 1) + t3bbb_022
         t3bbb_111 = (x356*(d_a(2)*x129*x79 - d_a(2)*x355*x70 + x209*x346 - x209*x353 + x209*x377 - &
                            x210*x343 - 3*x367 + 3*x368 - x369*x79 + 36*x380*x40))
         pd3_bbb(2, 2, 2) = pd3_bbb(2, 2, 2) + t3bbb_111
         t3bbb_112 = (x356*(x1*x113*x240 + x129*x134 - x14*x378*x41 + x211*x346 - x211*x353 + &
                            x211*x377 - x212*x343 + x334*x36 - x335*x371 + x375 + x380*x385))
         pd3_bbb(2, 2, 3) = pd3_bbb(2, 2, 3) + t3bbb_112
         pd3_bbb(2, 3, 2) = pd3_bbb(2, 3, 2) + t3bbb_112
         pd3_bbb(3, 2, 2) = pd3_bbb(3, 2, 2) + t3bbb_112
         t3bbb_122 = (x356*(x113*x2*x235 + x133*x136 - x15*x387 - x2*x365 + x215*x346 - x215* &
                            x353 + x215*x377 - x216*x343 + x342*x36 + x370 + x386*x388))
         pd3_bbb(2, 3, 3) = pd3_bbb(2, 3, 3) + t3bbb_122
         pd3_bbb(3, 2, 3) = pd3_bbb(3, 2, 3) + t3bbb_122
         pd3_bbb(3, 3, 2) = pd3_bbb(3, 3, 2) + t3bbb_122
         t3bbb_222 = (x356*(d_a(3)*x136*x79 - d_a(3)*x355*x77 + x219*x346 - x219*x353 + x219*x377 - &
                            x220*x343 - 3*x372 + 3*x373 - x374*x79 + 36*x388*x42))
         pd3_bbb(3, 3, 3) = pd3_bbb(3, 3, 3) + t3bbb_222
      end if
   end subroutine cfc_pair_term_eval

   !> Lift accumulated pseudo-density derivatives to log-PD derivatives.
   !>
   !> Applies the chain rule (Faa di Bruno) for f(r) = log(PD(r)) given
   !> PD and d^k_r PD. Outputs are SET (not accumulated) since the lift
   !> happens once after all atomic/pair contributions are summed.
   !>
   !> @param[in]  pd0       Value of PD at r
   !> @param[in]  pd1_r     First derivative d_i PD
   !> @param[in]  pd2_rr    Second derivative d_ij PD
   !> @param[in]  pd3_rrr   Third derivative d_ijk PD
   !> @param[in]  max_deriv Maximum derivative order to lift (0..3)
   !> @param[out] lpd0      log(PD)
   !> @param[out] lpd1_r    First derivative of log(PD)
   !> @param[out] lpd2_rr   Second derivative of log(PD)
   !> @param[out] lpd3_rrr  Third derivative of log(PD)
   pure subroutine cfc_log_lift(pd0, pd1_r, pd2_rr, pd3_rrr, max_deriv, &
                                lpd0, lpd1_r, lpd2_rr, lpd3_rrr)
      !> Pseudo-density value
      real(wp), intent(in)  :: pd0
      !> Pseudo-density gradient
      real(wp), intent(in)  :: pd1_r(3)
      !> Pseudo-density Hessian
      real(wp), intent(in)  :: pd2_rr(3, 3)
      !> Pseudo-density third derivative
      real(wp), intent(in)  :: pd3_rrr(3, 3, 3)
      !> Maximum derivative order to lift
      integer, intent(in)  :: max_deriv
      !> log(PD)
      real(wp), intent(out) :: lpd0
      !> Gradient of log(PD)
      real(wp), intent(out) :: lpd1_r(3)
      !> Hessian of log(PD)
      real(wp), intent(out) :: lpd2_rr(3, 3)
      !> Third derivative of log(PD)
      real(wp), intent(out) :: lpd3_rrr(3, 3, 3)

      !> Reciprocal powers of PD used by the chain rule
      real(wp) :: inv_pd, inv_pd2, inv_pd3
      !> Loop indices
      integer :: i, j, k

      lpd0 = 0.0_wp
      lpd1_r = 0.0_wp
      lpd2_rr = 0.0_wp
      lpd3_rrr = 0.0_wp

      if (pd0 <= 0.0_wp) return

      lpd0 = log(pd0)
      if (max_deriv < 1) return

      inv_pd = 1.0_wp/pd0
      do i = 1, 3
         lpd1_r(i) = pd1_r(i)*inv_pd
      end do
      if (max_deriv < 2) return

      inv_pd2 = inv_pd*inv_pd
      do j = 1, 3
         do i = 1, 3
            lpd2_rr(i, j) = pd2_rr(i, j)*inv_pd &
                            - pd1_r(i)*pd1_r(j)*inv_pd2
         end do
      end do
      if (max_deriv < 3) return

      inv_pd3 = inv_pd2*inv_pd
      do k = 1, 3
         do j = 1, 3
            do i = 1, 3
               lpd3_rrr(i, j, k) = pd3_rrr(i, j, k)*inv_pd &
                                   - (pd2_rr(i, j)*pd1_r(k) &
                                      + pd2_rr(i, k)*pd1_r(j) &
                                      + pd2_rr(j, k)*pd1_r(i))*inv_pd2 &
                                   + 2.0_wp*pd1_r(i)*pd1_r(j)*pd1_r(k)*inv_pd3
            end do
         end do
      end do
   end subroutine cfc_log_lift

end module moist_cavity_drop_lsf_cfc_kernel
