! SPDX-License-Identifier: MPL-2.0 AND Apache-2.0 AND CC-BY-4.0
! Lookup implementation: MPL-2.0
! Parameter sections retain their respective Apache-2.0 and CC BY 4.0 terms
!
! OPLS-AA LJ subsets from permissively licensed sources
!
! db:opls_135 selects a numerical type from OPLSAA-DB (Apache-2.0)
! tuk:a-c-1-1 selects a chemical tag from TUK-FFDat (CC BY 4.0)
! Source notices and unit corrections are retained with the data sections
module moist_model_moz_potential_lj_oplsaa_parameters
   use mctc_env, only: wp
   use mctc_io_convert, only: aatoau, kjtoau, kcaltoau
   use mctc_io_utils, only: to_lower
   implicit none(type, external)
   private

   public :: lookup_oplsaa_lj, n_oplsaa, oplsaa_key_len

   ! OPLSAA-DB parameter data: Apache-2.0
   !
   ! Parameter data: OPLSAA-DB by Leela S. Dodda, Jorgensen Lab, Yale University
   ! https://github.com/leelasd/OPLSAA-DB
   !
   ! Original export attribution:
   ! Writted by Leela S. Dodda leela.dodda@yale.edu
   ! GENERATED BY Server
   ! Jorgensen Lab @ Yale University
   !
   ! Changes: extracted LJ rows and elements from the OpenMM XML exports,
   ! deduplicated identical native keys, lowercased keys, added Fortran lookup
   ! All occurrences of each key agree in element, sigma and epsilon
   ! Each row names one source molecule archive as a reproducible witness
   ! Source units: sigma in nm, epsilon in kJ/mol
   ! Seven of the 464 archives contain only Z-matrices, without exported LJ data:
   ! M_11679, M_12675, M_6431, M_67828, M_9638, M_9639, M_9805
   ! This is a parameter subset, not the complete OPLS-AA master table
   !
   ! Original Apache-2.0 license follows
   !
   !                                  Apache License
   !                            Version 2.0, January 2004
   !                         http://www.apache.org/licenses/
   !
   !    TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION
   !
   !    1. Definitions.
   !
   !       "License" shall mean the terms and conditions for use, reproduction,
   !       and distribution as defined by Sections 1 through 9 of this document.
   !
   !       "Licensor" shall mean the copyright owner or entity authorized by
   !       the copyright owner that is granting the License.
   !
   !       "Legal Entity" shall mean the union of the acting entity and all
   !       other entities that control, are controlled by, or are under common
   !       control with that entity. For the purposes of this definition,
   !       "control" means (i) the power, direct or indirect, to cause the
   !       direction or management of such entity, whether by contract or
   !       otherwise, or (ii) ownership of fifty percent (50%) or more of the
   !       outstanding shares, or (iii) beneficial ownership of such entity.
   !
   !       "You" (or "Your") shall mean an individual or Legal Entity
   !       exercising permissions granted by this License.
   !
   !       "Source" form shall mean the preferred form for making modifications,
   !       including but not limited to software source code, documentation
   !       source, and configuration files.
   !
   !       "Object" form shall mean any form resulting from mechanical
   !       transformation or translation of a Source form, including but
   !       not limited to compiled object code, generated documentation,
   !       and conversions to other media types.
   !
   !       "Work" shall mean the work of authorship, whether in Source or
   !       Object form, made available under the License, as indicated by a
   !       copyright notice that is included in or attached to the work
   !       (an example is provided in the Appendix below).
   !
   !       "Derivative Works" shall mean any work, whether in Source or Object
   !       form, that is based on (or derived from) the Work and for which the
   !       editorial revisions, annotations, elaborations, or other modifications
   !       represent, as a whole, an original work of authorship. For the purposes
   !       of this License, Derivative Works shall not include works that remain
   !       separable from, or merely link (or bind by name) to the interfaces of,
   !       the Work and Derivative Works thereof.
   !
   !       "Contribution" shall mean any work of authorship, including
   !       the original version of the Work and any modifications or additions
   !       to that Work or Derivative Works thereof, that is intentionally
   !       submitted to Licensor for inclusion in the Work by the copyright owner
   !       or by an individual or Legal Entity authorized to submit on behalf of
   !       the copyright owner. For the purposes of this definition, "submitted"
   !       means any form of electronic, verbal, or written communication sent
   !       to the Licensor or its representatives, including but not limited to
   !       communication on electronic mailing lists, source code control systems,
   !       and issue tracking systems that are managed by, or on behalf of, the
   !       Licensor for the purpose of discussing and improving the Work, but
   !       excluding communication that is conspicuously marked or otherwise
   !       designated in writing by the copyright owner as "Not a Contribution."
   !
   !       "Contributor" shall mean Licensor and any individual or Legal Entity
   !       on behalf of whom a Contribution has been received by Licensor and
   !       subsequently incorporated within the Work.
   !
   !    2. Grant of Copyright License. Subject to the terms and conditions of
   !       this License, each Contributor hereby grants to You a perpetual,
   !       worldwide, non-exclusive, no-charge, royalty-free, irrevocable
   !       copyright license to reproduce, prepare Derivative Works of,
   !       publicly display, publicly perform, sublicense, and distribute the
   !       Work and such Derivative Works in Source or Object form.
   !
   !    3. Grant of Patent License. Subject to the terms and conditions of
   !       this License, each Contributor hereby grants to You a perpetual,
   !       worldwide, non-exclusive, no-charge, royalty-free, irrevocable
   !       (except as stated in this section) patent license to make, have made,
   !       use, offer to sell, sell, import, and otherwise transfer the Work,
   !       where such license applies only to those patent claims licensable
   !       by such Contributor that are necessarily infringed by their
   !       Contribution(s) alone or by combination of their Contribution(s)
   !       with the Work to which such Contribution(s) was submitted. If You
   !       institute patent litigation against any entity (including a
   !       cross-claim or counterclaim in a lawsuit) alleging that the Work
   !       or a Contribution incorporated within the Work constitutes direct
   !       or contributory patent infringement, then any patent licenses
   !       granted to You under this License for that Work shall terminate
   !       as of the date such litigation is filed.
   !
   !    4. Redistribution. You may reproduce and distribute copies of the
   !       Work or Derivative Works thereof in any medium, with or without
   !       modifications, and in Source or Object form, provided that You
   !       meet the following conditions:
   !
   !       (a) You must give any other recipients of the Work or
   !           Derivative Works a copy of this License; and
   !
   !       (b) You must cause any modified files to carry prominent notices
   !           stating that You changed the files; and
   !
   !       (c) You must retain, in the Source form of any Derivative Works
   !           that You distribute, all copyright, patent, trademark, and
   !           attribution notices from the Source form of the Work,
   !           excluding those notices that do not pertain to any part of
   !           the Derivative Works; and
   !
   !       (d) If the Work includes a "NOTICE" text file as part of its
   !           distribution, then any Derivative Works that You distribute must
   !           include a readable copy of the attribution notices contained
   !           within such NOTICE file, excluding those notices that do not
   !           pertain to any part of the Derivative Works, in at least one
   !           of the following places: within a NOTICE text file distributed
   !           as part of the Derivative Works; within the Source form or
   !           documentation, if provided along with the Derivative Works; or,
   !           within a display generated by the Derivative Works, if and
   !           wherever such third-party notices normally appear. The contents
   !           of the NOTICE file are for informational purposes only and
   !           do not modify the License. You may add Your own attribution
   !           notices within Derivative Works that You distribute, alongside
   !           or as an addendum to the NOTICE text from the Work, provided
   !           that such additional attribution notices cannot be construed
   !           as modifying the License.
   !
   !       You may add Your own copyright statement to Your modifications and
   !       may provide additional or different license terms and conditions
   !       for use, reproduction, or distribution of Your modifications, or
   !       for any such Derivative Works as a whole, provided Your use,
   !       reproduction, and distribution of the Work otherwise complies with
   !       the conditions stated in this License.
   !
   !    5. Submission of Contributions. Unless You explicitly state otherwise,
   !       any Contribution intentionally submitted for inclusion in the Work
   !       by You to the Licensor shall be under the terms and conditions of
   !       this License, without any additional terms or conditions.
   !       Notwithstanding the above, nothing herein shall supersede or modify
   !       the terms of any separate license agreement you may have executed
   !       with Licensor regarding such Contributions.
   !
   !    6. Trademarks. This License does not grant permission to use the trade
   !       names, trademarks, service marks, or product names of the Licensor,
   !       except as required for reasonable and customary use in describing the
   !       origin of the Work and reproducing the content of the NOTICE file.
   !
   !    7. Disclaimer of Warranty. Unless required by applicable law or
   !       agreed to in writing, Licensor provides the Work (and each
   !       Contributor provides its Contributions) on an "AS IS" BASIS,
   !       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
   !       implied, including, without limitation, any warranties or conditions
   !       of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A
   !       PARTICULAR PURPOSE. You are solely responsible for determining the
   !       appropriateness of using or redistributing the Work and assume any
   !       risks associated with Your exercise of permissions under this License.
   !
   !    8. Limitation of Liability. In no event and under no legal theory,
   !       whether in tort (including negligence), contract, or otherwise,
   !       unless required by applicable law (such as deliberate and grossly
   !       negligent acts) or agreed to in writing, shall any Contributor be
   !       liable to You for damages, including any direct, indirect, special,
   !       incidental, or consequential damages of any character arising as a
   !       result of this License or out of the use or inability to use the
   !       Work (including but not limited to damages for loss of goodwill,
   !       work stoppage, computer failure or malfunction, or any and all
   !       other commercial damages or losses), even if such Contributor
   !       has been advised of the possibility of such damages.
   !
   !    9. Accepting Warranty or Additional Liability. While redistributing
   !       the Work or Derivative Works thereof, You may choose to offer,
   !       and charge a fee for, acceptance of support, warranty, indemnity,
   !       or other liability obligations and/or rights consistent with this
   !       License. However, in accepting such obligations, You may act only
   !       on Your own behalf and on Your sole responsibility, not on behalf
   !       of any other Contributor, and only if You agree to indemnify,
   !       defend, and hold each Contributor harmless for any liability
   !       incurred by, or claims asserted against, such Contributor by reason
   !       of your accepting any such warranty or additional liability.
   !
   !    END OF TERMS AND CONDITIONS
   !
   !    APPENDIX: How to apply the Apache License to your work.
   !
   !       To apply the Apache License to your work, attach the following
   !       boilerplate notice, with the fields enclosed by brackets "[]"
   !       replaced with your own identifying information. (Don't include
   !       the brackets!)  The text should be enclosed in the appropriate
   !       comment syntax for the file format. We also recommend that a
   !       file or class name and description of purpose be included on the
   !       same "printed page" as the copyright notice for easier
   !       identification within third-party archives.
   !
   !    Copyright [yyyy] [name of copyright owner]
   !
   !    Licensed under the Apache License, Version 2.0 (the "License");
   !    you may not use this file except in compliance with the License.
   !    You may obtain a copy of the License at
   !
   !        http://www.apache.org/licenses/LICENSE-2.0
   !
   !    Unless required by applicable law or agreed to in writing, software
   !    distributed under the License is distributed on an "AS IS" BASIS,
   !    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   !    See the License for the specific language governing permissions and
   !    limitations under the License.

   !> Maximum length of a source-prefixed atomtype key
   integer, parameter :: oplsaa_key_len = 32
   !> Number of OPLSAA-DB native keys
   integer, parameter :: n_oplsaa_database = 526
   !> Number of TUK-FFDat chemical tags
   integer, parameter :: n_oplsaa_tuk = 125
   !> Number of source-prefixed LJ rows
   integer, parameter :: n_oplsaa = n_oplsaa_database + n_oplsaa_tuk

   !> One source LJ row
   !>
   !> Database rows use nm and kJ/mol; TUK rows use Angstrom and kcal/mol
   type :: lj_row_type
      !> Native lowercase key, without source prefix
      character(len=oplsaa_key_len) :: key
      !> Atomic number
      integer :: number
      !> LJ zero crossing, source length unit
      real(wp) :: sigma
      !> LJ well depth, source energy unit
      real(wp) :: epsilon
   end type lj_row_type

   !> Source db_rows 1-128
   type(lj_row_type), parameter :: db_rows_1(128) = [ &
      & lj_row_type("opls_1000", 6, 0.355000_wp, 0.292880_wp), & ! M_5324110
      & lj_row_type("opls_1001", 6, 0.355000_wp, 0.292880_wp), & ! M_5324110
      & lj_row_type("opls_1002", 6, 0.355000_wp, 0.292880_wp), & ! M_69590
      & lj_row_type("opls_1003", 6, 0.355000_wp, 0.292880_wp), & ! M_69590
      & lj_row_type("opls_1004", 6, 0.355000_wp, 0.292880_wp), & ! M_13065
      & lj_row_type("opls_1011", 6, 0.350000_wp, 0.276144_wp), & ! M_33643
      & lj_row_type("opls_1014", 53, 0.375000_wp, 2.510400_wp), & ! M_33643
      & lj_row_type("opls_1015", 1, 0.250000_wp, 0.125520_wp), & ! M_33643
      & lj_row_type("opls_1021", 7, 0.325000_wp, 0.711280_wp), & ! M_70970
      & lj_row_type("opls_1022", 6, 0.355000_wp, 0.292880_wp), & ! M_70970
      & lj_row_type("opls_1035", 6, 0.375000_wp, 0.439320_wp), & ! M_31374
      & lj_row_type("opls_1036", 8, 0.296000_wp, 0.878640_wp), & ! M_31374
      & lj_row_type("opls_1037", 7, 0.325000_wp, 0.711280_wp), & ! M_31374
      & lj_row_type("opls_1038", 6, 0.350000_wp, 0.276144_wp), & ! M_31374
      & lj_row_type("opls_1042", 1, 0.242000_wp, 0.062760_wp), & ! M_31374
      & lj_row_type("opls_1043", 6, 0.375000_wp, 0.439320_wp), & ! M_6228
      & lj_row_type("opls_1044", 8, 0.296000_wp, 0.878640_wp), & ! M_6228
      & lj_row_type("opls_1045", 1, 0.242000_wp, 0.062760_wp), & ! M_6228
      & lj_row_type("opls_1060", 14, 0.400000_wp, 0.418400_wp), & ! M_12426
      & lj_row_type("opls_1062", 14, 0.400000_wp, 0.418400_wp), & ! M_66185
      & lj_row_type("opls_1063", 14, 0.400000_wp, 0.418400_wp), & ! M_137730
      & lj_row_type("opls_1064", 1, 0.250000_wp, 0.125520_wp), & ! M_137730
      & lj_row_type("opls_1065", 6, 0.350000_wp, 0.276144_wp), & ! M_6396
      & lj_row_type("opls_1066", 6, 0.350000_wp, 0.276144_wp), & ! M_12426
      & lj_row_type("opls_1152", 6, 0.355000_wp, 0.317984_wp), & ! M_16695
      & lj_row_type("opls_135", 6, 0.350000_wp, 0.276144_wp), & ! M_10041
      & lj_row_type("opls_136", 6, 0.350000_wp, 0.276144_wp), & ! M_101194
      & lj_row_type("opls_137", 6, 0.350000_wp, 0.276144_wp), & ! M_10352
      & lj_row_type("opls_139", 6, 0.350000_wp, 0.276144_wp), & ! M_10041
      & lj_row_type("opls_140", 1, 0.250000_wp, 0.125520_wp), & ! M_10041
      & lj_row_type("opls_141", 6, 0.355000_wp, 0.317984_wp), & ! M_1105
      & lj_row_type("opls_142", 6, 0.355000_wp, 0.317984_wp), & ! M_10352
      & lj_row_type("opls_143", 6, 0.355000_wp, 0.317984_wp), & ! M_11240
      & lj_row_type("opls_144", 1, 0.242000_wp, 0.125520_wp), & ! M_10352
      & lj_row_type("opls_145", 6, 0.355000_wp, 0.292880_wp), & ! M_10008
      & lj_row_type("opls_146", 1, 0.242000_wp, 0.125520_wp), & ! M_10008
      & lj_row_type("opls_147", 6, 0.355000_wp, 0.292880_wp), & ! M_10390
      & lj_row_type("opls_148", 6, 0.350000_wp, 0.276144_wp), & ! M_1140
      & lj_row_type("opls_149", 6, 0.350000_wp, 0.276144_wp), & ! M_121008116
      & lj_row_type("opls_150", 6, 0.355000_wp, 0.317984_wp), & ! M_12248
      & lj_row_type("opls_151", 17, 0.340000_wp, 1.255200_wp), & ! M_10899
      & lj_row_type("opls_152", 6, 0.350000_wp, 0.276144_wp), & ! M_10899
      & lj_row_type("opls_153", 1, 0.250000_wp, 0.125520_wp), & ! M_10899
      & lj_row_type("opls_154", 8, 0.312000_wp, 0.711280_wp), & ! M_1031
      & lj_row_type("opls_155", 1, 0.000000_wp, 0.000000_wp), & ! M_1031
      & lj_row_type("opls_157", 6, 0.350000_wp, 0.276144_wp), & ! M_1031
      & lj_row_type("opls_158", 6, 0.350000_wp, 0.276144_wp), & ! M_13601
      & lj_row_type("opls_159", 6, 0.350000_wp, 0.276144_wp), & ! M_6386
      & lj_row_type("opls_160", 6, 0.350000_wp, 0.276144_wp), & ! M_6409
      & lj_row_type("opls_161", 6, 0.325000_wp, 0.259408_wp), & ! M_6409
      & lj_row_type("opls_162", 8, 0.307000_wp, 0.711280_wp), & ! M_6409
      & lj_row_type("opls_163", 1, 0.000000_wp, 0.000000_wp), & ! M_6409
      & lj_row_type("opls_164", 9, 0.294000_wp, 0.255224_wp), & ! M_6409
      & lj_row_type("opls_165", 1, 0.250000_wp, 0.125520_wp), & ! M_6409
      & lj_row_type("opls_166", 6, 0.355000_wp, 0.292880_wp), & ! M_10784
      & lj_row_type("opls_167", 8, 0.307000_wp, 0.711280_wp), & ! M_10784
      & lj_row_type("opls_168", 1, 0.000000_wp, 0.000000_wp), & ! M_10784
      & lj_row_type("opls_169", 8, 0.307000_wp, 0.711280_wp), & ! M_13601
      & lj_row_type("opls_170", 1, 0.000000_wp, 0.000000_wp), & ! M_13601
      & lj_row_type("opls_173", 6, 0.350000_wp, 0.276144_wp), & ! M_1567
      & lj_row_type("opls_174", 6, 0.350000_wp, 0.276144_wp), & ! M_206
      & lj_row_type("opls_176", 1, 0.250000_wp, 0.125520_wp), & ! M_1567
      & lj_row_type("opls_177", 8, 0.290000_wp, 0.585760_wp), & ! M_248758
      & lj_row_type("opls_178", 6, 0.355000_wp, 0.317984_wp), & ! M_6557
      & lj_row_type("opls_179", 8, 0.290000_wp, 0.585760_wp), & ! M_10824
      & lj_row_type("opls_180", 8, 0.290000_wp, 0.585760_wp), & ! M_10869
      & lj_row_type("opls_181", 6, 0.350000_wp, 0.276144_wp), & ! M_10824
      & lj_row_type("opls_182", 6, 0.350000_wp, 0.276144_wp), & ! M_10873
      & lj_row_type("opls_183", 6, 0.350000_wp, 0.276144_wp), & ! M_13607
      & lj_row_type("opls_184", 6, 0.350000_wp, 0.276144_wp), & ! M_561155
      & lj_row_type("opls_185", 1, 0.250000_wp, 0.125520_wp), & ! M_10824
      & lj_row_type("opls_186", 8, 0.290000_wp, 0.585760_wp), & ! M_13521790
      & lj_row_type("opls_189", 6, 0.350000_wp, 0.276144_wp), & ! M_8020
      & lj_row_type("opls_190", 1, 0.250000_wp, 0.125520_wp), & ! M_8020
      & lj_row_type("opls_193", 6, 0.350000_wp, 0.276144_wp), & ! M_13521790
      & lj_row_type("opls_194", 1, 0.250000_wp, 0.125520_wp), & ! M_13521790
      & lj_row_type("opls_195", 6, 0.350000_wp, 0.276144_wp), & ! M_206
      & lj_row_type("opls_196", 1, 0.250000_wp, 0.125520_wp), & ! M_206
      & lj_row_type("opls_199", 6, 0.355000_wp, 0.292880_wp), & ! M_10824
      & lj_row_type("opls_200", 16, 0.360000_wp, 1.778200_wp), & ! M_1567
      & lj_row_type("opls_202", 16, 0.360000_wp, 1.485320_wp), & ! M_1068
      & lj_row_type("opls_203", 16, 0.360000_wp, 1.485320_wp), & ! M_12232
      & lj_row_type("opls_204", 1, 0.000000_wp, 0.000000_wp), & ! M_1567
      & lj_row_type("opls_206", 6, 0.350000_wp, 0.276144_wp), & ! M_1567
      & lj_row_type("opls_209", 6, 0.350000_wp, 0.276144_wp), & ! M_1068
      & lj_row_type("opls_210", 6, 0.350000_wp, 0.276144_wp), & ! M_12230
      & lj_row_type("opls_213", 6, 0.350000_wp, 0.276144_wp), & ! M_12232
      & lj_row_type("opls_214", 6, 0.350000_wp, 0.276144_wp), & ! M_8077
      & lj_row_type("opls_218", 6, 0.350000_wp, 0.276144_wp), & ! M_244
      & lj_row_type("opls_220", 6, 0.350000_wp, 0.276144_wp), & ! M_15319
      & lj_row_type("opls_221", 6, 0.355000_wp, 0.292880_wp), & ! M_10869
      & lj_row_type("opls_224", 6, 0.350000_wp, 0.276144_wp), & ! M_141892
      & lj_row_type("opls_226", 17, 0.340000_wp, 1.255200_wp), & ! M_10900
      & lj_row_type("opls_227", 6, 0.355000_wp, 0.317984_wp), & ! M_10900
      & lj_row_type("opls_228", 6, 0.355000_wp, 0.292880_wp), & ! M_8766
      & lj_row_type("opls_231", 6, 0.375000_wp, 0.439320_wp), & ! M_211143
      & lj_row_type("opls_232", 6, 0.375000_wp, 0.439320_wp), & ! M_126
      & lj_row_type("opls_233", 6, 0.375000_wp, 0.439320_wp), & ! M_7189
      & lj_row_type("opls_234", 6, 0.375000_wp, 0.439320_wp), & ! M_11916
      & lj_row_type("opls_235", 6, 0.375000_wp, 0.439320_wp), & ! M_101194
      & lj_row_type("opls_236", 8, 0.296000_wp, 0.878640_wp), & ! M_101194
      & lj_row_type("opls_237", 7, 0.325000_wp, 0.711280_wp), & ! M_178
      & lj_row_type("opls_238", 7, 0.325000_wp, 0.711280_wp), & ! M_11954
      & lj_row_type("opls_239", 7, 0.325000_wp, 0.711280_wp), & ! M_101194
      & lj_row_type("opls_240", 1, 0.000000_wp, 0.000000_wp), & ! M_178
      & lj_row_type("opls_241", 1, 0.000000_wp, 0.000000_wp), & ! M_10871
      & lj_row_type("opls_242", 6, 0.350000_wp, 0.276144_wp), & ! M_11954
      & lj_row_type("opls_243", 6, 0.350000_wp, 0.276144_wp), & ! M_101194
      & lj_row_type("opls_244", 6, 0.350000_wp, 0.276144_wp), & ! M_12319
      & lj_row_type("opls_245", 6, 0.350000_wp, 0.276144_wp), & ! M_10975514
      & lj_row_type("opls_246", 6, 0.350000_wp, 0.276144_wp), & ! M_101194
      & lj_row_type("opls_247", 6, 0.375000_wp, 0.439320_wp), & ! M_1176
      & lj_row_type("opls_248", 8, 0.296000_wp, 0.878640_wp), & ! M_1176
      & lj_row_type("opls_249", 7, 0.325000_wp, 0.711280_wp), & ! M_1176
      & lj_row_type("opls_250", 1, 0.000000_wp, 0.000000_wp), & ! M_1176
      & lj_row_type("opls_251", 7, 0.325000_wp, 0.711280_wp), & ! M_11439
      & lj_row_type("opls_252", 6, 0.375000_wp, 0.439320_wp), & ! M_11439
      & lj_row_type("opls_253", 8, 0.296000_wp, 0.878640_wp), & ! M_11439
      & lj_row_type("opls_254", 1, 0.000000_wp, 0.000000_wp), & ! M_11439
      & lj_row_type("opls_257", 6, 0.350000_wp, 0.276144_wp), & ! M_11439
      & lj_row_type("opls_260", 6, 0.355000_wp, 0.292880_wp), & ! M_13019
      & lj_row_type("opls_261", 6, 0.365000_wp, 0.627600_wp), & ! M_13019
      & lj_row_type("opls_262", 7, 0.320000_wp, 0.711280_wp), & ! M_13019
      & lj_row_type("opls_263", 6, 0.355000_wp, 0.292880_wp), & ! M_10871
      & lj_row_type("opls_264", 17, 0.340000_wp, 1.255200_wp), & ! M_10871
      & lj_row_type("opls_265", 7, 0.325000_wp, 0.711280_wp), & ! M_10871
      & lj_row_type("opls_266", 6, 0.355000_wp, 0.292880_wp), & ! M_10871
      & lj_row_type("opls_267", 6, 0.375000_wp, 0.439320_wp)] ! M_1032

   !> Source db_rows 129-256
   type(lj_row_type), parameter :: db_rows_2(128) = [ &
      & lj_row_type("opls_268", 8, 0.300000_wp, 0.711280_wp), & ! M_1032
      & lj_row_type("opls_269", 8, 0.296000_wp, 0.878640_wp), & ! M_1032
      & lj_row_type("opls_270", 1, 0.000000_wp, 0.000000_wp), & ! M_1032
      & lj_row_type("opls_277", 6, 0.375000_wp, 0.439320_wp), & ! M_177
      & lj_row_type("opls_278", 8, 0.296000_wp, 0.878640_wp), & ! M_126
      & lj_row_type("opls_279", 1, 0.242000_wp, 0.062760_wp), & ! M_12319
      & lj_row_type("opls_280", 6, 0.375000_wp, 0.439320_wp), & ! M_12248
      & lj_row_type("opls_281", 8, 0.296000_wp, 0.878640_wp), & ! M_12248
      & lj_row_type("opls_282", 1, 0.242000_wp, 0.062760_wp), & ! M_10908
      & lj_row_type("opls_300", 7, 0.325000_wp, 0.711280_wp), & ! M_10285776
      & lj_row_type("opls_301", 1, 0.000000_wp, 0.000000_wp), & ! M_10285776
      & lj_row_type("opls_302", 6, 0.355000_wp, 0.209200_wp), & ! M_10285776
      & lj_row_type("opls_303", 7, 0.325000_wp, 0.711280_wp), & ! M_86137262
      & lj_row_type("opls_304", 1, 0.000000_wp, 0.000000_wp), & ! M_86137262
      & lj_row_type("opls_311", 7, 0.325000_wp, 0.711280_wp), & ! M_8861
      & lj_row_type("opls_312", 6, 0.350000_wp, 0.334720_wp), & ! M_8861
      & lj_row_type("opls_313", 7, 0.325000_wp, 0.711280_wp), & ! M_8861
      & lj_row_type("opls_314", 1, 0.000000_wp, 0.000000_wp), & ! M_8861
      & lj_row_type("opls_315", 6, 0.350000_wp, 0.334720_wp), & ! M_8861
      & lj_row_type("opls_316", 1, 0.250000_wp, 0.209200_wp), & ! M_8861
      & lj_row_type("opls_317", 6, 0.350000_wp, 0.334720_wp), & ! M_8861
      & lj_row_type("opls_318", 1, 0.250000_wp, 0.209200_wp), & ! M_8861
      & lj_row_type("opls_319", 7, 0.325000_wp, 0.711280_wp), & ! M_1135
      & lj_row_type("opls_320", 6, 0.375000_wp, 0.439320_wp), & ! M_1135
      & lj_row_type("opls_321", 7, 0.325000_wp, 0.711280_wp), & ! M_1135
      & lj_row_type("opls_322", 6, 0.375000_wp, 0.439320_wp), & ! M_1135
      & lj_row_type("opls_323", 6, 0.350000_wp, 0.334720_wp), & ! M_1135
      & lj_row_type("opls_324", 6, 0.350000_wp, 0.334720_wp), & ! M_1135
      & lj_row_type("opls_325", 1, 0.000000_wp, 0.000000_wp), & ! M_1135
      & lj_row_type("opls_326", 8, 0.296000_wp, 0.878640_wp), & ! M_1135
      & lj_row_type("opls_327", 1, 0.000000_wp, 0.000000_wp), & ! M_1135
      & lj_row_type("opls_328", 8, 0.296000_wp, 0.878640_wp), & ! M_1135
      & lj_row_type("opls_329", 1, 0.250000_wp, 0.209200_wp), & ! M_1174
      & lj_row_type("opls_330", 1, 0.250000_wp, 0.209200_wp), & ! M_1135
      & lj_row_type("opls_331", 6, 0.350000_wp, 0.334720_wp), & ! M_1135
      & lj_row_type("opls_332", 1, 0.250000_wp, 0.209200_wp), & ! M_1135
      & lj_row_type("opls_333", 7, 0.325000_wp, 0.711280_wp), & ! M_597
      & lj_row_type("opls_334", 6, 0.375000_wp, 0.439320_wp), & ! M_597
      & lj_row_type("opls_335", 7, 0.325000_wp, 0.711280_wp), & ! M_597
      & lj_row_type("opls_336", 6, 0.350000_wp, 0.334720_wp), & ! M_597
      & lj_row_type("opls_337", 6, 0.350000_wp, 0.334720_wp), & ! M_597
      & lj_row_type("opls_338", 6, 0.350000_wp, 0.334720_wp), & ! M_597
      & lj_row_type("opls_339", 1, 0.000000_wp, 0.000000_wp), & ! M_597
      & lj_row_type("opls_340", 8, 0.296000_wp, 0.878640_wp), & ! M_597
      & lj_row_type("opls_341", 7, 0.325000_wp, 0.711280_wp), & ! M_597
      & lj_row_type("opls_342", 1, 0.000000_wp, 0.000000_wp), & ! M_597
      & lj_row_type("opls_343", 1, 0.000000_wp, 0.000000_wp), & ! M_597
      & lj_row_type("opls_344", 1, 0.250000_wp, 0.209200_wp), & ! M_597
      & lj_row_type("opls_345", 1, 0.250000_wp, 0.209200_wp), & ! M_597
      & lj_row_type("opls_346", 7, 0.325000_wp, 0.711280_wp), & ! M_190
      & lj_row_type("opls_347", 6, 0.350000_wp, 0.334720_wp), & ! M_190
      & lj_row_type("opls_348", 7, 0.325000_wp, 0.711280_wp), & ! M_190
      & lj_row_type("opls_349", 6, 0.350000_wp, 0.334720_wp), & ! M_190
      & lj_row_type("opls_350", 6, 0.350000_wp, 0.334720_wp), & ! M_190
      & lj_row_type("opls_351", 6, 0.350000_wp, 0.334720_wp), & ! M_190
      & lj_row_type("opls_352", 7, 0.325000_wp, 0.711280_wp), & ! M_190
      & lj_row_type("opls_353", 6, 0.350000_wp, 0.334720_wp), & ! M_190
      & lj_row_type("opls_354", 7, 0.325000_wp, 0.711280_wp), & ! M_190
      & lj_row_type("opls_355", 1, 0.250000_wp, 0.209200_wp), & ! M_190
      & lj_row_type("opls_356", 7, 0.325000_wp, 0.711280_wp), & ! M_190
      & lj_row_type("opls_357", 1, 0.000000_wp, 0.000000_wp), & ! M_190
      & lj_row_type("opls_358", 1, 0.000000_wp, 0.000000_wp), & ! M_190
      & lj_row_type("opls_359", 1, 0.250000_wp, 0.209200_wp), & ! M_190
      & lj_row_type("opls_360", 1, 0.000000_wp, 0.000000_wp), & ! M_190
      & lj_row_type("opls_361", 7, 0.325000_wp, 0.711280_wp), & ! M_764
      & lj_row_type("opls_362", 6, 0.350000_wp, 0.334720_wp), & ! M_764
      & lj_row_type("opls_363", 7, 0.325000_wp, 0.711280_wp), & ! M_764
      & lj_row_type("opls_364", 6, 0.350000_wp, 0.334720_wp), & ! M_764
      & lj_row_type("opls_365", 6, 0.350000_wp, 0.334720_wp), & ! M_764
      & lj_row_type("opls_366", 6, 0.375000_wp, 0.439320_wp), & ! M_764
      & lj_row_type("opls_367", 1, 0.000000_wp, 0.000000_wp), & ! M_764
      & lj_row_type("opls_368", 7, 0.325000_wp, 0.711280_wp), & ! M_764
      & lj_row_type("opls_369", 1, 0.000000_wp, 0.000000_wp), & ! M_764
      & lj_row_type("opls_370", 8, 0.296000_wp, 0.878640_wp), & ! M_764
      & lj_row_type("opls_397", 6, 0.350000_wp, 0.334720_wp), & ! M_5899
      & lj_row_type("opls_398", 17, 0.340000_wp, 1.255200_wp), & ! M_6575
      & lj_row_type("opls_399", 6, 0.355000_wp, 0.317984_wp), & ! M_6575
      & lj_row_type("opls_415", 6, 0.420000_wp, 1.255200_wp), & ! M_878
      & lj_row_type("opls_416", 1, 0.250000_wp, 0.209200_wp), & ! M_878
      & lj_row_type("opls_417", 16, 0.425000_wp, 2.092000_wp), & ! M_878
      & lj_row_type("opls_418", 6, 0.420000_wp, 1.255200_wp), & ! M_887
      & lj_row_type("opls_419", 1, 0.250000_wp, 0.209200_wp), & ! M_887
      & lj_row_type("opls_420", 8, 0.315000_wp, 1.046000_wp), & ! M_887
      & lj_row_type("opls_465", 6, 0.375000_wp, 0.439320_wp), & ! M_10908
      & lj_row_type("opls_466", 8, 0.296000_wp, 0.878640_wp), & ! M_10908
      & lj_row_type("opls_467", 8, 0.300000_wp, 0.711280_wp), & ! M_10908
      & lj_row_type("opls_468", 6, 0.350000_wp, 0.276144_wp), & ! M_11124
      & lj_row_type("opls_469", 1, 0.242000_wp, 0.062760_wp), & ! M_11124
      & lj_row_type("opls_470", 6, 0.375000_wp, 0.439320_wp), & ! M_243
      & lj_row_type("opls_471", 6, 0.375000_wp, 0.439320_wp), & ! M_13654
      & lj_row_type("opls_472", 6, 0.355000_wp, 0.292880_wp), & ! M_31229
      & lj_row_type("opls_473", 8, 0.300000_wp, 0.711280_wp), & ! M_31229
      & lj_row_type("opls_474", 16, 0.355000_wp, 1.046000_wp), & ! M_70970
      & lj_row_type("opls_475", 8, 0.296000_wp, 0.711280_wp), & ! M_70970
      & lj_row_type("opls_476", 6, 0.350000_wp, 0.276144_wp), & ! M_70970
      & lj_row_type("opls_477", 1, 0.250000_wp, 0.125520_wp), & ! M_70970
      & lj_row_type("opls_478", 7, 0.325000_wp, 0.711280_wp), & ! M_72879
      & lj_row_type("opls_479", 1, 0.000000_wp, 0.000000_wp), & ! M_72879
      & lj_row_type("opls_480", 7, 0.325000_wp, 0.711280_wp), & ! M_97632
      & lj_row_type("opls_481", 1, 0.000000_wp, 0.000000_wp), & ! M_70970
      & lj_row_type("opls_482", 6, 0.350000_wp, 0.276144_wp), & ! M_97632
      & lj_row_type("opls_483", 1, 0.250000_wp, 0.125520_wp), & ! M_97632
      & lj_row_type("opls_488", 6, 0.355000_wp, 0.292880_wp), & ! M_7370
      & lj_row_type("opls_489", 6, 0.355000_wp, 0.292880_wp), & ! M_138143
      & lj_row_type("opls_490", 6, 0.350000_wp, 0.276144_wp), & ! M_7165
      & lj_row_type("opls_491", 6, 0.350000_wp, 0.276144_wp), & ! M_13654
      & lj_row_type("opls_492", 6, 0.350000_wp, 0.276144_wp), & ! M_10908
      & lj_row_type("opls_493", 16, 0.355000_wp, 1.046000_wp), & ! M_138400
      & lj_row_type("opls_494", 8, 0.296000_wp, 0.711280_wp), & ! M_138400
      & lj_row_type("opls_495", 16, 0.356000_wp, 1.652680_wp), & ! M_138143
      & lj_row_type("opls_496", 16, 0.356000_wp, 1.652680_wp), & ! M_534965
      & lj_row_type("opls_497", 8, 0.293000_wp, 1.171520_wp), & ! M_138143
      & lj_row_type("opls_498", 6, 0.350000_wp, 0.276144_wp), & ! M_14516
      & lj_row_type("opls_499", 6, 0.350000_wp, 0.276144_wp), & ! M_138143
      & lj_row_type("opls_515", 6, 0.350000_wp, 0.276144_wp), & ! M_1302
      & lj_row_type("opls_516", 6, 0.350000_wp, 0.276144_wp), & ! M_13065
      & lj_row_type("opls_517", 6, 0.355000_wp, 0.317984_wp), & ! M_221523
      & lj_row_type("opls_519", 6, 0.355000_wp, 0.292880_wp), & ! M_11795
      & lj_row_type("opls_520", 7, 0.325000_wp, 0.711280_wp), & ! M_1049
      & lj_row_type("opls_521", 6, 0.355000_wp, 0.292880_wp), & ! M_1049
      & lj_row_type("opls_522", 6, 0.355000_wp, 0.292880_wp), & ! M_1049
      & lj_row_type("opls_523", 6, 0.355000_wp, 0.292880_wp), & ! M_1049
      & lj_row_type("opls_524", 1, 0.242000_wp, 0.125520_wp), & ! M_1049
      & lj_row_type("opls_525", 1, 0.242000_wp, 0.125520_wp), & ! M_1049
      & lj_row_type("opls_526", 1, 0.242000_wp, 0.125520_wp), & ! M_1049
      & lj_row_type("opls_527", 7, 0.325000_wp, 0.711280_wp), & ! M_9261
      & lj_row_type("opls_528", 6, 0.355000_wp, 0.292880_wp), & ! M_9261
      & lj_row_type("opls_529", 1, 0.242000_wp, 0.125520_wp)] ! M_9261

   !> Source db_rows 257-384
   type(lj_row_type), parameter :: db_rows_3(128) = [ &
      & lj_row_type("opls_530", 7, 0.325000_wp, 0.711280_wp), & ! M_9260
      & lj_row_type("opls_531", 6, 0.355000_wp, 0.292880_wp), & ! M_9260
      & lj_row_type("opls_532", 6, 0.355000_wp, 0.292880_wp), & ! M_9260
      & lj_row_type("opls_533", 6, 0.355000_wp, 0.292880_wp), & ! M_9260
      & lj_row_type("opls_534", 1, 0.242000_wp, 0.125520_wp), & ! M_9260
      & lj_row_type("opls_535", 1, 0.242000_wp, 0.125520_wp), & ! M_9260
      & lj_row_type("opls_536", 1, 0.242000_wp, 0.125520_wp), & ! M_9260
      & lj_row_type("opls_537", 7, 0.325000_wp, 0.711280_wp), & ! M_9259
      & lj_row_type("opls_538", 6, 0.355000_wp, 0.292880_wp), & ! M_9259
      & lj_row_type("opls_539", 6, 0.355000_wp, 0.292880_wp), & ! M_9259
      & lj_row_type("opls_54", 6, 0.355000_wp, 0.276144_wp), & ! M_7843
      & lj_row_type("opls_540", 1, 0.242000_wp, 0.125520_wp), & ! M_9259
      & lj_row_type("opls_541", 1, 0.242000_wp, 0.125520_wp), & ! M_9259
      & lj_row_type("opls_542", 7, 0.325000_wp, 0.711280_wp), & ! M_137075
      & lj_row_type("opls_543", 6, 0.355000_wp, 0.292880_wp), & ! M_137075
      & lj_row_type("opls_544", 6, 0.355000_wp, 0.292880_wp), & ! M_137075
      & lj_row_type("opls_545", 1, 0.000000_wp, 0.000000_wp), & ! M_137075
      & lj_row_type("opls_546", 1, 0.242000_wp, 0.125520_wp), & ! M_137075
      & lj_row_type("opls_547", 1, 0.242000_wp, 0.125520_wp), & ! M_137075
      & lj_row_type("opls_548", 7, 0.325000_wp, 0.711280_wp), & ! M_1048
      & lj_row_type("opls_549", 7, 0.325000_wp, 0.711280_wp), & ! M_1048
      & lj_row_type("opls_55", 6, 0.341000_wp, 0.276144_wp), & ! M_10907
      & lj_row_type("opls_550", 6, 0.355000_wp, 0.292880_wp), & ! M_1048
      & lj_row_type("opls_551", 6, 0.355000_wp, 0.292880_wp), & ! M_1048
      & lj_row_type("opls_552", 6, 0.355000_wp, 0.292880_wp), & ! M_1048
      & lj_row_type("opls_553", 1, 0.000000_wp, 0.000000_wp), & ! M_1048
      & lj_row_type("opls_554", 1, 0.242000_wp, 0.125520_wp), & ! M_1048
      & lj_row_type("opls_555", 1, 0.242000_wp, 0.125520_wp), & ! M_1048
      & lj_row_type("opls_556", 1, 0.242000_wp, 0.125520_wp), & ! M_1048
      & lj_row_type("opls_557", 7, 0.325000_wp, 0.711280_wp), & ! M_69590
      & lj_row_type("opls_558", 6, 0.355000_wp, 0.292880_wp), & ! M_69590
      & lj_row_type("opls_559", 7, 0.325000_wp, 0.711280_wp), & ! M_69590
      & lj_row_type("opls_56", 6, 0.334000_wp, 0.276144_wp), & ! M_10907
      & lj_row_type("opls_560", 6, 0.355000_wp, 0.292880_wp), & ! M_795
      & lj_row_type("opls_561", 6, 0.355000_wp, 0.292880_wp), & ! M_69590
      & lj_row_type("opls_562", 1, 0.000000_wp, 0.000000_wp), & ! M_69590
      & lj_row_type("opls_563", 1, 0.242000_wp, 0.125520_wp), & ! M_69590
      & lj_row_type("opls_564", 1, 0.242000_wp, 0.125520_wp), & ! M_795
      & lj_row_type("opls_565", 1, 0.242000_wp, 0.125520_wp), & ! M_69590
      & lj_row_type("opls_566", 8, 0.290000_wp, 0.585760_wp), & ! M_518802
      & lj_row_type("opls_567", 6, 0.355000_wp, 0.292880_wp), & ! M_518802
      & lj_row_type("opls_568", 6, 0.355000_wp, 0.317984_wp), & ! M_518802
      & lj_row_type("opls_569", 1, 0.242000_wp, 0.125520_wp), & ! M_518802
      & lj_row_type("opls_57", 6, 0.351000_wp, 0.276144_wp), & ! M_10907
      & lj_row_type("opls_570", 1, 0.242000_wp, 0.125520_wp), & ! M_518802
      & lj_row_type("opls_571", 8, 0.290000_wp, 0.585760_wp), & ! M_9255
      & lj_row_type("opls_572", 6, 0.355000_wp, 0.292880_wp), & ! M_9255
      & lj_row_type("opls_573", 7, 0.325000_wp, 0.711280_wp), & ! M_9255
      & lj_row_type("opls_574", 6, 0.355000_wp, 0.292880_wp), & ! M_9255
      & lj_row_type("opls_575", 6, 0.355000_wp, 0.292880_wp), & ! M_9255
      & lj_row_type("opls_576", 1, 0.242000_wp, 0.125520_wp), & ! M_9255
      & lj_row_type("opls_577", 1, 0.242000_wp, 0.125520_wp), & ! M_9255
      & lj_row_type("opls_578", 1, 0.242000_wp, 0.125520_wp), & ! M_9255
      & lj_row_type("opls_579", 8, 0.290000_wp, 0.585760_wp), & ! M_9254
      & lj_row_type("opls_58", 6, 0.350000_wp, 0.276144_wp), & ! M_10907
      & lj_row_type("opls_580", 7, 0.325000_wp, 0.711280_wp), & ! M_9254
      & lj_row_type("opls_581", 6, 0.355000_wp, 0.292880_wp), & ! M_9254
      & lj_row_type("opls_582", 6, 0.355000_wp, 0.292880_wp), & ! M_9254
      & lj_row_type("opls_583", 6, 0.355000_wp, 0.292880_wp), & ! M_9254
      & lj_row_type("opls_584", 1, 0.242000_wp, 0.125520_wp), & ! M_9254
      & lj_row_type("opls_585", 1, 0.242000_wp, 0.125520_wp), & ! M_9254
      & lj_row_type("opls_586", 1, 0.242000_wp, 0.125520_wp), & ! M_9254
      & lj_row_type("opls_587", 7, 0.325000_wp, 0.711280_wp), & ! M_6736
      & lj_row_type("opls_588", 6, 0.355000_wp, 0.292880_wp), & ! M_6736
      & lj_row_type("opls_589", 6, 0.355000_wp, 0.292880_wp), & ! M_6736
      & lj_row_type("opls_59", 6, 0.350000_wp, 0.276144_wp), & ! M_10907
      & lj_row_type("opls_590", 6, 0.355000_wp, 0.292880_wp), & ! M_6736
      & lj_row_type("opls_591", 6, 0.355000_wp, 0.292880_wp), & ! M_6736
      & lj_row_type("opls_592", 6, 0.355000_wp, 0.292880_wp), & ! M_6736
      & lj_row_type("opls_593", 6, 0.355000_wp, 0.292880_wp), & ! M_6736
      & lj_row_type("opls_594", 6, 0.355000_wp, 0.292880_wp), & ! M_6736
      & lj_row_type("opls_595", 6, 0.355000_wp, 0.292880_wp), & ! M_6736
      & lj_row_type("opls_596", 1, 0.000000_wp, 0.000000_wp), & ! M_6736
      & lj_row_type("opls_597", 1, 0.242000_wp, 0.125520_wp), & ! M_6736
      & lj_row_type("opls_598", 1, 0.242000_wp, 0.125520_wp), & ! M_798
      & lj_row_type("opls_599", 1, 0.242000_wp, 0.125520_wp), & ! M_6736
      & lj_row_type("opls_60", 1, 0.250000_wp, 0.117152_wp), & ! M_10907
      & lj_row_type("opls_600", 1, 0.242000_wp, 0.125520_wp), & ! M_6736
      & lj_row_type("opls_601", 1, 0.242000_wp, 0.125520_wp), & ! M_6736
      & lj_row_type("opls_602", 1, 0.242000_wp, 0.125520_wp), & ! M_6736
      & lj_row_type("opls_603", 7, 0.325000_wp, 0.711280_wp), & ! M_7047
      & lj_row_type("opls_604", 6, 0.355000_wp, 0.292880_wp), & ! M_7047
      & lj_row_type("opls_605", 6, 0.355000_wp, 0.292880_wp), & ! M_7047
      & lj_row_type("opls_606", 6, 0.355000_wp, 0.292880_wp), & ! M_7047
      & lj_row_type("opls_607", 6, 0.355000_wp, 0.292880_wp), & ! M_7047
      & lj_row_type("opls_608", 6, 0.355000_wp, 0.292880_wp), & ! M_7047
      & lj_row_type("opls_609", 6, 0.355000_wp, 0.292880_wp), & ! M_7047
      & lj_row_type("opls_610", 6, 0.355000_wp, 0.292880_wp), & ! M_7047
      & lj_row_type("opls_611", 6, 0.355000_wp, 0.292880_wp), & ! M_7047
      & lj_row_type("opls_612", 6, 0.355000_wp, 0.292880_wp), & ! M_7047
      & lj_row_type("opls_613", 1, 0.242000_wp, 0.125520_wp), & ! M_7047
      & lj_row_type("opls_614", 1, 0.242000_wp, 0.125520_wp), & ! M_7047
      & lj_row_type("opls_615", 1, 0.242000_wp, 0.125520_wp), & ! M_7047
      & lj_row_type("opls_616", 1, 0.242000_wp, 0.125520_wp), & ! M_7047
      & lj_row_type("opls_617", 1, 0.242000_wp, 0.125520_wp), & ! M_7047
      & lj_row_type("opls_618", 1, 0.242000_wp, 0.125520_wp), & ! M_7047
      & lj_row_type("opls_619", 1, 0.242000_wp, 0.125520_wp), & ! M_7047
      & lj_row_type("opls_620", 7, 0.325000_wp, 0.711280_wp), & ! M_1044
      & lj_row_type("opls_621", 6, 0.355000_wp, 0.292880_wp), & ! M_1044
      & lj_row_type("opls_622", 7, 0.325000_wp, 0.711280_wp), & ! M_1044
      & lj_row_type("opls_623", 6, 0.355000_wp, 0.292880_wp), & ! M_1044
      & lj_row_type("opls_624", 6, 0.355000_wp, 0.292880_wp), & ! M_1044
      & lj_row_type("opls_625", 6, 0.355000_wp, 0.292880_wp), & ! M_1044
      & lj_row_type("opls_626", 7, 0.325000_wp, 0.711280_wp), & ! M_1044
      & lj_row_type("opls_627", 6, 0.355000_wp, 0.292880_wp), & ! M_1044
      & lj_row_type("opls_628", 7, 0.325000_wp, 0.711280_wp), & ! M_1044
      & lj_row_type("opls_629", 1, 0.242000_wp, 0.125520_wp), & ! M_1044
      & lj_row_type("opls_630", 1, 0.242000_wp, 0.125520_wp), & ! M_1044
      & lj_row_type("opls_631", 1, 0.242000_wp, 0.125520_wp), & ! M_1044
      & lj_row_type("opls_632", 1, 0.000000_wp, 0.000000_wp), & ! M_1044
      & lj_row_type("opls_633", 16, 0.360000_wp, 1.485320_wp), & ! M_9256
      & lj_row_type("opls_634", 6, 0.355000_wp, 0.292880_wp), & ! M_9256
      & lj_row_type("opls_635", 7, 0.325000_wp, 0.711280_wp), & ! M_9256
      & lj_row_type("opls_636", 6, 0.355000_wp, 0.292880_wp), & ! M_9256
      & lj_row_type("opls_637", 6, 0.355000_wp, 0.292880_wp), & ! M_9256
      & lj_row_type("opls_638", 1, 0.242000_wp, 0.125520_wp), & ! M_9256
      & lj_row_type("opls_639", 1, 0.242000_wp, 0.125520_wp), & ! M_9256
      & lj_row_type("opls_640", 1, 0.242000_wp, 0.125520_wp), & ! M_9256
      & lj_row_type("opls_641", 7, 0.325000_wp, 0.711280_wp), & ! M_9262
      & lj_row_type("opls_642", 6, 0.355000_wp, 0.292880_wp), & ! M_9262
      & lj_row_type("opls_643", 1, 0.242000_wp, 0.125520_wp), & ! M_9262
      & lj_row_type("opls_646", 7, 0.325000_wp, 0.711280_wp), & ! M_1318
      & lj_row_type("opls_647", 6, 0.355000_wp, 0.292880_wp), & ! M_1318
      & lj_row_type("opls_648", 6, 0.355000_wp, 0.292880_wp), & ! M_1318
      & lj_row_type("opls_649", 6, 0.355000_wp, 0.292880_wp), & ! M_1318
      & lj_row_type("opls_650", 6, 0.355000_wp, 0.292880_wp), & ! M_1318
      & lj_row_type("opls_651", 6, 0.355000_wp, 0.292880_wp), & ! M_1318
      & lj_row_type("opls_652", 6, 0.355000_wp, 0.292880_wp)] ! M_1318

   !> Source db_rows 385-512
   type(lj_row_type), parameter :: db_rows_4(128) = [ &
      & lj_row_type("opls_653", 1, 0.242000_wp, 0.125520_wp), & ! M_1318
      & lj_row_type("opls_654", 1, 0.242000_wp, 0.125520_wp), & ! M_1318
      & lj_row_type("opls_655", 1, 0.242000_wp, 0.125520_wp), & ! M_1318
      & lj_row_type("opls_656", 1, 0.242000_wp, 0.125520_wp), & ! M_1318
      & lj_row_type("opls_657", 7, 0.325000_wp, 0.711280_wp), & ! M_1390
      & lj_row_type("opls_658", 6, 0.355000_wp, 0.292880_wp), & ! M_1390
      & lj_row_type("opls_659", 7, 0.325000_wp, 0.711280_wp), & ! M_1390
      & lj_row_type("opls_660", 6, 0.355000_wp, 0.292880_wp), & ! M_1390
      & lj_row_type("opls_661", 6, 0.355000_wp, 0.292880_wp), & ! M_1390
      & lj_row_type("opls_662", 6, 0.350000_wp, 0.276144_wp), & ! M_1390
      & lj_row_type("opls_663", 1, 0.242000_wp, 0.125520_wp), & ! M_1390
      & lj_row_type("opls_664", 1, 0.242000_wp, 0.125520_wp), & ! M_1390
      & lj_row_type("opls_665", 1, 0.242000_wp, 0.125520_wp), & ! M_1390
      & lj_row_type("opls_666", 1, 0.250000_wp, 0.125520_wp), & ! M_1390
      & lj_row_type("opls_669", 6, 0.350000_wp, 0.276144_wp), & ! M_88359
      & lj_row_type("opls_679", 6, 0.350000_wp, 0.276144_wp), & ! M_137075
      & lj_row_type("opls_689", 6, 0.350000_wp, 0.276144_wp), & ! M_6736
      & lj_row_type("opls_690", 6, 0.355000_wp, 0.292880_wp), & ! M_13887
      & lj_row_type("opls_691", 6, 0.355000_wp, 0.292880_wp), & ! M_13887
      & lj_row_type("opls_692", 6, 0.355000_wp, 0.292880_wp), & ! M_13886
      & lj_row_type("opls_693", 6, 0.355000_wp, 0.292880_wp), & ! M_13886
      & lj_row_type("opls_694", 6, 0.355000_wp, 0.292880_wp), & ! M_13651
      & lj_row_type("opls_695", 6, 0.355000_wp, 0.292880_wp), & ! M_13651
      & lj_row_type("opls_696", 16, 0.360000_wp, 1.485320_wp), & ! M_8766
      & lj_row_type("opls_700", 6, 0.355000_wp, 0.317984_wp), & ! M_6360
      & lj_row_type("opls_701", 6, 0.350000_wp, 0.276144_wp), & ! M_6360
      & lj_row_type("opls_702", 1, 0.250000_wp, 0.125520_wp), & ! M_6360
      & lj_row_type("opls_711", 6, 0.343000_wp, 0.368192_wp), & ! M_10888024
      & lj_row_type("opls_712", 6, 0.343000_wp, 0.368192_wp), & ! M_10888024
      & lj_row_type("opls_713", 6, 0.343000_wp, 0.368192_wp), & ! M_74202
      & lj_row_type("opls_718", 6, 0.355000_wp, 0.292880_wp), & ! M_10008
      & lj_row_type("opls_719", 9, 0.285000_wp, 0.255224_wp), & ! M_10008
      & lj_row_type("opls_724", 6, 0.355000_wp, 0.292880_wp), & ! M_7368
      & lj_row_type("opls_725", 6, 0.325000_wp, 0.259408_wp), & ! M_5899
      & lj_row_type("opls_726", 9, 0.294000_wp, 0.255224_wp), & ! M_5899
      & lj_row_type("opls_727", 6, 0.355000_wp, 0.292880_wp), & ! M_9741
      & lj_row_type("opls_728", 9, 0.285000_wp, 0.255224_wp), & ! M_9741
      & lj_row_type("opls_729", 6, 0.355000_wp, 0.292880_wp), & ! M_7808
      & lj_row_type("opls_730", 35, 0.347000_wp, 1.966480_wp), & ! M_7808
      & lj_row_type("opls_731", 6, 0.355000_wp, 0.292880_wp), & ! M_10784
      & lj_row_type("opls_732", 53, 0.375000_wp, 2.510400_wp), & ! M_10784
      & lj_row_type("opls_733", 6, 0.350000_wp, 0.276144_wp), & ! M_138219
      & lj_row_type("opls_734", 16, 0.360000_wp, 1.778200_wp), & ! M_7969
      & lj_row_type("opls_735", 6, 0.355000_wp, 0.292880_wp), & ! M_7969
      & lj_row_type("opls_736", 6, 0.355000_wp, 0.292880_wp), & ! M_6367052
      & lj_row_type("opls_737", 6, 0.355000_wp, 0.292880_wp), & ! M_6367052
      & lj_row_type("opls_738", 6, 0.355000_wp, 0.292880_wp), & ! M_6367052
      & lj_row_type("opls_739", 6, 0.355000_wp, 0.292880_wp), & ! M_6367052
      & lj_row_type("opls_740", 1, 0.242000_wp, 0.125520_wp), & ! M_6367052
      & lj_row_type("opls_741", 1, 0.242000_wp, 0.125520_wp), & ! M_6367052
      & lj_row_type("opls_742", 6, 0.355000_wp, 0.209200_wp), & ! M_6367052
      & lj_row_type("opls_743", 7, 0.325000_wp, 0.711280_wp), & ! M_6367052
      & lj_row_type("opls_744", 1, 0.000000_wp, 0.000000_wp), & ! M_6367052
      & lj_row_type("opls_745", 1, 0.000000_wp, 0.000000_wp), & ! M_6367052
      & lj_row_type("opls_746", 1, 0.242000_wp, 0.125520_wp), & ! M_6367052
      & lj_row_type("opls_753", 7, 0.320000_wp, 0.711280_wp), & ! M_10994
      & lj_row_type("opls_754", 6, 0.330000_wp, 0.276144_wp), & ! M_10994
      & lj_row_type("opls_756", 6, 0.330000_wp, 0.276144_wp), & ! M_10994
      & lj_row_type("opls_757", 6, 0.330000_wp, 0.276144_wp), & ! M_11423741
      & lj_row_type("opls_759", 1, 0.250000_wp, 0.062760_wp), & ! M_10994
      & lj_row_type("opls_760", 7, 0.325000_wp, 0.502080_wp), & ! M_6375
      & lj_row_type("opls_761", 8, 0.296000_wp, 0.711280_wp), & ! M_6375
      & lj_row_type("opls_762", 6, 0.350000_wp, 0.276144_wp), & ! M_6375
      & lj_row_type("opls_763", 1, 0.250000_wp, 0.062760_wp), & ! M_6375
      & lj_row_type("opls_764", 6, 0.350000_wp, 0.276144_wp), & ! M_6587
      & lj_row_type("opls_767", 7, 0.325000_wp, 0.502080_wp), & ! M_7416
      & lj_row_type("opls_768", 6, 0.355000_wp, 0.292880_wp), & ! M_7416
      & lj_row_type("opls_769", 6, 0.330000_wp, 0.276144_wp), & ! M_8794
      & lj_row_type("opls_771", 8, 0.296000_wp, 0.878640_wp), & ! M_12021
      & lj_row_type("opls_772", 6, 0.375000_wp, 0.439320_wp), & ! M_12021
      & lj_row_type("opls_773", 8, 0.300000_wp, 0.711280_wp), & ! M_12021
      & lj_row_type("opls_774", 6, 0.350000_wp, 0.276144_wp), & ! M_7924
      & lj_row_type("opls_775", 6, 0.350000_wp, 0.276144_wp), & ! M_7924
      & lj_row_type("opls_776", 6, 0.350000_wp, 0.276144_wp), & ! M_7924
      & lj_row_type("opls_777", 1, 0.242000_wp, 0.062760_wp), & ! M_7924
      & lj_row_type("opls_778", 1, 0.242000_wp, 0.062760_wp), & ! M_7924
      & lj_row_type("opls_779", 1, 0.242000_wp, 0.062760_wp), & ! M_7924
      & lj_row_type("opls_781", 15, 0.374000_wp, 0.836800_wp), & ! M_199509
      & lj_row_type("opls_782", 6, 0.350000_wp, 0.276144_wp), & ! M_199509
      & lj_row_type("opls_783", 6, 0.350000_wp, 0.276144_wp), & ! M_199509
      & lj_row_type("opls_784", 1, 0.250000_wp, 0.125520_wp), & ! M_199509
      & lj_row_type("opls_789", 6, 0.350000_wp, 0.276144_wp), & ! M_12021
      & lj_row_type("opls_793", 6, 0.355000_wp, 0.292880_wp), & ! M_86137262
      & lj_row_type("opls_900", 7, 0.330000_wp, 0.711280_wp), & ! M_10824
      & lj_row_type("opls_901", 7, 0.330000_wp, 0.711280_wp), & ! M_10422
      & lj_row_type("opls_902", 7, 0.330000_wp, 0.711280_wp), & ! M_1146
      & lj_row_type("opls_903", 6, 0.350000_wp, 0.276144_wp), & ! M_6329
      & lj_row_type("opls_904", 6, 0.350000_wp, 0.276144_wp), & ! M_12219
      & lj_row_type("opls_905", 6, 0.350000_wp, 0.276144_wp), & ! M_1146
      & lj_row_type("opls_906", 6, 0.350000_wp, 0.276144_wp), & ! M_13369
      & lj_row_type("opls_907", 6, 0.350000_wp, 0.276144_wp), & ! M_10422
      & lj_row_type("opls_908", 6, 0.350000_wp, 0.276144_wp), & ! M_11723
      & lj_row_type("opls_909", 1, 0.000000_wp, 0.000000_wp), & ! M_10824
      & lj_row_type("opls_910", 1, 0.000000_wp, 0.000000_wp), & ! M_10422
      & lj_row_type("opls_911", 1, 0.250000_wp, 0.062760_wp), & ! M_10422
      & lj_row_type("opls_916", 6, 0.355000_wp, 0.292880_wp), & ! M_10824
      & lj_row_type("opls_917", 6, 0.355000_wp, 0.292880_wp), & ! M_11487
      & lj_row_type("opls_918", 6, 0.355000_wp, 0.292880_wp), & ! M_20038
      & lj_row_type("opls_919", 6, 0.350000_wp, 0.276144_wp), & ! M_7504
      & lj_row_type("opls_922", 6, 0.350000_wp, 0.276144_wp), & ! M_10869
      & lj_row_type("opls_924", 6, 0.350000_wp, 0.276144_wp), & ! M_7669
      & lj_row_type("opls_925", 6, 0.330000_wp, 0.359824_wp), & ! M_12309
      & lj_row_type("opls_926", 1, 0.242000_wp, 0.062760_wp), & ! M_12309
      & lj_row_type("opls_927", 6, 0.330000_wp, 0.878640_wp), & ! M_12309
      & lj_row_type("opls_930", 1, 0.250000_wp, 0.062760_wp), & ! M_12309
      & lj_row_type("opls_939", 6, 0.330000_wp, 0.878640_wp), & ! M_10390
      & lj_row_type("opls_946", 6, 0.355000_wp, 0.292880_wp), & ! M_519363
      & lj_row_type("opls_947", 6, 0.355000_wp, 0.317984_wp), & ! M_518802
      & lj_row_type("opls_948", 6, 0.355000_wp, 0.292880_wp), & ! M_519363
      & lj_row_type("opls_949", 6, 0.355000_wp, 0.292880_wp), & ! M_518802
      & lj_row_type("opls_956", 9, 0.294000_wp, 0.255224_wp), & ! M_12223
      & lj_row_type("opls_957", 6, 0.350000_wp, 0.276144_wp), & ! M_12223
      & lj_row_type("opls_958", 1, 0.250000_wp, 0.125520_wp), & ! M_12223
      & lj_row_type("opls_959", 6, 0.350000_wp, 0.276144_wp), & ! M_78988
      & lj_row_type("opls_961", 6, 0.350000_wp, 0.276144_wp), & ! M_6422
      & lj_row_type("opls_965", 9, 0.295000_wp, 0.221752_wp), & ! M_6422
      & lj_row_type("opls_966", 6, 0.325000_wp, 0.259408_wp), & ! M_640452
      & lj_row_type("opls_967", 1, 0.250000_wp, 0.125520_wp), & ! M_640452
      & lj_row_type("opls_970", 17, 0.340000_wp, 1.255200_wp), & ! M_10952
      & lj_row_type("opls_971", 6, 0.350000_wp, 0.276144_wp), & ! M_300
      & lj_row_type("opls_972", 1, 0.250000_wp, 0.125520_wp), & ! M_10952
      & lj_row_type("opls_973", 6, 0.350000_wp, 0.276144_wp), & ! M_10952
      & lj_row_type("opls_975", 35, 0.347000_wp, 1.966480_wp), & ! M_6227
      & lj_row_type("opls_976", 6, 0.350000_wp, 0.276144_wp), & ! M_6227
      & lj_row_type("opls_977", 1, 0.250000_wp, 0.125520_wp), & ! M_6227
      & lj_row_type("opls_980", 9, 0.294000_wp, 0.255224_wp), & ! M_67937
      & lj_row_type("opls_981", 17, 0.340000_wp, 1.255200_wp), & ! M_62324
      & lj_row_type("opls_982", 35, 0.347000_wp, 1.966480_wp)] ! M_69018

   !> Source db_rows 513-526
   type(lj_row_type), parameter :: db_rows_5(14) = [ &
      & lj_row_type("opls_983", 6, 0.355000_wp, 0.292880_wp), & ! M_68010
      & lj_row_type("opls_984", 8, 0.290000_wp, 0.585760_wp), & ! M_68010
      & lj_row_type("opls_985", 6, 0.350000_wp, 0.276144_wp), & ! M_68010
      & lj_row_type("opls_986", 9, 0.290000_wp, 0.251040_wp), & ! M_68010
      & lj_row_type("opls_987", 7, 0.325000_wp, 0.711280_wp), & ! M_11364
      & lj_row_type("opls_988", 6, 0.355000_wp, 0.292880_wp), & ! M_11364
      & lj_row_type("opls_989", 6, 0.350000_wp, 0.276144_wp), & ! M_7681
      & lj_row_type("opls_990", 6, 0.375000_wp, 0.439320_wp), & ! M_1990
      & lj_row_type("opls_992", 8, 0.296000_wp, 0.878640_wp), & ! M_1990
      & lj_row_type("opls_993", 7, 0.325000_wp, 0.711280_wp), & ! M_1990
      & lj_row_type("opls_994", 1, 0.000000_wp, 0.000000_wp), & ! M_1990
      & lj_row_type("opls_995", 8, 0.312000_wp, 0.711280_wp), & ! M_1990
      & lj_row_type("opls_996", 1, 0.000000_wp, 0.000000_wp), & ! M_1990
      & lj_row_type("opls_997", 6, 0.350000_wp, 0.276144_wp)] ! M_312683

   !> Complete source table
   type(lj_row_type), parameter :: db_rows(n_oplsaa_database) = [ &
      & db_rows_1, db_rows_2, db_rows_3, db_rows_4, db_rows_5]

! Parameter data licensed under CC BY 4.0
! https://creativecommons.org/licenses/by/4.0/
!
! Gajanan Kanagalingam, Sebastian Schmitt, Florian Fleckenstein, Simon Stephan
! TUK-FFDat, version 1 (2023), https://doi.org/10.5281/zenodo.8116422
! TUK-FFDat_OPLS-AA.xlsx, intermolecular sheet, rows 2-126
! Workbook SHA256: 9f0397e304c6d4e5e48f3002f49136f352292d4987418b60b49714af6a999424
! Data scheme: https://doi.org/10.1038/s41597-023-02369-8
!
! Changes: extracted LJ rows, lowercased tags, inferred atomic numbers from
! site labels (CC is aromatic C; CN is aromatic N), added Fortran lookup
! Charges and bonded parameters are omitted; X is literal in lookup keys
!
! Energy correction: workbook p2 is not eV as stated in the paper's Table 9
! All p2 values equal original OPLS epsilon in kcal/mol times
! 503.5803505638939, consistent with an approximate epsilon/kB conversion
! Restored the original kcal/mol values rather than treating p2 as eV or
! kelvin; every restored value is exactly on the source's 0.001 kcal/mol grid
! 124 of 125 element/sigma/epsilon combinations agree with OPLSAA-DB
! The remaining disulfide S row retains TUK's sigma=3.50 and epsilon=0.250
! No sigma correction is applied; source p3 is sigma in Angstrom
! Mixing follows native OPLS geometric rules, not the data scheme's ID 3
! This is a subset with chemical tags, not numerical OPLS atomtype IDs
! Each row retains the workbook's original parameter reference DOI

   !> Source tuk_rows 1-125
   type(lj_row_type), parameter :: tuk_rows_1(125) = [ &
      & lj_row_type("a-c-0-0", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("a-c-1-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("a-c-2-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("a-c-3-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("a-c-4-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("x-h-c-x"//achar(92)//"0", 1, 2.5_wp, 0.030_wp), & ! 10.1021/ja9621760
      & lj_row_type("x-h-c-x"//achar(92)//"1", 1, 2.5_wp, 0.030_wp), & ! 10.1021/ja9621760
      & lj_row_type("a-c-3-2", 6, 3.55_wp, 0.076_wp), & ! 10.1021/ja9621760
      & lj_row_type("a-c-2-2", 6, 3.55_wp, 0.076_wp), & ! 10.1021/ja9621760
      & lj_row_type("a-c-1-2", 6, 3.55_wp, 0.076_wp), & ! 10.1021/ja9621760
      & lj_row_type("x-h-c-x"//achar(92)//"2", 1, 2.42_wp, 0.030_wp), & ! 10.1021/ja9621760
      & lj_row_type("ak-o-1-1", 8, 3.12_wp, 0.170_wp), & ! 10.1021/ja9621760
      & lj_row_type("ak-c-1-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("ak-c-2-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("ak-c-3-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("ak-c-4-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("ak-h-o-1"//achar(92)//"1", 1, 0.0_wp, 0.000_wp), & ! 10.1021/ja9621760
      & lj_row_type("ak-h-c-1"//achar(92)//"1", 1, 2.5_wp, 0.030_wp), & ! 10.1021/ja9621760
      & lj_row_type("ak-h-c-2"//achar(92)//"1", 1, 2.5_wp, 0.030_wp), & ! 10.1021/ja9621760
      & lj_row_type("ak-h-c-3"//achar(92)//"1", 1, 2.5_wp, 0.030_wp), & ! 10.1021/ja9621760
      & lj_row_type("ak-h-c-4"//achar(92)//"1", 1, 2.5_wp, 0.030_wp), & ! 10.1021/ja9621760
      & lj_row_type("tl-s-1-1", 16, 3.55_wp, 0.250_wp), & ! 10.1021/ja9621760
      & lj_row_type("tl-h-s-1"//achar(92)//"1", 1, 0.0_wp, 0.000_wp), & ! 10.1021/ja9621760
      & lj_row_type("tl-c-1-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("tl-c-2-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("tl-c-3-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("tl-c-4-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("sd-s-2-1", 16, 3.55_wp, 0.250_wp), & ! 10.1021/ja9621760
      & lj_row_type("sd-c-1-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("sd-c-2-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("sd-c-3-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("sd-c-4-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("ds-s-2-1", 16, 3.5_wp, 0.250_wp), & ! 10.1021/ja9621760
      & lj_row_type("ds-c-1-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("ds-c-2-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("ds-c-3-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("ds-c-4-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("am-n-1-1", 7, 3.25_wp, 0.170_wp), & ! 10.1021/ja9621760
      & lj_row_type("am-h-n-x"//achar(92)//"1", 1, 0.0_wp, 0.000_wp), & ! 10.1021/ja9621760
      & lj_row_type("am-c-1-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("am-c-2-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("am-c-3-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("am-c-4-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("amp-n-1-1", 7, 3.25_wp, 0.170_wp), & ! 10.1021/ja9621760
      & lj_row_type("amp-h-n-1"//achar(92)//"1", 1, 0.0_wp, 0.000_wp), & ! 10.1021/ja9621760
      & lj_row_type("amp-c-1-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("amp-c-2-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("amp-c-3-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("amp-c-4-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("cacn-c-3-2", 6, 3.75_wp, 0.105_wp), & ! 10.1021/ja9621760
      & lj_row_type("cacn-o-1-x", 8, 2.96_wp, 0.210_wp), & ! 10.1021/ja9621760
      & lj_row_type("cacn-c-1-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("cacn-c-2-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("cacn-c-3-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("cacn-c-4-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("ad/x-c-x-2", 6, 3.75_wp, 0.105_wp), & ! 10.1021/ja9621760
      & lj_row_type("ad/x-o-1-2", 8, 2.96_wp, 0.210_wp), & ! 10.1021/ja9621760
      & lj_row_type("ad/x-h-c-2"//achar(92)//"2", 1, 2.42_wp, 0.015_wp), & ! 10.1021/ja9621760
      & lj_row_type("ad/1-n-1-1", 7, 3.25_wp, 0.170_wp), & ! 10.1021/ja9621760
      & lj_row_type("ad/2-n-2-1", 7, 3.25_wp, 0.170_wp), & ! 10.1021/ja9621760
      & lj_row_type("ad/3-n-3-1", 7, 3.25_wp, 0.170_wp), & ! 10.1021/ja9621760
      & lj_row_type("ad/1-h-n-1"//achar(92)//"1", 1, 0.0_wp, 0.000_wp), & ! 10.1021/ja9621760
      & lj_row_type("ad/2-h-n-2"//achar(92)//"1", 1, 0.0_wp, 0.000_wp), & ! 10.1021/ja9621760
      & lj_row_type("ad/2-c-1-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("ad/3-c-1-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("e-o-2-1", 8, 2.9_wp, 0.140_wp), & ! 10.1021/ja9621760
      & lj_row_type("e-c-1-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("e-c-2-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("e-c-3-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("e-c-4-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("e-h-c-1"//achar(92)//"1", 1, 2.5_wp, 0.030_wp), & ! 10.1021/ja9621760
      & lj_row_type("e-h-c-2"//achar(92)//"1", 1, 2.5_wp, 0.030_wp), & ! 10.1021/ja9621760
      & lj_row_type("e-h-c-3"//achar(92)//"1", 1, 2.5_wp, 0.030_wp), & ! 10.1021/ja9621760
      & lj_row_type("e-h-c-4"//achar(92)//"1", 1, 2.5_wp, 0.030_wp), & ! 10.1021/ja9621760
      & lj_row_type("ace-o-2-1", 8, 2.9_wp, 0.140_wp), & ! 10.1021/ja9621760
      & lj_row_type("ace-c-2-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("ace-h-c-2"//achar(92)//"1", 1, 2.5_wp, 0.030_wp), & ! 10.1021/ja9621760
      & lj_row_type("ace-c-3-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("ace-h-c-1"//achar(92)//"1", 1, 2.5_wp, 0.030_wp), & ! 10.1021/ja9621760
      & lj_row_type("ace-c-4-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("al-c-2-2", 6, 3.75_wp, 0.105_wp), & ! 10.1021/ja9621760
      & lj_row_type("al-o-1-2", 8, 2.96_wp, 0.210_wp), & ! 10.1021/ja9621760
      & lj_row_type("al-h-c-x"//achar(92)//"1", 1, 2.42_wp, 0.015_wp), & ! 10.1021/ja9621760
      & lj_row_type("al-c-1-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("al-c-2-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("al-c-3-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("al-c-4-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("al-h-c-2"//achar(92)//"2", 1, 2.42_wp, 0.015_wp), & ! 10.1021/ja9621760
      & lj_row_type("k-c-3-2", 6, 3.75_wp, 0.105_wp), & ! 10.1021/ja9621760
      & lj_row_type("k-o-1-2", 8, 2.96_wp, 0.210_wp), & ! 10.1021/ja9621760
      & lj_row_type("k-h-c-x-1", 1, 2.42_wp, 0.015_wp), & ! 10.1021/ja9621760
      & lj_row_type("cac-c-3-2", 6, 3.75_wp, 0.105_wp), & ! 10.1021/ja9621760
      & lj_row_type("cac-o-1-2", 8, 2.96_wp, 0.210_wp), & ! 10.1021/ja9621760
      & lj_row_type("cac-o-2-1", 8, 3.0_wp, 0.170_wp), & ! 10.1021/ja9621760
      & lj_row_type("cac-h-o-1/1", 1, 0.0_wp, 0.000_wp), & ! 10.1021/ja9621760
      & lj_row_type("b-cn-2-pdn/cc/cc", 7, 3.25_wp, 0.170_wp), & ! 10.1016/S0166-1280(97)00237-6
      & lj_row_type("b-cc-2-pdn/cc/cn/1", 6, 3.55_wp, 0.070_wp), & ! 10.1016/S0166-1280(97)00237-6
      & lj_row_type("b-cc-2-pdn/cc/cc/2", 6, 3.55_wp, 0.070_wp), & ! 10.1016/S0166-1280(97)00237-6
      & lj_row_type("b-cc-2-pdn/cc/cc/3", 6, 3.55_wp, 0.070_wp), & ! 10.1016/S0166-1280(97)00237-6
      & lj_row_type("b-h-cc-2"//achar(92)//"pdn/cc/cn/1", 1, 2.42_wp, 0.030_wp), & ! 10.1016/S0166-1280(97)00237-6
      & lj_row_type("b-h-cc-2"//achar(92)//"pdn/cc/cc/2", 1, 2.42_wp, 0.030_wp), & ! 10.1016/S0166-1280(97)00237-6
      & lj_row_type("b-h-cc-2"//achar(92)//"pdn/cc/cc/3", 1, 2.42_wp, 0.030_wp), & ! 10.1016/S0166-1280(97)00237-6
      & lj_row_type("b-cn-2-pdz/cc/cc", 7, 3.25_wp, 0.170_wp), & ! 10.1016/S0166-1280(97)00237-6
      & lj_row_type("b-cc-2-pdz/cc/cn/1", 6, 3.55_wp, 0.070_wp), & ! 10.1016/S0166-1280(97)00237-6
      & lj_row_type("b-cc-2-pdz/cc/cc/2", 6, 3.55_wp, 0.070_wp), & ! 10.1016/S0166-1280(97)00237-6
      & lj_row_type("b-h-cc-2"//achar(92)//"pdz/cc/cn/1", 1, 2.42_wp, 0.030_wp), & ! 10.1016/S0166-1280(97)00237-6
      & lj_row_type("b-h-cc-2"//achar(92)//"pdz/cc/cc/2", 1, 2.42_wp, 0.030_wp), & ! 10.1016/S0166-1280(97)00237-6
      & lj_row_type("b-cn-2-pmn/cc/cc", 7, 3.25_wp, 0.170_wp), & ! 10.1016/S0166-1280(97)00237-6
      & lj_row_type("b-cc-2-pmn/cn/cn/1", 6, 3.55_wp, 0.070_wp), & ! 10.1016/S0166-1280(97)00237-6
      & lj_row_type("b-cc-2-pmn/cc/cn/1", 6, 3.55_wp, 0.070_wp), & ! 10.1016/S0166-1280(97)00237-6
      & lj_row_type("b-cc-2-pmn/cc/cc/2", 6, 3.55_wp, 0.070_wp), & ! 10.1016/S0166-1280(97)00237-6
      & lj_row_type("b-h-cc-2"//achar(92)//"pmn/cn/cn/1", 1, 2.42_wp, 0.030_wp), & ! 10.1016/S0166-1280(97)00237-6
      & lj_row_type("b-h-cc-2"//achar(92)//"pmn/cc/cn/1", 1, 2.42_wp, 0.030_wp), & ! 10.1016/S0166-1280(97)00237-6
      & lj_row_type("b-h-cc-2"//achar(92)//"pmn/cc/cc/2", 1, 2.42_wp, 0.030_wp), & ! 10.1016/S0166-1280(97)00237-6
      & lj_row_type("b-cn-2-pzn/cc/cc", 7, 3.25_wp, 0.170_wp), & ! 10.1016/S0166-1280(97)00237-6
      & lj_row_type("b-cc-2-pzn/cc/cn/1", 6, 3.55_wp, 0.070_wp), & ! 10.1016/S0166-1280(97)00237-6
      & lj_row_type("b-h-cc-2"//achar(92)//"pzn/cc/cn/1", 1, 2.42_wp, 0.030_wp), & ! 10.1016/S0166-1280(97)00237-6
      & lj_row_type("b-cc-2-aro/cc/cc/x", 6, 3.55_wp, 0.070_wp), & ! 10.1021/ja9621760
      & lj_row_type("b-h-cc-2"//achar(92)//"aro/cc/cc/x", 1, 2.42_wp, 0.030_wp), & ! 10.1021/ja9621760
      & lj_row_type("b-cc-3-aro/c/cc/cc/0", 6, 3.55_wp, 0.070_wp), & ! 10.1021/ja9621760
      & lj_row_type("tolu-c-1-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("ethb-c-2-1", 6, 3.5_wp, 0.066_wp), & ! 10.1021/ja9621760
      & lj_row_type("phe-o-2-1", 8, 3.07_wp, 0.170_wp), & ! 10.1021/ja9621760
      & lj_row_type("phe-h-1-1", 1, 0.0_wp, 0.000_wp), & ! 10.1021/ja9621760
      & lj_row_type("b-cc-3-aro/o/cc/cc/0", 6, 3.55_wp, 0.070_wp)] ! 10.1021/ja9621760

   !> Complete source table
   type(lj_row_type), parameter :: tuk_rows(n_oplsaa_tuk) = [ &
      & tuk_rows_1]

contains

   !> Look up a source-prefixed OPLS-AA key in atomic units
   !>
   !> @param[in] key Case-insensitive key with db: or tuk: prefix
   !> @param[out] sigma LJ zero crossing, bohr
   !> @param[out] epsilon LJ well depth, Hartree
   !> @param[out] found Key present, including zero-LJ rows
   !> @param[out] number Optional atomic number; zero for missing keys
   pure subroutine lookup_oplsaa_lj(key, sigma, epsilon, found, number)
      !> Source-prefixed key
      character(len=*), intent(in) :: key
      !> LJ zero crossing, bohr
      real(wp), intent(out) :: sigma
      !> LJ well depth, Hartree
      real(wp), intent(out) :: epsilon
      !> Key present
      logical, intent(out) :: found
      !> Optional atomic number
      integer, intent(out), optional :: number
      character(len=len(key)) :: atom_key
      integer :: element, i

      sigma = 0.0_wp
      epsilon = 0.0_wp
      found = .false.
      element = 0
      atom_key = to_lower(adjustl(key))
      if (len_trim(atom_key) <= oplsaa_key_len) then
         if (index(atom_key, "db:") == 1) then
            do i = 1, n_oplsaa_database
               if (trim(atom_key(4:)) /= db_rows(i)%key) cycle
               sigma = db_rows(i)%sigma*10.0_wp*aatoau
               epsilon = db_rows(i)%epsilon*kjtoau
               element = db_rows(i)%number
               found = .true.
               exit
            end do
         else if (index(atom_key, "tuk:") == 1) then
            do i = 1, n_oplsaa_tuk
               if (trim(atom_key(5:)) /= tuk_rows(i)%key) cycle
               sigma = tuk_rows(i)%sigma*aatoau
               epsilon = tuk_rows(i)%epsilon*kcaltoau
               element = tuk_rows(i)%number
               found = .true.
               exit
            end do
         end if
      end if
      if (present(number)) number = element
   end subroutine lookup_oplsaa_lj

end module moist_model_moz_potential_lj_oplsaa_parameters
