!> Gaussian PCM pair-kernel value and derivatives
!>
!> AUTO-GENERATED by gen_amat_kernel.py -- DO NOT EDIT BY HAND.
!>
!> Provenance: this file was produced by `tools/maths/pcm_amat/gen_amat_kernel.py`
!> in the `moist_dev` repository and copied here verbatim.  That generator is
!> *not* part of this repository, so the file cannot be regenerated locally.
!> Any change to the pair mathematics has to go through the generator in
!> `moist_dev` and be re-copied; do not hand-edit the body below.
!>
module moist_model_component_pcm_amat_kernel
   use mctc_env_accuracy, only: wp
   implicit none(type, external)
   private

   public :: pcm_amat_x_far, pcm_amat_x_taylor
   public :: pcm_amat_boys0, pcm_amat_boys01, pcm_amat_boys012
   public :: pcm_amat_width0, pcm_amat_width1, pcm_amat_width2
   public :: pcm_amat_far_value, pcm_amat_far_grad, pcm_amat_far_hess
   public :: pcm_amat_far_value_row, pcm_amat_far_grad_row
   public :: pcm_amat_near_value, pcm_amat_near_grad, pcm_amat_near_hess
   public :: pcm_amat_diag_value, pcm_amat_diag_grad, pcm_amat_diag_hess

   !> Saturation threshold on x = (p*r)**2; above it erf(sqrt(x)) == 1 and
   !> exp(-x) == 0 in double precision, so the kernel is exactly Coulombic
   real(wp), parameter :: pcm_amat_x_far = 81.0_wp

   !> Threshold below which the Boys functions come from their Taylor series
   real(wp), parameter :: pcm_amat_x_taylor = 0.5_wp

contains

   !> Boys function F0(x) = sqrt(pi/(4x))*erf(sqrt(x)) for x >= 0
   !>
   !> Uses the degree-16 Taylor series below pcm_amat_x_taylor and the
   !> closed erf form above it.  The saturated branch drops erf entirely
   !>
   !> @param[in]  x   Boys argument (p*r)**2
   !> @param[out] f0  Boys function F0(x)
   pure subroutine pcm_amat_boys0(x, f0)
      !> Boys argument
      real(wp), intent(in) :: x
      !> Boys function F0(x)
      real(wp), intent(out) :: f0

      !> Square root of the Boys argument
      real(wp) :: sqrtx

      if (x <= pcm_amat_x_taylor) then
         f0 = 1.4483264643598138e-15_wp
         f0 = f0*x - 2.466827010264457e-14_wp
         f0 = f0*x + 3.9554295164585257e-13_wp
         f0 = f0*x - 5.9477940136376354e-12_wp
         f0 = f0*x + 8.35070279514724e-11_wp
         f0 = f0*x - 1.0892221037148573e-09_wp
         f0 = f0*x + 1.3122532963802806e-08_wp
         f0 = f0*x - 1.4503852223150468e-07_wp
         f0 = f0*x + 1.4589169000933706e-06_wp
         f0 = f0*x - 1.3227513227513228e-05_wp
         f0 = f0*x + 0.00010683760683760684_wp
         f0 = f0*x - 0.0007575757575757576_wp
         f0 = f0*x + 0.004629629629629629_wp
         f0 = f0*x - 0.023809523809523808_wp
         f0 = f0*x + 0.1_wp
         f0 = f0*x - 0.3333333333333333_wp
         f0 = f0*x + 1.0_wp
      else
         sqrtx = sqrt(x)
         if (x >= pcm_amat_x_far) then
            f0 = 0.88622692545275801_wp/sqrtx
         else
            f0 = 0.88622692545275801_wp*erf(sqrtx)/sqrtx
         end if
      end if

   end subroutine pcm_amat_boys0

   !> Boys functions F0(x), F1(x) and the Gaussian factor exp(-x)
   !>
   !> @param[in]  x   Boys argument (p*r)**2
   !> @param[out] f0  Boys function F0(x)
   !> @param[out] f1  Boys function F1(x)
   !> @param[out] ex  Gaussian factor exp(-x)
   pure subroutine pcm_amat_boys01(x, f0, f1, ex)
      !> Boys argument
      real(wp), intent(in) :: x
      !> Boys functions F0(x) and F1(x)
      real(wp), intent(out) :: f0, f1
      !> Gaussian factor exp(-x)
      real(wp), intent(out) :: ex

      ! Square root of the Boys argument and the recursion denominator
      real(wp) :: sqrtx, inv2x

      if (x <= pcm_amat_x_taylor) then
         ex = exp(-x)
         f0 = 1.4483264643598138e-15_wp
         f0 = f0*x - 2.466827010264457e-14_wp
         f0 = f0*x + 3.9554295164585257e-13_wp
         f0 = f0*x - 5.9477940136376354e-12_wp
         f0 = f0*x + 8.35070279514724e-11_wp
         f0 = f0*x - 1.0892221037148573e-09_wp
         f0 = f0*x + 1.3122532963802806e-08_wp
         f0 = f0*x - 1.4503852223150468e-07_wp
         f0 = f0*x + 1.4589169000933706e-06_wp
         f0 = f0*x - 1.3227513227513228e-05_wp
         f0 = f0*x + 0.00010683760683760684_wp
         f0 = f0*x - 0.0007575757575757576_wp
         f0 = f0*x + 0.004629629629629629_wp
         f0 = f0*x - 0.023809523809523808_wp
         f0 = f0*x + 0.1_wp
         f0 = f0*x - 0.3333333333333333_wp
         f0 = f0*x + 1.0_wp
         f1 = 1.3655649521106815e-15_wp
         f1 = f1*x - 2.317322342975702e-14_wp
         f1 = f1*x + 3.7002405153966856e-13_wp
         f1 = f1*x - 5.537601323041936e-12_wp
         f1 = f1*x + 7.732132217728926e-11_wp
         f1 = f1*x - 1.0020843354176688e-09_wp
         f1 = f1*x + 1.1981443140863431e-08_wp
         f1 = f1*x - 1.3122532963802806e-07_wp
         f1 = f1*x + 1.3053467000835422e-06_wp
         f1 = f1*x - 1.1671335200746965e-05_wp
         f1 = f1*x + 9.259259259259259e-05_wp
         f1 = f1*x - 0.000641025641025641_wp
         f1 = f1*x + 0.003787878787878788_wp
         f1 = f1*x - 0.018518518518518517_wp
         f1 = f1*x + 0.07142857142857142_wp
         f1 = f1*x - 0.2_wp
         f1 = f1*x + 0.3333333333333333_wp
      else if (x >= pcm_amat_x_far) then
         ex = 0.0_wp
         sqrtx = sqrt(x)
         f0 = 0.88622692545275801_wp/sqrtx
         f1 = 0.5_wp*f0/x
      else
         sqrtx = sqrt(x)
         ex = exp(-x)
         inv2x = 0.5_wp/x
         f0 = 0.88622692545275801_wp*erf(sqrtx)/sqrtx
         f1 = (f0 - ex)*inv2x
      end if

   end subroutine pcm_amat_boys01

   !> Boys functions F0(x), F1(x), F2(x) and the Gaussian factor exp(-x)
   !>
   !> @param[in]  x   Boys argument (p*r)**2
   !> @param[out] f0  Boys function F0(x)
   !> @param[out] f1  Boys function F1(x)
   !> @param[out] f2  Boys function F2(x)
   !> @param[out] ex  Gaussian factor exp(-x)
   pure subroutine pcm_amat_boys012(x, f0, f1, f2, ex)
      !> Boys argument
      real(wp), intent(in) :: x
      !> Boys functions F0(x), F1(x) and F2(x)
      real(wp), intent(out) :: f0, f1, f2
      !> Gaussian factor exp(-x)
      real(wp), intent(out) :: ex

      !> Square root of the Boys argument and the recursion denominator
      real(wp) :: sqrtx, inv2x

      if (x <= pcm_amat_x_taylor) then
         ex = exp(-x)
         f0 = 1.4483264643598138e-15_wp
         f0 = f0*x - 2.466827010264457e-14_wp
         f0 = f0*x + 3.9554295164585257e-13_wp
         f0 = f0*x - 5.9477940136376354e-12_wp
         f0 = f0*x + 8.35070279514724e-11_wp
         f0 = f0*x - 1.0892221037148573e-09_wp
         f0 = f0*x + 1.3122532963802806e-08_wp
         f0 = f0*x - 1.4503852223150468e-07_wp
         f0 = f0*x + 1.4589169000933706e-06_wp
         f0 = f0*x - 1.3227513227513228e-05_wp
         f0 = f0*x + 0.00010683760683760684_wp
         f0 = f0*x - 0.0007575757575757576_wp
         f0 = f0*x + 0.004629629629629629_wp
         f0 = f0*x - 0.023809523809523808_wp
         f0 = f0*x + 0.1_wp
         f0 = f0*x - 0.3333333333333333_wp
         f0 = f0*x + 1.0_wp
         f1 = 1.3655649521106815e-15_wp
         f1 = f1*x - 2.317322342975702e-14_wp
         f1 = f1*x + 3.7002405153966856e-13_wp
         f1 = f1*x - 5.537601323041936e-12_wp
         f1 = f1*x + 7.732132217728926e-11_wp
         f1 = f1*x - 1.0020843354176688e-09_wp
         f1 = f1*x + 1.1981443140863431e-08_wp
         f1 = f1*x - 1.3122532963802806e-07_wp
         f1 = f1*x + 1.3053467000835422e-06_wp
         f1 = f1*x - 1.1671335200746965e-05_wp
         f1 = f1*x + 9.259259259259259e-05_wp
         f1 = f1*x - 0.000641025641025641_wp
         f1 = f1*x + 0.003787878787878788_wp
         f1 = f1*x - 0.018518518518518517_wp
         f1 = f1*x + 0.07142857142857142_wp
         f1 = f1*x - 0.2_wp
         f1 = f1*x + 0.3333333333333333_wp
         f2 = 1.291750630374969e-15_wp
         f2 = f2*x - 2.1849039233770904e-14_wp
         f2 = f2*x + 3.475983514463553e-13_wp
         f2 = f2*x - 5.18033672155536e-12_wp
         f2 = f2*x + 7.198881719954517e-11_wp
         f2 = f2*x - 9.278558661274711e-10_wp
         f2 = f2*x + 1.1022927689594356e-08_wp
         f2 = f2*x - 1.198144314086343e-07_wp
         f2 = f2*x + 1.1810279667422524e-06_wp
         f2 = f2*x - 1.0442773600668338e-05_wp
         f2 = f2*x + 8.169934640522875e-05_wp
         f2 = f2*x - 0.0005555555555555556_wp
         f2 = f2*x + 0.003205128205128205_wp
         f2 = f2*x - 0.015151515151515152_wp
         f2 = f2*x + 0.05555555555555555_wp
         f2 = f2*x - 0.14285714285714285_wp
         f2 = f2*x + 0.2_wp
      else if (x >= pcm_amat_x_far) then
         ex = 0.0_wp
         sqrtx = sqrt(x)
         inv2x = 0.5_wp/x
         f0 = 0.88622692545275801_wp/sqrtx
         f1 = f0*inv2x
         f2 = 3.0_wp*f1*inv2x
      else
         sqrtx = sqrt(x)
         ex = exp(-x)
         inv2x = 0.5_wp/x
         f0 = 0.88622692545275801_wp*erf(sqrtx)/sqrtx
         f1 = (f0 - ex)*inv2x
         f2 = (3.0_wp*f1 - ex)*inv2x
      end if

   end subroutine pcm_amat_boys012

   !> Gaussian pair width p = xi_i*xi_j/sqrt(xi_i**2 + xi_j**2)
   !>
   !> @param[in]  xi_i  Gaussian width of tessera i
   !> @param[in]  xi_j  Gaussian width of tessera j
   !> @param[out] p     Pair width
   pure subroutine pcm_amat_width0(xi_i, xi_j, p)
      !> Gaussian widths of the two tesserae
      real(wp), intent(in) :: xi_i, xi_j
      !> Pair width
      real(wp), intent(out) :: p

      p = xi_i*xi_j/sqrt((xi_i**2 + xi_j**2))

   end subroutine pcm_amat_width0

   !> Gaussian pair width and its first derivatives
   !>
   !> @param[in]  xi_i  Gaussian width of tessera i
   !> @param[in]  xi_j  Gaussian width of tessera j
   !> @param[out] p     Pair width
   !> @param[out] p_i   dp/dxi_i
   !> @param[out] p_j   dp/dxi_j
   pure subroutine pcm_amat_width1(xi_i, xi_j, p, p_i, p_j)
      !> Gaussian widths of the two tesserae
      real(wp), intent(in) :: xi_i, xi_j
      !> Pair width
      real(wp), intent(out) :: p
      !> First derivatives of the pair width
      real(wp), intent(out) :: p_i, p_j
      !> Common subexpressions
      real(wp) :: w1_0, w1_1, w1_2, w1_3, w1_4

      w1_0 = xi_i**2
      w1_1 = xi_j**2
      w1_2 = w1_0 + w1_1
      w1_3 = 1.0_wp/sqrt(w1_2)
      w1_4 = 1.0_wp/(w1_2*sqrt(w1_2))
      p = w1_3*xi_i*xi_j
      p_i = -w1_0*w1_4*xi_j + w1_3*xi_j
      p_j = -w1_1*w1_4*xi_i + w1_3*xi_i

   end subroutine pcm_amat_width1

   !> Gaussian pair width and its first and second derivatives
   !>
   !> @param[in]  xi_i  Gaussian width of tessera i
   !> @param[in]  xi_j  Gaussian width of tessera j
   !> @param[out] p     Pair width
   !> @param[out] p_i   dp/dxi_i
   !> @param[out] p_j   dp/dxi_j
   !> @param[out] p_ii  d2p/dxi_i**2
   !> @param[out] p_ij  d2p/dxi_i dxi_j
   !> @param[out] p_jj  d2p/dxi_j**2
   pure subroutine pcm_amat_width2(xi_i, xi_j, p, p_i, p_j, p_ii, p_ij, p_jj)
      !> Gaussian widths of the two tesserae
      real(wp), intent(in) :: xi_i, xi_j
      !> Pair width
      real(wp), intent(out) :: p
      !> First derivatives of the pair width
      real(wp), intent(out) :: p_i, p_j
      !> Second derivatives of the pair width
      real(wp), intent(out) :: p_ii, p_ij, p_jj
      !> Common subexpressions
      real(wp) :: w2_0, w2_1, w2_2, w2_3, w2_4, w2_5, w2_6, w2_7
      real(wp) :: w2_8, w2_9

      w2_0 = xi_i**2
      w2_1 = xi_j**2
      w2_2 = w2_0 + w2_1
      w2_3 = 1.0_wp/sqrt(w2_2)
      w2_4 = 1.0_wp/(w2_2*sqrt(w2_2))
      w2_5 = w2_4*xi_j
      w2_6 = 1.0_wp/w2_2
      w2_7 = w2_0*w2_6
      w2_8 = w2_5*xi_i
      w2_9 = w2_1*w2_6
      p = w2_3*xi_i*xi_j
      p_i = -w2_0*w2_5 + w2_3*xi_j
      p_j = -w2_1*w2_4*xi_i + w2_3*xi_i
      p_ii = w2_8*(3.0_wp*w2_7 - 3.0_wp)
      p_ij = w2_3*(3.0_wp*w2_0*w2_1/w2_2**2 - w2_7 - w2_9 + 1.0_wp)
      p_jj = w2_8*(3.0_wp*w2_9 - 3.0_wp)

   end subroutine pcm_amat_width2

   !> Saturated-regime kernel value A = 1/r
   !>
   !> Valid for x = (p*r)**2 >= pcm_amat_x_far, where erf(p*r) == 1
   !>
   !> @param[in]  r2  Squared separation
   !> @param[out] a   Kernel value
   pure subroutine pcm_amat_far_value(r2, a)
      !> Squared separation
      real(wp), intent(in) :: r2
      !> Kernel value
      real(wp), intent(out) :: a

      a = 1.0_wp/sqrt(r2)

   end subroutine pcm_amat_far_value

   !> Saturated-regime kernel value and dA/dr2
   !>
   !> Both xi channels vanish identically in this regime, so they are not
   !> returned: dA/dxi_i = dA/dxi_j = 0 exactly
   !>
   !> @param[in]  r2    Squared separation
   !> @param[out] a     Kernel value
   !> @param[out] a_r2  dA/dr2
   pure subroutine pcm_amat_far_grad(r2, a, a_r2)
      !> Squared separation
      real(wp), intent(in) :: r2
      !> Kernel value
      real(wp), intent(out) :: a
      !> Derivative with respect to the squared separation
      real(wp), intent(out) :: a_r2

      a = 1.0_wp/sqrt(r2)
      a_r2 = -(1.0_wp/2.0_wp)/(r2*sqrt(r2))

   end subroutine pcm_amat_far_grad

   !> Saturated-regime kernel value and its first and second r2 derivatives
   !>
   !> Every channel involving xi_i or xi_j vanishes identically here
   !>
   !> @param[in]  r2      Squared separation
   !> @param[out] a       Kernel value
   !> @param[out] a_r2    dA/dr2
   !> @param[out] a_r2r2  d2A/dr2**2
   pure subroutine pcm_amat_far_hess(r2, a, a_r2, a_r2r2)
      !> Squared separation
      real(wp), intent(in) :: r2
      !> Kernel value
      real(wp), intent(out) :: a
      !> First and second derivatives with respect to the squared separation
      real(wp), intent(out) :: a_r2, a_r2r2

      a = 1.0_wp/sqrt(r2)
      a_r2 = -(1.0_wp/2.0_wp)/(r2*sqrt(r2))
      a_r2r2 = (3.0_wp/4.0_wp)/(r2*r2*sqrt(r2))

   end subroutine pcm_amat_far_hess

   !> Saturated-regime kernel values for a contiguous run of pairs
   !>
   !> One call per matrix row or tile keeps the transcendental-free inner
   !> loop vectorizable without paying per-pair call overhead
   !>
   !> @param[in]  n   Number of pairs
   !> @param[in]  r2  Squared separations (n)
   !> @param[out] a   Kernel values (n)
   pure subroutine pcm_amat_far_value_row(n, r2, a)
      !> Number of pairs
      integer, intent(in) :: n
      !> Squared separations
      real(wp), intent(in) :: r2(n)
      !> Kernel values
      real(wp), intent(out) :: a(n)

      !> Pair index
      integer :: k

      do k = 1, n
         a(k) = 1.0_wp/sqrt(r2(k))
      end do

   end subroutine pcm_amat_far_value_row

   !> Saturated-regime values and dA/dr2 for a contiguous run of pairs
   !>
   !> @param[in]  n     Number of pairs
   !> @param[in]  r2    Squared separations (n)
   !> @param[out] a     Kernel values (n)
   !> @param[out] a_r2  Derivatives dA/dr2 (n)
   pure subroutine pcm_amat_far_grad_row(n, r2, a, a_r2)
      !> Number of pairs
      integer, intent(in) :: n
      !> Squared separations
      real(wp), intent(in) :: r2(n)
      !> Kernel values
      real(wp), intent(out) :: a(n)
      !> Derivatives with respect to the squared separations
      real(wp), intent(out) :: a_r2(n)

      !> Pair index
      integer :: k

      do k = 1, n
         a(k) = 1.0_wp/sqrt(r2(k))
         a_r2(k) = -(1.0_wp/2.0_wp)/(r2(k)*sqrt(r2(k)))
      end do

   end subroutine pcm_amat_far_grad_row

   !> Full Gaussian pair kernel value A = erf(p*r)/r
   !>
   !> @param[in]  xi_i  Gaussian width of tessera i
   !> @param[in]  xi_j  Gaussian width of tessera j
   !> @param[in]  r2    Squared separation
   !> @param[out] a     Kernel value
   pure subroutine pcm_amat_near_value(xi_i, xi_j, r2, a)
      !> Gaussian widths of the two tesserae
      real(wp), intent(in) :: xi_i, xi_j
      !> Squared separation
      real(wp), intent(in) :: r2
      !> Kernel value
      real(wp), intent(out) :: a

      !> Pair width, Boys argument, and Boys function F0
      real(wp) :: p, x, f0

      call pcm_amat_width0(xi_i, xi_j, p)
      x = p*p*r2
      call pcm_amat_boys0(x, f0)

      a = 1.12837916709551257_wp*f0*p

   end subroutine pcm_amat_near_value

   !> Full Gaussian pair kernel value and first derivatives
   !>
   !> The xi channels are exp(-x)-weighted, so they are exponentially
   !> small (and eventually exactly zero) once the pair separates.
   !>
   !> @param[in]  xi_i    Gaussian width of tessera i
   !> @param[in]  xi_j    Gaussian width of tessera j
   !> @param[in]  r2      Squared separation
   !> @param[out] a       Kernel value
   !> @param[out] a_xi_i  dA/dxi_i
   !> @param[out] a_xi_j  dA/dxi_j
   !> @param[out] a_r2    dA/dr2
   pure subroutine pcm_amat_near_grad(xi_i, xi_j, r2, a, a_xi_i, a_xi_j, a_r2)
      !> Gaussian widths of the two tesserae
      real(wp), intent(in) :: xi_i, xi_j
      !> Squared separation
      real(wp), intent(in) :: r2
      !> Kernel value
      real(wp), intent(out) :: a
      !> Derivatives with respect to the Gaussian widths
      real(wp), intent(out) :: a_xi_i, a_xi_j
      !> Derivative with respect to the squared separation
      real(wp), intent(out) :: a_r2

      !> Pair width and its first derivatives
      real(wp) :: p, p_i, p_j
      !> Boys argument, Boys functions, and the Gaussian factor
      real(wp) :: x, f0, f1, ex
      !> Common subexpressions
      real(wp) :: ng_0

      call pcm_amat_width1(xi_i, xi_j, p, p_i, p_j)
      x = p*p*r2
      call pcm_amat_boys01(x, f0, f1, ex)

      ng_0 = 1.12837916709551257_wp*ex
      a = 1.12837916709551257_wp*f0*p
      a_xi_i = ng_0*p_i
      a_xi_j = ng_0*p_j
      a_r2 = -1.12837916709551257_wp*f1*p**3

   end subroutine pcm_amat_near_grad

   !> Full Gaussian pair kernel value and first and second derivatives
   !>
   !> @param[in]  xi_i         Gaussian width of tessera i
   !> @param[in]  xi_j         Gaussian width of tessera j
   !> @param[in]  r2           Squared separation
   !> @param[out] a            Kernel value
   !> @param[out] a_xi_i       dA/dxi_i
   !> @param[out] a_xi_j       dA/dxi_j
   !> @param[out] a_r2         dA/dr2
   !> @param[out] a_xi_i_xi_i  d2A/dxi_i**2
   !> @param[out] a_xi_i_xi_j  d2A/dxi_i dxi_j
   !> @param[out] a_xi_j_xi_j  d2A/dxi_j**2
   !> @param[out] a_xi_i_r2    d2A/dxi_i dr2
   !> @param[out] a_xi_j_r2    d2A/dxi_j dr2
   !> @param[out] a_r2_r2      d2A/dr2**2
   pure subroutine pcm_amat_near_hess(xi_i, xi_j, r2, a, a_xi_i, a_xi_j, a_r2, &
                                      a_xi_i_xi_i, a_xi_i_xi_j, a_xi_j_xi_j, &
                                      a_xi_i_r2, a_xi_j_r2, a_r2_r2)
      !> Gaussian widths of the two tesserae
      real(wp), intent(in) :: xi_i, xi_j
      !> Squared separation
      real(wp), intent(in) :: r2
      !> Kernel value
      real(wp), intent(out) :: a
      !> First derivatives with respect to the Gaussian widths
      real(wp), intent(out) :: a_xi_i, a_xi_j
      !> First derivative with respect to the squared separation
      real(wp), intent(out) :: a_r2
      !> Second derivatives with respect to the Gaussian widths
      real(wp), intent(out) :: a_xi_i_xi_i, a_xi_i_xi_j, a_xi_j_xi_j
      !> Mixed width/separation second derivatives
      real(wp), intent(out) :: a_xi_i_r2, a_xi_j_r2
      !> Second derivative with respect to the squared separation
      real(wp), intent(out) :: a_r2_r2

      !> Pair width and its first and second derivatives
      real(wp) :: p, p_i, p_j, p_ii, p_ij, p_jj
      !> Boys argument, Boys functions, and the Gaussian factor
      real(wp) :: x, f0, f1, f2, ex
      !> Common subexpressions
      real(wp) :: nh_0, nh_1, nh_2, nh_3, nh_4

      call pcm_amat_width2(xi_i, xi_j, p, p_i, p_j, p_ii, p_ij, p_jj)
      x = p*p*r2
      call pcm_amat_boys012(x, f0, f1, f2, ex)

      nh_0 = 1.12837916709551257_wp*ex
      nh_1 = nh_0*p_i
      nh_2 = nh_0*p_j
      nh_3 = 2.25675833419102515_wp*ex*p*r2
      nh_4 = p**2
      a = 1.12837916709551257_wp*f0*p
      a_xi_i = nh_1
      a_xi_j = nh_2
      a_r2 = -1.12837916709551257_wp*f1*p**3
      a_xi_i_xi_i = 1.12837916709551257_wp*ex*p_ii - nh_3*p_i**2
      a_xi_i_xi_j = 1.12837916709551257_wp*ex*p_ij - nh_3*p_i*p_j
      a_xi_j_xi_j = 1.12837916709551257_wp*ex*p_jj - nh_3*p_j**2
      a_xi_i_r2 = -nh_1*nh_4
      a_xi_j_r2 = -nh_2*nh_4
      a_r2_r2 = 1.12837916709551257_wp*f2*p**5

   end subroutine pcm_amat_near_hess

   !> Diagonal Gaussian self-interaction A_ii = sqrt(2/pi)*xi/f
   !>
   !> @param[in]  xi  Gaussian width of the tessera
   !> @param[in]  f   Switching factor of the tessera
   !> @param[out] a   Diagonal kernel value
   pure subroutine pcm_amat_diag_value(xi, f, a)
      !> Gaussian width of the tessera
      real(wp), intent(in) :: xi
      !> Switching factor of the tessera
      real(wp), intent(in) :: f
      !> Diagonal kernel value
      real(wp), intent(out) :: a

      a = 0.564189583547756287_wp*sqrt(2.0_wp)*xi/f

   end subroutine pcm_amat_diag_value

   !> Diagonal self-interaction and its first derivatives
   !>
   !> @param[in]  xi    Gaussian width of the tessera
   !> @param[in]  f     Switching factor of the tessera
   !> @param[out] a     Diagonal kernel value
   !> @param[out] a_xi  dA_ii/dxi
   !> @param[out] a_f   dA_ii/df
   pure subroutine pcm_amat_diag_grad(xi, f, a, a_xi, a_f)
      !> Gaussian width of the tessera
      real(wp), intent(in) :: xi
      !> Switching factor of the tessera
      real(wp), intent(in) :: f
      !> Diagonal kernel value
      real(wp), intent(out) :: a
      !> First derivatives of the diagonal kernel
      real(wp), intent(out) :: a_xi, a_f
      !> Common subexpressions
      real(wp) :: dg_0, dg_1

      dg_0 = 0.7978845608028654_wp
      dg_1 = dg_0/f
      a = dg_1*xi
      a_xi = dg_1
      a_f = -dg_0*xi/f**2

   end subroutine pcm_amat_diag_grad

   !> Diagonal self-interaction and its first and second derivatives
   !>
   !> @param[in]  xi       Gaussian width of the tessera
   !> @param[in]  f        Switching factor of the tessera
   !> @param[out] a        Diagonal kernel value
   !> @param[out] a_xi     dA_ii/dxi
   !> @param[out] a_f      dA_ii/df
   !> @param[out] a_xi_xi  d2A_ii/dxi**2
   !> @param[out] a_xi_f   d2A_ii/dxi df
   !> @param[out] a_f_f    d2A_ii/df**2
   pure subroutine pcm_amat_diag_hess(xi, f, a, a_xi, a_f, a_xi_xi, a_xi_f, a_f_f)
      !> Gaussian width of the tessera
      real(wp), intent(in) :: xi
      !> Switching factor of the tessera
      real(wp), intent(in) :: f
      !> Diagonal kernel value
      real(wp), intent(out) :: a
      !> First derivatives of the diagonal kernel
      real(wp), intent(out) :: a_xi, a_f
      !> Second derivatives of the diagonal kernel
      real(wp), intent(out) :: a_xi_xi, a_xi_f, a_f_f
      !> Common subexpressions
      real(wp) :: dh_0, dh_1, dh_2, dh_3

      dh_0 = 1.4142135623730951_wp
      dh_1 = 0.564189583547756287_wp*dh_0
      dh_2 = dh_1/f
      dh_3 = dh_1/f**2
      a = dh_2*xi
      a_xi = dh_2
      a_f = -dh_3*xi
      a_xi_xi = 0.0_wp
      a_xi_f = -dh_3
      a_f_f = 1.12837916709551257_wp*dh_0*xi/f**3

   end subroutine pcm_amat_diag_hess

end module moist_model_component_pcm_amat_kernel
