!> Low-level iSwiG switching pair kernel
!>
!> AUTO-GENERATED by iswig_gen.py -- DO NOT EDIT BY HAND.
!>
!> The DROP iSwiG switching factor at a surface point owned by atom `owner` is a
!> product over that atom's neighbours,
!>
!>    f = prod_k f_k ,    f_k = 1 - (erf(p_k) + erf(m_k))/2 ,
!>
!> with r_k = ||pos - R_k||, p_k = xi (rad_k + r_k) and m_k = xi (rad_k - r_k).
!> This module owns one neighbour's radial scalar algebra: the value f_k 
!> and the five log-derivative coefficients
!>
!>    c  = d  ln f_k / dr         e  = d2 ln f_k / dr2
!>    a  = d  ln f_k / dxi        b  = d2 ln f_k / dxi2
!>    dc = d2 ln f_k / dr dxi
!>
!> Log-derivatives are the right tool as L = ln f is a plain sum over neighbours.
!> Writing u_k = pos - R_k and n = u_k/r, the caller's rows follow from five scalars:
!>
!>    grad_A L         = -c_k n  (A = k),  +c_k n  (A = owner),  0 otherwise
!>    grad^2 ln f_k    = e_k n (x) n + (c_k/r)(I - n (x) n)     in the (k, owner) block
!>
!> and the second derivative of f = exp(L) adds a single rank-1 outer product
!> that collapses into one scalar per surface point; this keeps the contracted
!> second derivative O(n_nb).
module moist_cavity_drop_gaussian_kernel
   use mctc_env_accuracy, only: wp
   implicit none (type, external)
   private

   public :: iswig_pair_f0
   public :: iswig_pair_coeffs

contains

   !> Switching factor of one neighbour
   !>
   !> `f = 1 - (erf(xi (rad + r)) + erf(xi (rad - r)))/2`, which lies in [0, 1]:
   !> exactly 1 once the point is well outside the neighbour's sphere, exactly 0
   !> once it is well inside.  Both saturations are reachable in double
   !> precision, which is what the companion routine's guarded interface is for.
   !>
   !> @param[in]    xi     Gaussian width of the owning sphere
   !> @param[in]    rad    Radius of the neighbour sphere
   !> @param[in]    r      Distance from the surface point to the neighbour centre
   !> @param[out]   f      Switching factor of this neighbour
   pure subroutine iswig_pair_f0(xi, rad, r, f)
      !> Gaussian width of the owning sphere
      real(wp), intent(in) :: xi
      !> Radius of the neighbour sphere
      real(wp), intent(in) :: rad
      !> Distance from the surface point to the neighbour centre
      real(wp), intent(in) :: r
      !> Switching factor of this neighbour
      real(wp), intent(out) :: f

      f = -1.0_wp/2.0_wp*erf(xi*(-r + rad)) - 1.0_wp/2.0_wp*erf(xi*(r + rad)) + 1.0_wp
   end subroutine iswig_pair_f0

   !> Log-derivative coefficients of one neighbour's switching factor
   !>
   !> All five are derivatives of `ln f_k`, so the caller must have established
   !> that `f` is nonzero -- and that `r` is nonzero, since the row assembly
   !> divides by it -- before calling.  Passing `f` in rather than recomputing it
   !> is what makes that possible; see the module header.
   !>
   !> @param[in]    xi     Gaussian width of the owning sphere
   !> @param[in]    rad    Radius of the neighbour sphere
   !> @param[in]    r      Distance from the surface point to the neighbour centre
   !> @param[in]    f      Switching factor of this neighbour, from `iswig_pair_f0`; must be nonzero
   !> @param[out]   c      d ln f_k / dr
   !> @param[out]   e      d2 ln f_k / dr2
   !> @param[out]   a      d ln f_k / dxi
   !> @param[out]   b      d2 ln f_k / dxi2
   !> @param[out]   dc     d2 ln f_k / dr dxi
   pure subroutine iswig_pair_coeffs(xi, rad, r, f, c, e, a, b, dc)
      !> Gaussian width of the owning sphere
      real(wp), intent(in) :: xi
      !> Radius of the neighbour sphere
      real(wp), intent(in) :: rad
      !> Distance from the surface point to the neighbour centre
      real(wp), intent(in) :: r
      !> Switching factor of this neighbour, from `iswig_pair_f0`; must be nonzero
      real(wp), intent(in) :: f
      !> d ln f_k / dr
      real(wp), intent(out) :: c
      !> d2 ln f_k / dr2
      real(wp), intent(out) :: e
      !> d ln f_k / dxi
      real(wp), intent(out) :: a
      !> d2 ln f_k / dxi2
      real(wp), intent(out) :: b
      !> d2 ln f_k / dr dxi
      real(wp), intent(out) :: dc

      !> The two Gaussians, and common subexpressions
      real(wp) :: ctp0, exp_p, exp_m, ct0, ct1, ct2, ct3, ct4, ct5, ct6, ct7, ct8

      ctp0 = (xi*xi)
      exp_p = exp(-ctp0*((r + rad)*(r + rad)))
      exp_m = exp(-ctp0*((-r + rad)*(-r + rad)))

      ct0 = 1.0_wp/f
      ct1 = 0.564189583547756287_wp*xi
      ct2 = ct1*exp_m - ct1*exp_p
      ct3 = 1.0_wp/(f*f)
      ct4 = r + rad
      ct5 = r - rad
      ct6 = 1.12837916709551257_wp*ct0
      ct7 = -0.564189583547756287_wp*ct4*exp_p + 0.564189583547756287_wp*ct5*exp_m
      ct8 = (xi*xi)
      c = ct0*ct2
      e = -(ct2*ct2)*ct3 + ct6*(xi*xi*xi)*(ct4*exp_p - ct5*exp_m)
      a = ct0*ct7
      b = -ct3*(ct7*ct7) + ct6*xi*((ct4*ct4*ct4)*exp_p - (ct5*ct5*ct5)*exp_m)
      dc = &
         0.564189583547756287_wp*ct0*(2.0_wp*(ct4*ct4)*ct8*exp_p - 2.0_wp*(ct5*ct5)*ct8*exp_m + &
         exp_m - exp_p) - ct2*ct3*ct7
   end subroutine iswig_pair_coeffs

end module moist_cavity_drop_gaussian_kernel
